### ISSUE TITLE
Modify ticks and real time on the chart

### ISSUE THREAD

**Issue by Skarax** [swharden/ScottPlot#1]
Hi,

I'm currently using your library to make some live sensor chart. It's work fine, but I have two questions.
First, is there a way to modify programmactly the ticks the chart? (For example, just show four ticks instead of many ticks?)
And second, Is it possible to put real time (in DateTime) in the axis instead of real time in double?

Picture of the problem: [Picture.zip](https://github.com/swharden/ScottPlot/files/2292899/Picture.zip)

Thanks in advance!

**Comment by swharden** [comment]
For reference, this is the problem
![image](https://user-images.githubusercontent.com/4165489/44300831-32e1da80-a2db-11e8-9826-7aa43a63c4e2.png)

**Comment by swharden** [comment]
I replicated this problem:

## When X values are small
```cs
private void button1_Click(object sender, EventArgs e)
{
	int pointCount = 2000;
	double[] x = new double[pointCount];
	double[] y = new double[pointCount];
	for (int i=0; i< pointCount; i++)
	{
		x[i] = i;
		y[i] = Math.Sin((double)i / 100);
	}
	scottPlotUC1.PlotXY(x, y);
	scottPlotUC1.AxisAuto();
}
```
![image](https://user-images.githubusercontent.com/4165489/44300865-a388f700-a2db-11e8-9dbf-a4bd9bebcbe6.png)

## When X values are large

```cs
private void button1_Click(object sender, EventArgs e)
{
	int pointCount = 2000;
	double[] x = new double[pointCount];
	double[] y = new double[pointCount];
	for (int i=0; i< pointCount; i++)
	{
		x[i] = i*10000;
		y[i] = Math.Sin((double)i / 100);
	}
	scottPlotUC1.PlotXY(x, y);
	scottPlotUC1.AxisAuto();
}
```
![image](https://user-images.githubusercontent.com/4165489/44300869-b69bc700-a2db-11e8-82fb-5c288f3bd759.png)

**Comment by swharden** [comment]
Tick density is automatically guessed here:
https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/Axis.cs#L164-L169

**Comment by swharden** [comment]
I modified the core axis class https://github.com/swharden/ScottPlot/commit/f3b4cdbf3488814518049c57c36a466f3e501bb8 and now you can manually define `pixelsPerTick` for each axis. It's an approximate target for how far to space axis tick labels apart. You can use it like this:

```cs
scottPlotUC1.fig.xAxis.pixelsPerTick = 100;
scottPlotUC1.PlotXY(x, y);
scottPlotUC1.AxisAuto();
```

![image](https://user-images.githubusercontent.com/4165489/44300924-c962cb80-a2dc-11e8-887d-9bed38be171c.png)

I hope this works for you! Thanks for reporting the issue!
Scott
