### ISSUE TITLE
plt.Legend()

### ISSUE THREAD

**Issue by alex555176** [swharden/ScottPlot#10]
To whom it may concern,

This is really a great visualization library in C#
and I wonder if there is any new update on "Legend Function".
Legend, a rectangular showing the title of each Lines on the Figure.

Thank you and looking forward to your precious reply.
Best regard

**Comment by swharden** [comment]
@alex555176 a legend feature is not currently implemented and would be somewhat hard to add with the current code, but I'm working on version 3 of ScottPlot and I'll make a note right now to be sure support for a corner legend gets added into the next release. Thanks for the suggestion!

**Comment by alex555176** [comment]
@swharden 
Understood, and we are indeed looking forward on your latest version 3 ScottPlot.

**Comment by swharden** [comment]
[ScottPlot v3](https://github.com/swharden/ScottPlot/branches) is pretty far along now, so a legend will be supported pretty soon...

**Comment by swharden** [comment]
I just released ScottPlot v3 and [the cookbook](https://github.com/swharden/ScottPlot/blob/master/doc/cookbook/README.md#legend) demonstrates how to create a plot with a legend:

```cs
var plt = new ScottPlot.Plot(600, 400);
plt.PlotScatter(dataXs, dataSin, label: "first");
plt.PlotScatter(dataXs, dataCos, label: "second");
plt.AxisAuto();
plt.Legend();
plt.SaveFig("legendDemo.png");
```

![image](https://user-images.githubusercontent.com/4165489/58372625-6d257b80-7eee-11e9-8ccc-2c8cbe1f8f72.png)
