### ISSUE TITLE
small legend rendering problems

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#105]
### Issue 1: the center alignment is a little off

![image](https://user-images.githubusercontent.com/4165489/63230181-46b66a00-c1d7-11e9-9821-2ca87b72c681.png)

### Issue 2: Shadow looks bad after click-dragging
before | after
---|---
![image](https://user-images.githubusercontent.com/4165489/63230193-63eb3880-c1d7-11e9-8a44-0245ac66ad1c.png) | ![image](https://user-images.githubusercontent.com/4165489/63230197-6a79b000-c1d7-11e9-8757-5c7dd82dca7a.png)

**Comment by StendProg** [comment]
Issue 1 and 2 fixed at PR #106. 
Legend positions still calculated at old bmpData positions, and moved after to zero offset. Will it need full rework to new separate bmp concept?

**Comment by swharden** [comment]
> Issue 1 and 2 fixed at PR #106.

Thanks @StendProg! This looks much better now.

> Legend positions still calculated at old bmpData positions, and moved after to zero offset. Will it needed full rework to new separate bmp concept?

Now that the legend can be drawn on its own bitmap, much of the positioning code can be removed. This may dramatically reduce the size and complexity of [Legend.cs](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/Legend.cs).

This is a low priority refactor since it will not change any behavior. I'll leave this issue open until some of the more serious issues are fixed, then I'll come back and refactor this module.
