### ISSUE TITLE
draggable axis lines

### ISSUE THREAD

**Issue by plumforest** [swharden/ScottPlot#11]
I use the plt.data.AddVertLine() function add two vertical line to set a range between the two lines.
By now I have to add other control for the user to manipulate to set the X position of the line.
Is there any plan to add feature for  manipulating the the line position directly?

**Comment by swharden** [comment]
Hi @plumforest, at this time mouse interaction is not supported. The core of ScottPlot is mouse-unaware (designed to run from console applications), and any mouse tracking is provided by the user control. One could modify the user control to support this type of thing.

[Matplotlib](https://matplotlib.org/) (a successful graphing library for Python) doesn't provide object/mouse interactivity, but I can see the utility in adding "hover over a point to show its value" (https://github.com/swharden/ScottPlot/issues/9) and "drag-and-drop axis lines" (https://github.com/swharden/ScottPlot/issues/11) to ScottPlot so I'll leave this ticket open until I decide whether or not to add this functionality to [ScottPlot v3](https://github.com/swharden/ScottPlot/branches). 

I just added some code that continuously shows where the mouse is hovering in both pixel coordinates and graph unit coordinates which is a start. To add mouse/object interaction you'd have to determine which object is under the mouse and add custom code to the mouseDown and mouseUp functions which move that object around.

I'll leave this ticket open until I determine how feasible this is, and close it when I either have a working demo or decided not to support it for now.

https://github.com/swharden/ScottPlot/blob/09c23c89f24477e645b7baca816041208e57e6a7/src/ScottPlot/ScottPlotUC.cs#L87-L92

```
cursor is at {X=597,Y=212} which is {X=7.141343, Y=0.659011}
cursor is at {X=594,Y=201} which is {X=7.099603, Y=1.213397}
cursor is at {X=578,Y=188} which is {X=6.87699, Y=1.86858}
cursor is at {X=554,Y=172} which is {X=6.543071, Y=2.674959}
cursor is at {X=517,Y=153} which is {X=6.02828, Y=3.632534}
cursor is at {X=482,Y=143} which is {X=5.541315, Y=4.136521}
cursor is at {X=450,Y=136} which is {X=5.096089, Y=4.489312}
cursor is at {X=436,Y=136} which is {X=4.901303, Y=4.489312}
cursor is at {X=434,Y=136} which is {X=4.873477, Y=4.489312}
cursor is at {X=434,Y=137} which is {X=4.873477, Y=4.438913}
cursor is at {X=452,Y=143} which is {X=5.123916, Y=4.136521}
cursor is at {X=499,Y=151} which is {X=5.777841, Y=3.733332}
cursor is at {X=560,Y=157} which is {X=6.626551, Y=3.430939}
cursor is at {X=626,Y=165} which is {X=7.544828, Y=3.02775}
cursor is at {X=697,Y=171} which is {X=8.532672, Y=2.725358}
cursor is at {X=754,Y=173} which is {X=9.325729, Y=2.62456}
cursor is at {X=797,Y=173} which is {X=9.924001, Y=2.62456}
cursor is at {X=819,Y=173} which is {X=10.23009, Y=2.62456}
cursor is at {X=829,Y=173} which is {X=10.36923, Y=2.62456}
cursor is at {X=830,Y=173} which is {X=10.38314, Y=2.62456}
```

**Comment by plumforest** [comment]
Thanks for your replay.

**Comment by swharden** [comment]
ScottPlot now supports draggable axis lines. I'm going to test it out for a few days before I update it on NuGet, and until now and then the API might change slightly, but the code on GitHub now has this capability.

## Demo
* [compiled click-to-run demo](https://github.com/swharden/ScottPlot/tree/master/demos/ScottPlotDraggableMarkers/compiled)
* [source code](https://github.com/swharden/ScottPlot/tree/master/demos/ScottPlotDraggableMarkers/)

![](https://raw.githubusercontent.com/swharden/ScottPlot/master/demos/ScottPlotDraggableMarkers/screenshot.png)

## Usage
Indicate an axis is draggable when you first create it:
```cs
scottPlotUC1.plt.PlotHLine(position, draggable: true);
```

You can pull axis line positions from the _plottables_ List
```cs
var plottables = scottPlotUC1.plt.GetPlottables();
for (int i = 0; i < plottables.Count; i++)
{
	if (plottables[i] is ScottPlot.PlottableAxLine axLine)
	{
		string lineType = (axLine.vertical) ? "VLine" : "HLine";
		msg += $"{i}: {lineType} at {Math.Round(axLine.position, 4)}\r\n";
	}
}
```

I added events related to mouse/object interaction to ScottPlotUC you could use to trigger events when axis lines are dragged and dropped. The new events are: `MouseDownOnPlottable`, `MouseDragPlottable`, and `MouseDropPlottable`. See the [source code of the demo program](https://github.com/swharden/ScottPlot/blob/00070b6d03c1d49ad5eb208f6e71b644811e0935/demos/ScottPlotDraggableMarkers/Form1.cs#L73-L91) for an idea of how they work.
