### ISSUE TITLE
bugs in ScottPlot Settings pop-up menu

### ISSUE THREAD

**Issue by bukkideme** [swharden/ScottPlot#110]
Hello!
I played with the latest version, very nice new features! :)
However, I noticed so far a couple of issues:

1.: typing in a new axis limit, then clicking on "Apply" does not render/refresh the Graph to the new axis settings. This update only happens when we drag and pan the graph or do other operation.

2.: If we do not select any line in the "Plot Objects" window, and click on "Export CSV", we get an unhandled exception (System.ArgumentOutOfRangeException: 'Index was out of range. Must be non-negative and less than the size of the collection.). 
Since this settings pop-up window is a built-in feature, maybe this kind of error should be handled and even report to the user like "No Plot Object was selected, nothing to export!"...

**Comment by swharden** [comment]
Thanks for bringing these issues to my attention @bukkideme!

1: to fix the graph not updating after manually setting the axis limits I will add a call to `Render()` at the end of this block:
https://github.com/swharden/ScottPlot/blob/03356ace99f1e7b010caf259a1bd0274a121b512/src/ScottPlot/UserControls/FormsPlot.cs#L81-L84

2: To fix the error when you click export with nothing available to export, I'll simply gray-out the "export" button when that list is empty.

**Comment by swharden** [comment]
These issues are fixed now. I'll work tonight to further improve this settings window. Thanks again @bukkideme!

**Comment by swharden** [comment]
FYI new menu

![image](https://user-images.githubusercontent.com/4165489/63477884-55aa5000-c455-11e9-81f3-243397848b95.png)
