### ISSUE TITLE
Y axis labels - prevent auto scaling to +number

### ISSUE THREAD

**Issue by Bhandejiya** [swharden/ScottPlot#116]
When zoomed, the Y axis goes to auto-scaling and gives +number.

Is it possible to prevent that and display full range numbers in floating points?

**Comment by swharden** [comment]
Hi @Bhandejiya, 

This feature was just published on NuGet so you will have to upgrade to ScottPlot 3.1.3, but you can then customize this behavior like this:

```cs
formsPlot1.plt.Ticks(useExponentialNotation: false);
formsPlot1.plt.Ticks(useOffsetNotation: false);
formsPlot1.plt.Ticks(useMultiplierNotation: false);
```

**Comment by swharden** [comment]
I created cookbook demos to demonstrate this:

https://github.com/swharden/ScottPlot/tree/master/cookbook#multiplier-notation-default

https://github.com/swharden/ScottPlot/tree/master/cookbook#multiplier-notation-disabled
