### ISSUE TITLE
multiplier cut-off when no horizontal label

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#117]
The problem is that the multiplier gets cut-off when no horizontal axis label is used. This is not an easy problem to solve.

* A fixed padding is required. Otherwise mouse tracking becomes very difficult.
* We can't just increase the padding below the chart because most of the cookbook examples look bad (too much white space).
* Maybe we should move the multiplier _inside_ the data area?

![28_Axis_Exponent_And_Offset](https://user-images.githubusercontent.com/4165489/63655199-52fc7300-c753-11e9-8c07-2c57c8f42595.png)

**Comment by Bhandejiya** [comment]
A normal chart reader may confuse/find inconvenient if the multiplier is moved inside the chart area. 

It appears to be a problem for x-axis only.  

Is it possible to add a default one white space in x label to solve this issue?

**Comment by swharden** [comment]
> default one extra white space in x label

@Bhandejiya I think you're right. This solution is not ideal because most charts don't use multiplier notation, however it seems better than the alternative (being cut off).

**Comment by swharden** [comment]
I just made the change 16cb018155bbf469b59606ba9b0ba7abbdc806f9

... but _every_ image has more whitespace below the chart now.

![image](https://user-images.githubusercontent.com/4165489/63656031-63195000-c75d-11e9-97a8-4a5f69385431.png)
