### ISSUE TITLE
Fully working code in cookbook examples

### ISSUE THREAD

**Issue by StendProg** [swharden/ScottPlot#122]
Cookbook realy usefull part of this project. But code in examples not fully work. Data generation remains hidden. So it's not possible copy and run the code without thinking.
Will it possible to make some spoiler button near short code block, what reveals fully working code?

**Comment by swharden** [comment]
Very good idea @StendProg!

I updated the cookbook so all examples are self-contained: https://github.com/swharden/ScottPlot/tree/master/cookbook
