### ISSUE TITLE
QuickPlot - a developmental plotting library

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#123]
**History:** ScottPlot was an example from https://github.com/swharden/Csharp-Data-Visualization which grew too large and became its own project. ScottPlot has had 4 major versions, each coded from scratch as the tasks associated with plotting data became better understood. 

**Future:** One more iteration may be helpful to add support for multiple graphics systems (e.g., OpenGL), a better method of laying-out the figure (especially concerning axis ticks), and a simpler way to interact with the mouse (so user controls aren't so complicated).

**Proposal:** This version of ScottPlot (v3) works very well and I will continue to develop and maintain it. I'd like to start working on the next iteration of this project. I could either do this as a v4 branch of ScottPlot, or I could create a new project with a new name. Creating a new project seems like a good idea because (1) it wouldn't break the ScottPlot API for people already using it, and (2) we could choose a more descriptive name for the library.

**Developmental project:** QuickPlot (https://github.com/swharden/QuickPlot)

**Comment by bukkideme** [comment]
Yep, not breaking the existing API would be preferable, so I vote for a new project name. QuickPlot sounds good too!

**Comment by StendProg** [comment]
I'm already used to the ScottPlot, so ScottPlot v4  is more preferably for me. QuickPlot also looks like nice name. There are 3 simple rools for naming IMHO - short, easy to say, easy to remember, all another not so important.
Rewriting all project from scratch looks crazy (lots of work). But you better know that to do with this project.

**Comment by swharden** [comment]
> Not breaking the existing API would be preferable. QuickPlot sounds good too!

I started a project for testing:\
https://github.com/swharden/QuickPlot

> Rewriting all project from scratch looks crazy (lots of work)

Yet it is crazy =] 

It might not happen, but we'll see how far I get before I burn out! I'll keep supporting and developing ScottPlot in the mean time.

**Comment by swharden** [comment]
> I'm already used to the ScottPlot, so ScottPlot v4 is more preferably for me.

I want the new library to support multiple plots per figure. This is a pretty big breaking change. Users will primarily interact with `Figure` objects (which contain one or more `Plot` objects).

https://github.com/swharden/QuickPlot#code-concepts

Since you're used to ScottPlot v3, maybe this is a good reason to keep ScottPlot how it is.

**Comment by swharden** [comment]
QuickPlot has matured a lot. It has some fancy things. Mouse-interactive multi-plot figures are nice!

Skia was nice to work with, and combined with OpenGL it runs really fast, but it's not easy to get working on all systems (https://github.com/swharden/QuickPlot/issues/1). GDI+ is slow, but I think I'm going to keep using it because it simply works.

I'll turn my efforts back toward improving ScottPlot for now.

![image](https://user-images.githubusercontent.com/4165489/65391029-12801d00-dd32-11e9-9aef-b4331f3b2e32.png)
