### ISSUE TITLE
Overlapping axis label and tick values

### ISSUE THREAD

**Issue by bukkideme** [swharden/ScottPlot#127]
If we deactivate the multiplier option, the tick and axis labels overlap. See screenshots below.

![MultiplierON](https://user-images.githubusercontent.com/51174971/64613871-7a9c3e00-d3d7-11e9-8743-2105841f0eed.png)
![MultiplierOFF](https://user-images.githubusercontent.com/51174971/64613884-7d972e80-d3d7-11e9-94cb-28df34e1d4e9.png)

**Comment by swharden** [comment]
Hi @bukkideme thanks for reporting this. It seems the layout is not properly detecting and adjusting for the width of tick labels. It seems the [extra padding](https://github.com/swharden/ScottPlot/tree/master/cookbook#extra-padding) cookbook example is not producing the proper output. This code helps reproduce the error:
```cs
Random rand = new Random(0);
double[] xs = ScottPlot.DataGen.Consecutive(100);
double[] ys = ScottPlot.DataGen.RandomWalk(rand, 100, 1e2, 1e15);
formsPlot1.plt.YLabel("vertical units");
formsPlot1.plt.XLabel("horizontal units");
formsPlot1.plt.Ticks(useOffsetNotation: false, useMultiplierNotation: false);
formsPlot1.plt.PlotScatter(xs, ys);
formsPlot1.Render();
```

Using the ScottPlot (current source code, not the version on NuGet) this hack can fix your problem for now:
```cs
formsPlot1.plt.GetSettings().ticks.y.maxLabelSize = new SizeF(100, 100);
formsPlot1.plt.TightenLayout();
formsPlot1.Render();
```

... but a more permanent solution is needed! I'll work on this over the next few days. I've made a lot of progress on an improved layout system for [QuickPlot/dev](https://github.com/swharden/QuickPlot/tree/master/dev) so I look forward to bringing some of those ideas into ScottPlot.

**Comment by swharden** [comment]
I think this is solved! I'd still like to improve the layout engine... but it might be a while! It's more complicated than I thought.

Here's a cookbook picture to help us identify if this issue arises again:
https://github.com/swharden/ScottPlot/tree/master/cookbook#automatic-left-padding
