### ISSUE TITLE
replacing DataReceived in serial data plotter

### ISSUE THREAD

**Issue by strocchia** [swharden/ScottPlot#128]
Hi Scott,

This is great, I really like the simple UI you have created! I'm trying to make my own serial plotter implementation for a singular recording channel (whereas you have 4 ADC measurements). I've been reading a lot of blog & stackoverflow posts saying that using the 'DataReceived' event trigger is bad because it is unreliable and does not make proper use of the underlying Win32 API. Are you aware of this? I'm curious if you have recommendations on reliable data streaming. Thanks!

_Originally posted by @strocchia in https://github.com/swharden/ScottPlot/issues/82#issuecomment-530006377_

**Comment by swharden** [comment]
Hi @strocchia, 

Your post refers to the use of the event here:
https://github.com/swharden/ScottPlot/blob/020d0aed5521c46cb190fd2cc20f1baadb9ee837/demos/src/serial-data-plotter/Form1.cs#L67-L70

I haven't had any trouble with the use of `DataReceived`, but I'm also using this for relatively slow speed data (about 100 lines per second).

In the past I wrote a "serial listener" class which continuously and repeatedly runs `ser.ReadLine()`. The use of `DataReceived` seemed better than this, but I wasn't aware of its controversy. It seems to work well in my hands!

A quick google makes me think this problem affects systems which attempt to do a lot of work in the `DataReceived` function. I think if you minimize the task of your function to just adding lines of text to a buffer, then only processing that buffer when your CPU is free, you'll probably be fine!

Hope it helps,
Scott

**Comment by swharden** [comment]
Update: a better description of the problem (and workarounds) is here: http://www.sparxeng.com/blog/software/must-use-net-system-io-ports-serialport
