### ISSUE TITLE
version specification in readme

### ISSUE THREAD

**Issue by plumforest** [swharden/ScottPlot#13]
From the latest readme file , there are three main versions of ScottPlot, while v2 and v3 are in actively developed.

Would you please add some spec on these versions to get an introduction about features difference between them?

**Comment by plumforest** [comment]
API of v3 is very different from v2. 
How can I get a no-axis graph？
Code for v2 is like this:
`scottPlotUC1.plt.settings.SetDataPadding(0, 0, 0, 0);`

**Comment by swharden** [comment]
> From the latest readme file , there are three main versions of ScottPlot, while v2 and v3 are in actively developed. Would you please add some spec on these versions to get an introduction about features difference between them?

Thanks for the suggestion. I added additional information to the [Previous Versions](https://github.com/swharden/ScottPlot/blob/master/README.md#previous-versions) section of the front page.

_"ScottPlot has improved in performance and simplicity over time. Changes which resulted in a change to the API were compartmentalized into major release versions. It is recommended you use the latest version of ScottPlot for new projects, but all versions can be downloaded for backward-compatibility with existing projects. Each version has its own cookbook demonstrating how to use the API."_

> How can I get a no-axis graph? I dig into the source code for hours and fail to find an easy way to set the graph to zero-padding.

I'm sorry you had difficulty discovering how to do this. The "Frameless Plot" example in the cookbook shows how to create a plot with no axis:
https://github.com/swharden/ScottPlot/blob/master/doc/cookbook/README.md#frameless-plot

```cs
plt.Frame(drawFrame: false);
```
