### ISSUE TITLE
Mouse location on plot

### ISSUE THREAD

**Issue by AndrewN199** [swharden/ScottPlot#139]
I'm new to scottplot so if this is mentioned elsewhere please let me know. Is there a way to find the location of the mouse on the plot and put the values in the plot?

Ideally I'd like it to be pinned to the curve its plotting.

**Comment by swharden** [comment]
Hi @AndrewN199 

ScottPlot will plot values in a double array. You cannot use the mouse to change the content of the array (so no adding values of moving values) using ScottPlot, but you can write your own event handlers to do this if it is necessary for your application.

You can convert between pixel locations and coordinates using `plt.CoordinateFromPixel()` and `plt.CoordinateToPixel()`

If your goal is to interact with the mouse (a slightly different topic), you'll find the "show value on hover" demo (in the demos folder) useful.

Hope it helps!
