### ISSUE TITLE
GetPixel bug

### ISSUE THREAD

**Issue by plumforest** [swharden/ScottPlot#14]
[Settings.cs#L365](https://github.com/swharden/ScottPlot/blob/4ad7ebce39b1b7c975f3f4fbb24be38794287738/src/ScottPlot/Settings.cs#L365)

Take the X as example,
` int xPx = (int)((locationX - axis[0]) * xAxisScale);`
should be
` int xPx = (int)((locationX - axis[0]) * xAxisScale)+ dataOrigin.X;`
？

This fix cause new problem when render new graph. Sad!

**Comment by swharden** [comment]
Hi @plumforest. It seems you found that the GetPixel function is working well, and that changing it causes graphs to malfunction. Note that all cookbook examples produce their graphs without having to interact with the settings module: https://github.com/swharden/ScottPlot/blob/master/doc/cookbook/

In response to this ticket I added inline comments to clarify what these functions do and what tasks they were designed for:

https://github.com/swharden/ScottPlot/blob/8e6b8fac9e735733f71b34194df8101ab5ce43f3/src/ScottPlot/Settings.cs#L365-L372

https://github.com/swharden/ScottPlot/blob/8e6b8fac9e735733f71b34194df8101ab5ce43f3/src/ScottPlot/Settings.cs#L374-L381
