### ISSUE TITLE
Make "quickstart wpf" demo project UI layout look consistent when zooming.

### ISSUE THREAD

**Issue by morningkyle** [swharden/ScottPlot#142]
Tested on master branch, "quickstart wpf" startup UI looks like this:
 
<img width="436" alt="WpfPlot_Startup" src="https://user-images.githubusercontent.com/31173219/66020230-01e15b00-e519-11e9-86e0-34f7e412132d.PNG">

When zooming out the UI, the relative position of the "Add Plot" and "Clear" buttons do not keep consistent.  For example, when zooming out to full screen, it looks like this:
<img width="960" alt="WpfPlot_FullScreen" src="https://user-images.githubusercontent.com/31173219/66020417-98ae1780-e519-11e9-8caa-a94605d17323.PNG">

**Comment by morningkyle** [comment]
I made a small [PR ](https://github.com/swharden/ScottPlot/pull/143)to improve the UI layout and make it work consistently after zooming.  Although added a few lines layout control, hopefully, it does not increase the complexity of the demo code.

**Comment by swharden** [comment]
Hi @morningkyle, thanks for improving the WPF quickstart application! 

The WPF user control and demos are far under-developed compared to the WinForms code, so I'm happy to get input from someone more experienced with WPF!

I'd like to merge this in, but pull #143 has some layout-related code that I'm not yet ready to merge (issue #144). If you simplify the PR to only contain WPF-related changes, I'll merge it in right away!

**Comment by swharden** [comment]
Thanks @morningkyle!

**Comment by morningkyle** [comment]
OK, I have  updated last PR to this [PR](https://github.com/swharden/ScottPlot/pull/145), with only one file changed.
