### ISSUE TITLE
Add unit test to better qualify ScottPlot

### ISSUE THREAD

**Issue by morningkyle** [swharden/ScottPlot#147]
I see discussions [here](https://github.com/swharden/QuickPlot/issues/1). Since ScottPlot has already released 3.1.4, I guess it is not too early/late to discuss about adding unit test:)  Here is my proposal for the first step:

- [x]  Choose a suitable unit test framework
- [x]  Start adding minimal test for console based APIs
- [x] Watch and see how it is going and add more tests while involving the existing APIs

@swharden  How do you think about this topic?

**Comment by swharden** [comment]
Hi @morningkyle, 

YES! I will classify ScottPlot v3 and its API as "stable" and start adding some unit tests. 

You've probably noticed at [QuickPlot](https://github.com/swharden/QuickPlot/), in the discussion on [QuickPlot#1](https://github.com/swharden/QuickPlot/issues/1), and from recent comments in #86 that I have been ready to significantly rearrange (or even rewrite) the entire code base to maximize portability (.NET Standard), improve/simplify the class structure, support multiple-plot figures, and perhaps even use a different rendering engine (with hardware acceleration). These looming changes have made me hesitant to write meticulous tests for ScottPlot, as its internal structure seemed like a moving target and its content may even be fully rewritten shortly. I think the decision to preserve v3 is a good one, as it allows unit tests to be written immediately and gives comfort to its users that its API will no longer change. I will confine all my large-scale changes to an experimental v4 branch which may take months before it's ready for use.

I'll leave this ticket open until I have some tests up and running with Azure Pipelines

**Comment by swharden** [comment]
* I set-up unit testing with the Visual Studio Testing platform
* I configured Azure Pipelines to automatically run these tests
* I converted all the [cookbook figures](https://github.com/swharden/ScottPlot/tree/master/cookbook) into individual unit tests
* Additional unit tests can be added to [UnitTest1.cs](https://github.com/swharden/ScottPlot/blob/master/tests/ScottPlotTests/UnitTest1.cs)

```
Test Run Successful.
Total tests: 59
     Passed: 59
 Total time: 12.2865 Seconds
```

@morningkyle, thanks for encouraging me to set this up! Feel free to add special tests from here if you think they would be helpful.
