### ISSUE TITLE
nuget package 

### ISSUE THREAD

**Issue by plumforest** [swharden/ScottPlot#15]
I saw ScottPlot at the nuget and wanted to be the first downloader.
Howerver, I failed since .net framework version 4.5/4.6 lower than that one you build(4.7?).

I do suggest you to make the minimum version reset to be 4.5. It should be work as I successful run the source code v3.

**Comment by swharden** [comment]
Hi @plumforest, I'm happy to hear you found ScottPlot on NuGet!

I just recompiled ScottPlot using the .NET 4.5 Framework and it is available as ScottPlot 3.0.2 on NuGet:
https://www.nuget.org/packages/ScottPlot/

Let me know if this works for you!

**Comment by plumforest** [comment]
@swharden , the 3.0.2 version nuget package  works very well.
