### ISSUE TITLE
[Feature request] Tick value aliasing in PlotSignal

### ISSUE THREAD

**Issue by citizen3942** [swharden/ScottPlot#155]
In PlotSignal, we just have a sequence of ys, that are indexed. What could be a nice feature is to define a custom xSpacing and alias or rename or recalculate these values with a function/equation *f(i)*. Also a rounding for these values could be implemented here.

For example:
I have index 52,41375 that must correspond to 10 kHz
or 104,8257 that must be 20 kHz
and so on.

**Comment by swharden** [comment]
Hi @citizen3942, does this solve your problem?

```cs
plt.PlotSignal(ys: data, sampleRate: 524.1375‬);
```

The `data[52,41375]` will have the horizontal value of 10,000, and `data[104,8257]` will have a horizontal value of 20,000
