### ISSUE TITLE
.NET version bug in designer?

### ISSUE THREAD

**Issue by bukkideme** [swharden/ScottPlot#161]
Hi!

It happened that I need to develop some RS232 data logger for some of our old measurement systems, running Windows XP SP3 OS. 
Since we talk about XP, I set the Target framework to version 4, and I run these builts EXEs just fine on these WinXP machines.
I would like to use ScottPlot in these projects, so I just installed ScottPlot via nuget. However, I just cannot find FormsPlot control in the Toolbox, neither VS can recognize the "using ScottPlot;" line in my code.

My question is that, can ScottPlot be used in .NET 4.0 Winform projects?
Steps to reproduce the issue (?):
1. Create a new Winform project in VS 2019 Community Edition
2. Set the Target Framework to version 4.
3. Install ScottPlot package via nuget. It installs just fine.
4. ScottPlot.FormsPlot cannot be found in Toolbox, so cannot be added to the Form.
5.  Even if you set Target Framework back to 4.7.2, ScottPlot cannot be used/found in the Form/Toolbox.

**Comment by bukkideme** [comment]
I should read before opening an issue:
the first page states that ScottPlot targets dotnet 4.5 😁
Sorry for opening the issue. :)

**Comment by swharden** [comment]
Hi @bukkideme, it should work with any .NET Framework version 4.5 and up. It doesn't _only_ work on 4.5.

Here's a screenshot where I installed it with NuGet in a .NET Framework 4.7.2 project
![image](https://user-images.githubusercontent.com/4165489/67950425-ea50cd00-fbbf-11e9-9ec4-6c4bec099d4e.png)

**Comment by swharden** [comment]
> 5. Even if you set Target Framework back to 4.7.2, ScottPlot cannot be used/found in the Form/Toolbox.

You might have to re-install it with NuGet after changing your framework 🤔

**Comment by bukkideme** [comment]
> > 1. Even if you set Target Framework back to 4.7.2, ScottPlot cannot be used/found in the Form/Toolbox.
> 
> You might have to re-install it with NuGet after changing your framework 🤔

Yes, I meant dotNET 4.5 and above.
Re-installation does not work, I cannot get FormsPlot control in Toolbox :( I had to create a new project and copy my code there, this was the only way.
