### ISSUE TITLE
Second X and Y axes - feature request 

### ISSUE THREAD

**Issue by bukkideme** [swharden/ScottPlot#162]
Is it possible to plot secondary X and Y axes, using the recent version? If not, can we get such feature in one of the next releases?
thanks! :)

**Comment by swharden** [comment]
This is surprisingly difficult to implement in ScottPlot. I'll take a closer look and see what options are available...

Dual-axes are present in QuickPlot https://github.com/swharden/QuickPlot/issues/12#issuecomment-546740606 but that project isn't mature yet.

**Comment by swharden** [comment]
Unfortunately, this would take a lot of work because ScottPlot was not designed to support multiple axes (or nonlinear axes) and adding this would require modifying a lot of modules. This request is not impossible to achieve, but I don't think it's a good use of my time at this point. Instead, I would like to invest my development time into further developing QuickPlot (which _already_ supports multi-Y axis plots).

... what would you think about having non-interactive multi-axis plots? It's a bit of a hack, but this could be done by creating two ScottPlots, matching their layouts (but having different axes), rendering them as Bitmaps with transparent backgrounds, then "adding" them on top of each other and saving the output. I could add a function to the `ScottPlot.Tools` module which does this 🤔

**Comment by bukkideme** [comment]
Thanks for looking into this option! And I totally understand that efforts need into QuickPlot now. Actually I just convinced myself that a second Y-axis plot is not really needed. I just make a selector on the GUI where the user can select between two plots, this is fast and simple.
Another option could be just to create two plots top of each other, and match their time axis. This would help to see trends and correlations...

**Comment by el-aasi** [comment]
> Unfortunately, this would take a lot of work because ScottPlot was not designed to support multiple axes (or nonlinear axes) and adding this would require modifying a lot of modules. This request is not impossible to achieve, but I don't think it's a good use of my time at this point. Instead, I would like to invest my development time into further developing QuickPlot (which _already_ supports multi-Y axis plots).
> 
> ... what would you think about having non-interactive multi-axis plots? It's a bit of a hack, but this could be done by creating two ScottPlots, matching their layouts (but having different axes), rendering them as Bitmaps with transparent backgrounds, then "adding" them on top of each other and saving the output. I could add a function to the `ScottPlot.Tools` module which does this 🤔

Did you get to implement it? :)

**Comment by el-aasi** [comment]
@swharden ah no, I was aware that the full (proper) implementation for the double axes is still on the road map, I was meaning the hack around for static (using transparent pictures) for the ScotPlott.Tools?

**Comment by swharden** [comment]
This sample code demonstrates how to merge two plots to simulate multiple Y axes. It is pretty bad.

```cs
// create one plot with small numbers
var plt1 = new ScottPlot.Plot(400, 300);
plt1.PlotSignal(new double[] { 1, 3, 2, 4 }, color: Color.Blue);

// greate another plot big numbers
var plt2 = new ScottPlot.Plot(400, 300);
plt2.PlotSignal(new double[] { 200, 400, 100, 200 }, color: Color.Red);

// make it clear with no ticks
plt2.Style(figBg: Color.Transparent, dataBg: Color.Transparent);
plt2.YTicks(new double[0], new string[0]);

// draw the second plot on top of the first one
var bmp1 = plt1.GetBitmap();
var bmp2 = plt2.GetBitmap();
Bitmap bmp = new Bitmap(bmp1);
using var gfx = Graphics.FromImage(bmp);
gfx.DrawImage(bmp2, 0, 0);
bmp.Save("combined.bmp");
```

![image](https://user-images.githubusercontent.com/4165489/95472370-f22cfb80-0950-11eb-8cc4-cbe59fb1a2e6.png)
 
Problems:
* You can only show one of the Y axis ticks
* There is not support for showing ticks on the right side yet
* Grid lines overlap the lower plot
* This is not mouse interactive

I hope this helps!

**Comment by el-aasi** [comment]
> This sample code demonstrates how to merge two plots to simulate multiple Y axes. It is pretty bad.
> 
> ```cs
> // create one plot with small numbers
> var plt1 = new ScottPlot.Plot(400, 300);
> plt1.PlotSignal(new double[] { 1, 3, 2, 4 }, color: Color.Blue);
> 
> // greate another plot big numbers
> var plt2 = new ScottPlot.Plot(400, 300);
> plt2.PlotSignal(new double[] { 200, 400, 100, 200 }, color: Color.Red);
> 
> // make it clear with no ticks
> plt2.Style(figBg: Color.Transparent, dataBg: Color.Transparent);
> plt2.YTicks(new double[0], new string[0]);
> plt2.XTicks(new double[0], new string[0]);
> plt2.Grid(false);
> 
> // draw the second plot on top of the first one
> var bmp1 = plt1.GetBitmap();
> var bmp2 = plt2.GetBitmap();
> Bitmap bmp = new Bitmap(bmp1);
> using var gfx = Graphics.FromImage(bmp);
> gfx.DrawImage(bmp2, 0, 0);
> bmp.Save("combined.bmp");
> ```
> 
> ![image](https://user-images.githubusercontent.com/4165489/95472798-72ebf780-0951-11eb-83ce-87c1852d0269.png)
> 
> The biggest limitation is that you can only show ticks for one Y axis (since there is not support for showing ticks on the right side yet)...
> 
> I hope this helps!

I am not sure that you picked the correct image, if so maybe I don't understand exactly what you did in there :)) (visual wise), in any case, let me take this into a new issue, and I will explain in more detailed exactly where I think an issue occurs.
