### ISSUE TITLE
Modifying plotted data - zero sized arrays as inputs?

### ISSUE THREAD

**Issue by bukkideme** [swharden/ScottPlot#163]
I wonder how to handle the following scenario.
I continuously collect measurement data, and put it into arrays. Regarding to the example at Cookbook section "Modifying plotted data": 

> / After an array is plotted with PlotSignal() or PlotScatter() its contents 
//   can be updated (by changing values in the array) and they will be displayed 
//   at the next render. This makes it easy to create live displays.

However, I would like to call PlotScatter() method only once before starting the measurement, in the Form.Load() event. After this whenever I add data to the arrays, I just need to call the Render() method to update the plot. Recently PlotScatter cannot handle zero sized arrays, and throws an error. Of course I can just program around this issue (I call the PlotScatter once in the data adding event when the first data pair generated), but what do you think, should the PlotScatter accept zero sized arrays simply?

**Comment by swharden** [comment]
Check out the "Live Data" demos in the demo application. Do these examples help you come up with a way to plot measurement data?

![image](https://user-images.githubusercontent.com/4165489/67965477-7bcc3900-fbd8-11e9-97cb-debdcb254901.png)

**Comment by bukkideme** [comment]
Yes, they do! Thanks!
