### ISSUE TITLE
user control: overridable OnDoubleClick event

### ISSUE THREAD

**Issue by FadyDev2** [swharden/ScottPlot#166]
Is it possible to make the benchmark hint disabled?
If yes, is it possible to allow for a DoubleClick event on the plot for implementing custom functionality (like opening the chart in a bigger window if double clicked)?

Thanks in advance for your help.

**Comment by swharden** [comment]
> Is it possible to override the double-click event to do something custom (instead of toggling benchmark display)?

I like this idea! I'll implement this shortly and add a demo which shows how to override the event.

**Comment by swharden** [comment]
@FadyDev2 I just committed changes which I think solves this issue. I created a demo program which demonstrates these features too. These features aren't on NuGet yet, but I'll probably make a release this weekend.

### Disable double-click benchmark toggling
https://github.com/swharden/ScottPlot/blob/bc6b1d6c3cf12601a2f3d309a09892c10a83fb45/demos/WinForms/Demos/FormOverride.cs#L28

### Perform custom action on double-click
FormsPlot has some custom events which you can bind to:

![image](https://user-images.githubusercontent.com/4165489/68438224-70a57a00-0191-11ea-826b-0133ba7ba7d5.png)

https://github.com/swharden/ScottPlot/blob/3524818f6f90013154ade97ec35e1781e42eddf7/demos/WinForms/Demos/FormOverride.cs#L55-L59

**Comment by swharden** [comment]
this feature is now in the latest NuGet package
https://github.com/swharden/ScottPlot/releases
