### ISSUE TITLE
multi-plot figure

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#167]
Create a class for creating multi-plot images with ScottPlot (not for use by its user controls):

```cs
var mp = new ScottPlot.MultiPlot(width: 800, height: 600, rows: 2, cols: 2);
mp.subplots[0].PlotSignal(someData1);
mp.subplots[1].PlotSignal(someData2);
mp.subplots[2].PlotSignal(someData3);
mp.subplots[3].PlotSignal(someData4);
mp.SaveFig("multiplot.png");
```

Make it easy to match axes/layouts between plots:

```cs
var mp = new ScottPlot.MultiPlot(width: 800, height: 600, rows: 2, cols: 1);

mp.subplots[0].Title("First Dataset");
mp.subplots[0].PlotSignal(someData1);
mp.subplots[1].Title("Second Dataset");
mp.subplots[1].PlotSignal(someData2);

// apply the axes and layout from plot 1 to plot 2
mp.subplots[1].MatchAxis(mp.subplots[0]);
mp.subplots[1].MatchLayout(mp.subplots[0]);

mp.SaveFig("multiplot.png");
```

**Comment by swharden** [comment]
That was easy: 

### Multiplot.cs

https://github.com/swharden/ScottPlot/blob/5c8af86a1f3d1908c67bc077f867dfebde142a76/src/ScottPlot/MultiPlot.cs#L9-L84

### Cookbook Example
https://github.com/swharden/ScottPlot/blob/5c8af86a1f3d1908c67bc077f867dfebde142a76/tests/Cookbook.cs#L1408-L1425

### Cookbook Output
![image](https://user-images.githubusercontent.com/4165489/68348936-76378d00-00c9-11ea-9a85-217ba0fd599b.png)

**Comment by jsr1611** [comment]
Hello @swharden ,
Please, elaborate on how this code can be integrated with Winforms.
Like, where is the code part that generates FormsPlot ?
At least give some guide how to start it...

Thank you!

**Comment by swharden** [comment]
Hi @jsr1611, 

The multiplot module is only for use in console applications. If you want to create a WinForms (or WPF) application with multiple plots, drag/drop multiple FormsPlot (or WpfPlot) controls onto your form.

If you want to get fancy and link axes of different plots together, the ScottPlot demo https://swharden.com/scottplot/demo demonstrates how this can be done (with source code in this repo).

Hope it helps!
Scott
