### ISSUE TITLE
CandleStick fails when plotting a single point

### ISSUE THREAD

**Issue by Minu476** [swharden/ScottPlot#172]

**Comment by swharden** [comment]
Hi @Minu476 I'm not sure I understand the issue.

One can create an OHLC like this:
```cs
var ohlc = new ScottPlot.OHLC(open, high, low, close, timeSeconds);
```

An array of OHLC objects can be plotted with:
```cs
plt.PlotCandlestick(ohlcArray);
```

Is the problem that a crash occurs when plotting an array with only one ohlc?

**Comment by Minu476** [comment]
If there is only one data point on some plottables, IndexOutOfBound exception will be triggered.

**Comment by Minu476** [comment]
Hi scaot this is Nasser

**Comment by Minu476** [comment]
scott

**Comment by swharden** [comment]
> If there is only one data point on some plottables, IndexOutOfBound exception will be triggered.

Thanks for the clarification Nasser! I'll look into this one shortly

**Comment by swharden** [comment]
The for block should only run if there's more than 1 candle:

https://github.com/swharden/ScottPlot/blob/b858f9a88e30aab8783f4b8b8549ff7e41cdae02/src/ScottPlot/plottables/PlottableOHLC.cs#L39-L60

**Comment by swharden** [comment]
Fixed this with a one-line modification: https://github.com/swharden/ScottPlot/commit/9966d7e2e4af538b2764573e838cebe242a0fc11

I'll make a new NuGet package this weekend
