### ISSUE TITLE
Changing some properties like color, lineStyle after creating plottable with constructor, has no effect.

### ISSUE THREAD

**Issue by Minu476** [swharden/ScottPlot#173]
```cs
var hb = formsPlot1.plt.PlotScatter(
	Xs[brick].Values.ToArray(), 
	highBands[brick][c].Values.ToArray(), 
	color: Color.Green, 
	lineWidth: 2,
	markerShape: ScottPlot.MarkerShape.none);

hb.label = "Brick_" + brick + "_HB_" + c;
hb.lineStyle = ScottPlot.LineStyle.Dash;
hb.color = Color.Blue;

if (myCurrentTemplate.Plottables.ContainsKey(hb.label))
	hb.visible = myCurrentTemplate.Plottables[hb.label].visible;
else 
	hb.visible = false;
```
in above code snippet lablel and visibility will get modified but color and lineStyle will remain unchanged.

**Comment by swharden** [comment]
Thanks for mentioning this @Minu476. I solved the issue and will publish a new NuGet package this weekend.

I created a test which recreated the original problem

https://github.com/swharden/ScottPlot/blob/3687cd50295431764cce5bf0584634d494c49862/tests/Styling.cs#L13-L36

It now produces the correct output

![image](https://user-images.githubusercontent.com/4165489/68812901-341ac800-0642-11ea-8943-793406eb3ac8.png)

**Comment by Minu476** [comment]
Dear Scott,

Thank you for fixing both  issues. You are very smart and wonderful person!
When I get time; I share my story of lifetime trading system development
with you! There is a light at end of tunnel specially for individuals as
smart as you in that game.

Kind regards,

Nasser
