### ISSUE TITLE
option to define tick positions and labels from arrays

### ISSUE THREAD

**Issue by Minu476** [swharden/ScottPlot#174]
In some chart type such as Renko bars, the bars are not at fixed time intervals.
 DateTime[] Xs={d0,d1,d2,d3,...   dn}
user can select how the datetime should be displayed in multi_Level labels such as enclosed screen shots:
![2019-11-16](https://user-images.githubusercontent.com/15093536/68997742-77ea1900-085e-11ea-8108-2713063ccc75.png)

**Comment by Minu476** [comment]
![2019-11-16 (1)](https://user-images.githubusercontent.com/15093536/68997803-46be1880-085f-11ea-8698-d9523f095b76.png)

**Comment by Minu476** [comment]
May be the best way to implement this feature is to add array of string to XLabel!?

**Comment by swharden** [comment]
Being able to manually set tick positions and labels from arrays would be useful for time charts but also for bar graphs. Perhaps we could create some optional arguments for Ticks() which look something like this?

```cs
double[] positions = {1, 2, 3};
string[] labels = {"one", "two", "three"};
plt.Ticks(manualPositions: positions; manualLabels: labels);
```

**Comment by Minu476** [comment]
Its great! You are idea as always are fantastic.

**Comment by swharden** [comment]
@Minu476 thanks for the suggestion! It might take a few days to implement since this relates to #108 but it'll get done soon. I'll leave this tick open to track its progress.

**Comment by Minu476** [comment]
I noticed that the distinct strings must be plotted when the new index has a different string than the previous index.

**Comment by swharden** [comment]
> I noticed that the distinct strings must be plotted when the new index has a different string than the previous index.

I'm not sure I fully understand your question.

However, if an array of string labels is not given my plan is to have the labels created automatically based on the given positions.

**Comment by Minu476** [comment]
the attached charts will display year and week no of the year in two lines. if you go to shorter interwal will display day of week and hour and minutes.

**Comment by swharden** [comment]
@Minu476 I think your question is, _"When plotting DateTime arrays, will the automatically-generated ticks have a logical tick spacing such as years, months, days, or hours based upon the span of the time range given? Will this tick spacing change appropriately as the graph is zoomed in and out?"_ 

Yes, that is my goal.

Let me know if I misunderstood your question.

**Comment by Minu476** [comment]
I think you got it right, Thank you.

**Comment by swharden** [comment]
I addded `XTicks()` and `YTicks()` which gives the programmer full control of tick positions and labels.

I'll publish a new NuGet package with this feature later today or tomorrow.

I will do more work to allow automatic determination of ideal tick positions and labels, but this will be tracked as part of issue #108

```cs
var plt = new ScottPlot.Plot(600, 400);
plt.Title("Custom Tick Positions and Labels");
plt.PlotSignal(ScottPlot.DataGen.Sin(50));

double[] xPositions = { 7, 21, 37, 46 };
string[] xLabels = { "VII", "XXI", "XXXVII", "XLVI" };
plt.XTicks(xPositions, xLabels);

double[] yPositions = { -1, 0, .5, 1 };
string[] yPabels = { "bottom", "center", "half", "top" };
plt.YTicks(yPositions, yPabels);

plt.SaveFig("customTicks.png");
```

![image](https://user-images.githubusercontent.com/4165489/69000585-16e33500-08a0-11ea-8efb-a67191d0f68f.png)

**Comment by swharden** [comment]
I added this example to the cookbook too
https://github.com/swharden/ScottPlot/tree/master/cookbook#custom-tick-labels

**Comment by Minu476** [comment]
Dear Scott,

Thank you for doing ticks option with custom string., well done! Sorry for
not replying earlier, I was spending time with my grand children.
I hope you are also resting this weekend!

with kind regards,
Nasser
