### ISSUE TITLE
multiple Y axes

### ISSUE THREAD

**Issue by Narvaris** [swharden/ScottPlot#180]
Hi,

Is it possible to have the option plot signals on the left axes or the right axes?
I am looking to plot multiple signals on the same plot with different  y axis resolution.

Thanks!

**Comment by swharden** [comment]
Hi @Narvaris, unfortunately no this is not currently possible with ScottPlot.

This _is_ possible with [QuickPlot (see #12)](https://github.com/swharden/QuickPlot/issues/12), but that project isn't as mature as ScottPlot yet.

**Comment by swharden** [comment]
Following-up, this is possible now:
https://swharden.com/scottplot/faq/multi-axis
