### ISSUE TITLE
CandleChart - Tooltip

### ISSUE THREAD

**Issue by satyat110** [swharden/ScottPlot#181]
Really appreciate your work. I am working on some financial project which I have some candle charts and need some help to achieve below 
- How can I show the open, close, high, low with date on the mouseover each candle?
- How I can make the the X-axis as date from database instead of numbers?
- Based on the volume, can I control the size of the candle?

![chart](https://user-images.githubusercontent.com/58095701/69470955-68336e80-0d4f-11ea-9060-263b67a066dd.png)

**Comment by swharden** [comment]
Hi @satyat110 

## DateTime

> How I can make the the X-axis as date from database instead of numbers?

Inspired by your comment I made a few small improvements to OHLC charts which make it easier to display dates. When constructing an array of OHLC objects, each OHLC now accepts a `DateTime` (which makes a lot more sense than a double). You can then formal the horizontal axis to display tick labels in date format with:

```cs
plt.Ticks(dateTimeX: true);
```

I updated the examples in the cookbook:

* https://github.com/swharden/ScottPlot/tree/master/cookbook#candlestick
* https://github.com/swharden/ScottPlot/tree/master/cookbook#ohlc

![image](https://user-images.githubusercontent.com/4165489/69481966-e8a3af00-0de3-11ea-9989-845c55e838b8.png)

I also updated the financial plot demo:

![image](https://user-images.githubusercontent.com/4165489/69481953-ce69d100-0de3-11ea-9ea7-2cfe0ec90317.png)

## MouseOver events

> How can I show the open, close, high, low with date on the mouseover each candle?

The demo application (advanced tab, interactivity section, "show value on hover" button) shows how to do this with scatter plots. It should be straightforward to add code to the OHLC plot to allow it to perform a similar behavior, but that support is not currently present.

![image](https://user-images.githubusercontent.com/4165489/69482051-9ca53a00-0de4-11ea-8d1c-6a59989051a4.png)

> Based on the volume, can I control the size of the candle?

Not currently. The best way you could do this is to create a new type of plottable object which has price information _including_ volume. Perhaps call it `PlottableOHLCwithVolume`. It would inherit from `Plottable`. Its code would be mostly identical to `PlottableOHLC`, except it would also include volume and render the width of each bar accordingly. ScottPlot has been designed to be pretty easy to add custom plot types to for highly specific applications like yours.

**Comment by satyat110** [comment]
Thanks for your quick response. Let me try your recommendations and update you on this.

**Comment by swharden** [comment]
> Thanks for your quick response. Let me try your recommendations and update you on this.

Sure thing! Also note that my code suggestion uses features in the latest (source) version of ScottPlot. It's not on NuGet yet, but I'm going to release a new package on NuGet later today.

**Comment by swharden** [comment]
I added some code to the finance demo which shows how to get the `DateTime` of the point under the mouse. This should be a pretty strong start!

![image](https://user-images.githubusercontent.com/4165489/69482357-f2c7ac80-0de7-11ea-91cb-7ff09741b89e.png)

**Comment by satyat110** [comment]
Thanks Scott. I can able to add the OHLC values on candle hover over. This works!!!!! 
If we could able to change the background color of the whole text will differentiate and look nice :-)
Any suggestions...

![chartwithValue](https://user-images.githubusercontent.com/58095701/69483628-8b592f00-0dde-11ea-8e57-15bdde9377f3.png)

**Comment by swharden** [comment]
Hey that looks great!

Would you be up for modifying the code of the finance demo so it does this (with pull request), then I can use that as a starting point for improving the styling?

**Comment by satyat110** [comment]
Absolutely. I am more than happy to share the code what I am adding. Give me couple of days....

**Comment by swharden** [comment]
> Give me couple of days....

Sounds good! As soon as this is finished I'll combine your changes with #182 and release a new NuGet package whose improvements focus on OHLC/candlestick.

**Comment by swharden** [comment]
```cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ScottPlotDemos
{
    public partial class FormFinancial : Form
    {
        public FormFinancial()
        {
            InitializeComponent();
            Button1_Click(null, null);
        }

        private void Form1_Load(object sender, EventArgs e)
        {

        }

        private void GenerateNewData()
        {
            Random rand = new Random();

            int pointCount = 100;

            ScottPlot.OHLC[] ohlcs = ScottPlot.DataGen.RandomStockPrices(rand, pointCount);

            double[] volumes = ScottPlot.DataGen.Random(rand, pointCount, 500, 1000);
            double[] timestamps = new double[ohlcs.Length];
            for (int i = 0; i < timestamps.Length; i++)
                timestamps[i] = ohlcs[i].day;

            formsPlot1.plt.Clear();
            formsPlot1.plt.YLabel("Share Price");
            formsPlot1.plt.Title("ScottPlot Candlestick Demo");
            if (rbCandle.Checked)
                formsPlot1.plt.PlotCandlestick(ohlcs);
            else
                formsPlot1.plt.PlotOHLC(ohlcs);
            formsPlot1.plt.Ticks(dateTimeX: true);
            formsPlot1.plt.PlotText("", timestamps[10], ohlcs[10].low, bold: true, fontSize: 10, color: Color.Black);

            //Add an idication in the candle like Stock bought at this day...
            formsPlot1.plt.PlotText("B", timestamps[10], ohlcs[10].high, bold: true, fontSize: 10, color: Color.Blue);
            formsPlot1.plt.AxisAuto();

            formsPlot2.plt.Clear();
            formsPlot2.plt.YLabel("Volume");
            formsPlot2.plt.PlotBar(timestamps, volumes, barWidth: .5);
            formsPlot2.plt.AxisAuto(.01, .1);
            formsPlot2.plt.Axis(null, null, 0, null);
            formsPlot2.plt.Ticks(dateTimeX: true);

            formsPlot1.plt.MatchLayout(formsPlot2.plt, horizontal: true, vertical: false);
           
            formsPlot1.Render();
            formsPlot2.Render();

            lblHover.Text = "";
        }

        private void Button1_Click(object sender, EventArgs e)
        {
            GenerateNewData();
        }

        private void RbCandle_CheckedChanged(object sender, EventArgs e)
        {
            GenerateNewData();
        }

        private void RbOHLC_CheckedChanged(object sender, EventArgs e)
        {
            GenerateNewData();
        }

        private void formsPlot1_AxesChanged(object sender, EventArgs e)
        {
            formsPlot2.plt.MatchAxis(formsPlot1.plt, horizontal: true, vertical: false);
            formsPlot2.Render();
        }

        private void formsPlot2_AxesChanged(object sender, EventArgs e)
        {
            formsPlot1.plt.MatchAxis(formsPlot2.plt, horizontal: true, vertical: false);
            formsPlot1.Render();
        }

        private void formsPlot1_MouseMoved(object sender, EventArgs e)
        {
            Point mouseLoc = new Point(Cursor.Position.X, Cursor.Position.Y);
            mouseLoc.X -= this.PointToScreen(formsPlot1.Location).X;
            mouseLoc.Y -= this.PointToScreen(formsPlot1.Location).Y;

            PointF mouseCoordinate = formsPlot1.plt.CoordinateFromPixel(mouseLoc);
            DateTime dt = DateTime.FromOADate(mouseCoordinate.X);
            lblHover.Text = dt.ToString("dddd, MMM dd, yyyy");

            var plottables = formsPlot1.plt.GetPlottables();
            var scatterPlot = (ScottPlot.PlottableOHLC)plottables[0];
            var highlightText = (ScottPlot.PlottableText)plottables[1];
            var DDhighlightText = (ScottPlot.PlottableText)plottables[2];
            
            // determine which scatter point is closest to the mouse
            int closestIndex = 0;
            string location = string.Empty;
            double closestDistance = double.PositiveInfinity;
            for (int i = 0; i < scatterPlot.pointCount; i++)
            {
                //Added all 4 points to make sure tooltip covers all the size of the candle
                //@ High
                double dx = mouseLoc.X - formsPlot1.plt.CoordinateToPixel(scatterPlot.ohlcs[i].day, 0).X;
                double dy = mouseLoc.Y - formsPlot1.plt.CoordinateToPixel(0, scatterPlot.ohlcs[i].high).Y;
                double distance = Math.Sqrt(Math.Pow(dx, 2) + Math.Pow(dy, 2));
                if (closestIndex < 0)
                {
                    closestDistance = distance;
                }
                else if (distance < closestDistance)
                {
                    closestDistance = distance;
                    closestIndex = i;
                }

                //@ Low
                 dx = mouseLoc.X - formsPlot1.plt.CoordinateToPixel(scatterPlot.ohlcs[i].day, 0).X;
                 dy = mouseLoc.Y - formsPlot1.plt.CoordinateToPixel(0, scatterPlot.ohlcs[i].low).Y;
                 distance = Math.Sqrt(Math.Pow(dx, 2) + Math.Pow(dy, 2));
                if (closestIndex < 0)
                {
                    closestDistance = distance;
                }
                else if (distance < closestDistance)
                {
                    closestDistance = distance;
                    closestIndex = i;
                }

                //@ Open
                dx = mouseLoc.X - formsPlot1.plt.CoordinateToPixel(scatterPlot.ohlcs[i].day, 0).X;
                dy = mouseLoc.Y - formsPlot1.plt.CoordinateToPixel(0, scatterPlot.ohlcs[i].open).Y;
                distance = Math.Sqrt(Math.Pow(dx, 2) + Math.Pow(dy, 2));
                if (closestIndex < 0)
                {
                    closestDistance = distance;
                }
                else if (distance < closestDistance)
                {
                    closestDistance = distance;
                    closestIndex = i;
                }

                //@ Close
                dx = mouseLoc.X - formsPlot1.plt.CoordinateToPixel(scatterPlot.ohlcs[i].day, 0).X;
                dy = mouseLoc.Y - formsPlot1.plt.CoordinateToPixel(0, scatterPlot.ohlcs[i].low).Y;
                distance = Math.Sqrt(Math.Pow(dx, 2) + Math.Pow(dy, 2));
                if (closestIndex < 0)
                {
                    closestDistance = distance;
                }
                else if (distance < closestDistance)
                {
                    closestDistance = distance;
                    closestIndex = i;
                }
            }

            highlightText.x = scatterPlot.ohlcs[closestIndex].day;
            highlightText.y = scatterPlot.ohlcs[closestIndex].close;
            if (closestDistance < 20)
            {
                highlightText.text = string.Format(
                        "{0} \nHigh : {1}\nOpen : {2}\nClose: {3}\nLow  : {4}",
                        dt.ToShortDateString(),
                        Math.Round(scatterPlot.ohlcs[closestIndex].high, 2),
                        Math.Round(scatterPlot.ohlcs[closestIndex].open, 2),
                        Math.Round(scatterPlot.ohlcs[closestIndex].close, 2),
                        Math.Round(scatterPlot.ohlcs[closestIndex].low, 2)
                    );
            }
            else
            {
                highlightText.text = "";
            }
            formsPlot1.Render();
        }

        private void btnHline_Click(object sender, EventArgs e)
        {
            //Adding a Hline to provide the chart analyser to review the range.
            var plottables = formsPlot1.plt.GetPlottables();
            var scatterPlot = (ScottPlot.PlottableOHLC)plottables[0];
            formsPlot1.plt.PlotHLine(scatterPlot.ohlcs[0].high, lineWidth: 2, draggable: true);
            formsPlot1.Render();
        }
    }
    
}
```

**Comment by swharden** [comment]
![image](https://user-images.githubusercontent.com/4165489/69501343-1109d700-0ed2-11ea-8336-3aa1d678e452.png)

**Comment by leemidgley** [comment]
Hi, do you have some example code for this for plotting volume on a candlestick chart to an image? (ScottPlot v4.0)
e.g.

var klines = client.SpotApi.ExchangeData.GetKlinesAsync(
                    symbol: "BTCUSDT",
                    interval: Binance.Net.Enums.KlineInterval.OneHour,
                    startTime: DateTime.Now.AddDays(-1),
                    endTime: DateTime.Now,
                    limit: 24);
List<ScottPlot.OHLC> ohlcs = new List<ScottPlot.OHLC>();

foreach (var price in klines.Result.Data)
                {
                    var ohlc = new ScottPlot.OHLC(
                        (double)price.OpenPrice,
                        (double)price.HighPrice,
                        (double)price.LowPrice,
                        (double)price.ClosePrice,
                        (DateTime)price.OpenTime,
                     timeSpan: 1.0 / 60 / 24);

                    ohlcs.Add(ohlc);
                }

var plt = new ScottPlot.Plot(1600, 1024);
plt.PlotCandlestick(ohlcs.ToArray()); // works fine!
plt.PlotBar( // not sure how to do it to match above candlestick times and positions. <---------------

plt.SaveFig("c:\\test.png")


Thanks very much for your help.
