### ISSUE TITLE
improve OHLC constructor

### ISSUE THREAD

**Issue by Minu476** [swharden/ScottPlot#182]
Version 4.03 require the x coordinate be always declare as DateTime in OHLC class. This cause a major break in all existing codes that require double. An overload constructor will be nice. I got around this by using day public field afterward.

**Comment by swharden** [comment]
Hey @Minu476 thanks for mentioning this. I added an overload constructor like you suggested. 

I also renamed "day" to "time" because if the user is taking-over the horizontal axis units, the numbers might be in seconds or minutes or something other than days.

**Comment by swharden** [comment]
I'll wait until @satyat110 finishes their candlestick improvements (#181) then release a new NuGet package whose improvements focus on OHLC/candlestick.
