### ISSUE TITLE
Winform User control error.

### ISSUE THREAD

**Issue by satyat110** [swharden/ScottPlot#183]
With the latest ScottPlot.Winform from NuGet, its throwing the below error.

![Error](https://user-images.githubusercontent.com/58095701/69503097-3d6e2500-0ecb-11ea-845d-0661e64917fb.png)

**Comment by swharden** [comment]
Thanks for letting me know about this! I guess it's a problem if I just upgrade the ScottPlot package and don't also upgrade the WPF and WinForms controls packages (even though their code didn't change).

I just uploaded version 4.0.4 versions of the controls. Want to try it again and re-open this issue if you still have a problem?
