### ISSUE TITLE
Improve candle width detection

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#184]
Currently OHLC charts use the first two data points to determine candlestick width.

Change this to use the smallest inter-candle distance.

**Comment by satyat110** [comment]
Thanks Scott. will wait for the update

**Comment by swharden** [comment]
I think it's fixed now. Open this issue again it it doesn't work for you.

I'll issue a new NuGet package shortly.

**Comment by satyat110** [comment]
Thanks. Will wait for the update.

**Comment by swharden** [comment]
It’s already updated and live! 4.0.5
