### ISSUE TITLE
Optionally display lineWidth in legend

### ISSUE THREAD

**Issue by ab-tools** [swharden/ScottPlot#185]
I see that the `LineStyle` for legends can be adjusted already, but it seems that the line width is currently hard-coded.
Would it be possible to make this adjustable as well that the with of the line displayed in the legend box can be made a bit larger/thicker?

Thanks in advance
Andreas

**Comment by swharden** [comment]
Hey @ab-tools thanks for raising this point. I'll issue a change shortly.

I know this topic was discussed before (I think by @Padanian who did early work on the legend) and the conclusion at the time was that allowing line width to be reflected in the legend looked bad more often than not.

However, it seems useful to leave this option up to the _user_ using a flag like:

```cs
plt.Legend(fixedLineWidth: False);
```

Note to self, the legend item line width is defined here:
https://github.com/swharden/ScottPlot/blob/f436e120cfc3238d29a3cba13319dd3094e0bbc0/src/ScottPlot/Legend.cs#L230

and changing that `1` to `plottable.lineWidth` would probably do the trick

**Comment by ab-tools** [comment]
Great, thanks a lot, appreciating your very fast reply! :-)

**Comment by swharden** [comment]
Fixed! 

```cs
plt.Legend(fixedLineAndMarkerSize: false);
```

See the cookbook example: https://github.com/swharden/ScottPlot/tree/master/cookbook#styling-scatter-plots

**Comment by ab-tools** [comment]
Thanks a lot! :-)
