### ISSUE TITLE
Error in 4.0.5.0

### ISSUE THREAD

**Issue by gobikulandaisamy** [swharden/ScottPlot#188]
Dear Sir,
The same error noticed in 4.0.4.0 still occur in 4.0.5.0
Please refer previous post

GOBI.K

**Comment by swharden** [comment]
Will discuss in #187

**Comment by gobikulandaisamy** [comment]
Thank you so much sir. I will try this new version and give you the feedback.

**Comment by gobikulandaisamy** [comment]
New latest release is working fine sir.
