### ISSUE TITLE
[Feature Request] Show Value on hover

### ISSUE THREAD

**Issue by robokamran** [swharden/ScottPlot#190]
ScottPlot is a very neat component, I have already suggested for it to be added to [Awesome .NET!
](https://github.com/quozd/awesome-dotnet).

A very useful tool is to show tooltips when the mouse hovers over a point. The [ZedGraph](https://github.com/ZedGraph/ZedGraph) handles it perfectly using tooltips. The plot property is **IsShowPointValues**. I have provided a screenshot below:

![image](https://user-images.githubusercontent.com/8957516/70534052-7f57c600-1b6f-11ea-9fbc-99e5f0560a64.png)

**Comment by swharden** [comment]
Hi Robokamran, I'm glad you find this package useful!

"Show value on hover" already exists and a demo can be found in the demos folder. Admittedly it's a bit complex, but you may find that code useful. This topic is discussed in https://github.com/swharden/ScottPlot/issues/115
