### ISSUE TITLE
when i run ScottPlotDemos, System.NullReferenceException:

### ISSUE THREAD

**Issue by s3hengwu** [swharden/ScottPlot#191]
![微信截图_20191216103245](https://user-images.githubusercontent.com/8500025/70875048-96733980-1fef-11ea-937e-39689ce2af75.png)

**Comment by swharden** [comment]
Thanks for reporting this!

Are you able to compile the demos program from source? Does the one you compile yourself work on your system?

**Comment by s3hengwu** [comment]
![2](https://user-images.githubusercontent.com/8500025/70876562-ffa97b80-1ff4-11ea-9995-88473924de7c.png)

**Comment by swharden** [comment]
This is hard for me to diagnose since I cannot produce this error on my system. This may be related to #189

Are you using .NET Framework or .NET Core?

**Comment by swharden** [comment]
@s3hengwu I noticed you closed this issue. Did you resolve this problem?
