### ISSUE TITLE
Could not install package 'ScottPlot 4.0.9'

### ISSUE THREAD

**Issue by efakhri** [swharden/ScottPlot#197]
Hi,
I tried to install ScottPlot.Winforms, but i get the following error:
Install-Package : Could not install package 'ScottPlot 4.0.9'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by swharden** [comment]
Hi @efakhri, I just tested this and it seemed to work for me! Perhaps update visual studio and try again with a clean project?

![image](https://user-images.githubusercontent.com/4165489/71685045-31487380-2d65-11ea-8225-30aeeae928da.png)

![image](https://user-images.githubusercontent.com/4165489/71685073-41f8e980-2d65-11ea-9af6-e0dc000500c9.png)

```
Attempting to gather dependency information for package 'ScottPlot.WinForms.4.0.9' with respect to project 'WindowsFormsApp7', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 109.97 ms
Attempting to resolve dependencies for package 'ScottPlot.WinForms.4.0.9' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'ScottPlot.WinForms.4.0.9'
Resolved actions to install package 'ScottPlot.WinForms.4.0.9'
Adding package 'System.Drawing.Common.4.6.0' to folder 'C:\Users\swharden\source\repos\WindowsFormsApp7\packages'
Added package 'System.Drawing.Common.4.6.0' to folder 'C:\Users\swharden\source\repos\WindowsFormsApp7\packages'
Added package 'System.Drawing.Common.4.6.0' to 'packages.config'
Successfully installed 'System.Drawing.Common 4.6.0' to WindowsFormsApp7
Adding package 'ScottPlot.4.0.9' to folder 'C:\Users\swharden\source\repos\WindowsFormsApp7\packages'
Added package 'ScottPlot.4.0.9' to folder 'C:\Users\swharden\source\repos\WindowsFormsApp7\packages'
Added package 'ScottPlot.4.0.9' to 'packages.config'
Successfully installed 'ScottPlot 4.0.9' to WindowsFormsApp7
Adding package 'ScottPlot.WinForms.4.0.9' to folder 'C:\Users\swharden\source\repos\WindowsFormsApp7\packages'
Added package 'ScottPlot.WinForms.4.0.9' to folder 'C:\Users\swharden\source\repos\WindowsFormsApp7\packages'
Added package 'ScottPlot.WinForms.4.0.9' to 'packages.config'
Successfully installed 'ScottPlot.WinForms 4.0.9' to WindowsFormsApp7
Executing nuget actions took 4.39 sec
Time Elapsed: 00:00:04.9277509
========== Finished ==========
```

**Comment by swharden** [comment]
> ```Could not install package 'ScottPlot 4.0.9'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework.```

Oh, @efakhri, your problem is that you must be using .NET Framework 4.6.1 or newer. Supported frameworks are:

https://github.com/swharden/ScottPlot/blob/0c52169b41676702444701f8e096a5898ddecf70/src/ScottPlot.WinForms/ScottPlot.WinForms.csproj#L4
