### ISSUE TITLE
Find figure margins

### ISSUE THREAD

**Issue by Tarneil** [swharden/ScottPlot#2]
Hi,

I'm using your library in a spectrum analysis app. The image is shown inside a PictureBox and
I want to print x-axis units on mouse-click.

"fig1.xAxis.GetUnit" works fine, but pixels delivered by PictureBox1>MouseClick event
refers to the left edge of the box.

Is there a way to find figure margins? I found only "fig.FramePad", which can only write.

Thanks in advance!

**Comment by swharden** [comment]
You were close with `fig.FramePad`! You can probably get `fig.padT`,  `fig.padR`,  `fig.padB`,  and `fig.padL` to get the top, right, bottom, and left padding in pixels.

**Comment by Tarneil** [comment]
That's what I'm looking for. But they are private to fig.

**Comment by swharden** [comment]
I know this thread is a bit old, but you may be interested in the newer version of ScottPlot. This is possible now, and much simpler.

https://github.com/swharden/ScottPlot
https://github.com/swharden/ScottPlot/tree/master/doc

**Comment by swharden** [comment]
Specifically: 
https://github.com/swharden/ScottPlot/tree/master/doc#paddingpng

**Comment by Tarneil** [comment]
The thread is old, but the new version is still appreciated.
