### ISSUE TITLE
only render the first N data points in Signal plots

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#202]
If you have live incoming data populating a large array in memory, the first part of the array contains real values and the last part of the array contains zeros that should not be displayed. Consider extending `PlottableSignal` to allow only rendering the first N data points. Obviously the default would be to render all data points.

**Comment by StendProg** [comment]
This can be done with manual setup `Horisontal` axis range, or add axis range helper method that accept N. There is no need to change `PlottableSignal`. Maybe i misunderstand your idea.

**Comment by swharden** [comment]
If I want to plot 1 minute of data in real time (plot it live, as the data is recorded) it makes sense to create a double array in memory (of all 0s) then fill the array with data values as they are measured. I would like to display incoming data while hiding the 0s, like this.

![action-potential](https://user-images.githubusercontent.com/4165489/72170387-cddec700-339e-11ea-87c0-93243bd830f2.gif)

Perhaps a simpler way to implement this is to represent empty data values in the array as `double.PositiveInfinity` (rather than `0`) and skip drawing pixel columns which reach infinity 🤔

**Comment by swharden** [comment]
More specifically, I'd like to use ScottPlot to create an application to display voltage over long periods of time. I have a voltmeter which produces 1 measurement per second and sends it to the computer using a serial port.

Previously I used Python to create graphs ([pyTENMA](https://github.com/swharden/pyTENMA)) of voltage from this meter. That application produced a static graph, but I'd like to use ScottPlot to produce a live animated graph.

![image](https://user-images.githubusercontent.com/4165489/72171176-69bd0280-33a0-11ea-87fd-0b34723bb79a.png)

![image](https://user-images.githubusercontent.com/4165489/72171314-ba346000-33a0-11ea-8863-8e0793f28f27.png)

**Comment by StendProg** [comment]
Easy way to implement this without "magic" numbers:
nullable field indicating N.
```
int? DrawCount = null;
```
Draw methods use DrawCount instead of ys.Length if DrawCount not null.
Axis range calculation always use ys.Length.
But it need carefully change all `RenderHighDensity()`, `RenderLowDensity()`

**Comment by swharden** [comment]
> implement this without "magic" numbers

Ha! Yes, magic numbers are a bad code smell 😅 

> Use a nullable field indicating N
> ```
> int? DrawCount = null;
> ```
>
> But carefully change all `RenderHighDensity()`, `RenderLowDensity()` to use this number instead of `ys.Length`

I like this idea! I prefer the name `maxRenderIndex`

> For slow real-time data performance doesn't matter so you can recreate the array and re-plot on each new element.

I'm currently designing a circuit board to perform voltage measurements at a rate of about 100 per second, so performance is a goal.

**Comment by swharden** [comment]
I created a new demo program to make this feature easy to test when we figure out how to implement it. It also demonstrates the problem (zeros should not get plotted).

![incoming-data](https://user-images.githubusercontent.com/4165489/72193459-92acba00-33d7-11ea-807c-4019021a63bc.gif)

![image](https://user-images.githubusercontent.com/4165489/72193451-8c1e4280-33d7-11ea-9317-e6d5f4985918.png)

**Comment by swharden** [comment]
@StendProg actually `double.NaN` may be a good value to not render. I don't think I'd consider this a "magic number" since it literally means "not a number" 🤔 

I will still also add the `maxRenderIndex` argument since that will be computationally faster

**Comment by swharden** [comment]
This is what I came up with...

Using a class-level signal:

```cs
private ScottPlot.PlottableSignal signal;
```

```cs
signal = formsPlot1.plt.PlotSignal(dataValues);
```

Update the `maxRenderIndex` whenever new data has been added:
```cs
signal.maxRenderIndex = nextIndex;
```

Then `Render()` whenever you want (perhaps on a separate timer):
![incomingData](https://user-images.githubusercontent.com/4165489/72209478-76168d80-347c-11ea-8c93-392b92e3cfa7.gif)

**Comment by plumforest** [comment]
Below is a LabVIEW Chart, similar effect?




![labview_chart](https://user-images.githubusercontent.com/48978621/72234770-8f991000-3609-11ea-96cf-2dc9c52aa528.gif)
