### ISSUE TITLE
Scatter and Signal plots fail for data containing double.NaN

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#203]
If data contains even a single `double.NaN` value, the entire plot fails to render properly. How should `double.NaN` be handled? Perhaps it could indicate data points which should not be rendered (#202)

- [ ] `GetLimits()` in every `Plottable` should be modified to ignore `double.NaN`
- [ ] `Render()` in every `Plottable` should be modified to not render `double.NaN`

### Problem code:
```cs
double[] xs = new double[] { 1, double.NaN, 3, 4, 5, 6 };
double[] ys = new double[] { 1, 4, 9, 16, double.NaN, 36 };
var plt = new ScottPlot.Plot();
plt.PlotScatter(xs, ys);
plt.SaveFig("test.png");
```

### Current output:
![image](https://user-images.githubusercontent.com/4165489/72209088-c1c73800-3478-11ea-9f19-41e70f4c7094.png)

**Comment by plumforest** [comment]
I worked with LabVIEW graph control very a lot . 
LabVIEW graph controls do ignore NaN while drawing a line/curve.

In case a NaN in the middle of an array, both sides are render while a span left  between them.

**Comment by swharden** [comment]
Ignoring `double.NaN` requires a lot of `if` checks in loops which hurts performance. Since no one's ever _requested_ this functionality, I'd prefer to keep performance as high as possible.

If a data gap is truly desired, the best way to do it for now would be to plot two arrays.
