### ISSUE TITLE
Logarithmic axis

### ISSUE THREAD

**Issue by senged** [swharden/ScottPlot#207]
As far as I can tell this currently isn't supported. Request would be to allow setting any or all of the axis as log mode. Thanks.

**Comment by swharden** [comment]
Hi @senged, thanks for your suggestion. This topic comes up from time to time (#29, #41), but there is currently no way to plot data on log scales.

I will create some helper functions and code demos to demonstrate how to transform log data such that it can be plotted on a linear axis (giving the appearance of a log scale), but true rendering of nonlinear axes is unlikely to be supported.

I'll leave this ticket open to track progress toward this end. Thanks again for the suggestion!

**Comment by swharden** [comment]
I made a little tool to make this task easier and added a cookbook example showing how to do this.

https://github.com/swharden/ScottPlot/tree/master/cookbook#log-axis

I'll publish this on NuGet shortly

```cs
// plot the data using a linear axis
subplot1.PlotScatter(dataXs, dataYs, lineWidth: 0);
subplot1.Title("Data (Linear Scale)");
subplot1.YLabel("Vertical Units");
subplot1.XLabel("Horizontal Units");

// plot the same data using a log axis
subplot2.PlotScatter(dataXs, ScottPlot.Tools.Log10(dataYs), lineWidth: 0);
subplot2.Title("Data (Log Scale)");
subplot2.YLabel("Vertical Units (10^)");
subplot2.XLabel("Horizontal Units");
```

![image](https://user-images.githubusercontent.com/4165489/72669016-cea8d600-39fa-11ea-8f44-1c1ec06f8ce8.png)

**Comment by at2software** [comment]
Hello @swharden and sorry for reaching out in this way. A few months ago we sent a development inquiry via email which is kind of related to this issue. I don't know if you received it (I can resend it of course if you're interested), but we would still be very interested in this feature. Are there any possibilities that this can be re-considered to implement?
Please feel free to delete this post if you should find it inadequate.
