### ISSUE TITLE
improve support for Linux and macOS

### ISSUE THREAD

**Issue by Hexxonite** [swharden/ScottPlot#211]
Hi there,

I was trying to get this Library working under a .net core 2.1 app on my ubuntu 18.04 server.
During this process I was getting some weird errors which were eventually boiled down to being the exact same issue like [THIS](https://stackoverflow.com/questions/49453681/net-core-using-system-drawing-common-on-linux-in-docker-could-not-open-disp)

On this line: https://github.com/swharden/ScottPlot/blob/bbfa3f5d8264338814c946aaaee955f2c082313a/src/ScottPlot/Config/TextLabel.cs#L25

If I understood correctly, the usage of "FromHwnd" will basically invoke some code which requires a graphical interface to be present.  As my server is purely a "backend" I dont really want to install an x-server just for plotting some graphs. This would be my last resort...

I am not familar with the Details, but as the solution on stackoverflow suggest, might there be a way to use `Graphics.FromImage()` at this place without any loss of funtionality?

I think this would greatly benefit cross-platform compatibility :)

Thanks in advance.

**Comment by StendProg** [comment]
Gfx object you point used only for `MeasureString()`. I think it safe to make replacement you suggested.

Does Azure piplines use Windows instances to run tests? Its good improvement to setup additional Linux based pipeline for test, to avoid problems like this issue.

**Comment by Hexxonite** [comment]
Hi again and Thanks for the quick response :)

The method you proposed is working fine, however I encountered another error where the "Segoe UI"-Font wouldn't be found. So I created a Helper-Class to check if any preffered defaults exist on the system and replaced the static strings in some cases.

During this I also encountered the "CourierNew" Font being used in some cases by "markers"? But I personally dont use these and didn't have any problems. Some further investigation might be required though...

Regarding the Azure Pipeline I sadly dont have any knowledge but it seems like a good idea for sure :)

Here is the PR:

https://github.com/swharden/ScottPlot/pull/212

**Comment by swharden** [comment]
Hi @Hexxonite, thanks for reporting this and issuing a PR. I'll refine the PR a bit then merge it in today. 

@StendProg thanks for your early reply. Azure Pipelines is just building on a Windows system, but I'll add Linux to it today and ensure ScottPlot builds and tests pass.

The Azure Pipelines configuration file is: [/dev/devops/azure-pipelines.yml](https://github.com/swharden/ScottPlot/blob/master/dev/devops/azure-pipelines.yml)

**Comment by swharden** [comment]
fixed, see notes in #212
