### ISSUE TITLE
second Y axis

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#213]
I frequently get new requests to add support for a second Y axis. This topic has been raised before (#162, #41). This feature will probably require refactoring of many modules, but it's probably worth it.

QuickPlot can do this. https://github.com/swharden/QuickPlot/issues/12

**Comment by MoniNahear** [comment]
I think the zooming/pen for this case should be common to the X axis and separated for the Y Axis

**Comment by swharden** [comment]
I added this to the ScottPlot 4.1 branch feature list:
https://github.com/swharden/ScottPlot/blob/master/dev/changelog.md

**Comment by swharden** [comment]
I mean https://github.com/swharden/ScottPlot/blob/dev/4.1/dev/changelog.md
