### ISSUE TITLE
add "copy to clipboard" options to user controls

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#220]
- [ ] add _copy image to clipboard_ option to the right-click menu
- [ ] add _copy all data to clipboard_ button to the settings dialog
- ~~add _copy visible data to clipboard_ button to the settings dialog~~ Too complicated for an unclear use case. This can be added later if truly desired.

**Comment by bukkideme** [comment]
Hello! What will be copied to clipboard? The whole data range, or the visible section like when the plot is zoomed in?
It would be handy to have option to only copy the visible data range.
Thanks for your efforts! :)

**Comment by swharden** [comment]
> Hello! What will be copied to clipboard? 

I was actually thinking the image (Bitmap) would get copied, but maybe we could also add data export options.

> The whole data range, or the visible section like when the plot is zoomed in?
> It would be handy to have option to only copy the visible data range.

Maybe both?

The best place to do this may be to add "copy to clipboard" buttons here:
![image](https://user-images.githubusercontent.com/4165489/73224781-9a3ec380-4138-11ea-8ccd-47848dddf9c7.png)

**Comment by swharden** [comment]
![image](https://user-images.githubusercontent.com/4165489/73612852-95a55f80-45bd-11ea-8f6c-591d56e6df27.png)

![image](https://user-images.githubusercontent.com/4165489/73612870-bd94c300-45bd-11ea-86e5-d84ad5ca0c43.png)
