### ISSUE TITLE
Is there any way to have only integer Y axis?

### ISSUE THREAD

**Issue by teejay-87** [swharden/ScottPlot#221]
Is there any way to have only integer Y axis?

Note that bars with value = 0.05 have that value instead of 0 just to show a small bar instead of nothing.

![image](https://user-images.githubusercontent.com/17051981/73267167-c01ba500-41d8-11ea-8983-3dc9cbe0424d.png)

**Comment by swharden** [comment]
Sort of...

```cs
plt.Grid(ySpacing: 1);
```

https://github.com/swharden/ScottPlot/tree/master/cookbook#manual-grid-spacing

Let me know how that works for you!

**Comment by teejay-87** [comment]
Already tried that. Nothing changes.

My code:
`
var startDate = DateTime.Now.AddDays(-6).Date;
var data = Database.GetRebootEventsTable().Where(e => e.Date >= startDate).ToListAsync().Result;

var y2max = 2D;
var plt = new ScottPlot.Plot(800, 500);

double[] xs = Enumerable.Range(1, 7).Select(i => i * 10.0).ToArray();
DateTime[] xDates = Enumerable.Range(0, 7).Reverse().Select(i => DateTime.Now.AddDays(-i).Date).ToArray();

for (var eventTypeIndex = 0; eventTypeIndex < eventTypes.Count; eventTypeIndex++)
{
    string eventType = eventTypes[eventTypeIndex];
    var dataYs = xDates.Select(d => Math.Max(data.Count(e => e.EventType == eventType && e.Date.Date == d), 0.05)).ToArray();
    plt.PlotBar(xs, dataYs, barWidth: 1.5, xOffset: -eventTypes.Count + (eventTypeIndex + 0.75) * 1.75);
    y2max = Math.Max(y2max, dataYs.Max());
}

plt.Legend(location: ScottPlot.legendLocation.upperLeft);

string[] labels = xDates.Select(d => d.ToString("dd/MM/yyyy")).ToArray();
plt.XTicks(xs, labels);

plt.Axis(y1: -0.25, y2: y2max + 0.25);
plt.XLabel("Day");
plt.YLabel("Occurrences");

plt.SaveFig(statsPlotFile);
`

**Comment by swharden** [comment]
Thanks for reporting this @teejay-87! This was a bug on this line:

https://github.com/swharden/ScottPlot/blob/44e0b2c78b59e738f30de3925be8eb69374a700f/src/ScottPlot/Config/TickCollection.cs#L128

I fixed the bug just now with ab7a12c68d4056a304e17795daaa7066430d4c71 and will release a new NuGet package now. It should be live within half an hour. Thanks for reporting this!

**Comment by teejay-87** [comment]
Works fine, thanks for fixing that!
