### ISSUE TITLE
Disabling X & Y Label not working

### ISSUE THREAD

**Issue by ckovamees** [swharden/ScottPlot#222]
It seems like the `enable` parameter on the XLabel() and YLabel() methods aren't implemented.

To reproduce, add enable: false like this to Cookbook.cs Figure_01a_Quickstart():
`plt.XLabel("Time (seconds)", enable: false);`

**Comment by swharden** [comment]
Hi @ckovamees thanks for reporting this!

It converts `enable` to `settings.xLabel.visible` here:
https://github.com/swharden/ScottPlot/blob/b15f2e670723db26b09b6cebcf5b0a0aba74386b/src/ScottPlot/Plot.cs#L840-L857

... but `settings.xLabel.visible` is indeed being ignored here:

https://github.com/swharden/ScottPlot/blob/115fa516c28113eac55b29ff76595c0e6127383f/src/ScottPlot/Renderer.cs#L122-L129

I could either add support for the `enable` argument... or I could just remove the enable argument and indicate that doing `plt.XLabel("")` or `plt.XLabel(null)` are the same as disabling them 🤔

**Comment by ckovamees** [comment]
Thanks Scott.
`XLabel("")` worked while using `null` didn't.

**Comment by swharden** [comment]
As you can see by all the commits, this issue wasn't easy to fix (in a way that supported Windows, MacOS, and Linux) but it's working now. It'll get released with my next NuGet package. Thanks again for raising this issue @ckovamees!

This issue inspired me to thoroughly test every argument of every publicly accessible method (#224). 

@StendProg I heavily refactored [Fonts.cs](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/Config/Fonts.cs) again (#216) to add support for sans, serif, and monospace fonts (and OS-specific tests to confirm it works).
