### ISSUE TITLE
show ticks but not tick labels

### ISSUE THREAD

**Issue by ckovamees** [swharden/ScottPlot#223]
Is there a way to disable the ticks values from being displayed on an axis? I just want the ticks, but not the numbers.

I tried
`plot.Ticks(dateTimeX: true, displayTicksX: false);`
But the Dates still show up on the X-axis.

Thx

**Comment by swharden** [comment]
Thanks for the suggestion! I added arguments to Ticks() to do this. This will be live on NuGet later today.

```cs
var plt = new ScottPlot.Plot(width, height);
plt.Title("Hide Tick Labels (but not ticks)");
plt.PlotSignal(ScottPlot.DataGen.Sin(50));
plt.Ticks(displayTickLabelsX: false);
```

![image](https://user-images.githubusercontent.com/4165489/73613086-15ccc480-45c0-11ea-83d8-e3274587c593.png)
