### ISSUE TITLE
Correct way of getting max/min of rendered axis?

### ISSUE THREAD

**Issue by ckovamees** [swharden/ScottPlot#225]
Sorry for bombarding you with questions - but, I really like how easy it is to create great looking graphs with ScottPlot!

I use `Settings settings = MultiPlot.subplots[0].GetSettings();` to get the `settings.axes.y.max` and the min values. I use the data for some math to determine what side of a line to put some text. I get this on the console:

> WARNING: GetSettings() is only for development and testing

Is there another way to get to the max and min tick values of an axis?

**Comment by swharden** [comment]
```cs
// get the axis limits of the current view (x1, x2, y1, y2)
var viewLimits = plt.Axis();
```

Alternatively, you could ask each plottable object how large it is by either capturing the plottable when you create it and asking:

```cs
// get the axis limits of the data for a plotted object (x1, x2, y1, y2)
var scatter = plt.PlotScatter(xs, ys);
var dataLimits = scatter.GetLimits();
```

Or cycling through all the plottables with `plt.GetPlottables()` and doing the same thing.

Does this help answer your question?

**Comment by swharden** [comment]
... note that the view limits aren't fitted to the data until a render is requested or AxisAuto() is called

**Comment by ckovamees** [comment]
Yes, thank you. The plt.Axis() works.
