### ISSUE TITLE
AxSpan draggable not implemented

### ISSUE THREAD

**Issue by StendProg** [swharden/ScottPlot#228]
It looks like `PlottableAxSpan` has draggable api, but not implemented.
Additionaly it will be usefull to have `OnChanged(double newValue)` events for both borders, which rises on end drag by user.

**Comment by swharden** [comment]
Thanks for mentioning this @StendProg! It looks like there is not an easy fix for this because all my draggable code was made to drag a single line (axis line), not two edges of a span... so it is difficult to get this working with a simple fix. 

This difficulty indicates to me that I should refactor how all dragging is handled. I think it is time to create an `IDraggable` interface. It might take me a few days to work this out! Thanks again for pointing this issue out.

**Comment by swharden** [comment]
This now works in FormsPlot and WpfPlot

New draggables (draggable plottables) will be easy to create with `IDraggable`
https://github.com/swharden/ScottPlot/blob/dff32dd829b44fd2f25b21015de64495c3dd6ce5/src/ScottPlot/plottables/IDraggable.cs#L7-L17

The plot module now has two new public methods:
https://github.com/swharden/ScottPlot/blob/dff32dd829b44fd2f25b21015de64495c3dd6ce5/src/ScottPlot/Plot.cs#L696-L705

https://github.com/swharden/ScottPlot/blob/dff32dd829b44fd2f25b21015de64495c3dd6ce5/src/ScottPlot/Plot.cs#L707-L717

**Comment by StendProg** [comment]
Hi @swharden.
Thanks for this big amout of work.
I checked this, have some ideas that to add and refactor. Try to make this soon.
There are one thing i really can't solve. Dragging axises or spans looks much more laggy then paning. Check the code, it have the same math complexity. Profiled, also nothing specal. But dragging goes like 3 fps, when pan or zoom goes smooth.

**Comment by swharden** [comment]
> Dragging axes or spans looks much more laggy then panning

Maybe anti-aliasing isn't turned off while dragging portables?

**Comment by StendProg** [comment]
>Maybe anti-aliasing isn't turned off while dragging portables?

I tryed that too, the same result.

**Comment by StendProg** [comment]
Found that, 
https://github.com/swharden/ScottPlot/blob/334f93dec027cd8d950bc63561f0925612d7e3c1/src/ScottPlot.WinForms/FormsPlot.cs#L57
shoud be 
```c#
if (isPanningOrZooming || isMovingDraggable)
```
Spent few hours try to find that....

**Comment by swharden** [comment]
> > Maybe anti-aliasing isn't turned off while dragging portables?
> 
> I tryed that too, the same result.

We should properly alias while dragging

https://github.com/swharden/ScottPlot/blob/334f93dec027cd8d950bc63561f0925612d7e3c1/src/ScottPlot.WinForms/FormsPlot.cs#L216

Like we do while panning

https://github.com/swharden/ScottPlot/blob/334f93dec027cd8d950bc63561f0925612d7e3c1/src/ScottPlot.WinForms/FormsPlot.cs#L207
