### ISSUE TITLE
Horizontal line draw in low quality bug.

### ISSUE THREAD

**Issue by StendProg** [swharden/ScottPlot#232]
Draw horizontal line with disabled antialiasing produce strange effect.
![HorizontalBug](https://user-images.githubusercontent.com/53831487/73680930-531f7800-46ce-11ea-8e2b-f004995ea2e8.png)

**Comment by swharden** [comment]
So weird! 🤣 This seems to be a bug in `System.Drawing.Graphics.DrawLine()` that causes an artifact when non-anti-aliased lines are drawn off the screen to the right. I can fix it by restricting the horizontal line slightly.

**Comment by swharden** [comment]
... I am curious if this bug can be recreated using a scatter plot with perfectly horizontal lines. If it is, since the bug is in `System.Drawing.Graphics`, there might not be much we can do to fix it
