### ISSUE TITLE
add ability to set culture at the Plot level

### ISSUE THREAD

**Issue by teejay-87** [swharden/ScottPlot#236]
Is there a way to have date ticks with different culture notation?

I currently change the culture of current thread, but that's not a best approach for sure:

```csharp
var savedCurrentCulture = Thread.CurrentThread.CurrentCulture;
Thread.CurrentThread.CurrentCulture = CultureInfo.GetCultureInfo("it");

var plt = new ScottPlot.Plot(1200, 500);
plt.PlotSignal(data, sampleRate: 1, xOffset: dateFrom.ToOADate(), lineWidth: 3, color: Color.Red);
plt.AxisAuto(0.05, 0);
plt.Axis(null, null, 0, Math.Round((data.Max() + 2000) / 1000) * 1000);
plt.Ticks(dateTimeX: true);
plt.XLabel("Day");
plt.YLabel("Value");
plt.SaveFig(statsPlotFile);

Thread.CurrentThread.CurrentCulture = savedCurrentCulture;
```

**Comment by swharden** [comment]
Hi @teejay-87, there's not currently a way to do that but adding a way would be a good idea! A way to set the culture at the plot level would be nice to set date format and numerical format of tick labels. 

I'll add this shortly. Thanks for the idea!

**Comment by swharden** [comment]
This is what I came up with. Thanks for the suggestion @teejay-87! 

I'll close this ticket when it's updated on NuGet

```cs
var culture = System.Globalization.CultureInfo.CreateSpecificCulture("de"); // German
plt.SetCulture(culture);
```

![image](https://user-images.githubusercontent.com/4165489/73997889-dab6f200-492d-11ea-8284-7104a325d686.png)

```cs
var culture = System.Globalization.CultureInfo.CreateSpecificCulture("hu"); // Hungarian
plt.SetCulture(culture);
```

![image](https://user-images.githubusercontent.com/4165489/73997922-e60a1d80-492d-11ea-9eb4-39aa8c5b7158.png)

**Comment by swharden** [comment]
Just pushed 4.0.18 to NuGet, it should be live a few minutes from now.

Let me know if this doesn't do the trick!

**Comment by teejay-87** [comment]
Thanks, I'll try it in the next days
