### ISSUE TITLE
launch an interactive plot without creating a GUI for it

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#237]
After creating a plot:

```cs
var plt = new ScottPlot.Plot(width, height);
var data = ScottPlot.DataGen.Sin(100);
plt.PlotSignal(data);
```

It would be nice if you could launch a launch a data browser window using a one-line command without actually having to create a window and add a user control... something like: 

```cs
plt.LaunchFormsPlot();
plt.LaunchWpfPlot();
```

The code could live in extension methods packaged in the user control modules.

**Comment by StendProg** [comment]
Simpe way, but not interactive is render to bitmap and set it to new `Form.BackgroundImage`

**Comment by swharden** [comment]
> non-interactive is render could assign Bitmap to `Form.BackgroundImage`

True, but that would require a Form to already be open. What I want to do is have `plt.LaunchFormsPlot()` to create a new Form, programmatically add a `FormsPlot`, set the dock to full, then launch the form with `ShowDialog()`. Perhaps an argument could control if non-blocking `Show()` is used instead.

This would make it easy to pop-up an interactive data plot from a console application.

> Another similar thing I am interested in is the ability to render all cookbook examples in a FormsPlot user control. This would be useful for testing Skia.

This is a great idea! I'll look into it (#239)

**Comment by StendProg** [comment]
>programmatically add a FormsPlot

Going this way you get right result, but this is not so simple.
You need to inject or sync existing `plot` with `FormsControl.Plot`.There are a lot possible side effects. 
To avoid that, good way is add additional `FormsControl` constructor accepting plot as argument. In this constructor repeat all code instead of creating new plot.

**Comment by swharden** [comment]
> > programmatically add a FormsPlot
> 
> Going this way you get right result, but this is not so simple.
> You need to inject or sync existing `plot` with `FormsControl.Plot`.There are a lot possible side effects.
> To avoid that, good way is add additional `FormsControl` constructor accepting plot as argument. In this constructor repeat all code instead of creating new plot.

This is an interesting idea! I think I understand it properly... it would let the user do something like this to launch their plot in a mouse-interactive window:

```cs
var plt = new ScottPlot.Plot(width, height);
plt.PlotSignal(ScottPlot.DataGen.Sin(100));

ScottPlot.WinForms.Show(plt);
```

**Comment by swharden** [comment]
I'm surprised I never thought of this before! Users can create plots and interactively launch them without ever having to design a GUI themselves. This could get interesting 🤔 

```cs

private void btnDataViewer_Click(object sender, EventArgs e)
{
	int pointCount = 50;
	double[] dataXs = ScottPlot.DataGen.Consecutive(pointCount);
	double[] dataSin = ScottPlot.DataGen.Sin(pointCount);
	double[] dataCos = ScottPlot.DataGen.Cos(pointCount);

	var plt = new ScottPlot.Plot();
	plt.PlotScatter(dataXs, dataSin);
	plt.PlotScatter(dataXs, dataCos);
	plt.Title("ScottPlot Quickstart");
	plt.XLabel("Time (seconds)");
	plt.YLabel("Potential (V)");
	plt.Style(ScottPlot.Style.Control);

	using (var viewer = new ScottPlot.FormsPlotViewer(plt))
		viewer.ShowDialog();
}
```

![image](https://user-images.githubusercontent.com/4165489/73999861-10f77000-4934-11ea-92b7-bc129a8c8b9e.png)

**Comment by swharden** [comment]
I'll keep developing this as part of 4.1 (it's not really an issue)
