### ISSUE TITLE
create a tool to run cookbook examples interactively

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#239]
Figure out a way to run all cookbook examples in a FormsPlot and WPF plot. Not only is this useful for testing interaction and user controls, but it will also be useful for testing Skia when that day comes.

Suggested by @StendProg in #237

**Comment by StendProg** [comment]
I will try to explain:
I rebased `SkiaControl` branch to `master` last weekend. After solving a lots of merge conflicts and compiler errors, it's good idea to test library in different modes. Cookbook already render a lot of different modes, but in offscreen to bitmap using GDI. It's easy and fast to check with eyes possible render artifacts just by scrolling generated cookbook.
This is for incomplete tests only. And I actually interested in only `SignalConst` and `axSpan` working on skia control. I will easy manual test this.
This issue don't deserve a solution more then few lines of code.

**Comment by swharden** [comment]
> I rebased `SkiaControl` branch to `master` last weekend. 

I am so impressed! That sounds like a lot of work.

> This issue don't deserve a solution more then few lines of code.

I agree this could be simple, but I've wanted to make an interactive cookbook for a long time. Many graphing library demos are like this - they have a ComboBox of demos on the left and every time you click one it plots on the right. I won't remove the current GDI method (it's great for automated tests and generating the cookbook webpage), but I'd like to use reflection to create an interactive version as well.

I added it to my [ScottPlot 4.1 to-do list](https://github.com/swharden/ScottPlot/blob/dev/4.1/dev/changelog.md) so I'll close this issue and track progress in the 4.1 branch

**Comment by StendProg** [comment]
I solved my problem with reflection as you mentioned.
Winforms demo running on `SkiaControl` is more usefull for tests then cookbook.
Single replacement of `fomsPlot = new FormsPlot();` with `formsPlot = new FormsPlotSkia();` for each demo `Form` do the trick. 
If you are interested in details: https://github.com/StendProg/ScottPlot/blob/SkiaControl/dev/ScottPlotSkia/WinformsSkiaDemosLauncher/Program.cs
