### ISSUE TITLE
Fix cookbook SaveFig() and create Multiplot.GetSubplot()

### ISSUE THREAD

**Issue by Resonanz** [swharden/ScottPlot#242]
One small issue is an error I get using the "Multiplot" demo code on [this](https://github.com/swharden/ScottPlot/tree/master/cookbook) page is that `plt.Save` results in the compiler saying that there is no definition or methods for `Save`. `SaveFig` does the job, but does not provide an overload to pass the plot dimensions. The dimensions are instead defined when the new `plt` object is created. I'm curious as to why there are two different methods? Could they be combined into one?

**Comment by swharden** [comment]
Thanks @resonaz! I'm on a phone so I'll be brief 

The Multiplot() constructor has arguments for size

I'll take a closer look at the broken Save()

**Comment by StendProg** [comment]
If I cleary understand, there are 2 problems:
- ~~Multiplot~~ All cookbook code examples contain not existing `plt.Save()`.`plt.SaveFig()` actualy used to render cookbook examples.
- There is no API for save some single plot from `MultiPlot`.

@Resonanz, you can save single plot from multiplot by calling:
```c#
plt.subplots[row * plt.cols + col].SaveFig("FileName");
```
`row` and `col` - row and column of plot to save.

As @Resonanz  point `SaveFig(string FileName,int row, int col)` will be good `Multiplot` API improvment.

**Comment by swharden** [comment]
> All cookbook code examples show `plt.Save()` instead of `plt.SaveFig()` 

Wow! That's been overlooked for the last few months. Thanks for noticing that! It should be fixed now

> @Resonanz, you can save a subplot from a multiplot by calling:
> 
> ```cs
> plt.subplots[subplotRow * plt.cols + subplotColumn].SaveFig("FileName");
> ```

Thanks @StendProg, that is an excellent way to address a subplot of a multiplot by its column and row index.

> As @Resonanz point `SaveFig(string FileName,int row, int col)` will be good `Multiplot` API improvment.

@StendProg yes, but only for saving. Perhaps adding a `Plot GetSubplot(int row, int column)` would be more flexible as it lets the user do more things such as:

```cs
var mp = new ScottPlot.MultiPlot(rows: 2, cols: 2);
mp.GetSubplot(1, 2).Title("Random Points");
mp.GetSubplot(2, 1).AxisAuto();
mp.GetSubplot(2, 2).SaveFig("bottomRight.png");
```

What do you think?

**Comment by swharden** [comment]
I went ahead and added the `GetSubplot()` function and updated the cookbook to use it:
https://github.com/swharden/ScottPlot/tree/master/cookbook#multiplot

@StendProg what do you think?

https://github.com/swharden/ScottPlot/blob/638acf305ac04b67f4878a05fc38d4af8bcbf858/src/ScottPlot/MultiPlot.cs#L85-L100

**Comment by StendProg** [comment]
Indexing starting at 1 looks unusual for c# users.

More perfect and simple solution is to store subplots at rectangle array initially.
```c#
public readonly Plot[,] subplots;
or
public readonly Plot[][] subplots;
```

Multiplot indexer overload can produce simple API:
```c#
var mp = new ScottPlot.MultiPlot(rows: 2, cols: 2);
mp[1, 2].Title("Random Points");
```
Not sure double indexer overload possible.

**Comment by swharden** [comment]
@StendProg done!

I won't do the rectangular array because I want to make it slightly easier to support non-rectangular layouts if we decide to in the future. GetSubplot() will be easy to overload to add advanced features like this.

Thanks for both of your help on this one! I'll release the next version on NuGet shortly
