### ISSUE TITLE
Add support for box plots

### ISSUE THREAD

**Issue by Benny121221** [swharden/ScottPlot#244]
The statistics plot options are currently pretty limited. Box plots could change that.

https://www.isixsigma.com/wp-content/uploads/2019/07/Box-Plot.gif

^Example in case you aren't familiar

**Comment by swharden** [comment]
@Benny121221 this is an excellent idea!

https://en.wikipedia.org/wiki/Box_plot

The PlottableBar could be modified to create a PlottableBox

https://github.com/swharden/ScottPlot/tree/master/cookbook#plot-bar-data

We could also add tools to the statistics module to turn a double arrays into the various box components. One thing to keep in mind is that many people use boxes to show quartiles, but I often use boxes to show standard error, so we should keep it flexible.

**Comment by Benny121221** [comment]
#246

**Comment by swharden** [comment]
### I created `ScottPlot.Statistics.PopulationStats()`
to make it easy to get min, max, mean, median, standard deviation, standard error, etc.

https://github.com/swharden/ScottPlot/blob/ade0446036fb4d814d49d4d4aff8b938b2e9ce81/src/ScottPlot/Statistics/PopulationStats.cs#L8-L58

### I created `ScottPlot.Statistics.BoxAndWhisker`
it is similar to OHLC. You're intended to build them and pass an array of these into Plot functions

https://github.com/swharden/ScottPlot/blob/ade0446036fb4d814d49d4d4aff8b938b2e9ce81/src/ScottPlot/Statistics/BoxAndWhisker.cs#L7-L75

### You can build a `BoxAndWhisker` like this

https://github.com/swharden/ScottPlot/blob/ade0446036fb4d814d49d4d4aff8b938b2e9ce81/demos/WinForms/Demos/FormBoxWhisker.cs#L20-L32

### You can plot `BoxAndWhiskers[]` like this

https://github.com/swharden/ScottPlot/blob/ade0446036fb4d814d49d4d4aff8b938b2e9ce81/demos/WinForms/Demos/FormBoxWhisker.cs#L82-L97

![image](https://user-images.githubusercontent.com/4165489/74205246-88831300-4c44-11ea-9324-7407c031d839.png)

**Comment by swharden** [comment]
@Benny121221 did an awesome job with #246! I modified the interactive demo to showcase both of our plottables. I'm impressed there were no merge conflicts even though we both did the same thing at the same time 😎 

![image](https://user-images.githubusercontent.com/4165489/74206134-0dbbf700-4c48-11ea-860c-94e4030b67e8.png)

### Using Scott's Version
https://github.com/swharden/ScottPlot/blob/aad44762d282d24d6d7e49e74ccf9c04c3f23f40/demos/WinForms/Demos/FormBoxWhisker.cs#L58-L76

### Using Benny's Version
https://github.com/swharden/ScottPlot/blob/aad44762d282d24d6d7e49e74ccf9c04c3f23f40/demos/WinForms/Demos/FormBoxWhisker.cs#L27-L42

### Comparison
I think the biggest difference in our implementations is @Benny121221's does math and mine doesn't (my math was extracted to a population stats module, and even a separate box and whisker builder). Since box and whiskers aren't always quartiles (I've seen them used to show limits and stdev or stderr) there might be an advantage to keeping calculations out of the plottable 🤔 

I think the final version should accept `double[] values` to let the user plot individual values over (or beside) the box plot.

**Comment by Benny121221** [comment]
When using boxwhisker plots to show quartiles, it is common to extend the whiskers only to 1.5 * IQR, and to plot any points outside of that as either dots or asterisks. This 1.5 * IQR rule is a simple rule for detecting outliers.

It looks like your code draws the whiskers out to the most extreme point, which is another common way of drawing these plots. I think this should probably make its way into an argument like `bool plotOutliersIndividually` or something like that

**Comment by swharden** [comment]
> When using boxwhisker plots to show quartiles, it is common to extend the whiskers only to 1.5 * IQR, and to plot any points outside of that as either dots or asterisks. This 1.5 * IQR rule is a simple rule for detecting outliers.

@Benny121221 I'd really like to use the math you cane up with here:

https://github.com/swharden/ScottPlot/blob/aad44762d282d24d6d7e49e74ccf9c04c3f23f40/src/ScottPlot/plottables/PlottableBoxAndWhiskerV2.cs#L79-L90

What do you think about moving it into the population stats module?

https://github.com/swharden/ScottPlot/blob/aad44762d282d24d6d7e49e74ccf9c04c3f23f40/src/ScottPlot/Statistics/PopulationStats.cs#L8-L58

> It looks like your code draws the whiskers out to the most extreme point, which is another common way of drawing these plots. I think this should probably make its way into an argument like `bool plotOutliersIndividually` or something like that

What about having multiple box plot builders? Something like the following function but one which returns the proper values. This would could become `GetBoxAndWhisker_LimitsAndDeviation` and the other one could be `GetBoxAndWhisker_OutliersAndQuartiles` or something.

https://github.com/swharden/ScottPlot/blob/aad44762d282d24d6d7e49e74ccf9c04c3f23f40/demos/WinForms/Demos/FormBoxWhisker.cs#L44-L56

If you want to have a go at it I'll stop making changes for a bit to avoid merge conflicts. Thanks again for all your work on this! I'm looking forward to your thoughts here

**Comment by Benny121221** [comment]
Yeah sure I'll have a crack at it

**Comment by swharden** [comment]
> Yeah sure I'll have a crack at it

Sounds great! I look forward to seeing what you come up with!

Right now that method is in `FormBoxWhisker.cs`... but it seems like code that builds `BoxAndWhisker` objects from `double[]` data might be good static methods in a `ScottPlot.Statistics.BoxAndWhiskerFactory` static class 🤔

**Comment by Benny121221** [comment]
#247

**Comment by swharden** [comment]
I consolidated a lot of the discussion/code from this issue into one place. However, the styling still needs a lot of work. I intentionally have not placed user-facing styling arguments in the Plot module while I work to refactor it some more. I'll probably work on some other issues, then loop back around to this one.

One thing to note is that I created a `ScottPlot.Demos` module which contains plots that can be accessed from within the WinForms and WPF demos.

https://github.com/swharden/ScottPlot/blob/35e792dd25944b989dd5f6736ebd5447d100e959/src/ScottPlot/Demo/PlotTypes/BoxAndWhisker.cs#L11-L24

![image](https://user-images.githubusercontent.com/4165489/75122851-ee719080-566f-11ea-96e9-caad45eb9a4b.png)

**Comment by swharden** [comment]
I'll close this issue and track progress on box plot refactoring in #315

**Comment by swharden** [comment]
following up, ScottPlot 4.0.25 has some new related features. Check out the cookbooks to see what's possible now:

### Bar Plot
This is a relatively simple plot type. It's just for bar plots, and it does not display population details (like scatter plots of individual data points).
http://swharden.com/scottplot/cookbooks/4.0.25/#PlotTypes_Bar_Quickstart

### Box and Whisker Plot
This has extensive options, including displaying as bar plots, and rendering population data points next to the box/bar plot.
http://swharden.com/scottplot/cookbooks/4.0.25/#PlotTypes_Populations_PlotPopulationSeriesUnique
