### ISSUE TITLE
create tests to assess thread safety

### ISSUE THREAD

**Issue by StendProg** [swharden/ScottPlot#245]
`Settings.GetPixel()` and `Settings.GetLocation()` are not thread safe.
This break `Signal` and `SignalConst` parallel render.
This methods use `xAxisScale` and `yAxisScale`, and they reference to `Bitmap`(bmpData). Bitmap class not thread safe. 
Will it possible to make xAxisScale regular field, and update it then bitmap size actually changed?

Additionaly it will be usefull to have some `GetPixelX()` and `GetPixelY()`. It allow to make a bit optimizations to signal render. In some cases it need to calc only one coordinate.

**Comment by swharden** [comment]
> `xAxisScale` and `yAxisScale` reference to `Bitmap`(bmpData). Bitmap class not thread safe.
> Will it possible to make xAxisScale regular field, and update it then bitmap size actually changed?

Yes, I can make this change!

Do you think you can make a multi-threaded test which fails so I can be confident that my fix is successful? I don't know much about threading so I'm not sure how difficult this is...

> Additionaly it will be usefull to have some `GetPixelX()` and `GetPixelY()`. It allow to make a bit optimizations to signal render. In some cases it need to calc only one coordinate.

Good idea - I'll do this as well.

**Comment by StendProg** [comment]
> Do you think you can make a multi-threaded test which fails so I can be confident that my fix is successful? I don't know much about threading so I'm not sure how difficult this is...

Existing `RenderHighDensityParallel` throws on bitmap access. Good idea to add tests, but I can do it only tomorrow.

**Comment by swharden** [comment]
> > Do you think you can make a multi-threaded test which fails so I can be confident that my fix is successful? I don't know much about threading so I'm not sure how difficult this is...
> 
> Existing `RenderHighDensityParallel` throws on bitmap access. Good idea to add tests, but I can do it only tomorrow.

Thanks for looking into it @StendProg! Take as long as you need.

This is why I disabled `useParallel` (#72) by default. If we get good at writing tests to prove things are thread safe I'd be happy to turn this back on.

I'm working hard on ScottPlot (in the dev branch) to remove `System.Drawing` from ScottPlot. Once that's finished we can be more confident everything is thread safe! It might take some more time to develop though 😅

**Comment by swharden** [comment]
> `Settings.GetPixel()` and `Settings.GetLocation()` are not thread safe.
> This break `Signal` and `SignalConst` parallel render.
> This methods use `xAxisScale` and `yAxisScale`, and they reference to `Bitmap`(bmpData). Bitmap class not thread safe.
> Will it possible to make xAxisScale regular field, and update it then bitmap size actually changed?
> 
> Additionaly it will be usefull to have some `GetPixelX()` and `GetPixelY()`. It allow to make a bit optimizations to signal render. In some cases it need to calc only one coordinate.

Good idea @StendProg - I made those functions. I also added GetLocationX() and GetLocationY().

I look forward to learning what you discover about testing thread safety!

**Comment by StendProg** [comment]
PR #248 add tests to assess thread safety.

**Comment by swharden** [comment]
> Thanks, it works for now.

Almost... #248 fails tests on Linux due to some type of infinite loop. Any thoughts on how to fix this?

> This useless X coordinate calculation has long been haunting me.

🤣

**Comment by StendProg** [comment]
> Almost... #248 fails tests on Linux due to some type of infinite loop. Any thoughts on how to fix this?

It stacked at .net package rebuilding. I think simple pipline restart solve problem.

**Comment by swharden** [comment]
You're right - I just re-ran the build and it passed. Thanks @StendProg!

**Comment by swharden** [comment]
merged #248
