### ISSUE TITLE
demonstrate how to create and load custom plottables

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#249]
It should be possible to create a new custom plottable, add it to the list, and have it plotted on ScottPlot ***without changing any ScottPlot code***. Create a demo program which shows how to do this.

The Plot module lets me get the list of plottables. I should be able to just add my custom plottable to this list and it will appear.

https://github.com/swharden/ScottPlot/blob/aad44762d282d24d6d7e49e74ccf9c04c3f23f40/src/ScottPlot/Plot.cs#L708-L711

**Comment by apriori** [comment]
That is already working. I implemented a custom plot type (filled  multisignal envelope) exactly in this way.  Just implement `Plottable` , add it exactly to the named list and you're done. 

Current issue though is, that `ScottPlot.Plot.Clear()` does not clear custom plottables.

**Comment by swharden** [comment]
> ... it was not totally obvious how to ...

Yeah, it's possible as-is but a little clunky. I think a concise quickstart guide to designing custom plottables would be nice! 

Also a new function like `Plot.AddPlottable(IPlottable customPlottable)`

**Comment by swharden** [comment]
Here's an example. I create a new Plottable totally outside the ScottPlot namespace:
https://github.com/swharden/ScottPlot/blob/af33308f6f3a7f90079fe487e21f3de33a7b4f5a/tests/Experimental/BarGraphTests.cs

Then I plotted it with the new `Plot.Add()` function:

https://github.com/swharden/ScottPlot/blob/af33308f6f3a7f90079fe487e21f3de33a7b4f5a/tests/Experimental/BarGraphTests.cs#L95-L99
