### ISSUE TITLE
Windows scaling bug

### ISSUE THREAD

**Issue by leifhelm** [swharden/ScottPlot#254]
When viewing a plot on a display with 150% scaling a graph appears but it just covers about half the box. The other half is gray.

**Comment by swharden** [comment]
Hi @leifhelm, I'm using 150% display scaling and the demo plot looks good to me

scaling settings | demo program
---|---
![image](https://user-images.githubusercontent.com/4165489/74551294-e8b5d580-4f20-11ea-8d25-224483d9b8c1.png) | ![image](https://user-images.githubusercontent.com/4165489/74551247-d6d43280-4f20-11ea-8121-a9e0a1bea710.png)

Can you provide a code sample which fails on your machine?

**Comment by leifhelm** [comment]
Sorry my mistake. Scaling works perfectly

Am 14.02.2020 5:56 Nachm. schrieb "Scott W Harden" <notifications@github.com

**Comment by swharden** [comment]
> Sorry my mistake. Scaling works perfectly

Glad it's working for you! 👍
