### ISSUE TITLE
WPF namespace code missing in XAML following install

### ISSUE THREAD

**Issue by Resonanz** [swharden/ScottPlot#258]
Hi Scott, I notice that if I follow the instruction on the Github home page, then the WPF instal does not work as described.

Steps:

1. I start a new .NET Core project, and immediately install the NuGet Scottplot.WPF package.
2. I then add the code `<ScottPlot:WpfPlot Name="wpfPlot1"/>` between the grid tags in my XAML file.
3. I then get the error `The namespace prefix "ScottPlot" is not defined. WpfApp16	MainWindow.xaml`
4. Adding `xmlns:ScottPlot="clr-namespace:ScottPlot;assembly=ScottPlot.WPF"` into the XAML preamble seems to do the trick to fix it.
5. Adding your code snippet immediately after `InitializeComponent()` then plots a nice graph!!!

**Comment by swharden** [comment]
Hi @Resonanz, thanks for mentioning this! I modified the quickstart instructions based upon your suggestion. What do you think of the new instructions?

https://github.com/swharden/ScottPlot/blob/master/README.md#interactive-plot-wpf
