### ISSUE TITLE
add support for stacked bar plots

### ISSUE THREAD

**Issue by SoManyUsernamesTaken** [swharden/ScottPlot#260]
I noticed PlottableBar implements an (effectively) unused, unexposed baseline (currently a single float). I want to plot stacked bars (e.g. bar 1 is from 0 to 2 and bar 2 is from 2 to 5). It is possible to get acceptable behavior for doing stacked bars in many cases with the current interface, however not in all (and in particular not in mine). Would you consider exposing an optional argument which allows one to specify a baseline array for the bars? This could also of course be useful for other things.

**Comment by swharden** [comment]
Hey @SoManyUsernamesTaken, thanks for the suggestion! I'll try out a few different implementations and hopefully roll this feature into the main branch within the next few days.

**Comment by swharden** [comment]
I'll close this issue and track progress toward this goal in #315

**Comment by swharden** [comment]
This is perhaps an intellectually unsatisfying solution... but it works! 😅 

![image](https://user-images.githubusercontent.com/4165489/77810817-01132700-706d-11ea-9e46-eb601fab85ec.png)

```cs
var plt = new ScottPlot.Plot(600, 400);

// create some sample data
double[] xs = { 1, 2, 3, 4, 5, 6, 7 };
double[] valuesA = { 1, 2, 3, 2, 1, 2, 1 };
double[] valuesB = { 3, 3, 2, 1, 3, 2, 1 };

// to simulate stacking B on A, shift B up by A
double[] valuesB2 = new double[valuesB.Length];
for (int i = 0; i < valuesB.Length; i++)
    valuesB2[i] = valuesA[i] + valuesB[i];

// plot the bar charts in reverse order (highest first)
plt.PlotBar(xs, valuesB2, label: "Series B");
plt.PlotBar(xs, valuesA, label: "Series A");

// improve the styling
plt.Legend(location: legendLocation.upperRight);
plt.Axis(y1: 0, y2: 7);
plt.Title("Stacked Bar Charts");
plt.SaveFig("PlotTypes_Bar_Stacked.png");
```

**Comment by swharden** [comment]
following up, ScottPlot 4.0.25 has some new related features. Check out the cookbooks to see what's possible now:

### Bar Plot
This is a relatively simple plot type. It's just for bar plots, and it does not display population details (like scatter plots of individual data points).
http://swharden.com/scottplot/cookbooks/4.0.25/#PlotTypes_Bar_Quickstart

### Box and Whisker Plot
This has extensive options, including displaying as bar plots, and rendering population data points next to the box/bar plot.
http://swharden.com/scottplot/cookbooks/4.0.25/#PlotTypes_Populations_PlotPopulationSeriesUnique
