### ISSUE TITLE
Improve WPF Quickstart instructions

### ISSUE THREAD

**Issue by Resonanz** [swharden/ScottPlot#262]
Hi Scott, #258 has disappeared so I have started another issue to reply to your question.

You added the following to the README... and asked for my comments..... I think kinda a bit unclear so will have a go further below....

Original:

Add xmlns:ScottPlot="clr-namespace:ScottPlot;assembly=ScottPlot.WPF" to your Window
Add <ScottPlot:WpfPlot Name="wpfPlot1" /> somewhere in your layout

Suggested:

Add xmlns:ScottPlot="clr-namespace:ScottPlot;assembly=ScottPlot.WPF" to the top section of your XAML code

Add <ScottPlot:WpfPlot Name="wpfPlot1" /> to the bottom section of your XAML code, between the <Grid> or similar tags

**Comment by swharden** [comment]
Thanks for the suggestion @Resonanz! How about this?

### Interactive Plot (WPF)
* Install the `ScottPlot.WPF` NuGet package
* Add the WpfPlot control by modifying your XAML file:
  * Add `xmlns:ScottPlot="clr-namespace:ScottPlot;assembly=ScottPlot.WPF"` to the top section
  * Add `<ScottPlot:WpfPlot Name="wpfPlot1" />` to the layout area
* Add code to the startup sequence of your CS file:
```cs
double[] dataX = new double[] {1, 2, 3, 4, 5};
double[] dataY = new double[] {1, 4, 9, 16, 25};
wpfPlot1.plt.PlotScatter(dataX, dataY);
wpfPlot1.Render();
```

**Comment by swharden** [comment]
https://github.com/swharden/ScottPlot#interactive-plot-wpf
