### ISSUE TITLE
PlotSignal lineWidth and markerSize

### ISSUE THREAD

**Issue by bukkideme** [swharden/ScottPlot#263]
Hello!

Latest release. I would only like to plot points, and no connecting lines.
Setting lineWidth to zero works for Scatter Plot:
`formsPlot1.plt.PlotScatter(dataRandom3, dataRandom4, lineWidth: 0);`

However, does not seem to work for Signal plotting:
`formsPlot1.plt.PlotSignal(dataRandom3, lineWidth: 0);`
Rendering this plot signal still shows connecting lines.

Thanks for looking into this!

**Comment by StendProg** [comment]
Hi @bukkideme . I fix this issue in #264.
There is only one unsolved quession. That to do in `HighDensity` mode. If you disable lines, you see nothing. I prefer stay it as before for `HighDensityMode`.

**Comment by swharden** [comment]
Hey @bukkideme, I agree this looks odd. I created a test to demonstrate it:

![image](https://user-images.githubusercontent.com/4165489/74896678-e6111100-5362-11ea-87ca-e572a9209465.png)

@StendProg I think I have a solution for high density mode: for each pixel column, expand the min/max to ensure its vertical span in pixels is >= markerSize

What do you think?

**Comment by StendProg** [comment]
> I think I have a solution for high density mode: for each pixel column, expand the min/max to ensure its vertical span in pixels is >= markerSize

Set `pen.lineWidth = markerSize` for `HighDensity` mode can produce the same result without any math. But i afraid it will be look worse.

It's a bit strange then marker's magicaly appear then you zoomed in to `LowDensity` mode, but i already used to it.
Slightly increase `pen.lineWidth` up to `markerSize` then you zoomed in close to `LowDensity` area can produce interesting animation. It must be tried to say for sure.

**Comment by swharden** [comment]
> Smoothly increase `pen.lineWidth` up to `markerSize` then you zoomed in close to `LowDensity` area can produce interesting animation. It must be tried to say for sure.

@StendProg this is an excellent idea! It looks great. Here's a demo with markersize: 20

![smoothMarker](https://user-images.githubusercontent.com/4165489/75204270-68704b00-573e-11ea-9050-807004ce500e.gif)

**Comment by swharden** [comment]
Not too complicated! I'll add similar code to SignalConst then close this issue.
https://github.com/swharden/ScottPlot/blob/74fa3050d38065ca819234e54d0855e419288f6d/src/ScottPlot/plottables/PlottableSignal.cs#L123-L130
