### ISSUE TITLE
Azure Pipelines changed default OSX font (breaking ScottPlot font tests)

### ISSUE THREAD

**Issue by StendProg** [swharden/ScottPlot#265]
#264 have failed pipeline. 
`Test_DefaultFont_MatchesOsExpectations()` failed on MacOs VM.
Maybe its not correct, to check in tests something outside project code.
This test causes a false alarm and will have to be rewritten every time Azure changes the virtual machine setup.

**Comment by swharden** [comment]
Yeah this is SUPER annoying... it looks like "Times" was changed to "Times New Roman" 🙈 

I'll probably leave it just to see how often this happens. If it happens frequently, I'll just disable the test.
