### ISSUE TITLE
add events to WpfPlot control

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#266]
@StendProg made some excellent suggestions in PR #238 

The original PR wasn't merged because the modifications were to axis line and span files which had already been deleted (separated into horizontal and vertical files). However these changes should be made again, but more extensively. For example, this dirty block in the FormsPlot control can be greatly improved:

https://github.com/swharden/ScottPlot/blob/f9d0e4630ecdd48813dbc2275e4cab617c43ce3d/src/ScottPlot.WinForms/FormsPlot.cs#L352-L367

**Comment by StendProg** [comment]
This code use correct pattern. You actually need null check and better place for it is separate method. Many people do this.
But, there is simple trick from John Skeet. Subscribe to event with empty delegate at init. So, you never get null delegate, don`t need for null check and can directly call event delegate from code. Negative side is that this empty delegate invokes each time. This tiny performance lost acceptable in most scenarious.
You can stay with existing code, it correct, faster,more flexible and already written.
One thing i see to improve. Pass both args (sender, eventArg) to each On.... handler. It simplier then they all even and match standart pattern.

**Comment by swharden** [comment]
> This code use correct pattern. You actually need null check and better place for it is separate method. Many people do this.

Thank you for the reassurance! I'll keep these events as they are in the WinForms control and add the same events to the WpfPlot control (which currently has no events). I'll probably add a `Render` event to this list too.
