### ISSUE TITLE
multiplot user controls

### ISSUE THREAD

**Issue by Resonanz** [swharden/ScottPlot#267]
Hi Scott, I am brain-dumping here in order to both post an idea for your possible future developments, and also to let you know what I am trying to implement in my project.

What I am wanting to do is have about 100 plots in a 10x10 grid. It is quite an overhead to add 100 XAML elements, so thinking that in my dream world I could have one element with some n x m dimensions and margins and padding etc. and then access all the 100 plots thru an array, or perhaps a jagged array that I can load and update as I please.

What do you think? I wish i could code this but it is a bit above my current abilities.

I'm using the .NET Core version if that is at all useful.

**Comment by swharden** [comment]
I'll give this a shot! It might take a few days until I get around to it, but I'll leave this ticket open until I create a demo application showing how to do this (assuming I can figure it out).

Curiously, what are you using 100 interactive plots for? Are you writing software for an EEG machine or something? Perhaps if I knew more about your application I could design the demo to be more relevant to it.

PS: this conversation is a continuation of #257

**Comment by Resonanz** [comment]
Thanks. I'm plotting data from a multi-well plate. Seems it will also need to be threaded so that the plots can be updated as we go along.

**Comment by swharden** [comment]
I'm almost done with a demo application that does this. However, this ScottPlot-independent example may be useful to others so I'll post it here:

### XAML (just a named grid)

```xaml
<Window x:Class="WPF.Examples.ProceduralPlots"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WPF.Examples"
        mc:Ignorable="d"
        Title="Procedurally-Generated ScottPlots" Height="700" Width="900">

    <Grid x:Name="MainGrid"/>

</Window>
```

### Startup sequence

```cs
int columnCount = 5;
int rowCount = 7;

MainGrid.ColumnDefinitions.Clear();
for(int i=0; i<columnCount; i++)
	MainGrid.ColumnDefinitions.Add(new ColumnDefinition());

MainGrid.RowDefinitions.Clear();
for (int i = 0; i < rowCount; i++)
	MainGrid.RowDefinitions.Add(new RowDefinition());

Random rand = new Random();
for(int rowIndex=0; rowIndex<rowCount; rowIndex++)
{
	for (int colIndex = 0; colIndex < columnCount; colIndex++)
	{
		var randomColorBrush = new SolidColorBrush(Color.FromRgb((byte)rand.Next(0, 150), (byte)rand.Next(0, 150), (byte)rand.Next(0, 150)));

		var lbl = new Label
		{
			Content = $"column {colIndex}, row {rowIndex}",
			Foreground = Brushes.White,
			Background = randomColorBrush,
			VerticalContentAlignment = VerticalAlignment.Center,
			HorizontalContentAlignment = HorizontalAlignment.Center
		};

		Grid.SetColumn(lbl, colIndex);
		Grid.SetRow(lbl, rowIndex);

		MainGrid.Children.Add(lbl);
	}
}
```

### Output
![image](https://user-images.githubusercontent.com/4165489/75115433-78980580-562c-11ea-9abd-7bb75ee963ae.png)

**Comment by swharden** [comment]
Replacing the label creation code with this does the trick for ScottPlots:

```cs

var wpfPlot = new ScottPlot.WpfPlot();
wpfPlot.plt.Title($"column {colIndex + 1}, row {rowIndex + 1}");
wpfPlot.plt.PlotSignal(ScottPlot.DataGen.RandomWalk(rand, 100));
wpfPlot.Render();

Grid.SetColumn(wpfPlot, colIndex);
Grid.SetRow(wpfPlot, rowIndex);
MainGrid.Children.Add(wpfPlot);
```

![image](https://user-images.githubusercontent.com/4165489/75115528-43d87e00-562d-11ea-8086-5a1a2e5a69db.png)

I'll post the code in a few minutes 👍

**Comment by Resonanz** [comment]
Hi Scott, I wondering if this code has made it into a release? Sorry, I'm not sure how to figure that out... will there be a demo in The Cookbook? I would like to try placing some buttons and textboxes on the WPF form alongside the MainGrid but so far have not managed this. I can write some instructions for generating a minimal working example if I could sort the above. Thanks.

**Comment by swharden** [comment]
Hey @Resonanz, 

Your question is actually a "how do I use WPF" question, not "how do I use ScottPlot" one, so it can be answered without requiring a ScottPlot code change or release. The example I wrote for you which was used to produce the screenshot is:

* [/demos/WPF/Examples/ProceduralPlots.xaml](https://github.com/swharden/ScottPlot/blob/master/demos/WPF/Examples/ProceduralPlots.xaml)
* [/demos/WPF/Examples/ProceduralPlots.xaml.cs](https://github.com/swharden/ScottPlot/blob/master/demos/WPF/Examples/ProceduralPlots.xaml.cs)

If you want to fill some areas of the WPF layout with buttons and textboxes, the best place to ask questions related to that would be a forum dedicated to WPF.

I'm right in the middle of greatly refactoring how the demo applications work, so some of the demo code is a bit sloppy and hard to find at the moment. I hope you find this useful though!

Scott

**Comment by Resonanz** [comment]
Hi Scott, the following may help; if not, ignore :-)

So, the code snippets above will plot lots of colorful blocks or lots of plots, however the WPF form code you have used will not allow other elements onto the form. I think the problem is that "MainGrid" as you have used it does not allow other elements to be placed on the same MainGrid.

To fix this I have made a Grid and then placed your code within that (I have called the Grid SPGrid), along with buttons and textboxes, and now everything displays. Here is the full working code -- it is exactly your code above with a few small mods. Hope this will help someone or you can use it in your documentation.

```
<Window x:Class="WpfApp27.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d"
        Title="Procedurally-Generated ScottPlots" Height="700" Width="900">

    <Grid x:Name="Grid" Margin="10">
        <Grid x:Name="SPGrid" Height="654" Width="600" VerticalAlignment="Top" HorizontalAlignment="Left"/>
        <Button Content="Button" HorizontalAlignment="Left" Margin="683,85,0,0" VerticalAlignment="Top" Height="48" Width="127"/>
        <Button Content="Button" HorizontalAlignment="Left" Margin="683,171,0,0" VerticalAlignment="Top" Height="48" Width="127"/>
        <Button Content="Button" HorizontalAlignment="Left" Margin="683,258,0,0" VerticalAlignment="Top" Height="48" Width="127"/>
        <TextBox HorizontalAlignment="Left" Margin="639,439,0,0" Text="TextBox" TextWrapping="Wrap" VerticalAlignment="Top" Width="197" Height="27"/>
        <TextBox HorizontalAlignment="Left" Margin="639,471,0,0" Text="TextBox" TextWrapping="Wrap" VerticalAlignment="Top" Width="197" Height="27"/>
        <TextBox HorizontalAlignment="Left" Margin="639,503,0,0" Text="TextBox" TextWrapping="Wrap" VerticalAlignment="Top" Width="197" Height="27"/>
    </Grid>

</Window>
```

```
using System;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;


namespace WpfApp27
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();


			int columnCount = 5;
			int rowCount = 7;

			SPGrid.ColumnDefinitions.Clear();
			for (int i = 0; i < columnCount; i++)
				SPGrid.ColumnDefinitions.Add(new ColumnDefinition());

			SPGrid.RowDefinitions.Clear();
			for (int i = 0; i < rowCount; i++)
				SPGrid.RowDefinitions.Add(new RowDefinition());

			Random rand = new Random();
			for (int rowIndex = 0; rowIndex < rowCount; rowIndex++)
			{
				for (int colIndex = 0; colIndex < columnCount; colIndex++)
				{
					var randomColorBrush = new SolidColorBrush(Color.FromRgb((byte)rand.Next(0, 150), (byte)rand.Next(0, 150), (byte)rand.Next(0, 150)));

					var lbl = new Label
					{
						Content = $"column {colIndex}, row {rowIndex}",
						Foreground = Brushes.White,
						Background = randomColorBrush,
						VerticalContentAlignment = VerticalAlignment.Center,
						HorizontalContentAlignment = HorizontalAlignment.Center
					};

					Grid.SetColumn(lbl, colIndex);
					Grid.SetRow(lbl, rowIndex);

					SPGrid.Children.Add(lbl);
				}
			}
		}
	}
}

```

**Comment by Resonanz** [comment]
And here is working code with the NuGet .NET Core package installed. This plots nicely:

```
using System;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;


namespace WpfApp27
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();


			int columnCount = 5;
			int rowCount = 7;

			SPGrid.ColumnDefinitions.Clear();
			for (int i = 0; i < columnCount; i++)
				SPGrid.ColumnDefinitions.Add(new ColumnDefinition());

			SPGrid.RowDefinitions.Clear();
			for (int i = 0; i < rowCount; i++)
				SPGrid.RowDefinitions.Add(new RowDefinition());

			Random rand = new Random();
			for (int rowIndex = 0; rowIndex < rowCount; rowIndex++)
			{
				for (int colIndex = 0; colIndex < columnCount; colIndex++)
				{
					var wpfPlot = new ScottPlot.WpfPlot();
					wpfPlot.plt.Title($"column {colIndex + 1}, row {rowIndex + 1}");
					wpfPlot.plt.PlotSignal(ScottPlot.DataGen.RandomWalk(rand, 100));
					wpfPlot.Render();

					Grid.SetColumn(wpfPlot, colIndex);
					Grid.SetRow(wpfPlot, rowIndex);
					SPGrid.Children.Add(wpfPlot);
				}
			}
		}
	}
}
```
