### ISSUE TITLE
Need Improvement in formsplot.mousecordinate

### ISSUE THREAD

**Issue by gobikulandaisamy** [swharden/ScottPlot#270]
Please find the attached PDF and Testplot.zip.
[Need Improvement in mousecordinate.pdf](https://github.com/swharden/ScottPlot/files/4244280/Need.Improvement.in.mousecordinate.pdf)
[TestPlot.zip](https://github.com/swharden/ScottPlot/files/4244281/TestPlot.zip)

**Comment by swharden** [comment]
I think this was all fixed in #269 

It's not on nuget yet though but it is fixed here if you download ScottPlot from github
