### ISSUE TITLE
labels are too large when display scaling is used (WPF only)

### ISSUE THREAD

**Issue by zrolfs** [swharden/ScottPlot#273]
Hello!
First off, thank you for making this excellent library.
I am having an issue where the x-axis labels are being slightly cropped off. I'm sure this is user error, but I can't find a solution. I'm using the QuickStart example for the WPF on version 4.0.18.

![image](https://user-images.githubusercontent.com/16883585/75273023-ae6ff200-57c4-11ea-8e08-b9908eee88b5.png)

Thank you for your help,
Zach

**Comment by swharden** [comment]
Thanks for reporting this @zrolfs! I'll take a closer look at this tonight

**Comment by swharden** [comment]
Hey @zrolfs, the quickstart here works fine on my machine: [/doc/quickstart/WpfApp](https://github.com/swharden/ScottPlot/tree/master/doc/quickstart/WpfApp)

https://github.com/swharden/ScottPlot/blob/c723b897e364314a9eec7905afa3ea8fa9e71d46/doc/quickstart/WpfApp/MainWindow.xaml#L10-L12

https://github.com/swharden/ScottPlot/blob/c723b897e364314a9eec7905afa3ea8fa9e71d46/doc/quickstart/WpfApp/MainWindow.xaml.cs#L23-L31

Is the code you're using different than this?

**Comment by swharden** [comment]
... and I have to ask, are you using display scaling? If you disable display scaling, is the problem fixed? GDI+ (ScottPlot's rendering system until version 4.2 is released) is known to play well with scaled displays.

I'll go ahead and close this issue for now because I think you can fix your issue with:

```cs
plt.Layout(yScaleWidth: 20, titleHeight: 20, xLabelHeight: 20, y2LabelWidth: 20);
```

https://github.com/swharden/ScottPlot/tree/master/cookbook#custom-padding

**Comment by zrolfs** [comment]
Thanks for your help and quick response @swharden!

When I download and run the quickstart solution, I get the same issue:
![image](https://user-images.githubusercontent.com/16883585/75314406-47365a00-5825-11ea-93bc-f064866b80b8.png)

I'm not sure if I'm using display scaling or not... I can follow up if you're interested.

The line `RatioComparisonPlot.plt.Layout(yScaleWidth:20, titleHeight: 20, xLabelHeight: 20, y2LabelWidth: 20);`
fixed the x-axis but cropped the y-axis. However, `RatioComparisonPlot.plt.Layout(titleHeight: 20, xLabelHeight: 20, y2LabelWidth: 20);` worked great for both! This think this work around will be acceptable for me. Thanks again!

**Comment by swharden** [comment]
> `RatioComparisonPlot.plt.Layout(titleHeight: 20, xLabelHeight: 20, y2LabelWidth: 20);` worked great for both! I think this work around will be acceptable for me. Thanks again!

Sounds good! Another thing to try could be `plt.Ticks(fontSize: 10);`

Best,
Scott

**Comment by swharden** [comment]
I ran across this problem myself. It looks like title and axis label size is normal, but ticks are huge. I'm using display scaling on this computer. My guess is that tick label font size isn't set, and being auto-detected somehow 🤔 

![image](https://user-images.githubusercontent.com/4165489/75559039-c340c580-5a10-11ea-8dad-9df068540539.png)

**Comment by swharden** [comment]
An alternative temporary fix is:

```cs
wpfPlot1.plt.Ticks(fontSize: 8);
```

**Comment by zrolfs** [comment]
Yep, that works for me!

**Comment by zrolfs** [comment]
Maybe unrelated, but I'm getting two horizontal red lines on the perimeter of the plot. Are you familiar with this? They're visible in the first figure.

**Comment by swharden** [comment]
> Maybe unrelated, but I'm getting two horizontal red lines on the perimeter of the plot. Are you familiar with this? They're visible in the first figure.

Yeah, this was fixed by 7e72265a624466585c5efe877b79f012999e1835

It'll be fixed in the next NuGet release

**Comment by swharden** [comment]
Fixed this issue with 4837053 - it'll be in the next NuGet release (hopefully today)

**Comment by swharden** [comment]
Spoke too soon. Ticks are still oddly larger than labels when display scaling is on.
![image](https://user-images.githubusercontent.com/4165489/75611581-bfcd3d00-5ae9-11ea-8412-8ae92fb52115.png)

**Comment by swharden** [comment]
Finally figured this out...

All fonts created like this
```cs
var fnt = new Font(fontName, fontSize);
```
should be like this to disable display scaling:
```cs
var fnt = new Font(fontName, fontSize, GraphicsUnit.Pixel);
```

or like this to support display scaling:
```cs
var fnt = new Font(fontName, fontSize, GraphicsUnit.Point);
```

A thorough review of the whole project should be conducted to find all new Font creations and ensure consistency. I bet something similar should be done with lines, circles, etc. The simplest solution for now is to disable display scaling across the whole project and work only in pixel units.
