### ISSUE TITLE
cookbook misrepresents Plot.SaveFig() arguments

### ISSUE THREAD

**Issue by Resonanz** [swharden/ScottPlot#276]
plt.SaveFig arguments in the cookbook show dimensions:

`plt.SaveFig(600, 400, "01e_Legend.png");`

however these are not available. Is this documentation out-of-date, or is it that I am using .NET Core 3.1?

**Comment by swharden** [comment]
Oh man good catch! I've got to fix that for sure 😝 thanks for letting me know about it!

The line in the cookbook generator that needs fixing is here:
https://github.com/swharden/ScottPlot/blob/337c36cbd9d050e16023924b15c41c2cd199ee15/tests/Cookbook/Report.cs#L83-L84

**Comment by swharden** [comment]
actually, a totally new cookbook system solved this issue!
