### ISSUE TITLE
Edit NuGet description to indicate supported frameworks

### ISSUE THREAD

**Issue by Resonanz** [swharden/ScottPlot#278]
When I go to NuGet and search for ScottPlot, it is not obvious which is for .NET Core and which is for .NET Framework. Can the description be made clearer?

**Comment by swharden** [comment]
The package supports both! I'll add this to the description

**Comment by swharden** [comment]
![Capture+_2020-02-27-17-33-48~2](https://user-images.githubusercontent.com/4165489/75493263-7a90fa00-5987-11ea-9517-0b4d107a66f5.png)

**Comment by swharden** [comment]
Done! Thanks for the tip. I also gave this topic its own section header on the main page:
https://github.com/swharden/ScottPlot#supported-platforms

**Comment by swharden** [comment]
spaces in the description make it display poorly in narrow browser windows. It also has funny indentation. note to self: fix this before next release

https://www.nuget.org/packages/ScottPlot/
