### ISSUE TITLE
Procedural (and small) plotting shows line (= borders?)

### ISSUE THREAD

**Issue by Resonanz** [swharden/ScottPlot#279]
When plotting really small plots (100x100px for example) and also procedural plots, there appears a thin line demarcating the plots.

![image](https://user-images.githubusercontent.com/6218191/75495664-e759d200-5a23-11ea-9825-f6a3441d64a1.png)

**Comment by swharden** [comment]
You're right! That was fixed in 7e72265 by forcing ScottPlot to have a transparent background. That change isn't on NuGet yet, but it has been made to the source (so I'll close this issue).

You can fix it by using ScottPlot from source, or perhaps by changing:

```cs
var wpfPlot = new ScottPlot.WpfPlot();
```

to:

```cs
var wpfPlot = new ScottPlot.WpfPlot { Background = Brushes.Transparent };
```
