### ISSUE TITLE
manually define grid spacing

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#28]
modify `Grid()` to add arguments which allow the user to manually define grid spacing (or send `null` for automatic). X and Y grids should be controlled independently.

**Comment by swharden** [comment]
## Possible Solution
I think I came up with something that could work... though I might refine it a bit between now and when it's released on NuGet. @citizen3942 what do you think?

```cs
scottPlotUC1.plt.Grid(xSpacing: 5, ySpacing: 0.2);
```

## Working Demo
I made a demo program using this method: check out the [source code](https://github.com/swharden/ScottPlot/tree/master/demos/ScottPlotDemoCustomGrid) or the [compiled version](https://github.com/swharden/ScottPlot/tree/master/demos/ScottPlotDemoCustomGrid/compiled)

![image](https://user-images.githubusercontent.com/4165489/60225943-0251c200-9857-11e9-8cda-afc3096e15e9.png)

**Comment by citizen3942** [comment]
This is really good, though the ticks are not synchronized in the compiled version. My development has those ticks turned off, so I am good.

**Comment by swharden** [comment]
> the ticks are not synchronized in the compiled version

@citizen3942 what do you mean? The text labels don't align with grid lines? It works as expected for me...

Extremely dense ticks cause text labels to overlap, but this is expected if you manually define tick spacing.

**Comment by citizen3942** [comment]
I mean the text labels alignment with grid lines.

![image](https://user-images.githubusercontent.com/7060628/60269266-c9692a00-98f6-11e9-9626-6ae905788776.png)

The labels should be halved once they start overlapping. Say, we have grid-line with label, then the next one does not have, and the one after that has label, and so on.

**Comment by swharden** [comment]
This is indeed a bug! 

When it looks "broken" it fixes itself as soon as you click-drag to pan, so I'll take a closer look and make sure the tick labels regenerate and the graph is properly re-rendered every time the tick spacing is changed.

**Comment by swharden** [comment]
I fixed this issue 21fd69115fd0026ede30d4fec5a80a3953ea4ee1 and updated the [compiled demo](https://github.com/swharden/ScottPlot/tree/master/demos/ScottPlotDemoCustomGrid/compiled). These new grid arguments for manually setting grid spacing will probably make it unchanged into the next release.

https://github.com/swharden/ScottPlot/blob/21fd69115fd0026ede30d4fec5a80a3953ea4ee1/src/ScottPlot/Plot.cs#L448-L457
