### ISSUE TITLE
sign packages

### ISSUE THREAD

**Issue by jmecosta** [swharden/ScottPlot#283]
Hi,

can you please provided signed nuget packages please... this is the new trend in .net world!

thanks

**Comment by swharden** [comment]
Hey @jmecosta, thanks for the suggestion! I'll sign the next release.

**Comment by swharden** [comment]
> Hey @jmecosta, thanks for the suggestion! I'll sign the next release.

I said this when I thought it was free like how I sign my Android apps before uploading them to the Play store. I now appreciate that this is not the case:

Provider | Yearly cost
---|---
[DigiCert](https://www.digicert.com/code-signing/) | $474
[Symantec](https://trustcenter.websecurity.symantec.com/process/trust/productOptions?productType=SoftwareValidationClass3) | $499
[GoDaddy](https://www.godaddy.com/web-security/code-signing-certificate) | $599 ($199 renew)
[GlobalSign](https://www.globalsign.com/en/code-signing-certificate) | $289
[Sectigo](https://sectigo.com/signing-certificates/code-signing) | $166

While I like the idea, this is not feasible for a small open-source project like ScottPlot. If you have more information about this topic (such as how to sign nuget packages using free tools the way [Google makes it easy to sign packages for Google Play](https://support.google.com/googleplay/android-developer/answer/7384423)) let me know! I'm certainly interested in learning more...

Scott

**Comment by jmecosta** [comment]
apologies, i meant sign with strong name!  they dont necessarily need to be singned with a payed certificate. the error is that i cant use this assembly because it doenst have strong name!

**Comment by swharden** [comment]
https://docs.microsoft.com/en-us/dotnet/standard/assembly/sign-strong-name

**Comment by swharden** [comment]
https://github.com/dotnet/runtime/blob/master/docs/project/strong-name-signing.md

**Comment by swharden** [comment]
> can you please provided signed nuget packages please... 

Hey @jmecosta, packages are signed and new NuGet packages will be uploaded this weekend. 

I committed the keys into the repo which felt weird, but I'm reminded that keys are to provide unique IDs and not intended for any security purposes.

**Comment by jmecosta** [comment]
Great, thanks.
