### ISSUE TITLE
Interactive cookbook repeated rerender.

### ISSUE THREAD

**Issue by StendProg** [swharden/ScottPlot#294]
Steps to reproduce:
1. Click and hold mouse button.
2. Start mouse move.
3. Stop mouse move, but still hold mouse button.

Benchmark and cookbook shows repeated rerender, looks like `mouse move event` triggered, but mouse not moving.
Maybe this is what is intended for interactive cookbook, but it look different with previous behavior.

Update:
Disable gBPlot.Text updates, fix this issue.
It looks like updating parent container context somehow affect on `MouseMove` `event`.

**Comment by swharden** [comment]
@StendProg thanks for noticing this!

I made a textbox beneath the plot which now gets updated with benchmark information and it seems to have resolved the problem.

![image](https://user-images.githubusercontent.com/4165489/76685194-38eb8a80-65e8-11ea-80cf-1ae807307647.png)
