### ISSUE TITLE
Custom formatting function for ticks

### ISSUE THREAD

**Issue by OgreTransporter** [swharden/ScottPlot#297]
It would be helpful if you could specify a custom formatting function for the ticks, which gets the value of the tick and returns a string. So you can format the ticks more easily yourself. For example date and time for a scatter plot. Or is there already a possibility to display date & time in a scatter plot? Otherwise you could simply use the DateTime.ticks as X values and then use a formatting function to create a DateTime object and then a formatted string from the ticks.

**Comment by swharden** [comment]
Hey @OgreTransporter, do these methods / examples provide the functionality you're looking for?

```cs
plt.Ticks(dateTimeX: true);
```

http://swharden.com/scottplot/cookbooks/4.0.20/#Customize_Ticks_DateAxis

```cs
double[] xPositions = { 7, 21, 37, 46 };
string[] xLabels = { "VII", "XXI", "XXXVII", "XLVI" };
plt.XTicks(xPositions, xLabels);
```

http://swharden.com/scottplot/cookbooks/4.0.20/#Customize_Ticks_Positions

**Comment by swharden** [comment]
The examples above combined with the feature that was just added in #301 will probably solve your issue.

http://swharden.com/scottplot/cookbooks/4.0.21/#Customize_Ticks_CustomCulture

If not, feel free to open this issue again
