### ISSUE TITLE
Grid Spacing on Horizintal / X Date Axis

### ISSUE THREAD

**Issue by SeidChr** [swharden/ScottPlot#299]
Hi there, thank you for the great tool :)

Using your lib for my corona tracker: https://github.com/SeidChr/COVID-19-Report-Data-Pipeline/wiki/The-Plot

Trying to set a grid spacing on the X axis to 7 days, so one can easily count the weeks, but whatever i put in the plt.Grid(xSpacing: XXX) command seems to have not effect at all.

Is there some way to achieve this?

**Comment by swharden** [comment]
I created a cookbook example to test this out and track progress toward fixing this issue. You're correct, `plt.Grid(xSpacing: 1)` is ignored when `plt.Ticks(dateTimeX: true)` is used.

I'll leave this open to track my progress toward fixing this issue.

In the mean time, you could define tick positions manually like this:
http://swharden.com/scottplot/cookbooks/4.0.20/#Customize_Ticks_Positions
It would also give you an opportunity to format the labels as you like.

**Comment by swharden** [comment]
**I remembered why this is so difficult:** If a user wanted to define horizontal tick spacing as 1 month, how would they do it? They can't define a certain number of days (how DateTime.ToOATime() works) because different months have different names. Working with DateTimes is very challenging...

Still working on a fix. It will probably require the user define a DateTime unit of magnitude, and the tick spacing (multiples of that magnitude) like this:

```cs
plt.Ticks(dateTimeX: true, dateTimeUnit: Config.DateTimeUnit.months, dateTimeSpacing: 1);
```

**Comment by swharden** [comment]
A high DateTime density highlights the need for #160, but fixed-unit DateTime grid spacing seems to be working now.

https://github.com/swharden/ScottPlot/blob/749c4b8ddf358fdee797ff8d884fcb0781bfdc8d/tests/Ticks/TickGeneration.cs#L70

![image](https://user-images.githubusercontent.com/4165489/76707630-36ac2d80-66c7-11ea-97de-aad80c5127b5.png)

**Comment by SeidChr** [comment]
Cool, and interface looks good. 
Can't wait for the release 😊

**Comment by swharden** [comment]
Now that #300 is completed I think this issue is solved.

```cs
pltTest.Ticks(dateTimeX: true, xTickRotation: 45);
pltTest.Layout(xScaleHeight: 60);
```

![image](https://user-images.githubusercontent.com/4165489/76708046-4aa55e80-66ca-11ea-9189-345352955e02.png)

**Comment by SeidChr** [comment]
Hi, what do you think, when could you make a release?

**Comment by swharden** [comment]
> Hi, what do you think, when could you make a release?

Source code is ready to use now
https://github.com/swharden/ScottPlot/archive/master.zip

I'll fix a few more things then upload a new NuGet package tonight

**Comment by swharden** [comment]
> > Hi, what do you think, when could you make a release?
> 
> Source code is ready to use now

Inspired by this comment I added a new section to the readme:
https://github.com/swharden/ScottPlot#build-from-source

I'll post a nuget package in a few more minutes though
