### ISSUE TITLE
histogram

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#30]
add `Plot.PlotHistogram()` which takes a 1D dataset, optional arguments about bin size and limits and normalization, creates the bins/counts, then just calls `Plot.Bar(bins, counts)`

... or consider making a `ScottPlot.Histogram` class? It may be easier to just `Plot.Bar(hist.bins, hist.counts)`. This also makes it easy to package different features like placing limits at the 95 percentile, or adding stats to test for normal distribution

**Comment by AteCoder** [comment]
Typically, the histogram includes two bins outside the range, one at index 0, for the counts below the minimum and the other at index n+1 counting values above the maximum. Then, each bin might count items within half open intervals, i.e., (xi,xi+1] or [xi, xi+1) with the out of range bin eanges matching the in range bin intervals. 

Scott, thank u for the great job u have been doing on this project. Please keep your charts tight, simple and fast!

**Comment by swharden** [comment]
@AteCoder you raise some excellent points, thanks for the suggestions! They encouraged me to read more on this topic.

Present behavior for a histogram where min/max is manually defined is for out-of-bounds data to be added to the lowest bin or highest bin. This is probably poor design because it's not what users would expect. Your suggestion is to have an extra bin added to each side of the histogram to catch these outliers, which sounds like a better idea... but it still feels slightly off if users aren't expecting it (bin[0] will be lower than their defined minimum).

I checked matplotlib (a prominent graphing library for Python) and noticed that [matplotlib.pyplot.hist2d()](https://matplotlib.org/3.1.0/api/_as_gen/matplotlib.pyplot.hist2d.html#matplotlib.pyplot.hist2d) and [matplotlib.pyplot.hist()](https://matplotlib.org/3.1.0/api/_as_gen/matplotlib.pyplot.hist.html) both actually _ignore_ out-of-range data. Perhaps this should be the default case for ScottPlot, and I can add a `catchOutliers` argument which, if true, would catch outliers into an extra pair of bins like you suggested.

I'll work on this a bit more (related to issue #34) and update this issue when I've made progress.

Histograms are currently generated by:
https://github.com/swharden/ScottPlot/blob/7a643ccf3f727578bc8d3c4f3e1723f894d05099/src/ScottPlot/Histogram.cs#L63-L78

**Comment by AteCoder** [comment]
Either way would be fine assuming the will be documented.

Values that fall outside the min/max range might better be called 'out of range' values because 'outliers' are typically defined based on quartiles and may not match what the user may  set as the min/max values.




________________________________

**Comment by AteCoder** [comment]
BTW, seeing that the index is rounded, which means tge mid values are rounded to even values as opposed to away from zero as in Excel. Consequently, the intervals switch between (,] and [,) on odd and even indexes. This is likely minutia but shows how coding shortcuts have interesting implications.

Keeping the code as is would be fine aiming at simplicity and speed, but, perhaps, when time allows, an alternative histogram function could be offered by the purists.  

On the accumulation if values at the first and last bins, note that it depends on the objectives. In quality assurance, the limits are typically set at 6 sigma (+/-3sigma) and the out of range values should not be counted with in range values, obviously (the work around might be to add a bin on each end but that would change the range). So the Python implementation might reveal a different mindset, such as likelihood issues related to AI. Totally different ball game.


Thanks again for your great effort!

**Comment by swharden** [comment]
@AteCoder thank you for your insightful comments! I especially liked your suggestion auto-detecting min/max to +/- 3*stDev. I added a several arguments to the `Histogram` constructor which lets you customize all the options we've discussed so far. What do you think?

Users who require specific analytical procedures (like interval switching histograms) should probably use a dedicated statistics library to generate the histogram data they need, then use ScottPlot to display it.

### Histogram Constructor
https://github.com/swharden/ScottPlot/blob/8fe93569372ce511fc390395b8bb1f91e48d5e39/src/ScottPlot/Histogram.cs#L20-L56

### Demo Program
I made a new histogram demo that lets you play with these options ([source](https://github.com/swharden/ScottPlot/tree/master/demos/ScottPlotDemoHistogram))
![image](https://user-images.githubusercontent.com/4165489/60389098-ceaaae00-9a89-11e9-955b-3c7ebc0e8fcc.png)

**Comment by AteCoder** [comment]
trying 10 values and bin count of 10 leaving the other options unchanged, i got 10 values between 0 and 100.  In this case, should the bin width be 10? it seems to be around 15. Where should the first bin start? it seems it starting at -10, should it start at 0?  Also, i get three values between 30 and 40 but the bin count of the bin that seems to span that range is 4.  
Does it make sense to expect bin(0) at [0,10) and bin(0)+= 1 if 0 = Math.Max(0,Math.Floor((x-x0)/dX))), where x0 is the low limit and dX is the bin width?

**Comment by swharden** [comment]
I added a box displaying the bins to the histogram demo program to simplify assessment.

When you plot values with a bin count of 10 _using default max and min_ values, the max and min are the mean +/- 3*stDev of the data. The binSize is then (max - min) / binCount. Since the standard deviation changes with every new dataset, bin[0] (and the binSize) changes with every new dataset.
![image](https://user-images.githubusercontent.com/4165489/60398901-7fb55500-9b2b-11e9-8f12-6370992fa5c4.png)

To get a fixed binSize when targeting a binCount, manually define min/max. This also places bin[0] at a predictable location (min).
![image](https://user-images.githubusercontent.com/4165489/60398927-b4291100-9b2b-11e9-9169-73e57d02151d.png)

I think this is the behavior a user would expect... but if I missed something certainly let me know!

**Comment by AteCoder** [comment]
On the second example bin count is 10 but the list has 11 bins. Also, bin 9 centers at zero. This could be okay in some applications. Another way of looking at the bins is as basckets which hold the number of items matching their range, in which case bin 0 is [0,10), 1: [10,20),...,9:[90,100).
________________________________

**Comment by swharden** [comment]
You raised an excellent point: when defining binCount as 10, the Histogram produces 11 bins. This is a problem, and the last bin is always empty since it is the same value as max. I will modify the code to prevent this last bin from being created - does this fully resolve the issue?
