### ISSUE TITLE
Put X-Labels at an angle

### ISSUE THREAD

**Issue by SeidChr** [swharden/ScottPlot#300]
I know it from the usual tools like excel or google spreadsheets, that you can have X-labels that are printed at an angle, so there can be more lables on less space:

![image](https://user-images.githubusercontent.com/1927076/76689600-cd310e00-6637-11ea-8d1d-d8d4bdf925e8.png)

Couldnt find a way to do this with ScottPlot. Can you add it?

**Comment by swharden** [comment]
Thanks for the suggestion @SeidChr! This would be a great improvement, especially for date ticks.

A small gotcha would be that the layout-detecting code currently uses tick label height to determine how much space to allocate for the lower ticks, but once we get ticks rendering at an angle I can adjust the layout code to accomodate it.

Would you be interested in giving this a try? Horizontal ticks are rendered in this code block. I'd suggest starting by hard-coding a 45º angle, then later worrying about how to let the user select this.

https://github.com/swharden/ScottPlot/blob/69ede7b1e6cdb80eaea81567e617db599b9868c1/src/ScottPlot/Renderer.cs#L273-L274

**Comment by swharden** [comment]
I'll tackle this now. I can get code hints from the solution of #160.

**Comment by swharden** [comment]
![image](https://user-images.githubusercontent.com/4165489/76708355-7aedfc80-66cc-11ea-87d9-f222e13b3dbf.png)
