### ISSUE TITLE
modified git history (and impact on forks)

### ISSUE THREAD

**Issue by StendProg** [swharden/ScottPlot#305]
Hi @swharden .
You rewrite git history?
I try to make PR and get difference in 1400 commits.

**Comment by swharden** [comment]
Yeah, I edited the history to remove thousands of cookbook images (#271) which were making this repo unnecessarily large. The only modifications in the code base are deletions the /cookbook folder, but I understand this changed all the commit hashes moving forward.

What do you think the best way is to proceed with your PR? Make a new clone, copy/paste the /src file, then make a new PR? I'm really sorry for making this complicated - hopefully the issue won't be too hard to resolve!

**Comment by StendProg** [comment]
I will make this PR in my fork #306.
You can manual grab this, this contain only additions.
That I afraid for, it's `SkiaControl` branch.
By rewriting history you made unactual all forks.
In all git books present this words: "`Never` change history for published brunches".
I will investigate tomorrow that is possible to do with this problem.

**Comment by swharden** [comment]
> I will make this PR in my fork #306.
> You can manual grab this, this contain only additions.

I applied the patches you described and closed #306

> In all git books present this words: "`Never` change history for published brunches".

I am aware this is highly discouraged. Those books also say to only check-in source code (not binaries and data) to source control, and my initial motivation was to correct that problem... but I recognize I may have made a much bigger problem in the proccess.

> That I afraid for, it's `SkiaControl` branch.
> By rewriting history you made unactual all forks.
> I will investigate tomorrow that is possible to do with this problem.

I now recognize the magnitude of this problem for branches depending on the ScottPlot history. I have a copy of this repo saved before I modified the history. I can try to push that back up to GitHub, and perhaps your branch will return to normal. What do you think?

**Comment by swharden** [comment]
> I have a copy of this repo saved [a few hours ago] before I modified the history. 
I can try to push that back up to GitHub, and perhaps your branch will return to normal.

I think we should try this. Even if it doesn't work, it seems unlikely to make the problem worse. I'll wait until I hear back from you though.

**Comment by StendProg** [comment]
> I now recognize the magnitude of this problem for branches depending on the ScottPlot history. I have a copy of this repo saved before I modified the history. I can try to push that back up to GitHub, and perhaps your branch will return to normal. What do you think?

I think what has been done is done. There is not so much people affected by this. Some type of notification for active contributors will be good. But i think they got this then try to sync with upstream. It's easy to remove fork and create new one, but loose all data
`SkiaControl` present and work in my fork, the only problem is syncing with new upstream. Maybe there easy way to solve this. I investigate tomorrow.
Don't worry so much. You done much much more then break ;-)

**Comment by swharden** [comment]
> There is not so much people affected by this. 

True, but this affected you, and I consider you of my most skilled and helpful contributors! Your work on the `SkiaControl` and the contributions you have made to ScottPlot represent a fantastic efforts, and I feel bad for modifying the repo in a way that made your fork difficult to work on.

> Maybe there easy way to solve this. I investigate tomorrow.

Let me know what I can do to help! I'll wait to make any changes (including trying to revert to my saved repo with the original history) until I hear back from you. Hopefully we can find a good solution to this issue!

**Comment by StendProg** [comment]
Git is a magic system. For now i have `masterOld`, `SkiaControl` (based on old master), `master` (upstream version) and `SkiaControlClean` all in my fork. `SkiaControlClean` based on new `master`, I done it with applying patches on new branch.
So, this problem solved for me.

**Comment by swharden** [comment]
> Git is a magic system. For now i have `masterOld`, `SkiaControl` (based on old master), `master` (upstream version) and `SkiaControlClean` all in my fork. `SkiaControlClean` based on new `master`, I done it with applying patches on new branch.
> So, this problem solved for me.

This is great to hear! I'm glad you found a solution. I'll be careful to ensure I never modify the history of public branches again 👍
