### ISSUE TITLE
Autoscale axes

### ISSUE THREAD

**Issue by Resonanz** [swharden/ScottPlot#309]
Hi Scott, great job with the new releases !!!  Wondering about autoscaling scatter plots..... have you considered adding that as an option? Thanks !

**Comment by swharden** [comment]
`plt.AxisAuto()` or middle-clicking the user control should do the trick!

Re-open this issue if you had something else in mind :+1:

**Comment by swharden** [comment]
Actually, maybe I should alias `plt.AxisAuto` to `plt.AutoAxis` to make it easier to discover :thinking:

**Comment by swharden** [comment]
Auto-scaling an axis is an extremely common task. To make the function easier to locate, I added alias functioned named `AutoAxis()` and `AutoScale()`.

They're marked as obsolete so if a user finds them and tries to use them, they're notified of the correct function to use: `AxisAuto()`
