### ISSUE TITLE
clean-up demos folder

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#31]
The majority of code in this repo is now demos. Should demos get their own repo? Perhaps we can keep 1 master demo here that demonstrates all core features?

**Comment by citizen3942** [comment]
In my opinion it is nice to have all demos listed in this current repository, otherwise one must put in more effort to find different solutions from other "areas".

**Comment by swharden** [comment]
Regarding the [/demos/](/demos/) folder I will
* Add a readme and screenshot to every demo
* Automate the build process so binary versions of demos are always available

**Comment by swharden** [comment]
Reorganization is happening here
https://github.com/swharden/ScottPlot/tree/cleaner-demos
