### ISSUE TITLE
programmatically create grid of WpfPlot controls #3

### ISSUE THREAD

**Issue by Resonanz** [swharden/ScottPlot#311]
Hi Scott, I have a class that creates a 12 x 8 grid which is partly shown below. The code in the class fills each cell with a ScottPlot.WpfPlot object as shown below. The WPF XAML code displays these plots nicely on a WPF grid, but...... weirdy thing is that this code produces a rectangular plot outline box at (0,0) which is top left position even if I never call the setRow and setColumn, but just use the first code block below. If I click inside the rectangle, gridlines appear and axes are both labeled from -1 to +1.  I'm wondering if there is a small bug that places a minimum of one rectangle on the grid? Other locations on the grid, where I add data using the second block of code below, plot the data nicely at the correct locations. Any thoughts?

First code block

```
        public ScottPlotGrid(Grid SPGrid, int numPlotColumns, int numPlotRows)
        {
            this.SPGrid = SPGrid;
            this.numPlotColumns = numPlotColumns;
            this.numPlotRows = numPlotRows;

            this.SPGrid.ColumnDefinitions.Clear();
            for (int i = 0; i < numPlotColumns; i++)
                this.SPGrid.ColumnDefinitions.Add(new ColumnDefinition());

            this.SPGrid.RowDefinitions.Clear();
            for (int i = 0; i < numPlotRows; i++)
                this.SPGrid.RowDefinitions.Add(new RowDefinition());

            wpfPlot = new ScottPlot.WpfPlot[numPlotColumns * numPlotRows];  // Create and array to hold the row x col ScottPlot objects

            for (int idx = 0; idx < (numPlotColumns * numPlotRows); idx++)  // Instantiate ScottPlot objects, and pop them into the grid
            {
                wpfPlot[idx] = new ScottPlot.WpfPlot();
                SPGrid.Children.Add(wpfPlot[idx]);
            }
        }
```

Second code block

```
        public void PlotCorrelation(int wellNum, int numCols, AviDataStor dataStor)
        {
            wpfPlot[wellNum].plt.PlotScatter(dataStor.dataColumns[0], dataStor.dataColumns[1], lineWidth: 0, markerSize: 3);
            wpfPlot[wellNum].plt.AxisAuto();
            wpfPlot[wellNum].Render();

            Grid.SetColumn(wpfPlot[wellNum], wellNum % numCols); // Convert linear well number into 2d row/column
            Grid.SetRow(wpfPlot[wellNum], wellNum / numCols);
        }
```

**Comment by swharden** [comment]
> code produces a plot at (0,0) even if I never call the SetRow or SetColumn

Take a closer look at the values SetColumn and SetRow is using. Replace the last two lines of your `PlotCorrelation()` method with this and run the program and inspect the output:

```cs
int columnIndex = wellNum % numCols;
int rowIndex = wellNum / numCols;
Debug.WriteLine($"Creating plot at {columnIndex }, {rowIndex}");

Grid.SetColumn(wpfPlot[wellNum], columnIndex);
Grid.SetRow(wpfPlot[wellNum], rowIndex);
```

Are you sure a plot is showing up at (0, 0) even though it is not placed there?

**Comment by swharden** [comment]
This may be a better answer:

```cs
for (int idx = 0; idx < (numPlotColumns * numPlotRows); idx++)
{
    wpfPlot[idx] = new ScottPlot.WpfPlot();
    SPGrid.Children.Add(wpfPlot[idx]);
}
```

This code block is placing an empty ScottPlot into every grid square. If you don't want a grid placed at (0, 0), modify the for loop to start at 1: `int idx = 1`

**Comment by StendProg** [comment]
Then you do `SPGrid.Children.Add(wpfPlot[idx]);` and not specify `Grid.Row`, `Grid.Column` for them, they all dropped to (0, 0) element of Grid.

To follow WPF patterns you must avoid using code behind instead of xaml for markup.
For that you can do:
Make simple container for Grid element:
```c#
 public class PlotElement
    {
        public int X { get; set; }
        public int Y { get; set; }
        public ScottPlot.WpfPlot Control { get; set; }
    }
```

Make property in window class (code behind) to hold that elements:
```c#
        public List<PlotElement> plots { get; set; }
```

Fill that list in window constructor:
```c#
    plots = new List<PlotElement>();
    double[] xs = new double[] { 1, 2, 3 };
    double[] ys = new double[] { 5, 2, 7 };
    for (int x = 0; x < 12 ; x++) 
    {
        for (int y = 0; y < 8; y++)
        {
            PlotElement elem = new PlotElement()
            {
                X = x,
                Y = y,
                Control = new ScottPlot.WpfPlot()
            };
            elem.Control.plt.PlotScatter(xs, ys, lineWidth: 0, markerSize: 3);
            elem.Control.plt.AxisAuto();
            elem.Control.Render();
            plots.Add(elem);
     }            
```

and bind that list using xaml:
```c#
 <Grid>
        <ItemsControl ItemsSource="{Binding ElementName=controlGrid, Path=plots}">
            <ItemsControl.ItemsPanel>
                <ItemsPanelTemplate>
                    <Grid>
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition/>
                            <ColumnDefinition/>
                            <ColumnDefinition/>
                            <ColumnDefinition/>
                            <ColumnDefinition/>
                            <ColumnDefinition/>
                            <ColumnDefinition/>
                            <ColumnDefinition/>
                            <ColumnDefinition/>
                            <ColumnDefinition/>
                            <ColumnDefinition/>
                            <ColumnDefinition/>
                        </Grid.ColumnDefinitions>
                        <Grid.RowDefinitions>
                            <RowDefinition/>
                            <RowDefinition/>
                            <RowDefinition/>
                            <RowDefinition/>
                            <RowDefinition/>
                            <RowDefinition/>
                            <RowDefinition/>
                            <RowDefinition/>                      
                        </Grid.RowDefinitions>
                    </Grid>
                </ItemsPanelTemplate>
            </ItemsControl.ItemsPanel>
            <ItemsControl.ItemTemplate>
                <DataTemplate>
                    <ContentControl Content="{Binding Control}"/>
                </DataTemplate>
            </ItemsControl.ItemTemplate>
            <ItemsControl.ItemContainerStyle>
                <Style>
                    <Setter Property="Grid.Row" Value="{Binding Path=Y}"/>
                    <Setter Property="Grid.Column" Value="{Binding Path=X}"/>
                </Style>
            </ItemsControl.ItemContainerStyle>
        </ItemsControl>
    </Grid>
```

`controlGrid` is the window name, you can specify it in `<window>` section

**Comment by swharden** [comment]
> To follow WPF patterns you must avoid using code behind instead of xaml for markup.
> For that you can do ...

Wow @StendProg thank you for the fantastic example! Your advice for WPF is exccellent! I used it to create a new demo.

![image](https://user-images.githubusercontent.com/4165489/77017162-0fb45c80-6950-11ea-9623-6582b015f690.png)

**Comment by Resonanz** [comment]
Thanks a lot guys, I will study this code until I understand it !!!

**Comment by Resonanz** [comment]
Just to note here that for whatever reason, I could not get StendProg's code above to display anything on the form. I copied Scott's code from the "ManyPlots" demo code and that displayed fine. I have poked around and cannot see why it does not display. StendPlot's code is very elegant, but I cannot make it display anything.

**Comment by swharden** [comment]
> Just to note here that for whatever reason, I could not get StendProg's code above to display anything on the form. I copied Scott's code from the "ManyPlots" demo code and that displayed fine. I have poked around and cannot see why it does not display. StendPlot's code is very elegant, but I cannot make it display anything.

Don't forget to set the name of your `<Window />` - I overlooked that at first.

https://github.com/swharden/ScottPlot/blob/d0f0e8eeee437038c5f19942990b4fc3ef23e67e/src/ScottPlot.Demo.WPF/WpfDemos/ManyPlots.xaml#L8

> Guys, not sure how to contact you to say thanks, so "thanks !". Can you advise on a good book or resource for WPF programming covering "code behind" and binding and so on?

I just wait for @StendProg to post code then I study it 😜 

I'm pretty new to WPF so I don't have a great answer. I see this question asked on reddit a lot. Common answers are [pluralsight videos](https://www.pluralsight.com/search?q=wpf) (sign up for a free trial) and https://www.wpf-tutorial.com/ (free I think)

**Comment by StendProg** [comment]
I am also new to WPF, and can't make recomendation. To narrow your search you can add `MVVM` pattern. There is lots of information, if you understand base concept of `MVVM` you can find a lot.
I spend about hour to make my example work, I am also new to `WPF`, have a base understanding of `MVVM`. Code in model haven't any dependencyes on View....
