### ISSUE TITLE
draggable axis line limits

### ISSUE THREAD

**Issue by citizen3942** [swharden/ScottPlot#32]
Perhaps there should be possibility to keep the draggable line within plot area? Right now if I drag a line out of plot area, I can never access it again - that is of course if I have defined my axis region manually and is rendered every iteration in such area.

Maybe defining V or H lines like:
```csharp
public void PlotVLine(double x, Color? color = null, double lineWidth = 1, string label = null, bool draggable = false, bool bounds = false, double xMin = 0, double xMax = 50)
```

**Comment by swharden** [comment]
This is a good idea. I'll put this in shortly. 

I'll probably add arguments so you can call it like like:

```cs
plt.PlotVLine(123, draggable: true, dragLimitLower: 0, dragLimitUpper: 1000);
```

And those limits will default to - and + infinity if not specified.

**Comment by swharden** [comment]
I added 2 extra arguments to let you limit how far the user can drag a draggable axis line. 6af45afc0932a52d50dac3daff173d9d94f9689b

```cs
scottPlotUC1.plt.PlotVLine(position, draggable: true, dragLimitLower: 0, dragLimitUpper: 49);
```

By default those arguments are negative and positive infinity (no restriction on dragging).

I'll publish this with the next NuGet release
