### ISSUE TITLE
 Support of the Scott Hardens (PhD) ScottPlot for the Moxymonitor ANT to Serial Converter to support the GARMIN watch

### ISSUE THREAD

**Issue by PeterGamma** [swharden/ScottPlot#322]
I miss support of the Scott Hardens (PhD) ScottPlot for the Moxymonitor ANT to Serial Converter to support the GARMIN watch:

https://www.thisisant.com/forum/viewthread/7074/P15/

Greetings from Peter Gamma (Meditator with a GITHUB):

https://github.com/PeterGamma

but without programming skills.

**Comment by swharden** [comment]
Hi @PeterGamma, I think ScottPlot can be used for this. However, somebody would need to write C# software to interface the Garmin GPS watch first. This would definitely require programming skills, and is best accomplished by someone who owns a Garmin GPS watch

**Comment by PeterGamma** [comment]
Bad luck. For practising meditation, I always have GPS off. For me personally, it is not a GPS watch, but together with a POLAR OH1 and a STRYD foot pod as far as accuracy is concerned an underestimated research grade device, which deserves attention and will be successful sooner or later. Thank you anyway, Scott.

**Comment by PeterGamma** [comment]
The Vivoactive 3 is currently the best selling watch from GARMIN. Most of the people use it only for a short time. They are cheap on ebay. Compared to an ECG device, a  Vivoactive 3 or Forerunner 235, the inaccuracy is about 5%. Paired to a POLAR OH1, the Vivoactive 3 is as accurate as an ECG device. 
https://the5krunner.com/2019/04/06/polar-oh1-review-2019/#PRICING_AVAILABILITY_Polar_OH1_Review
I invite all skilled C# programers to add the GARMIN watch to the ScottPlott. You won t regret it.

**Comment by swharden** [comment]
For ECG, this software uses ScottPlot. @PeterGamma you may find it useful https://github.com/swharden/SoundCardECG

**Comment by PeterGamma** [comment]
Thank you Scott. I know SoundCardECG, it s a great device. To honor your do it yourself ECG, I mentioned it in the GARMIN forum. Thank you Scott for your great work and your commitement.

**Comment by PeterGamma** [comment]
Here is the link:
https://forums.garmin.com/developer/connect-iq/f/discussion/209439/eventhubapp

**Comment by PeterGamma** [comment]
Scott: 

https://www.swharden.com/wp/about-scott/

developed the sound card ecg:

https://www.youtube.com/watch?v=sP_-f5nsOEo

and the ScottPlot:

https://github.com/swharden/ScottPlot

There are now two options availble for a live-stream from a GARMIN watch:

1. Moxymonitor ANT to Serial Converter which is commercially available (for MATLAB):

https://www.thisisant.com/forum/viewthread/7074/

2. Garmin IoT Series is a Microsoft Azure Cloud solution from Dave Does Demos :

https://forums.garmin.com/developer/connect-iq/f/discussion/209439/eventhubapp

But which is software is available to analyze real-time data from a GARMIN watch? Is it possible to use Scott s software for the GARMIN watch ? (yes, Scott answered this question already). Is there any software which is better than Scott s software to use it for the GARMIN watch?

**Comment by PeterGamma** [comment]
I suggest the developement of a new GARMIN watch app called "real-time Namaste". But it could also suggest the developement of a new app called "EventHubApp bridge to Dr. Scott Hardens Scott Plott".

https://forums.garmin.com/developer/connect-iq/f/app-ideas/220116/combining-namaste-app-and-eventhubapp-to-make-a-live-stream-to-dr-hardens-scott-plott

**Comment by PeterGamma** [comment]
For me personally, this issue is not resolved. It is a real problem which makes me suffer. 
Maybe we will find a c # programmer somewhere at Garmin, Microsoft, MATLAB or at the research institutes, or among ScottPlott lovers. Is it possible to open this issue again?
