### ISSUE TITLE
How can ScottPlot be used in Xamarin.Forms?

### ISSUE THREAD

**Issue by leonyu1010** [swharden/ScottPlot#329]
I would like to try using this library in a Xamarin.forms project.  Do you think it is feasible? 
I am thinking I need to add a ScottPlot.WpfPlot equivalent for Xamarin.forms.  do u think something like  SkiaSharp SKCanvasView is going to work?

**Comment by swharden** [comment]
hey @leonyu1010 

The ScottPlot package targets .NET Standard 2.0 so it should install on Xamarin.forms.

Using code like this you can create a plot as a Bitmap in memory:

```cs
double[] dataX = new double[] {1, 2, 3, 4, 5};
double[] dataY = new double[] {1, 4, 9, 16, 25};
var plt = new ScottPlot.Plot(600, 400);
plt.PlotScatter(dataX, dataY);
Bitmap bmp = plt.GetBitmap();
```

From there perhaps you can use a library like SkiaSharp to display the Bitmap: [Bitmap Basics in SkiaSharp](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/basics/bitmaps).

If you come up with some working code, let me know and I can use it to create a Xamarin.Forms quickstart to go on http://swharden.com/scottplot/quickstart

**Comment by leonyu1010** [comment]
@swharden thanks for the quick reply. I will try it out.

**Comment by swharden** [comment]
> @swharden thanks for the quick reply. I will try it out.

Sounds great - I look forward to hearing what you find out! I'll close this issue unless we hit a snag along the way.
