### ISSUE TITLE
ScottPlot.WPF should multi-target .NET Framework and .NET Core

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#333]
right now the ScottPlot.WPF project (which provides the `WpfPlot` control) only targets .NET Core 3.0. Since ScottPlot targets .NET Standard, it should be possible to dual-target .NET Core and .NET Framework with this package.

Then I can update the demo to use .NET Framework 4.6.1 because that's more commonly available on more peoples' computers at the moment. Actually, 4.7.2 is a better choice because it produces far fewer DLLs.

**Comment by Resonanz** [comment]
Will they work on Core 3.1 Scott?  And will NuGet packages use 3.1?

**Comment by swharden** [comment]
> Will they work on Core 3.1 Scott? And will NuGet packages use 3.1?

Yep, anything newer will still work. .NET Framework 4.6.1 and .NET Core 3.0 are the ***minimum*** supported functions, so you should be good! 👍
