### ISSUE TITLE
Percentage tick labels

### ISSUE THREAD

**Issue by deiruch** [swharden/ScottPlot#336]
**What can we do to make ScottPlot better?**
I'm trying to do a Scatter plott with percentages on both axes. It'd be great it ScottPlot supported conversion from "0.3184" to "31.8%" with a simple flag.

```cs
var plot = new ScottPlot.Plot();
...
plot.Ticks(percentages: true);
```

A more flexible, alternative solution of #297 might help in this case as well.

**Comment by swharden** [comment]
> I'm trying to do a Scatter plott with percentages on both axes. It'd be great it ScottPlot supported conversion from "0.3184" to "31.8%" with a simple flag.

Hi @deiruch thanks for the suggestion! I think this is true, and a flexible option that also supported currency would be nice. I'll think about the best way to implement this and make an update soon!

**Comment by swharden** [comment]
Hey @deiruch, thanks again for the suggestion! I think this solution is an improvement across the board.

Users can now define a [standard numeric string format](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings) for X and Y tick labels. This lets users display ticks using scientific notation, percentage, currency, etc. and also control the precision of the numbers displayed in tick labels.

```cs
plt.Ticks(numericFormatStringX: "E2", numericFormatStringY: "P1");
```

![image](https://user-images.githubusercontent.com/4165489/78610631-4d135800-7833-11ea-83a0-90d9de55b342.png)

What do you think?

**Comment by deiruch** [comment]
Fantastic! Exactly what I was looking for!!!

**Comment by swharden** [comment]
Just published a NuGet package. It should be live shortly. Let me know if anything else comes up. 

Thanks again @deiruch!
