### ISSUE TITLE
Custom ContextMenu overridden by default one (WpfPlot)

### ISSUE THREAD

**Issue by Antracik** [swharden/ScottPlot#337]
As of updating to the latest ScottPlot (4.0.27) my custom context menu in WPF is no longer accessible and being overridden by the default provided one.

**Comment by swharden** [comment]
Hi @Antracik, thaks for reporting this! The FormsPlot control has had an overridable context menu for some time, but the WpfPlot control just got a context menu in this last release https://github.com/swharden/ScottPlot/commit/298a0a2cae6c7c1b7858132f83e4e79a77947264 which is what caused this issue.

```xaml
<ScottPlot:WpfPlot Name="wpfPlot2">
    <ScottPlot:WpfPlot.ContextMenu Name="cm" StaysOpen="True">
        <MenuItem Header="Add a Sine Wave" Click="AddSine"/>
        <MenuItem Header="Clear the Plot" Click="ClearPlot"/>
    </ScottPlot:WpfPlot.ContextMenu>
</ScottPlot:WpfPlot>
```

To put some code with this issue, if you try to add your own context, the XAML editor produces an error message `The property "ContextMenu" can only be set once`.

I'm adding "custom right-click menu" examples to the WinForms and WPF demo applications now, which will let me figure out the best way to do this in in both WinForms and WPF

**Comment by swharden** [comment]
@Antracik, I made some changes that improved how users can add a custom right-click menu to FormsPlot and WpfPlot. There is now a demo application for FormsPlot and WpfPlot to demonstrate this.

My understanding of the original problem is that WpfPlot's default context menu was defined in XAML and was not overridable. The solution was to make the right-click menu a property which can be replaced by the user.

https://github.com/swharden/ScottPlot/blob/50bc84aa9262c9282759f13b09e2ecc8e370fef4/src/ScottPlot.Demo.WPF/WpfDemos/RightClickMenu.xaml.cs#L32-L41

Let me know what you think of this solution!\
If you think it looks good I can publish it on NuGet this morning.

**Comment by Antracik** [comment]
I did try something like the code given above, but with the ContextMenu property exposed by WpfPlot inheritance of UserControl, while I'm sure that the given solution will work is there any reason as to why the already exposed ContextMenu property is not used?

**Comment by swharden** [comment]
> is there any reason as to why the already exposed ContextMenu property is not used?

@Antracik this is good suggestion! It was not trivial under the hood because I had to add some logic to intercept the right-click so the menu does not open when right-click-drag zooming, but I think the solution now looks good and is simple to interface.

What do you think?

### WinForms (set the ContextMenuStrip)
```cs
ContextMenuStrip customMenu = new ContextMenuStrip();
customMenu.Items.Add(new ToolStripMenuItem("Add Sine Wave", null, new EventHandler(AddSine)));
customMenu.Items.Add(new ToolStripMenuItem("Clear Plot", null, new EventHandler(ClearPlot)));
formsPlot1.ContextMenuStrip = customMenu;
```

### WPF (set the ContextMenu)
```cs
MenuItem addSinMenuItem = new MenuItem() { Header = "Add Sine Wave" };
addSinMenuItem.Click += AddSine;
MenuItem clearPlotMenuItem = new MenuItem() { Header = "Clear Plot" };
clearPlotMenuItem.Click += ClearPlot;

ContextMenu rightClickMenu = new ContextMenu();
rightClickMenu.Items.Add(addSinMenuItem);
rightClickMenu.Items.Add(clearPlotMenuItem);

wpfPlot1.ContextMenu = rightClickMenu;
```

**Comment by Antracik** [comment]
> I had to add some logic to intercept the right-click so the menu does not open when right-click-drag 

This is something else that I had an issue with but as it didn't bother me that much  I forgot to mention it. 

The solution looks good, thank you for your quick help in the matter!

**Comment by swharden** [comment]
Just published a NuGet package. It should be live shortly. Let me know if anything else comes up. 

Thanks again @Antracik!
