### ISSUE TITLE
Polygon fill alpha not applied on legend

### ISSUE THREAD

**Issue by SeidChr** [swharden/ScottPlot#341]
**Describe the bug**
fill color of the polygon looks different on the polygon than it looks on the legend:
![image](https://user-images.githubusercontent.com/1927076/78987130-67984a80-7b2d-11ea-8ca7-4142baa3f69d.png)

**To Reproduce**
use fill alpha on polygon

**Comment by swharden** [comment]
I think this one's in the bag! I may have also fixed the rendering bug that made the legend have a white block in the middle on Linux. Want to check this one out on your Linux system and see how it looks?

![image](https://user-images.githubusercontent.com/4165489/79031398-72be9b00-7b6c-11ea-9d93-20c60f6c0fb3.png)

I'm pretty confident this did the trick, but feel free to open this issue again if the result isn't what you expected. Thanks again for mentioning this @SeidChr!

**Comment by SeidChr** [comment]
looks promising!
its a hazzle to use your dev code for developing this. ill wait for the release to test it.

**Comment by swharden** [comment]
Use whatever workflow works best for you, but using the latest version and updating with git seems easier than manually updating with NuGet on every release
https://github.com/swharden/scottplot#build-scottplot-from-source-code

> To use the latest ScottPlot source code in your application, download this repository and add references in your project to ScottPlot.csproj, and one of ScottPlot.WPF.csproj or ScottPlot.WinForms.csproj (in the src folder).
