### ISSUE TITLE
PlotFill() between two curves

### ISSUE THREAD

**Issue by SeidChr** [swharden/ScottPlot#343]
**What can we do to make ScottPlot better?**

instead of just taking an array of xs and on of ys, i'd love to see a strong simplification of that api, so you can pass two sets of ys and the plot will be drawn between them. Like a "SignalRangePolygon" ?!

Im sure you can derive something from the code i wrote for my project, using your polygon api:
https://github.com/SeidChr/COVID-19-Report-Data-Pipeline/blob/310f4e91988ad31519bc951396795f249db5db61/src/Plotting/Plotter.cs#L413
```cs
        private int CreateSignalBasedPlotArea(
            Plot plt,
            IEnumerable<PlotData> data,
            Func<PlotData, int> getUpperValue,
            Func<PlotData, int> getLowerValue,
            double start,
            string label,
            Color color)
        {
            var sig = data
                .Select(pd =>
                {
                    var upper = getUpperValue(pd);
                    var lower = getLowerValue(pd);
                    return (upper, doubleUpper: (double)upper, lower, doubleLower: (double)lower);
                }).ToArray();

            var arrayLength = sig.Length;

            var xs = new double[arrayLength * 2];
            var ys = new double[arrayLength * 2];

            var fd = start;
            var rd = start + (arrayLength - 1);

            for (int i = 0, y = arrayLength, r = arrayLength - 1; i < arrayLength; i++, y++, r--)
            {
                xs[i] = fd;
                xs[y] = rd;

                fd += 1d;
                rd -= 1d;

                ys[i] = sig[i].doubleUpper;
                ys[y] = sig[r].doubleLower;
            }

            plt.PlotPolygon(
                xs,
                ys,
                fillColor: color,
                fillAlpha: PolygonFillAlpha,
                label: label + $" ({sig.Last().upper - sig.Last().lower})");

            return sig.Max(s => s.upper);
        }
```

ps: the implizit "zero-line" polygon, when there is no lower line of the polygon, but just a straight line from the last to the first point on the y-zero axis, should probably also be part of the interface somehow.
I derived this code from your sample in the cookbook:
https://github.com/SeidChr/COVID-19-Report-Data-Pipeline/blob/310f4e91988ad31519bc951396795f249db5db61/src/Plotting/Plotter.cs#L374

**Comment by swharden** [comment]
> instead of just taking an array of xs and on of ys, i'd love to see a strong simplification of that api, so you can pass two sets of ys and the plot will be drawn between them.

@SeidChr this might already exist. PlotFill() has two overloads. You can do this:

```cs
plt.PlotFill(xs1, ys1, xs2, ys2);
```

You could pass in the same `xs` twice if they're identical, but keeping them separate like this lets you also shade between two lines that have different X values.

> the implicit "zero-line" polygon, when there is no lower line of the polygon, but just a straight line from the last to the first point on the y-zero axis, should probably also be part of the interface somehow.

This is configurable by setting the optional `baseline` argument when calling PlotFill()

```cs
plt.PlotFill(xs, ys, baseline: 123);
```

Do these two solutions solve your issue? 

Thanks for the other issues you opened. I'll start working on those one by one and update them as I make progress.

**Comment by SeidChr** [comment]
Sounds good, didn't know about plotfill.
Will check tomorrow 😊

**Comment by swharden** [comment]
> Sounds good, didn't know about plotfill.
> Will check tomorrow 😊

It is one of the newest things in the library so it was easy to miss! #255 

I'll bet it'll solve your issues, but if not don't hesitate to open this issue up again. Good luck!

**Comment by SeidChr** [comment]
I just realized PlotFill is not available in .28 😞 
Seems like there happened a lot in the #255 ticket since i have last seen it.
Will wait for the next release then..

maybe you could add a "beta" release line for your dev builds? :)

**Comment by swharden** [comment]
> maybe you could add a "beta" release line for your dev builds? :)

This might happen when I introduce large, breaking changes for 4.0 -> 4.1, but is unnecessary most of the time because it's pretty trivial to just use the latest source code. I know I already pointed you to do this link, but I'm adding it here to benefit future readers of this issue:

https://github.com/swharden/ScottPlot#build-scottplot-from-source-code

> To use the latest ScottPlot source code in your application, download this repository and add references in your project to ScottPlot.csproj, and one of ScottPlot.WPF.csproj or ScottPlot.WinForms.csproj (in the src folder).
