### ISSUE TITLE
figure out how to view Azure Pipelines cookbook images

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#345]
Azure Pipelines is running all the tests on every commit, and this includes rebuilding the cookbook. I want to see what the output figures look like on Linux and MacOS.

Unfortunately, it seems Azure Pipelines is incapable of publishing build artifacts from NUnit tests projects (which ScottPlot uses).

https://docs.microsoft.com/en-us/azure/devops/pipelines/test/collect-screenshots-and-video?view=azure-devops#publish-attachments-when-not-using-the-visual-studio-test-task

A solution may be to create a MSTest project just for generating the cookbook and making the output accessible on Azure Pipelines. Alternatively, the newer GitHub Workflows might be able to aid here (@SeidChr is using this in #340)

EDIT: a solution which supports NUnit is simply to add some azure pipeline tasks to publish the test output folder (containing all the PNGs) as a build artifact.

**Comment by SeidChr** [comment]
I upload my Image output to an azure blob storage to make them publicly available. Sadly the GitHub artifacts are zipped and thus not really directly displayable with a browser

**Comment by swharden** [comment]
@SeidChr thanks for the tip! I'll take a look at your repo for hints on how to do this. I'm pretty new in this area.

I figured out how to display individual test output through the web interface. It was pretty convoluted...

![image](https://user-images.githubusercontent.com/4165489/79048145-fc13b300-7be8-11ea-8d91-176b74244005.png)

**Comment by swharden** [comment]
A better way to do this was to use the existing tests which save the whole cookbook and additional test images in the output folder, and publish the whole output folder as an Azure Pipelines build artifact.

I created a separate artifact for Linux, MacOS, and Windows to make it easy to compare... and I can already tell MacOS has some issues 😅 #340 but as far as this issue is concerned, we are in a good spot now.

![image](https://user-images.githubusercontent.com/4165489/79048896-2c118500-7bee-11ea-9a47-83b3a59e817e.png)

**Comment by swharden** [comment]
@SeidChr in response to your earlier comment about preview build NuGet packages, I exposed the build folder in Azure Pipelines which contains bleeding-edge NuGet packages built after every commit is posted to GitHub. 

If you're adventurous you're welcome to give those a try!

![image](https://user-images.githubusercontent.com/4165489/79049177-ee156080-7bef-11ea-8ae0-8d9bf360bfc1.png)
