### ISSUE TITLE
financial chart improvements

### ISSUE THREAD

**Issue by Minu476** [swharden/ScottPlot#346]
**What can we do to make ScottPlot better?**

First thank you Dr. Scott for your extreme efforts and amazing talent to make such great improvements in this library.

I am trying it now and find following small issues:

1) To make and overlay of candlestick charts( 5 minute,hourly and diay for example) with proper candle start time and end time i have to modify your library to make candle with based on time.

2) To plot Bollinger bands with filled shaded color between high band and low band, if I use PlotPolygon/PlotFill, i can not use Datetime for X axis to add it to overlay of my candlesticks drown as above.

3) To skip non trading hours or weekend  gaps on chart, I have to use dates as labels.

Please note  with several different charts i can see a lot more that before and i am very happy!

**Comment by swharden** [comment]
Hi @Minu476, I'm glad you are enjoying ScottPlot!

All 3 of your notes are related to challenges associated with using DateTime as horizontal units. I recommend not doing this if you want fine-tuned control of your plot, and instead using a series of ascending numbers for each candlestick: 1, 2, 3, etc.

> To make and overlay of candlestick charts( 5 minute,hourly and diay for example) with proper candle start time and end time i have to modify your library to make candle with based on time.

I'm not sure I fully understand the concern. Can you add a screenshot and/or code sample to help demonstrate the deficiency? If you haven't seen it, review the cookbook examples related to this topic:
* http://swharden.com/scottplot/cookbooks/4.0.29/#plottypes-finance-ohlc-with-gaps
* http://swharden.com/scottplot/cookbooks/4.0.29/#plottypes-finance-ohlc-without-gaps

> To plot Bollinger bands ... i can not use Datetime for X axis to add it to overlay of my candlesticks drown as above.

This is correct. If you used an ascending series of values (1, 2, 3...) for your horizontal axis, use those same values to plot your Bollinger bands.

This issue reminds me that I should add a Bollinger band and SMA example for the cookbook. Thanks for mentioning it!

> To skip non trading hours or weekend gaps on chart, I have to use dates as labels.

You don't have to. By default the horizontal axis tick labels will display as 1, 2, 3... etc. If you want them to appear as dates, however, you must manually define the tick positions and labels.

**Comment by swharden** [comment]
Originally I didn't understand your title, but I do now:
_EvilPlot - Combinator for Graphics_ is a plotting library for Scala.

* https://cibotech.github.io/evilplot/
* https://github.com/cibotech/evilplot

**Comment by Minu476** [comment]
Hi Scott,
Thank you for fast reply and great suggestions.
I had a typo, the width of candle now is fixed and calculated based on plot
data for all bars. For overlaying candles of different interval will be
great that the candle width be based on start time and end time of each
candle, so will be calculated from data.

with kind regards

Nasser

**Comment by swharden** [comment]
I think I understand your request. Currently you can create and plot candles like this:

```cs
var ohlcs = new ScottPlot.OHLC[]
{
    new ScottPlot.OHLC(273, 275, 264, 265, 1),
    new ScottPlot.OHLC(267, 276, 265, 274, 2),
    new ScottPlot.OHLC(277, 280, 275, 278, 3),
};

var plt = new ScottPlot.Plot(400, 300);
plt.Grid(false);
plt.PlotCandlestick(ohlcs);
plt.Axis(-1, 5);
```

![image](https://user-images.githubusercontent.com/4165489/79080941-fef4cd80-7ce6-11ea-949f-efc21342670f.png)

However, you would like each candle to have its own "width" property which you could define. This way some candles could be wider than others. Is this a good summary of your request?

**Comment by swharden** [comment]
If I create an OHLC constructor overload has a new argument for width:

```cs
var ohlcs = new ScottPlot.OHLC[]
{
    // open, high, low, close, time, timeSpan
    new ScottPlot.OHLC(273, 275, 264, 265, 1, 1),
    new ScottPlot.OHLC(267, 276, 265, 274, 2.5, 2),
    new ScottPlot.OHLC(277, 280, 275, 278, 4, 1),
};
```

You could toggle whether or not that width is used to display the candles:
```cs
var plt = new ScottPlot.Plot(400, 300);
plt.PlotCandlestick(ohlcs, autoWidth: false);
```

![image](https://user-images.githubusercontent.com/4165489/79081172-e1c0fe80-7ce8-11ea-81db-ff4bcf3724a0.png)

What do you think of this solution?

**Comment by Minu476** [comment]
Yes good idea, that exactly what I wanted!  Also note that when I plot
candle with bigger time span I like to plot it transparent. So I can see
which candles are behind it.
Thank you.

**Comment by Minu476** [comment]
For X axis if  we add a property as Indexed = true/false then no matter
what data type is in Xs[]  (date or double)  sorted data will be indexed
and potted.

**Comment by swharden** [comment]
Regarding color and transparency, I made a change so you can use custom colors (including those with transparency).

```cs
var colorUp = System.Drawing.ColorTranslator.FromHtml("#9926a69a");
var colorDown = System.Drawing.ColorTranslator.FromHtml("#99ef5350");
```

```
plt.PlotCandlestick(ohlcs, colorUp, colorDown, autoWidth: false);
```

![image](https://user-images.githubusercontent.com/4165489/79081627-3c5c5980-7ced-11ea-9fe5-48019754de80.png)

You can use this to plot a semi-transparent series over an opaque one. If you only want wide days to be transparent, put wide days all in one series and normal days all in another.

**Comment by swharden** [comment]
> For X axis if we add a property as Indexed = true/false then no matter what data type is in Xs[] (date or double) sorted data will be indexed and potted. 

I like this idea. I added a `sequential` argument. What do you think?

PS: images/text usually display better if you use the GitHub issue page to write messages instead of email https://github.com/swharden/ScottPlot/issues/346

```cs
plt.PlotCandlestick(ohlcs);
```
![image](https://user-images.githubusercontent.com/4165489/79081960-22704600-7cf0-11ea-80c0-f8d60229c7ac.png)

```cs
plt.PlotCandlestick(ohlcs, sequential: true);
```
![image](https://user-images.githubusercontent.com/4165489/79081965-3320bc00-7cf0-11ea-9a64-f48726e27a1b.png)

**Comment by Minu476** [comment]
fantastic!

**Comment by swharden** [comment]
Excellent! I'll close this issue now and this feature will make it in the next NuGet release. Thanks again for the suggestion @Minu476
