### ISSUE TITLE
user control axis limits

### ISSUE THREAD

**Issue by LogDogg** [swharden/ScottPlot#349]
Is it possible to set bounds for an axis outside of which the user cannot zoom out/pan by any means, similar to OxyPlot's AbsoluteMinimum and AbsoluteMaximum?

**Comment by swharden** [comment]
> Is it possible to set bounds for an axis outside of which the user cannot zoom out/pan by any means, similar to OxyPlot's AbsoluteMinimum and AbsoluteMaximum?

Hey @LogDogg thanks for the question. There's not a way to do that currently. The closest you can do is use `formsPlot1.Configure()` to lock the horizontal and/or vertical axis.

I like the idea though! I'll look into it further and come up with a solution, then update this ticket when I make progress. I'm thinking it will look something like:
```cs
double[] limits = {xLow, xHigh, yLow, yHigh};
formsPlot1.Configure(axisLimits: limits);
```

**Comment by swharden** [comment]
Thanks again for suggesting this @LogDogg! 

This is what I came up with:
```cs
formsPlot1.plt.AxisBounds(0, 50, -1, 1);
```

I'll release an updated NuGet package this evening.
