### ISSUE TITLE
Ignore an axis on rectangle zoom

### ISSUE THREAD

**Issue by LogDogg** [swharden/ScottPlot#353]
It would be really useful if the rectangle zoom ignored locked axes (or other, custom defined ones). Locking an axis essentially means it shouldn't be changed by the user and rectangle zoom bypasses this.

**Comment by swharden** [comment]
Good point @LogDogg!

Clarifying this topic, locking an axis like this:
```cs
formsPlot1.Configure(lockVerticalAxis: true);
```

...means that when you middle-click-drag to draw a zoom rectangle, zooming on the locked axes are ignored. Perhaps I could add an option like this to override that behavior:
```
formsPlot1.Configure(middleClickZoomIgnoresAxisLocks: true);
```

What do you think about this potential solution?

**Comment by LogDogg** [comment]
That would be great. I also suggest that the rectangle should span from top to bottom (if the vertical axis is locked) when this option is enabled to reflect this behaviour, but I don't know how difficult it would be to implement.

**Comment by swharden** [comment]
> the rectangle should span from top to bottom if the vertical axis is locked

I _really_ like this idea. I'll look into it - thanks for the tip!

**Comment by swharden** [comment]
Looks and feels great! Thanks for the suggestion @LogDogg, this will make it into the next release on NuGet shortly

![locked](https://user-images.githubusercontent.com/4165489/80928916-f3407800-8d75-11ea-9d84-64985780247d.gif)
