### ISSUE TITLE
Great project

### ISSUE THREAD

**Issue by lefig** [swharden/ScottPlot#355]
Just a brief mention of my appreciation for a great project.

I have been a long time user.

Thank you

Fig

**Comment by swharden** [comment]
Thank you so much @lefig / Fig! 

I initially wrote this library as a tool just for me to use, but it's been fun to watch it mature as a public project and I love hearing that other people enjoy using it too! It keeps getting better over time, and I look forward to watching the future of this library continue to unfold!

Thanks again for your inspiring comment.
Scott
