### ISSUE TITLE
WpfPlot fails in designer view on .NET Framework

### ISSUE THREAD

**Issue by iu2kxv** [swharden/ScottPlot#356]
I cannot install the package with the error attached.
I tried to use .net 4.7.2 and 4.8 but nothing improved.
My project is 64 bit wpf.

Error		Could not install package 'ScottPlot 4.0.29'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	

Anyone can say why? Is it because I'm using 64 bit?

Thank you, Phil

**Comment by swharden** [comment]
@iu2kxv I just created a new .NET Framework 4.8 WPF project and installed the packages successfully. I'm on a 64-bit system too.

* Perhaps try this on a new project you create from scratch?
* Perhaps upgrade your Visual Studio?

![image](https://user-images.githubusercontent.com/4165489/79702578-fadf2780-8273-11ea-94a2-9ce3718d871e.png)

```
Attempting to gather dependency information for package 'ScottPlot.WPF.4.0.29' with respect to project 'WpfApp7', targeting '.NETFramework,Version=v4.8'
Gathering dependency information took 58.27 ms
Attempting to resolve dependencies for package 'ScottPlot.WPF.4.0.29' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'ScottPlot.WPF.4.0.29'
Resolved actions to install package 'ScottPlot.WPF.4.0.29'
  GET https://api.nuget.org/v3-flatcontainer/scottplot.wpf/4.0.29/scottplot.wpf.4.0.29.nupkg
  OK https://api.nuget.org/v3-flatcontainer/scottplot.wpf/4.0.29/scottplot.wpf.4.0.29.nupkg 275ms
Installing ScottPlot.WPF 4.0.29.
Adding package 'ScottPlot.WPF.4.0.29' to folder 'C:\Users\scott\Source\Repos\WpfApp7\packages'
Added package 'ScottPlot.WPF.4.0.29' to folder 'C:\Users\scott\Source\Repos\WpfApp7\packages'
Added package 'ScottPlot.WPF.4.0.29' to 'packages.config'
Successfully installed 'ScottPlot.WPF 4.0.29' to WpfApp7
Executing nuget actions took 1.03 sec
Time Elapsed: 00:00:01.1369614
========== Finished ==========
```

**Comment by swharden** [comment]
Hi @iu2kxv, I think I was able to recreate this error and I learned a little more about it.

Interestingly this is some type of bug that only affects the designer view. The program compiles and runs fine...

* Only WPF projects are affected if using .NET Framework (.NET Core has no error)
* Only the Visual Studio Designer is affected. The program compiles fine and looks normal when run with F5

![image](https://user-images.githubusercontent.com/4165489/80927658-406c1c00-8d6d-11ea-9650-ba74097f8688.png)

**Comment by swharden** [comment]
@iu2kxv I think this has to do with the old (non-SDK) csproj file format. I figured out how to fix it:

* Create a new WPF application for .NET Core
* Edit the csproj file and change `TargetFramework` to `net472`
* Add `<ScottPlot:WpfPlot/>` to your layout
* Hover over that statement, hit "show potential fixes", and select "Add xmlns ScottPlot"
* Rebuild the application

The application now builds for .NET Framework 4.7.2, and the designer mode properly displays ScottPlot
