### ISSUE TITLE
Center text above plot

### ISSUE THREAD

**Issue by Resonanz** [swharden/ScottPlot#364]
**What can we do to make ScottPlot better?**
Text is not centered across the top of the plot box. Perhaps centering takes into account the text on the vertical axis, but in any case from a "beauty" point of view, I think centering would make the plot output look nicer and be more visually appealing. 

Example of plot, text not centered: [http://swharden.com/scottplot/cookbooks/4.0.29/#quickstart-quickstart-scatter-plot-quickstart](http://swharden.com/scottplot/cookbooks/4.0.29/#quickstart-quickstart-scatter-plot-quickstart)

**Comment by swharden** [comment]
Hi @Resonanz, the Title text is centered in the _Figure_ while the horizontal axis label is centered against the plot data area.

One of the other will always look off-center, and this seemed like the most logical way to position things. What do you think?

![image](https://user-images.githubusercontent.com/4165489/80622509-e68aef80-8a16-11ea-824c-c65b60b165a2.png)

This image shows the center positions. In this view, it appears the horizontal axis label is actually off-center:

![image](https://user-images.githubusercontent.com/4165489/80622418-c22f1300-8a16-11ea-9d05-f0f8bba31477.png)

**Comment by swharden** [comment]
It looks like matplotlib aligns the title center with the data area center (not the figure center) so maybe this should be the default behavior of ScottPlot too 🤔 

![image](https://user-images.githubusercontent.com/4165489/80622934-80eb3300-8a17-11ea-9723-f0f61662e8ff.png)

![image](https://user-images.githubusercontent.com/4165489/80623062-aaa45a00-8a17-11ea-993c-3da308726260.png)

**Comment by Resonanz** [comment]
Hi Scott, a non-centered title looks increasingly ugly as plots get smaller, or as the title gets shorter. I am fitting 96 plots on one screen, so it looks quite bad :-)

The other issue I have is the position of the vertical axis text. On the plot immediately above, the axis text looks nicely positioned and placed and sized. For my small plots below, the vertical text is way off in left field.

![image](https://user-images.githubusercontent.com/6218191/80641280-b5fb9200-8ab8-11ea-9677-a4f13b741fff.png)

**Comment by swharden** [comment]
@Resonanz thanks for the feedback! As you point out, the smaller the plot is the more obvious it becomes that the title appears oddly aligned. I'll change it to align with the data area like the xLabel does.

Regarding the right edge not showing, does changing padding to 1 help?
```cs
plotName[wellNumber].WpfPlot.plt.TightenLayout(padding: 1);
```

PS: I'm super absorbed in another project right now, but it won't take too much longer, then I'll swing back to ScottPlot and work on all of the issues. I know they're accumulating, but I'll get to them soon 😅

**Comment by Resonanz** [comment]
Padding: 1 doesn't seem to change anything.

**Comment by swharden** [comment]
Just fixed this and it'll be on NuGet in a day or two. Thanks @Resonanz! This does look better. 

I don't think this needs a toggle flag to switch between these behaviors, but it would be easy enough to add later if we decide to.

### Before: title center-aligned with the figure
![image](https://user-images.githubusercontent.com/4165489/80926742-13b50600-8d67-11ea-893f-68953561a24c.png)

### After: title center-aligned with the data area
![image](https://user-images.githubusercontent.com/4165489/80926830-8f16b780-8d67-11ea-8958-c7d9b5f5a003.png)

**Comment by jaguarxii** [comment]
Hi I know this is a bit old, but I cannot make the title align to the center of the figure, is this a feature?

![image](https://github.com/user-attachments/assets/1efc8c88-7916-4336-b349-bc13b703774f)

**Comment by swharden** [comment]
Excellent question @jaguarxii! I'll open an issue to track progress toward getting this back into the latest version #4455
