### ISSUE TITLE
RightClickMenu in FormsPlot doesn't disable 

### ISSUE THREAD

**Issue by thunderstatic** [swharden/ScottPlot#365]
I want to disable menu strip of FormsPlot in WinForms project but **enableRightClickMenu** flag doesn't work.
Temporary solution for me: `[FormsPlotName].ContextMenuStrip = null;`

![screenshot](https://user-images.githubusercontent.com/47780366/80776019-af355380-8b7a-11ea-952b-bcaf4abbb65a.jpg)

**Comment by swharden** [comment]
Thanks for reporting this @thunderstatic! I'll fix this issue in the next release 👍

**Comment by eduhza** [comment]
Hello swharden.

Not only the the menu, but also zooming and panning are not desabling in [FormsPlotName].Configure();

FormsPlot1.Configure(
                        enablePanning: false,
                        enableZooming: false,
                        enableRightClickMenu: false,
                        lowQualityWhileDragging: false,
                        enableDoubleClickBenchmark: false,
                        lockVerticalAxis: false,
                        lockHorizontalAxis: false,
                        equalAxes: false);

**Comment by swharden** [comment]
> I want to disable menu strip of FormsPlot in WinForms project but **enableRightClickMenu** flag doesn't work.
> Temporary solution for me: `[FormsPlotName].ContextMenuStrip = null;`

@thunderstatic thanks for tip! I just made the change and `Configure(enableRightClickMenu: false)` now works as expected.

> Not only the the menu, but also zooming and panning are not disabling in [FormsPlotName].Configure();
> 
> FormsPlot1.Configure(
> enablePanning: false,
> enableZooming: false,
> enableRightClickMenu: false,
> lowQualityWhileDragging: false,
> enableDoubleClickBenchmark: false,
> lockVerticalAxis: false,
> lockHorizontalAxis: false,
> equalAxes: false);

@eduhza I can't seem to recreate this issue. Check out the FormsPlot Config demo - it demonstrates all the arguments of `Configure()` in action. If you still think there is a problem, feel free to re-open this issue (or post a new one).

![image](https://user-images.githubusercontent.com/4165489/80926547-08ada600-8d66-11ea-8de5-f13179c36b58.png)

**Comment by eduhza** [comment]
In the FormsPlot Config demo 4.0.22 the argument "pannable" is working but "zoomable" doesn't.
With zoom I mean, scrolling the middle mouse button and selecting an area clickling with middle button mouse.

**Comment by swharden** [comment]
> With zoom I mean, scrolling the middle mouse button and selecting an area clicking with middle button mouse.

I see the problem now @eduhza, thanks for clarifying it!

```cs
formsPlot1.Configure(enableScrollWheelZoom: false);
```

That disables the scroll wheel zoom, but not middle-click-drag zoom... I'll update the behavior so that one line of code will disable both

**Comment by swharden** [comment]
Got it fixed now, thanks @eduhza!
