### ISSUE TITLE
plot data with random datetime 

### ISSUE THREAD

**Issue by jmecosta** [swharden/ScottPlot#366]
hi,

i have this kind of data, these are execution times for an operation that i want to detect regressions

2/4/2020 10:00 - 10
3/4/2020 11:00 - 10
3/4/2020 14:00 - 10
23/4/2020 15:00 - 20

i would like to create a datetime plot that has only the samples above. i tought about reconstructing the data however its not correct for end users since between 3/4 to 23/4 the regression might happen.

we are using a differnt library in javascript for web pages and that supports it
![image](https://user-images.githubusercontent.com/1041352/80799957-e7578900-8bb0-11ea-9cd8-9bc190e2838d.png)

i would like to get the same with scottplot! is this possible?

thanks in advance

**Comment by swharden** [comment]
Hi @jmecosta,

Most of this is doable, with a couple exceptions. Multiple Y axes are not yet supported (#180) but I'll leave this issue open to let me consider again how I might be able to implement this because the request keeps coming up. Also horizontal legends are currently not supported.

On the other hand if you had 3 stacked plots that shared the same X axis (http://swharden.com/scottplot/cookbooks/4.0.29/#advanced-multiplot-multiplot-quickstart) you could show this data with ScottPlot

**Comment by jmecosta** [comment]
@swharden thanks, multiple Y values per X value is not something im interested (if i understood #180 properly)

i think i didn't explain myself properly, x axis will always be a unique since its a datatime object. i just want it not to be uniform.... ive looked in api but i could only find a start time and a  constant increment (apologies if i havent find what i want in doc)

so what i want is ScottPlot.Plot(dates, values)  where:

dates [] = [1 May, 2 May, 10 May]
values [] = [10, 10. 20]

the plot should look more or less the same as i put above in picture

thanks again

**Comment by swharden** [comment]
Sounds good! You'll do something like:

```cs
// you have values as a double array
double[] ys = {1, 2, 3...};

// you have dates as DateTime array
DateTime[] dts = [1 May, 2 May, 10 May];

// convert your DateTime array to a double array
double[] xs = new double[dts.Length];
for (int i=0; i<dts.Length; i++)
    xs[i] = dts[i].ToOADate();

// make a scatter plot (supports unevenly spaced data)
plt.PlotScatter(xs, ys);

// make horizontal axis ticks display using DateTime format
plt.Ticks(dateTimeX: true);
```

Let me know if this answers your question 👍

**Comment by jmecosta** [comment]
perfect
![image](https://user-images.githubusercontent.com/1041352/80861065-dc662c80-8c74-11ea-9ed7-df687b9f7315.png)

thanks again for the quick help!
