### ISSUE TITLE
PlottableScatter.GetLimits() throws System.InvalidOperationException: Sequence contains no elements

### ISSUE THREAD

**Issue by JagDTalcyon** [swharden/ScottPlot#369]
**Describe the bug**
Provide a clear and concise description of what the bug is

Unhandled exception. System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Min(IEnumerable`1 source)
   at ScottPlot.PlottableScatter.GetLimits()
   at ScottPlot.Settings.AxisAuto(Double horizontalMargin, Double verticalMargin, Boolean xExpandOnly, Boolean yExpandOnly, Boolean autoX, Boolean autoY)
   at ScottPlot.Plot.RenderBitmap()
   at ScottPlot.Plot.GetBitmap(Boolean renderFirst, Boolean lowQuality)
   at ScottPlot.WpfPlot.Render(Boolean skipIfCurrentlyRendering, Boolean lowQuality, Boolean recalculateLayout)

**To Reproduce**
Describe what we can do to reproduce the behavior

```cs
// include code to help us reproduce this bug
```

**Screenshots**
If applicable, add screenshots to help explain your problem

**Comment by JagDTalcyon** [comment]
Unhandled exception. System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Min(IEnumerable`1 source)
   at ScottPlot.PlottableScatter.GetLimits()
   at ScottPlot.Settings.AxisAuto(Double horizontalMargin, Double verticalMargin, Boolean xExpandOnly, Boolean yExpandOnly, Boolean autoX, Boolean autoY)
   at ScottPlot.Plot.Axis(Nullable`1 x1, Nullable`1 x2, Nullable`1 y1, Nullable`1 y2)
   at ScottPlot.WpfPlot.UserControl_MouseDown(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at APRIS_Analysis.App.Main()

On Clicking the mouse button on plot, the above exception occurs.

**Comment by swharden** [comment]
Hi @JagDTalcyon, thanks for reporting this. Unfortunately there's not enough information here to re-create this issue. 

What data are you trying to plot?

This code works for me. Does it work for you?

```cs
double[] dataX = new double[] {1, 2, 3, 4, 5};
double[] dataY = new double[] {1, 4, 9, 16, 25};
formsPlot1.plt.PlotScatter(dataX, dataY);
formsPlot1.Render();
```

I'll close this issue for now but will re-open it when there's a better description of the problem and how to recreate it.

**Comment by JagDTalcyon** [comment]
@swharden Thanks for the reply.

I have a number of series to be added to the plot.

After the series are being added, I need plot to autoaxis.

Once, I click to autoaxis, it shows the above error.

Do, i need to render the plt after adding any series ?

**Comment by swharden** [comment]
The error says `Sequence contains no elements`

Are you trying to plot an array with no data? That may be the issue.

Check to ensure the arrays you plot contain data. If this was the problem, I can improve this issue by checking for arrays with zero length and throwing a more descriptive exception.

**Comment by JagDTalcyon** [comment]
Hi,
I have used plt.GetTotalPoints() to check and then render the plot.
Let me know the process after adding a series to plt and auto axis.

Thanks.

**Comment by swharden** [comment]
Hi @JagDTalcyon,

All you need to do is this:

```cs
double[] dataX = new double[] {1, 2, 3, 4, 5};
double[] dataY = new double[] {1, 4, 9, 16, 25};
formsPlot1.plt.PlotScatter(dataX, dataY);
formsPlot1.Render();
```

Are your `dataX` and `dataY` zero element arrays? If so, this is what your problem is. Make sure both of those arrays contain values.

**Comment by JagDTalcyon** [comment]
@swharden what if the x and y values are 0?
Will that be an issue ?

**Comment by swharden** [comment]
This is okay:
```cs
double[] dataX = {0, 0, 0};
double[] dataY = {0, 0, 0};
```

This will fail:
```cs
double[] dataX = {};
double[] dataY = {};
```

Does this help answer your question?

**Comment by JagDTalcyon** [comment]
My series sometimes have the values like:
double[] dataX = {0, 0, 0};
double[] dataY = {0, 0, 0};

But still the render() gives that exception

**Comment by swharden** [comment]
@JagDTalcyon this program works for me.

```cs
using System.Windows.Forms;

namespace FormsPlotSandbox
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();

            double[] dataX = { 0, 0, 0 };
            double[] dataY = { 0, 0, 0 };
            formsPlot1.plt.PlotScatter(dataX, dataY);
            formsPlot1.Render();
        }
    }
}
```

![image](https://user-images.githubusercontent.com/4165489/80981842-802c1580-8df8-11ea-803f-112101eceb18.png)

Do you have a code sample which will allow me to recreate your error?

**Comment by JagDTalcyon** [comment]
Code in function:
```
            for (int grp = 0; grp < UniqueGroupNumbers.Count; grp++)
            {
                scatter = SignalPlot.plt.PlotScatter(
                    plot_x_values_list[grp].ToArray(),
                    plot_y_values_list[grp].ToArray(),
                    //color: HeatMapColors[grp],
                    lineWidth: 0,
                    markerSize: 3,
                    label: TubeID);
                scatter.SaveCSV(path + TubeID + "_" + grp + ".csv");
                //SignalPlot.plt.AxisAuto();
                if (SignalPlot.plt.GetTotalPoints() > 0)
                    SignalPlot.Render();
            }
```

wpf xaml:
```
        <Grid Grid.Row="1" Grid.Column="0" Margin="5" Name="PlotGrid" VerticalAlignment="Stretch" HorizontalAlignment="Stretch">
            <ScottPlot:WpfPlot Name="SignalPlot" Margin="5"/>
        </Grid>
```

**Comment by swharden** [comment]
Thanks for the code sample! I think we are converging on a solution here. I still suspect the crash happens when you plot arrays with no data. Does this solve your issue?

```cs
double[] xs = plot_x_values_list[grp].ToArray();
double[] ys = plot_y_values_list[grp].ToArray();

if ((xs.Length == 0) || (ys.Length == 0))
    throw new Exception("can not plot empty arrays");

SignalPlot.plt.PlotScatter(xs, ys, lineWidth: 0, markerSize: 3, label: TubeID);
SignalPlot.plt.Render();
```

**Comment by JagDTalcyon** [comment]
![image](https://user-images.githubusercontent.com/40381914/80985398-c23d7180-8e61-11ea-9701-fb0245ab7b46.png)

**Comment by swharden** [comment]
@JagDTalcyon I'm glad we ruled-out the zero-element issue! It seems that your problem exists outside this for loop.

Does your contain other calls to `TubeSignalPlot` than just the ones we see here?

**Comment by JagDTalcyon** [comment]
yes, i have 2 other for loops like the same mentioned. 

Is that the issue ?

**Comment by swharden** [comment]
> yes, i have 2 other for loops like the same mentioned.
> 
> Is that the issue ?

Have you added code like this to all the loops?

```cs
if ((xs.Length == 0) || (ys.Length == 0))
    throw new Exception("can not plot empty arrays");
```

I still suspect somewhere your program is failing because it is plotting an array with zero elements 😅

**Comment by JagDTalcyon** [comment]
Thanks for your help...

That solved my nightmare...

**Comment by swharden** [comment]
That's great news @JagDTalcyon! Thanks for your continued effort. I response to this issue I added a similar check for zero-length arrays in the scatter plot constructor e76720a36b85619a6f41e70f2924a5419b3574f9 so if this happens again it will fail with a descriptive error message. That will make it into ScottPlot 4.0.31 which will get released within the next few days.

**Comment by JagDTalcyon** [comment]
Thanks.

**Comment by JagDTalcyon** [comment]
Sorry to disturb you.
I have another question.
What if the value is double.NaN is supplied to the plot?

**Comment by swharden** [comment]
> What if the value is double.NaN is supplied to the plot?

It draws makers ignoring the NaN, but if a line connects them the line gets confused.

```cs
double[] dataX = { 1, 2, 3, 4, 5 };
double[] dataY = { 1, 3, double.NaN, 16, 25 };

var plt = new ScottPlot.Plot(400, 300);
plt.PlotScatter(dataX, dataY);
```

![image](https://user-images.githubusercontent.com/4165489/81001189-5fbe8400-8e15-11ea-871f-a0b041261d3d.png)

**Comment by blackbirddevelopment** [comment]
I am receiving the same error "Sequence contains no elements". I check all the arrays I am using and they have values. 
I am adding three "new ScottPlot.Plottable.ScatterPlot(xValues, yValues)" to the Plot. As soon as the process of adding the ScatterPlots completes and the Render() method is called, I get the error below:

This exception was originally thrown at this call stack:
    System.Linq.ThrowHelper.ThrowNoElementsException()
    System.Linq.Enumerable.First<TSource>(System.Collections.Generic.IEnumerable<TSource>)
    ScottPlot.Settings.GetYAxis(int)
    ScottPlot.Settings.GetPlotDimensions(int, int, double) in Settings.cs
    ScottPlot.Plot.RenderPlottables(System.Drawing.Bitmap, bool, double) in Plot.Render.cs
    ScottPlot.Plot.Render(System.Drawing.Bitmap, bool, double) in Plot.Render.cs
    ScottPlot.Control.ControlBackEnd.Render(bool, bool) in Backend.cs
    ScottPlot.Control.ControlBackEnd.ProcessEvent(ScottPlot.Control.EventProcess.IUIEvent) in Backend.cs
    ScottPlot.Control.ControlBackEnd.RenderRequest(ScottPlot.RenderType) in Backend.cs
    ScottPlot.Control.ControlBackEnd.Resize(float, float, bool) in Backend.cs

Could this be tied to the "System.Linq.Enumerable.First" call?

My code is below. All arrays return non-zero values and no nulls.
Code:
        private void PlotData()
        {
            var xyValues = from p in _context.Run
                           where p.Id == 4
                           where p.RunNumber == 1
                           select new
                           {
                               SequenceNumber = (double)p.SequenceNumber,
                               Hctvalue = (double)p.Hctvalue,
                               Bvvalue = (double)p.Bvvalue,
                               Satval = (double)p.Satval
                           };
            // labels
            RunPlot.Plot.Title("HcT Values");
            RunPlot.Plot.XLabel("Sequence Value");

            // fill arrays
            xValues = xyValues.Select(x => x.SequenceNumber).ToArray();
            yHctValues = xyValues.Select(y => y.Hctvalue).ToArray();
            yBvValues = xyValues.Select(y => y.Bvvalue).ToArray();
            ySatValues = xyValues.Select(y => y.Satval).ToArray();

            if (xValues.Length == 0)
                throw new Exception("xValues Array Empty");
            else
            {
                var plottable1 = new ScottPlot.Plottable.ScatterPlot(xValues, yHctValues);
                plottable1.Label = "Hct";
                plottable1.YAxisIndex = 0;
                plottable1.Color = Color.Blue;
                plottable1.LineWidth = 4;
                if ((xValues.Length == 0) || (yHctValues.Length == 0))
                    throw new Exception("yHctValues Array Empty");
                else
                    RunPlot.Plot.Add(plottable1);

                var plottable2 = new ScottPlot.Plottable.ScatterPlot(xValues, yBvValues);
                plottable2.Label = "BV";
                plottable2.YAxisIndex = 1;
                plottable2.Color = Color.Red;
                plottable2.LineWidth = 4;
                plottable2.Label = "BV";
                if ((xValues.Length == 0) || (yBvValues.Length == 0))
                    throw new Exception("yBvValues Array Empty");
                else
                    RunPlot.Plot.Add(plottable2);

                var plottable3 = new ScottPlot.Plottable.ScatterPlot(xValues, ySatValues);
                plottable3.Label = "Sat";
                plottable3.YAxisIndex = 2;
                plottable3.Color = Color.Green;
                plottable3.LineWidth = 4;
                if ((xValues.Length == 0) || (ySatValues.Length == 0))
                    throw new Exception("ySatValues Array Empty");
                else
                    RunPlot.Plot.Add(plottable3);

                RunPlot.Render();
            }
        }


Thanks for any help in advance.

Steve J

**Comment by grasmanek94** [comment]
I think this happens when AutoSize / fit is specified, and the user zooms out or moves the render field outside of any visible data points, making Render try to render a `null` enumerable (no data points in view). Usually happens when I try to maximize or scroll/move and a .refresh call is being called at an unfortunate time.
