### ISSUE TITLE
SignalXY for unevenly-spaced data

### ISSUE THREAD

**Issue by LogDogg** [swharden/ScottPlot#374]
The main advantage of SignalPlot is it's well optimized rendering, giving you the ability to render millions of points (I tried it with 100 million and it was still usable). But it only works for data that comes in a fixed interval. ScatterPlot, on the other hand, does not need evenly spaced data, but for that very reason it is really hard, if not impossible to optimize.

So my suggestion is: make a new Plottable that's a mix of SignalPlot and ScatterPlot. What I mean by that, the Plottable should allow data that's not evenly spaced, but all the points must come in order (eg. xs[] = { 0, 1, 5, 6, 12 } is good, but xs[]= { 0, 4, 2, 7, 5 } isn't). Then, the RenderHighDensity function (similar to the one in PlottableSignal) could divide and compact the data to render according to the x values of the points, instead of their indexes (like it does in PlottableSignal).

In my experience, everyone who wants to plot some data has that data in order, but the interval between the points isn't always the same. I think the library would benefit a lot from this new plottable for that very reason.

**Comment by StendProg** [comment]
Hi @LogDogg , you provided interesting sugettion.
I want to share my thoughts on it:
1. You can manual convert not evently spaced data to evently spaced by some type of interpolation.
Result signal will look the same and work fast. Only memory and convertion time is the price.
2. Most huge datasets comes from ADC, and already evently spaced. Are there really not evently spaced huge datasets  for which `Scatter` performance is not enough?
3. I think overload for `PlotSignal()` more suitable than new plot type. If `xs[]` argument provided to `PlotSignal(xs, ys, ...)` it works like you discribed.
4. If `xs[]` array sorted there is possible to find each interval border for `O(logN)` with binary search.
It slower then constant time currently used in `Signal` but i think it fast enouth. Given the fact that `pixel` intervals go sequentially, additional performance optimizations may be found.

**Comment by LogDogg** [comment]
Hi @StendProg, thank you for taking the time to read and think about my suggestion. I'd like to adress the points you brought up:
1. I agree, but adding points is just a workaround, not a solution. It also adds data that wasn't there originally, which may affect user experience.
2. I agree, but the problem arises when there are gaps in the data. If a system collects data every 2 seconds and from time to time it stops working for a minute, it makes the data ineligible for the SignalPlot. You could fill in the missing points, but again, it provides false information to the user and shows data that isn't actually there.
3. That's a great idea. 
4. I haven't really got the implementation all figured out, just the basic idea, I'll look into it a bit more. The idea you suggested would probably be a bit slower than the regular SignalPlot, but it will certanly be better than ScatterPlot.

**Comment by StendProg** [comment]
PR #375 contain basic implementation of this mode.
It works fast on million points dataset without any posible optimizations.
If you have any idea how to improve, you a welcome.

@LogDogg thank for you idea, and especially for pointing to data with gaps. It's real use case for me too.

**Comment by LogDogg** [comment]
I've been busy the last few days so I couldn't get around to testing it, but it definitely looks promising! I'll see if I can think of any improvements over the weekend.

**Comment by swharden** [comment]
@LogDogg this was a wonderful idea and @StendProg your PR #375 is an impressive implementation! This new plot type looks really useful.

I don't want users to confuse this plot type with `Signal`, which is still faster. To keep the separation clear I called this new plot type `SignalXY` and let users call it with a separate function `Plot.PlotSignalXY()` rather than an overload of `Plot.PlotSignal()`. 

```cs
Random rand = new Random(0);
int pointCount = 100_000;
double[] ys = new double[pointCount];
double[] xs = new double[pointCount];
for (int i = 1; i < ys.Length; i++)
{
    ys[i] = ys[i - 1] + rand.NextDouble() - .5;
    xs[i] = xs[i - 1] + rand.NextDouble();
}
```

```cs
plt.PlotSignalXY(xs, ys);
plt.Axis(20530, 20560, -61, -57);
```

![image](https://user-images.githubusercontent.com/4165489/82128189-3b549700-9787-11ea-97ed-121614ba706d.png)

I notice marker size looks funny when data points are uneven. @StendProg what do you think is the best way to fix this?

**Comment by StendProg** [comment]
For each data point  minimal distance (x coordinate only) to neighboring points(left and right) calculates.
Marker size calculates on this value like `Signal` do, but for each point it has it own value.
Points close to high density mode drawes with smaller marker.
I taked the same coefficients from `Signal` marker size animation. 
Maybe some tweaks make it looks better.
Or possible some mistakes in distance calculation.
Anyway markers have different size only then close to high density mode. They all goes even size in low density ( more then 10 pixel between datapoints)

**Comment by swharden** [comment]
@StendProg I modified the rendering method to determine marker size based on data density (the number of points drawn in the view). With this change:

* all markers are the same size

* marker size is calculated once (not inside a loop)

* `FindNeigborDistances()` is not required. _I did not delete this useful code. Instead I moved it into `CalcIntervalParams()` and it is run if the `calculateNeighborDistances` argument is set._

What do you think of this solution?

![xy2](https://user-images.githubusercontent.com/4165489/82152972-bb840680-9832-11ea-9ce3-8eda9cf7e675.gif)
![xy1](https://user-images.githubusercontent.com/4165489/82152973-bc1c9d00-9832-11ea-9b9e-db7b55452a99.gif)

**Comment by swharden** [comment]
... to be fair, a disadvantage of this method is that marker size changes as you drag around transition zones where data density changes. This looks a bit odd, but I don't think it's too bad.

![xy3](https://user-images.githubusercontent.com/4165489/82153064-3ea55c80-9833-11ea-95e2-7b5773589a7d.gif)

**Comment by swharden** [comment]
@envine mentioned in #493 that `minRenderIndex` and `maxRenderIndex` are not supported by SignalXY. I suspect this is also the case for SignalConst... How complex do you think this would be to support? An alternative option would be to remove the arguments and intentionally not support it.

```cs
Random rand = new Random(0);
double[] xs = ScottPlot.DataGen.Consecutive(100_000);
double[] ys = ScottPlot.DataGen.RandomWalk(rand, 100_000);
var plt = new ScottPlot.Plot(500, 350);
plt.PlotSignalXY(xs, ys, minRenderIndex: 4000, maxRenderIndex: 5000);
```

![image](https://user-images.githubusercontent.com/4165489/88481911-25541700-cf2c-11ea-8c2a-4907060e4f59.png)

The expected behavior is that only points between index 4000 and 5000 would be displayed on the graph. The intended use case is where a large array is created in memory once, and slowly filled (e.g., with sensor data) and only the filled parts of the array are to be displayed on the graph. This behavior is currently supported by `PlotSignal()`.
