### ISSUE TITLE
Log10 returns NaN which breaks GetLimits()

### ISSUE THREAD

**Issue by Benny121221** [swharden/ScottPlot#376]
**Describe the bug**
If you attempt to use a `ScottPlot.Tools.Log10` on a dataset which contains 0, it will appear to work properly. However, `Math.Log10(0)` returns `double.NegativeInfinity`, which does not play nicely with `Plottable.GetLimits()`. It causes the axis to return limits of `[double.NaN, double.NaN]`. This does not cause a crash, but simply for the plot to not draw.

**To Reproduce**
Use `ScottPlot.Tools.Log10` on a dataset which contains 0.

I modified the Log Axis demo to look like this:

```cs
public class LogAxis : PlotDemo, IPlotDemo
        {
            public string name { get; } = "Log Axis";
            public string description { get; } = "";

            public void Render(Plot plt)
            {
                // generate some interesting log-distributed data
                int pointCount = 200;
                double[] dataXs = new double[pointCount];
                double[] dataYs = new double[pointCount];
                Random rand = new Random(0);
                for (int i = 0; i < pointCount; i++)
                {
                    double x = 10.0 * i / pointCount;
                    dataXs[i] = x;
                    dataYs[i] = Math.Pow(2, x) + rand.NextDouble() * i;
                }

                dataYs[0] = 0;

                // this tool can convert linear data to log data
                double[] dataYsLog = ScottPlot.Tools.Log10(dataYs);

                foreach(double curr in dataYsLog) {
                    Debug.WriteLine(curr);
                }
                plt.PlotScatter(dataXs, dataYsLog, lineWidth: 0);

                // call this to move minor ticks to simulate a log scale
                plt.Ticks(logScaleY: true);

                plt.Title("Data (Log Scale)");
                plt.YLabel("Vertical Units (10^x)");
                plt.XLabel("Horizontal Units");
            }
        }
```

**Screenshots**
If applicable, add screenshots to help explain your problem
Output for given code:

![image](https://user-images.githubusercontent.com/8635304/81349821-01e0a500-907e-11ea-96c4-4a3607449137.png)

Debug output: https://pastebin.com/9vYd9Hdm

**Comment by Benny121221** [comment]
I'm going to open a PR shortly to deal with this, I was thinking of yoinking the solution from https://stackoverflow.com/questions/40219639/how-to-deal-with-zero-in-log-plot, which was to transition to a linear scale for values around 0. However, for scatter plots dealing with small y values this would be very noticeable. I think I am just going to return `double.NaN` and accept that that point will not be visible. This is the behaviour of my graphing calculator and I think is the best solution.

Note that it does not fail for sets containing negative numbers, as 
![image](https://user-images.githubusercontent.com/8635304/81350106-7e738380-907e-11ea-9659-fbc2c889ac6c.png)

`double.NaN` does not break anything, it just stops that point from being drawn.

**Comment by swharden** [comment]
Thanks for bringing this up @Benny121221! While your fix helps the case for 0, it alerted me to the fact that taking Log10 of negative numbers returns `double.NaN` which seems to break the scatter plot's `GetLimits()` method. I'll merge-in your fix and continue to work on this a bit more...

**Comment by swharden** [comment]
For now I think the best solution is to not allow `double.NaN` get into data that gets plotted. Most plottables aren't capable of rendering arrays containing `NaN`. 

My thinking is that if users want to fine-tune how the Log10 conversion works (becoming linear near 0, discarding imaginary numbers, etc) they can write their own conversion method rather than using the one in the tools folder.

```cs
double[] xs = ScottPlot.DataGen.Range(-10, 10, .1, true);
double[] ys = ScottPlot.DataGen.Sin(xs, mult: 100);
double[] logYs = ScottPlot.Tools.Log10(ys);

plt.PlotScatter(xs, logYs);
plt.YLabel("Log10(Sin(x) * 100)");
plt.Ticks(logScaleY: true);
```

![image](https://user-images.githubusercontent.com/4165489/82128942-28dd5c00-978d-11ea-9fe3-590a9b4347a0.png)

Thanks again for raising this issue @Benny121221!

**Comment by Benny121221** [comment]
`double.NaN` doesn't break it _as_ much as ±`double.Infinity`, as it just causes getLimits to ignore it. Whereas infinity will zoom the graph out infinitely far, which is not great.

**Comment by Benny121221** [comment]
Ah got you, sorry I made that comment before I saw yours.

So right now what is the behaviour of the Log10 tool?

**Comment by swharden** [comment]
> So right now what is the behaviour of the Log10 tool?

Mathematicians may cringe here, but it now returns 0 instead of anything irrational. This way we know the returned array is always suitable for plotting

https://github.com/swharden/ScottPlot/blob/df531ccb55ca3b2c31067191b825c2652d4bb6ea/src/ScottPlot/Tools.cs#L231-L237

**Comment by Benny121221** [comment]
> Mathematicians may cringe here

Did I mention I'm starting a Math minor in the fall? In seriousness though, that's probably the best option. Complex numbers don't play nicely with graphs unless you add another dimension

**Comment by swharden** [comment]
> Did I mention I'm starting a Math minor in the fall?

That's awesome! What a cool field to study

> In seriousness though, that's probably the best option. Complex numbers don't play nicely with graphs unless you add another dimension. Not to mention that log(0) doesn't even have a value in the complex plane

I'm happy to hear you think this is an acceptable solution given the circumstances! Let me know when you finish you math minor so I can add a note that says _this method is endorsed by a mathematician_ 😜 

I feel like I need a degree in mathematics to figure out where to place tick marks 🙈 it's surprisingly hard #394

Thanks again for your help on this one @Benny121221!
