### ISSUE TITLE
WpfPlot mouse tracking support for DPI scaling

### ISSUE THREAD

**Issue by Benny121221** [swharden/ScottPlot#379]
**Describe the bug**
Both demos produce coordinates above and to the left of the mouse cursor. WinForms does not have this issue. I am unsure if the problem is from the demo or the library.

**To Reproduce**
Open the demos and wiggle your mouse.

**Screenshots**
If applicable, add screenshots to help explain your problem
![image](https://user-images.githubusercontent.com/8635304/81450854-7714ae80-9140-11ea-951b-b0346782a018.png)

Apologies for the image turns out it's quite annoying to take a screenshot with the mouse cursor shown. Anyways, you can see that my mouse is around (100,0), but the demo says it is on (76.9,0.5)

**Comment by swharden** [comment]
Thanks for reporting this @Benny121221!

I'll bet this has to do with display scaling - I'd guess your monitor running at 150% display magnification.

I think `MouseDevice.GetPosition` returns non-scaled values but the picture displays using scaled values. The fix will be to correct the coordinates by the DPI scaling factor in the demo program...

```cs
dpiScale = settings.gfxFigure.DpiX / 96;
```

**Comment by Benny121221** [comment]
Yep, it was display scaling. My monitor was on 125%. I added a PR #380 to fix it.

I had forgotten that WinForms has different (read poor) display scaling from Windows scaling which makes them always act like 96 DPI screens. It's also why WinForms applications often looks blurry

**Comment by swharden** [comment]
Awesome @Benny121221, quick work there! Think the PR is ready to merge now or are you still working on it?

**Comment by Benny121221** [comment]
It fails some tests, I didn't realize that it wouldn't work multithreaded -_-

**Comment by swharden** [comment]
It did just start failing... but I'm guessing that has to do with a change due to Azure Pipelines.

This code looks great! I'll merge it shortly. Thanks again @Benny121221!

**Comment by Benny121221** [comment]
No, it legitimately fails the tests, I'm running them locally

**Comment by swharden** [comment]
> No, it legitimately fails the tests, I'm running them locally

Oh, this was my bad - I wasn't looking closely enough at the file that got changed. The best fix here is only to change the WPF control, since that's the only place where DPI scaling is used.

The WPF control has a value which gets updated to be the current DPI scale factor:
https://github.com/swharden/ScottPlot/blob/0c1196c3a6eaab80ee6479ee917fb472011112e4/src/ScottPlot.WPF/WpfPlot.xaml.cs#L34

Maybe a good solution here is to add a function to the WPF control like:
```cs
public (double x, double y) GetMouseCoordinates() {
    /* smarts */
    return (x, y);
}
```

**Comment by Benny121221** [comment]
It passes tests now, I made a fix before I read your comment. Mine requires two locks on the `gfxFigure` object, which isn't ideal, but those locks are only required once each in the entirety of the program's runtime, so I think I can live with that

**Comment by Benny121221** [comment]
And wouldn't grabbing it from the WpfPlot still require locks?

**Comment by swharden** [comment]
> And wouldn't grabbing it from the WpfPlot still require locks?

I think the reason it's okay is because this value is only looked-up once in the initializer.

It looks like whenever the mouse moves the latest DPI-corrected pixel position is stored in `mouseLocation` (which is private). Perhaps we could add a method like this?

```cs
// return the position of the mouse in axis units (not pixels)
public (double x, double y) GetMouseCoordinates() {
    double x = plt.CoordinateFromPixelX(mouseLocation.X);
    double y = plt.CoordinateFromPixelY(mouseLocation.Y);
    return (x, y);
}
```

**Comment by Benny121221** [comment]
I added the method and changed the demos to use it.

However, I still vote that the `plt.CoordinateFromPixel` stuff stays, because it is still a useful function, and it would be a shame to break backwards compatibility. I don't think we can get rid of the locks because the settings object will always need to yoink from a graphics object, and we want that to work multithreaded-ly. Plus two locks which trigger once in the entirety of the program's runtime shouldn't ever be noticeable.

**Comment by swharden** [comment]
> I added the method and changed the demos to use it.

These changes look great! I like the use of tuples here.

> However, I still vote that the `plt.CoordinateFromPixel` stuff stays, because it is still a useful function, and it would be a shame to break backwards compatibility. I don't think we can get rid of the locks because the settings object will always need to yoink from a graphics object, and we want that to work multithreaded-ly. Plus two locks which trigger once in the entirety of the program's runtime shouldn't ever be noticeable.

Maybe we can meet in the middle and get the best of both worlds here... How about when a Plot is initialized we can look up the DPI scale just once and store it in the Settings module as a double (rather than making it an auto-property)? A lock is probably not even needed. We can use `settings.gfxFigure` the line after it's created. What do you think about this option?

https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/Plot.cs#L86-L99

Also I see that `using System.Windows` got added to Settings.cs - is this necessary?

**Comment by Benny121221** [comment]
I implemented your suggestions. I agree, it makes more sense to fill in the dpi scale on initializing the graphics object, not on the first time user code requires it. It also prevents all the threading issues because the initialization is already synchronous code.

**Comment by swharden** [comment]
This looks fantastic @Benny121221, thanks so much!
