### ISSUE TITLE
"Object is currently in use elsewhere" error in multi-threaded app

### ISSUE THREAD

**Issue by Minu476** [swharden/ScottPlot#387]
What is your recommended solution for exception caught at formplot1.Render() in a Multi-Threaded application with  Message=Object is currently in use elsewhere.

BTW this version has many great improvements and I love it. Thank you for hard work!

**Comment by swharden** [comment]
Hey @Minu476, I think I need more context (full sample code?) to know for sure, but I think fundamentally System.Drawing is not thread-safe so ScottPlot probably isn't safe to use in a multi-threaded application.

I'm currently working on making the rendering engine "swappable" (so SkiaSharp + OpenGL can be used instead of System.Drawing, which is thread safe), but this is a little ways off.

**Comment by swharden** [comment]
Actually, I might be able to help a bit here. If you plot `someArray`

```cs
formsPlot1.plt.PlotSignal(someArray);
```

... ScottPlot will hold onto it and try to read from that array later when the user control is being drawn. If you've locked or changed that array in another thread, you'll probably get that "object is currently in use" error. The solution is to copy `someArray` before sending it to ScottPlot:

```cs
double[] someArrayCopied = new double[someArray.Length];
Array.Copy(someArray, 0, someArrayCopied, 0, someArray.Length);
```

Let me know if this fixes your problem!

**Comment by Minu476** [comment]
Thanks for your ideas and clarification that ScottPlot is not designed for
multi threaded applications.
I am getting that error always when system.Drawing is busy doing
rendering,as all my collections are immutable and thread safe.
From your future plan of "swappable" rendering engine, and my requirement
to update chart about every minute, I got the idea of using two instance of
ScottPlot objects, to alternate them while updating chart and using it to
solve my problem.

I also have another question: Does PlotFill/PlotOHLC  maintaining that last
index drawn as now on each update iI am copying the whole data series to
Xs[],Ys[]?  This over doing rendering may be the source of my problem.

**Comment by swharden** [comment]
> I got the idea of using two instance of ScottPlot objects, to alternate them while updating chart and using it to solve my problem.

Double-buffering with ScottPlots - that's very clever! I wouldn't have thought of that one

> I also have another question: Does PlotFill/PlotOHLC  maintaining that last
index drawn as now on each update iI am copying the whole data series to
Xs[],Ys[]?  This over doing rendering may be the source of my problem.

Maybe this example can answer your question:

```cs
// put this at the class-level of your form
private double[] arrayJustForDisplaying;
```

```cs
// put this in your start-up sequence
arrayJustForDisplaying = new double[sourceData.Length];
formsPlot1.plt.PlotSignal(arrayJustForDisplaying);
```

```cs
// call this with a timer or something
Array.Copy(source, 0, arrayJustForDisplaying , 0, sourceData.Length);
formsPlot1.plt.AxisAuto();
formsPlot1.Render();
```

You only have to plot an array one time, then you can update its values later and render it later. Does this help answer your question?

**Comment by Minu476** [comment]
I think so! Let's get this implementation and try it. If we can generate a
test and try it will be nice.
