### ISSUE TITLE
Are MouseDown and MouseUp events implemented?

### ISSUE THREAD

**Issue by LogDogg** [swharden/ScottPlot#389]
I can't get them to work, so I was wondering if they are supposed to work in the first place? If they aren't I'll definitely turn this into a feature request, since those 2 simple events expand the customizability of the library by a lot.
I was trying this on a FormsPlot. 

EDIT: I know that MouseDownOnPlottable exists, but that's not what I need.

**Comment by swharden** [comment]
Hey @LogDogg I may have fixed this with #390 but it's also worth noting that the FormsPlot has some custom mouse events under the "Misc" category. Let me know if this doesn't solve your issue! 👍
