### ISSUE TITLE
configurable legend location

### ISSUE THREAD

**Issue by Padanian** [swharden/ScottPlot#39]
Further to #10 issue closed on May, I was wondering whether it would be possible to extend the feature, but positioning the legend frame on other corners too, like top left corner. 
I'd like to help with coding, if it's ok with Scott.

**Comment by swharden** [comment]
This sounds like a great idea! Thanks for the pull request too - I’ll review it in the next day or two.

To make this even more portable, I’m thinking of rendering the legend as a small square bitmap, then placing that bitmap at the user-specified location. The advantage of this method is that the user could also do something like `getLegendBitmap()` and display the legend outside the plot image. This would be most useful in GUI applications with lots of plot objects (and big legends) so the legend doesn’t overlap the data. What do you think?

**Comment by Padanian** [comment]
It would be great, although my C# is a little bit rusty. I'm a vb.net
developer mostly.Or, we could parametrise the size of the legend to
reduce the size to 1/2 and 1/3 of normale size, by reducing frame and
font size. With that, and the ability to put the legend on any of four
corners, I think we should cover most of scenarios.

In the meantime, I would like to submit a new idea, that would be a
single feature not available on any other chart/graphs packages to my
knowledge.I'll submit a separate issue for that.

----- Messaggio Originale -----
Da: "swharden/ScottPlot" 
A:"swharden/ScottPlot" 
Cc:"Alessandro Mandelli" , "Author" 
Inviato:Tue, 16 Jul 2019 12:31:06 +0000 (UTC)
Oggetto:Re: [swharden/ScottPlot] Legend (#10 issue) but on top left
corner (#39)

	This sounds like a great idea! Thanks for the pull request too -
I’ll review it in the next day or two. 

	To make this even more portable, I’m thinking of rendering the
legend as a small square bitmap, then placing that bitmap at the
user-specified location. The advantage of this method is that the user
could also do something like getLegendBitmap() and display the legend
outside the plot image. This would be most useful in GUI applications
with lots of plot objects (and big legends) so the legend doesn’t
overlap the data. What do you think? 

	—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub [1], or mute the
thread [2]. [ { "@context": "http://schema.org", "@type":
"EmailMessage", "potentialAction": { "@type": "ViewAction", "target":
"https://github.com/swharden/ScottPlot/issues/39?email_source=notificationsu0026email_token=AB3I2BCUQ5SMUTWO75OJXITP7W5QHA5CNFSM4IDT5IDKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2AWDXQ#issuecomment-511795678",
"url":
"https://github.com/swharden/ScottPlot/issues/39?email_source=notificationsu0026email_token=AB3I2BCUQ5SMUTWO75OJXITP7W5QHA5CNFSM4IDT5IDKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2AWDXQ#issuecomment-511795678",
"name": "View Issue" }, "description": "View this Issue on GitHub",
"publisher": { "@type": "Organization", "name": "GitHub", "url":
"https://github.com" } } ]

Links:
------
[1]
https://github.com/swharden/ScottPlot/issues/39?email_source=notifications&amp;email_token=AB3I2BCUQ5SMUTWO75OJXITP7W5QHA5CNFSM4IDT5IDKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2AWDXQ#issuecomment-511795678
[2]

**Comment by swharden** [comment]
I'll probably modify your pull #40 to model [matplotlib.pyplot.legend](https://matplotlib.org/3.1.0/api/_as_gen/matplotlib.pyplot.legend.html#matplotlib.pyplot.legend) location keywords.

>The strings 'upper left', 'upper right', 'lower left', 'lower right' place the legend at the corresponding corner of the axes/figure. The strings 'upper center', 'lower center', 'center left', 'center right' place the legend at the center of the corresponding edge of the axes/figure.

**Comment by Padanian** [comment]
Super

----- Messaggio Originale -----
Da: "swharden/ScottPlot" 
A:"swharden/ScottPlot" 
Cc:"Alessandro Mandelli" , "Author" 
Inviato:Tue, 16 Jul 2019 15:02:08 +0000 (UTC)
Oggetto:Re: [swharden/ScottPlot] Legend (#10 issue) but on top left
corner (#39)

	I'll probably modify your pull #40 [1] to model
matplotlib.pyplot.legend [2] location keywords.  

	The strings 'upper left', 'upper right', 'lower left', 'lower right'
place the legend at the corresponding corner of the axes/figure. The
strings 'upper center', 'lower center', 'center left', 'center right'
place the legend at the center of the corresponding edge of the
axes/figure.  

	—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub [3], or mute the
thread [4]. [ { "@context": "http://schema.org", "@type":
"EmailMessage", "potentialAction": { "@type": "ViewAction", "target":
"https://github.com/swharden/ScottPlot/issues/39?email_source=notificationsu0026email_token=AB3I2BGX7XVYNL6YZZJFWNDP7XPGTA5CNFSM4IDT5IDKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2BEUGI#issuecomment-511855129",
"url":
"https://github.com/swharden/ScottPlot/issues/39?email_source=notificationsu0026email_token=AB3I2BGX7XVYNL6YZZJFWNDP7XPGTA5CNFSM4IDT5IDKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2BEUGI#issuecomment-511855129",
"name": "View Issue" }, "description": "View this Issue on GitHub",
"publisher": { "@type": "Organization", "name": "GitHub", "url":
"https://github.com" } } ]

Links:
------
[1] https://github.com/swharden/ScottPlot/pull/40
[2]
https://matplotlib.org/3.1.0/api/_as_gen/matplotlib.pyplot.legend.html#matplotlib.pyplot.legend
[3]
https://github.com/swharden/ScottPlot/issues/39?email_source=notifications&amp;email_token=AB3I2BGX7XVYNL6YZZJFWNDP7XPGTA5CNFSM4IDT5IDKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2BEUGI#issuecomment-511855129
[4]

**Comment by swharden** [comment]
Hey @Padanian I merged #40 and it will probably get published in the next NuGet release some time next weekend. Thanks for the improvement!

I'm thinking about making two more changes but I'm interested in your input: First, I'd like to add "center" as both vertical and horizontal options. Second, I'd like to use an enumeration instead of a string for legend location so intellisense will pop-up a list of possible positions for the user.

```cs
plt.Legend(location: "BottomLeft");
```

would become something like

```cs
plt.Legend(location: ScottPlot.legendLocations.BottomLeft);
```

What do you think? If you're in favor, do you want to code this or should I do it?

**Comment by Padanian** [comment]
Enum is certainly the way to go, and it was my first elected choice, to be honest.
I can code it.

**Comment by Padanian** [comment]
Pull request submitted

**Comment by swharden** [comment]
@Padanian thanks for your hard work! I just merged #44 and it's looking great. I refactored your code a bit so that the enumeration is never converted to an int, but always passed as the enumeration itself.

I made a new [standalone legend demo](https://github.com/swharden/ScottPlot/blob/master/demos/ScottPlotLegend/) to make it easier to experiment with legend functions. Notice how that example shows how to convert all available enumeration options to/from strings eliminating the need for if statements.

I also added an example to the cookbook:
https://github.com/swharden/ScottPlot/blob/dba76dd07a61f910c9d034b8b42474068733670a/demos/ScottPlotCookbook/Recipes.cs#L126

For reference, the main code you worked on is here.
https://github.com/swharden/ScottPlot/blob/dba76dd07a61f910c9d034b8b42474068733670a/src/ScottPlot/Renderer.cs#L100-L186

Are you satisfied with the result?

**Comment by Padanian** [comment]
I told you my c# was rusty. 
This ScottPlot.legendLocation location =
(ScottPlot.legendLocation)Enum.Parse(typeof(ScottPlot.legendLocation),
locationString);is brilliant.
Thank you for allowing me to mess around with your code.

----- Messaggio Originale -----
Da: "swharden/ScottPlot" 
A:"swharden/ScottPlot" 
Cc:"Alessandro Mandelli" , "Mention" 
Inviato:Mon, 22 Jul 2019 22:18:38 +0000 (UTC)
Oggetto:Re: [swharden/ScottPlot] configurable legend location (#39)

	@Padanian [1] thanks for your hard work! I just merged #44 [2] and
it's looking great. I refactored your code a bit so that the
enumeration is never converted to an int, but always passed as the
enumeration itself. 

	I made a new standalone legend demo [3] to make it easier to
experiment with legend functions. Notice how that example shows how to
convert all available enumeration options to/from strings eliminating
the need for if statements. 

	I also added an example to the cookbook:
https://github.com/swharden/ScottPlot/blob/dba76dd07a61f910c9d034b8b42474068733670a/demos/ScottPlotCookbook/Recipes.cs#L126
[4] 

	For reference, the main code you worked on is here.
https://github.com/swharden/ScottPlot/blob/dba76dd07a61f910c9d034b8b42474068733670a/src/ScottPlot/Renderer.cs#L100-L186
[5] 

	Are you satisfied with the result? 

	—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub [6], or mute the
thread [7]. [ { "@context": "http://schema.org", "@type":
"EmailMessage", "potentialAction": { "@type": "ViewAction", "target":
"https://github.com/swharden/ScottPlot/issues/39?email_source=notificationsu0026email_token=AB3I2BBBBJX353LEEKYJWNTQAYW3PA5CNFSM4IDT5IDKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2RKQUA#issuecomment-513976400",
"url":
"https://github.com/swharden/ScottPlot/issues/39?email_source=notificationsu0026email_token=AB3I2BBBBJX353LEEKYJWNTQAYW3PA5CNFSM4IDT5IDKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2RKQUA#issuecomment-513976400",
"name": "View Issue" }, "description": "View this Issue on GitHub",
"publisher": { "@type": "Organization", "name": "GitHub", "url":
"https://github.com" } } ]

Links:
------
[1] https://github.com/Padanian
[2] https://github.com/swharden/ScottPlot/pull/44
[3]
https://github.com/swharden/ScottPlot/blob/master/demos/ScottPlotLegend/
[4]
https://github.com/swharden/ScottPlot/blob/dba76dd07a61f910c9d034b8b42474068733670a/demos/ScottPlotCookbook/Recipes.cs#L126
[5]
https://github.com/swharden/ScottPlot/blob/dba76dd07a61f910c9d034b8b42474068733670a/src/ScottPlot/Renderer.cs#L100-L186
[6]
https://github.com/swharden/ScottPlot/issues/39?email_source=notifications&amp;email_token=AB3I2BBBBJX353LEEKYJWNTQAYW3PA5CNFSM4IDT5IDKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2RKQUA#issuecomment-513976400
[7]

**Comment by cchiu827** [comment]
> This sounds like a great idea! Thanks for the pull request too - I’ll review it in the next day or two.
> 
> To make this even more portable, I’m thinking of rendering the legend as a small square bitmap, then placing that bitmap at the user-specified location. The advantage of this method is that the user could also do something like `getLegendBitmap()` and display the legend outside the plot image. This would be most useful in GUI applications with lots of plot objects (and big legends) so the legend doesn’t overlap the data. What do you think?

Is the function of display the legend outside the plot area available? Sorry that I cannot figure this out reading through this issue stream.

Thanks,
Chao-An

**Comment by swharden** [comment]
@cchiu827 `plt.GetLegendBitmap()` will return a `Bitmap` containing the legend. This will require you to place it somewhere in your Form (on a Picturebox) or Window (on a canvas), but you can put it anywhere in your application. Hope this helps!

**Comment by cchiu827** [comment]
That sounds like a plan. Thank you so much.
Chao-An

Scott W Harden <notifications@github.com> 於 2020年7月16日 週四 下午6:34寫道：
