### ISSUE TITLE
Winform formsPlot1 will cause MouseMove event not be fired anymore.

### ISSUE THREAD

**Issue by Minu476** [swharden/ScottPlot#390]
To create this problem:
On a standard winfowmApp created by Vs 2019 show mouse move on statusbar. When you sun everything is fine.

Then drop ScottPlot control on the form, mousemove will not be working. I noticed some other mouse events also had same problem, but not remember now.

**Comment by swharden** [comment]
Hi @Minu476, you raised a very important point. The user controls are intercepting `MouseMove` and not manually triggering `base.OnMouseMove()`. Same for MouseDown, MouseUp, MouseDoubleClick, and MouseWheel events.

I'll work to modify all the events the user controls intercept to ensure they are also forwarded to the `base` object.

Note: The user controls do have a custom `MouseMoved` event you can use to get mouse position, but I'll leave this issue open to track progress toward properly forwarding the regular events to the base objects.

**Comment by swharden** [comment]
I think this problem is fixed with b049516 - thanks for mentioning the issue! If it doesn't resolve your problem let me know 👍
