### ISSUE TITLE
Plottable Class will be more useful if label field define in it. 

### ISSUE THREAD

**Issue by Minu476** [swharden/ScottPlot#391]
I was trying to set visibility on/off in my bollingerbands which use PlotFill, but was unable to select my desired plot among plottable list from Setting.plottables as PlotFill hide the label and I had to use toString and parse it.

**Comment by swharden** [comment]
Hi @Minu476, thanks for reporting this! I'm having difficulty understanding your description of this problem though. Can you provide a code sample showing what you had to do, and indicate what you wish you could have done?

**Comment by Minu476** [comment]
public abstract class Plottable
    {
        // in ScottPlot 3.1 this class will move to
ScottPlot.Plottable.IPlottable
        public bool useParallel = false;
        public bool visible = true;
                 suggesting move label here                 public string
label;
        public abstract void Render(Settings settings);
        public abstract override string ToString();
        public abstract Config.AxisLimits2D GetLimits();
        public abstract int GetPointCount();
        public abstract Config.LegendItem[] GetLegendItems();
    }
 *we create many plotFills with*
 public PlottablePolygon PlotFill(
            double[] xs1,
            double[] ys1,
            double[] xs2,
            double[] ys2,
            string label = null,     // using propername as lable
            double lineWidth = 0,
            Color? lineColor = null,
            bool fill = true,
            Color? fillColor = null,
            double fillAlpha = 1,
            double baseline = 0
            )

but plotFill is drived from following class:

public class PlottablePolygon : Plottable
{
public override string ToString()
        {
            return $"PlottablePolygon with {GetPointCount()} points";
        }
}

then In custom contextMenu with rightclik we like to toggle visibility of
those PlotFills
all plottables only show above string which is not helpful to identify the
plot

**Comment by swharden** [comment]
Hey @Minu476, thank you so much for clarifying!

It sounds like the problem is that the right-click settings menu in the Windows Forms control uses the `toString()` label when it lists all the plottable objects, but labels like "PlottablePolygon" aren't enough to identify your shapes. You'd like this list to also include the label of the plottable objects.

This is a good idea! I think the best way to fix this is for me to change the code of that combobox so each item also includes its label. `PlottablePolygon with 4 points` will instead read as `polygon A: PlottablePolygon with 4 points`. What do you think of this solution?

https://github.com/swharden/ScottPlot/blob/0c1196c3a6eaab80ee6479ee917fb472011112e4/src/ScottPlot.WinForms/FormSettings.cs#L59-L62

![image](https://user-images.githubusercontent.com/4165489/82109329-18809f00-9703-11ea-8858-8e3b620c6958.png)

**Comment by Minu476** [comment]
does plotObject give access to the label?

**Comment by swharden** [comment]
I'll refactor the plottables a bit to make this work. Not every plottable has a label. Annotation and L-shaped scalebars are examples of plottables without a label. I think an `ILabelable` would be appropriate here 🤔 

I'm going to work a lot on ScottPlot this weekend, so I'll definitely get to this in the next day or two! Thanks again for the suggestion

**Comment by Minu476** [comment]
I am maintaining my own plottable  in a dictionary and moving ahead but the
name of plot must be visible in all plot type in the settings.
Currently ScatterPlot and signal are available.

 private void SetVisibility(object sender, EventArgs e)
        {

            _myDialog.ShowDialog();
            if (_myDialog.DialogResult == DialogResult.OK)
            {
                foreach (var gran in _intervals)
                {
                    foreach (var plot in _myPlottables)
                    {
                        if (plot.Key.StartsWith(gran) &&
plot.Key.EndsWith("_21"))
                        {
                            plot.Value.visible = _myDataToPlot.Columns[gran
+ "_bolL_21"].visible;
                        }


                        if (plot.Key.StartsWith(gran) &&
plot.Key.EndsWith("_144"))
                        {
                            plot.Value.visible = _myDataToPlot.Columns[gran
+ "_bolL_144"].visible;
                        }


                        if (plot.Key.StartsWith(gran) &&
plot.Key.EndsWith("_233"))
                        {
                            plot.Value.visible = _myDataToPlot.Columns[gran
+ "_bolL_233"].visible;
                        }


                        if (plot.Key.StartsWith(gran) &&
plot.Key.EndsWith("_377"))
                        {
                            plot.Value.visible = _myDataToPlot.Columns[gran
+ "_bolL_377"].visible;
                        }

                    }

                }
                formsPlot1.Render();
            }
        }

**Comment by swharden** [comment]
The best solution would be for the user to create a custom right-click menu or modify plot objects programmatically. 

However, adding the label to the ToString output was an improvement!

![image](https://user-images.githubusercontent.com/4165489/82134404-94dbb680-97c5-11ea-8e23-fa282a8ff5f7.png)
