### ISSUE TITLE
lineStyle support for Signal and SignalConst

### ISSUE THREAD

**Issue by bukkideme** [swharden/ScottPlot#392]
There is no lineStyle option for PlottableSignals. It would be great to have it, so we can use for example:
lineStyle: LineStyle.Dash, etc.

Is there a reason why it was not implemented? Performance reason for example?
Thanks!

**Comment by swharden** [comment]
Hey @Benny121221,

The primary reason is that `Signal` and `SignalConst` don't actually draw lines. They perform some math optimization to determine what _pixels_ are covered by the data, and they selectively fill-in those pixels. We call this "high density mode" when the horizontal density of signals is greater than the density of pixels.

![image](https://user-images.githubusercontent.com/4165489/82124631-5a92fa80-976e-11ea-98e6-88b8c017e9c0.png)

However, low density mode occurs when you zoom into a signal. In this case there is less than one point per pixel column, and lines are indeed drawn. `Signal` and `SignalConst` may be able to use these line styles when zoomed in. I'll take a closer look to see how feasible this is. Thanks for the suggestion!

**Comment by swharden** [comment]
To test this I added lines of code to [PlottableSignal.cs](https://github.com/swharden/ScottPlot/blob/2ab1c29297dc04db8f57c40ed726b9aab5216982/src/ScottPlot/plottables/PlottableSignal.cs) and added:

```sc
// in RenderHighDensity() and RenderHighDensityDistribution()
pen.DashPattern = StyleTools.DashPattern(LineStyle.Solid);
```

```cs
// in RenderLowDensity()
pen.DashPattern = StyleTools.DashPattern(LineStyle.Dash);
```

The effect isn't as bad as I predicted 🤔 

![signal-pen2](https://user-images.githubusercontent.com/4165489/82159578-3a8e3480-985d-11ea-94b2-99d60cdd0ab5.gif)

**Comment by swharden** [comment]
Done! Thanks for the suggestion @bukkideme, this will make it in the release later today 👍
