### ISSUE TITLE
Use ImmutableSortedSet for growing data

### ISSUE THREAD

**Issue by Minu476** [swharden/ScottPlot#395]
As ImmutableSortedList can be converted to Arrays, it's use will simplify the growing live data cases implementation.

**Comment by swharden** [comment]
Hi @Minu476, thanks for suggesting this!

I think you're referring to [`System.Collections.Immutable.ImmutableSortedSet<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutablesortedset-1)

I haven't looked into it in depth yet, but my concern is that ScottPlot only plots `double[]` objects. You could use `list.ToArray()` to convert the `ImmutableSortedSet` to a `double[]`, but this ***copies*** all the elements in the list and must be performed after every addition to the list, and I'm worried about performance if such copying is called frequently. What do you think? If I'm misunderstanding your suggestion, a few lines of sample code might help clarify it.

**Comment by Minu476** [comment]
I made mistake, I wanted to refer to ImmutableSortedDictionary<,> which key will use X as key  and Y as value.
We can add a range of elements  or single element to list.
This will allow ScottPlot to have a method  Add for adding or initializing data. But Render will be used to copy the dictionary even as updating live data can add to dictionary at the same time.
I don't know each Render() will render the whole array every time or only additions? this might be a correct concern in case of the latter.

**Comment by Minu476** [comment]
Multiple Ys also will be easy to implement by using manay instance of this dictionary.

**Comment by Minu476** [comment]
Good morning,
Just few notes from my observations on getting:  Message=Object is currently in use elsewhere.
1) It happened almost in plotting manual ticks shown in this code segment at very end:
  foreach (var gran in _intervals)
            {
                if (_myDataToPlot.Columns[gran + "_bolL_21"].active)
                {
                     var pl1= formsPlot1.plt.PlotFill(_myDataToPlot.ColumnDataPoints[gran + "_bolH_21"].Keys.ToArray(),
                        _myDataToPlot.ColumnDataPoints[gran + "_bolH_21"].Values.ToArray(),
                        _myDataToPlot.ColumnDataPoints[gran + "_bolL_21"].Keys.ToArray(),
                        _myDataToPlot.ColumnDataPoints[gran + "_bolL_21"].Values.ToArray(),
                        gran + "_Bol_21", 1.0, _myDataToPlot.Columns[gran + "_bolL_21"].LineColor, true,
                        _myDataToPlot.Columns[gran + "_bolL_21"].FillColor, 0.40);
                     _myPlottables.Add(gran + "_bolL_21",pl1);
                }

                if (_myDataToPlot.Columns[gran + "_bolL_144"].active)
                {
                    var pl2 =formsPlot1.plt.PlotFill(_myDataToPlot.ColumnDataPoints[gran + "_bolH_144"].Keys.ToArray(),
                      _myDataToPlot.ColumnDataPoints[gran + "_bolH_144"].Values.ToArray(),
                      _myDataToPlot.ColumnDataPoints[gran + "_bolL_144"].Keys.ToArray(),
                      _myDataToPlot.ColumnDataPoints[gran + "_bolL_144"].Values.ToArray(),
                      gran + "_Bol_144", 1.0, _myDataToPlot.Columns[gran + "_bolL_144"].LineColor, true,
                      _myDataToPlot.Columns[gran + "_bolL_144"].FillColor, 0.40);
                    _myPlottables.Add(gran + "_bolL_144", pl2);
                }

                if (_myDataToPlot.Columns[gran + "_bolL_233"].active)
                {
                    var pl3=formsPlot1.plt.PlotFill(_myDataToPlot.ColumnDataPoints[gran + "_bolH_233"].Keys.ToArray(),
                        _myDataToPlot.ColumnDataPoints[gran + "_bolH_233"].Values.ToArray(),
                        _myDataToPlot.ColumnDataPoints[gran + "_bolL_233"].Keys.ToArray(),
                        _myDataToPlot.ColumnDataPoints[gran + "_bolL_233"].Values.ToArray(),
                        gran + "_Bol_233", 1.0, _myDataToPlot.Columns[gran + "_bolL_233"].LineColor, true,
                        _myDataToPlot.Columns[gran + "_bolL_233"].FillColor, 0.40);
                    _myPlottables.Add(gran + "_bolL_233", pl3);
                }

                if (_myDataToPlot.Columns[gran + "_bolL_377"].active)
                {
                    var pl4 =formsPlot1.plt.PlotFill(_myDataToPlot.ColumnDataPoints[gran + "_bolH_377"].Keys.ToArray(),
                        _myDataToPlot.ColumnDataPoints[gran + "_bolH_377"].Values.ToArray(),
                        _myDataToPlot.ColumnDataPoints[gran + "_bolL_377"].Keys.ToArray(),
                        _myDataToPlot.ColumnDataPoints[gran + "_bolL_377"].Values.ToArray(),
                        gran + "_Bol_377", 1.0, _myDataToPlot.Columns[gran + "_bolL_377"].LineColor, true,
                        _myDataToPlot.Columns[gran + "_bolL_377"].FillColor, 0.40);
                    _myPlottables.Add(gran + "_bolL_377", pl4);
                }
            }

            XLabelPlot(formsPlot1, _myData.Bars["H1"], true);
            formsPlot1.Render();
I later noticed i can call skipIfCurrentlyRendering=true)

**Comment by Minu476** [comment]
It also happened when I was updating with live data and moved the charts with mouse(zoom,pan,..)

**Comment by Minu476** [comment]
Updating live data in financial series should be very easy by calling a method Add(bars), which will add a range of bars at end of data.

**Comment by swharden** [comment]
Hey @Minu476 thank you for these ideas! I updated the roadmap to include creation of a demo application specifically for finance, and this will demonstrate how to plot live incoming financial data that grows with time. [ImmutableSortedDictionary<TKey,TValue>](https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutablesorteddictionary-2) might be the best tool for the job, but I'll explore that further when I start making the demo app.

It's probably a bigger discussion than we should have here, but perhaps an alternative solution is for the OHLC plottable to accept `List<OHLC>` rather than `OHLC[]`. This way it would be extremely easy to add data, and you'd eliminate all of your `.ToArray()` statements 🤔 

I'll close this issue for now, but I look forward to working more on the financial charting components of ScottPlot in the near future!
