### ISSUE TITLE
Add NaN support to Scatter and Fill Plots

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#396]
It seems like the scatter plot should support `double.NaN`. The reason it doesn't is because `NaN` makes its way into `PointF` and `Graphics.DrawLine()` freaks out if the first or last point is a `NaN`

Discarding `NaN` from the list of plotted points would require checking every value to see if it's `NaN` which is a slight performance hit... but Scatter already isn't highly performant, so maybe it's not much of a loss. This could even be toggled with a flag.

- [x] Support `NaN` in Scatter plots
- [x] Support `NaN` in Polygon plots (and Fill plots)

**Comment by swharden** [comment]
This is now supported. Shaded Bollinger bands (which contain `double.NaN` for pre-average Xs and Ys) are now possible (#397)

![image](https://user-images.githubusercontent.com/4165489/82135397-5a2b4b80-97d0-11ea-94ac-ea0d80b60ac2.png)

**Comment by Minu476** [comment]
Looks great!
