### ISSUE TITLE
Create tools for SMA and Bollinger Bands

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#397]
These are very common tasks for people making Candlestick plots of financial data

* https://en.wikipedia.org/wiki/Moving_average
* https://en.wikipedia.org/wiki/Bollinger_Bands

**Comment by swharden** [comment]
SMA and Bollinger bands are now supported, but they only work for plot types that can handle NaN (#396)

### Simple Moving Average (SMA)

```cs
Random rand = new Random(0);
double[] xs = DataGen.Consecutive(150);
OHLC[] ohlcs = DataGen.RandomStockPrices(rand, xs.Length);
double[] sma20 = ScottPlot.Statistics.Finance.SMA(ohlcs, 20);
double[] sma50 = ScottPlot.Statistics.Finance.SMA(ohlcs, 50);

// replace timestamps with a series of numbers starting at 0
for (int i = 0; i < ohlcs.Length; i++)
    ohlcs[i].time = i;

var plt = new ScottPlot.Plot(600, 400);
plt.PlotCandlestick(ohlcs);
plt.PlotScatter(xs, sma20, label: "20 day SMA",
    color: Color.Blue, markerSize: 0, lineWidth: 2);
plt.PlotScatter(xs, sma50, label: "50 day SMA",
    color: Color.Maroon, markerSize: 0, lineWidth: 2);
```
![image](https://user-images.githubusercontent.com/4165489/82133551-a8821f80-97bb-11ea-8999-fd6ae3009417.png)

### Bollinger Bands

```cs
Random rand = new Random(0);
double[] xs = DataGen.Consecutive(150);
OHLC[] ohlcs = DataGen.RandomStockPrices(rand, xs.Length);
(var sma, var bolL, var bolU) = ScottPlot.Statistics.Finance.Bollinger(ohlcs);

// replace timestamps with a series of numbers starting at 0
for (int i = 0; i < ohlcs.Length; i++)
    ohlcs[i].time = i;

var plt = new ScottPlot.Plot(600, 400);
plt.PlotCandlestick(ohlcs);
plt.PlotScatter(xs, bolL, color: Color.Blue, markerSize: 0);
plt.PlotScatter(xs, bolU, color: Color.Blue, markerSize: 0);
plt.PlotScatter(xs, sma, color: Color.Blue, markerSize: 0, lineStyle: LineStyle.Dash);
```

![image](https://user-images.githubusercontent.com/4165489/82133568-c485c100-97bb-11ea-8983-933b5efed5d3.png)

**Comment by swharden** [comment]
@Minu476 I see in #391 you mentioned Bollinger bands, so I thought you might find this useful for your project. Now that there's a [ScottPlot.Statistics.Finance](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/Statistics/Finance.cs) module, do you have C# code ready to go for other common technical indicators you think may be useful?

I thought about implementing [Exponential Moving Average (EMA)](https://www.investopedia.com/terms/e/ema.asp) too but I had to stop because if I chase all the technical indicators I find interesting I'll never get anything else done 🤣 🙈

**Comment by Minu476** [comment]
That was fast!  I use also Donchian bands sometimes, but using too many indicator add to more confusion only in my view. Now, only concentrating on Bolliger bands with 1 stdv Up and down and always use the filled area between high and low to read the signal from it.

**Comment by swharden** [comment]
> That was fast! I use also Donchian bands sometimes, but using too many indicator add to more confusion only in my view. Now, only concentrating on Bolliger bands with 1 stdv Up and down and always use the filled area between high and low to read the signal from it.

Currently the Bollinger bands are set to 2SD up and down. Do you think we should change this? ... or make that an argument?

https://github.com/swharden/ScottPlot/blob/2657eb2170e3d15b8ebe3241f26ad46024c433c3/src/ScottPlot/Statistics/Finance.cs#L82-L96

Also notice that since fill can't plot data with NaN in it (yet) it can't be used with these methods 😅 but the solution there I guess is to update fill to support NaN

**Comment by Minu476** [comment]
Make it an argument will be more useful.

**Comment by Minu476** [comment]
I am sure you will see sequential x axis is needed in all financial related Plottables.

**Comment by swharden** [comment]
> Make it an argument will be more useful.

Done! It defaults to 20-day and 2*SD which I think is typical (https://www.fidelity.com/learning-center/trading-investing/technical-analysis/technical-indicator-guide/bollinger-bands) but you can control these parameters with arguments

```cs
(var sma, var bolL, var bolU) = ScottPlot.Statistics.Finance.Bollinger(ohlcs, 20, 2);

plt.PlotCandlestick(ohlcs);
plt.PlotScatter(xs, bolL, color: Color.Blue, markerSize: 0);
plt.PlotScatter(xs, bolU, color: Color.Blue, markerSize: 0);
plt.PlotScatter(xs, sma, color: Color.Blue, markerSize: 0, lineStyle: LineStyle.Dash);
```

1SD from SMA | 2SD from SMA (default)
---|---
![image](https://user-images.githubusercontent.com/4165489/82134772-65c74400-97c9-11ea-9ae2-e696a2f0fb2c.png) | ![image](https://user-images.githubusercontent.com/4165489/82134775-6f50ac00-97c9-11ea-8dc0-3dbc2f51e2bf.png)

> I am sure you will see sequential x axis is needed in all financial related Plottables.

For sure! I added a `sequential` argument to the `RandomStockPrices()` method to make sequential data easier to generate in the future.

> I use also Donchian bands sometimes

If you're inspired to add those it's probably a copy/paste with a small modification to the Bollinger method - feel free to stick it in and issue a PR! I'm reaching my limit for today so I'll go ahead and close this issue. Lots of good stuff here! Thanks for all your input @Minu476
