### ISSUE TITLE
Continuously auto-scale axis while dragging

### ISSUE THREAD

**Issue by Minu476** [swharden/ScottPlot#398]
Demo of locked vertical axis has fixed y scale range and as you zoom or pan does not reflect the proper data in view. 
I want to achieve something like full featured chart of [Symbol] say SPX500_USD shown by

   www.tradingview.com

**Comment by swharden** [comment]
Ha, I love tradingview! You can see I copied their colors for my candlesticks 😈

I think the best solution here is actually for me to create a full-featured finance-only demo application. Financial tasks are very different than general plotting tasks, so a standalone demo (rather than a cookbook example here or there) might be good to consolidate finance-related tasks into a single code example. I'll add that to the roadmap and keep this issue focused on the axis locking issue you mentioned...

**Comment by swharden** [comment]
@Minu476 this seems to be working for me in the demo application

![image](https://user-images.githubusercontent.com/4165489/82133799-07e12f00-97be-11ea-86e5-487dac457b7c.png)

```cs
formsPlot1.Configure(lockVerticalAxis: true);
```

Let me know if I misunderstood your question!

**Comment by swharden** [comment]
ohhh... I think I understand now.  You don't want the vertical axis to be ***locked***, you want it to be ***continuously auto-scaled***... I'll think about the best way to do this!

**Comment by Minu476** [comment]
You got it perfectly!

**Comment by Minu476** [comment]
in Tradingview chart if you hold Ctrl key down and use mouse wheel you will see that point in chart fixed but both scale will adopt with data in view.

**Comment by swharden** [comment]
I think the best solution here is for me to create a new user control just for finance plots. The FormsPlot and WpfPlot controls are so general-purpose that it's hard to support everything, and this is one of those examples.

The limiting factor to "setting the axis limits to fit the data in the view" is that there's not currently a way to determine the axis limits of data _within the view_. AxisAuto() works to get the limits of all the data, but there's no code currently anywhere that can auto-fit Y to the current X view. This would be pretty hard to do inside ScottPlot, so for now the best solution is to do it on the user end. 

This method can't easily be done in real time, but it can be triggered by the MouseUp event:

![candle-animated](https://user-images.githubusercontent.com/4165489/82134014-8fc83880-97c0-11ea-9b1e-2f816198e1d7.gif)

```cs

OHLC[] ohlcs = DataGen.RandomStockPrices(new Random(0), 200);
private void FormSandbox_Load(object sender, EventArgs e)
{
    Random rand = new Random();
    formsPlot1.plt.PlotCandlestick(ohlcs);
    formsPlot1.Render();
}

private void formsPlot1_MouseUp(object sender, MouseEventArgs e)
{
    // determine the axis where we are now
    double[] axes = formsPlot1.plt.Axis();
    double xLow = axes[0];
    double xHigh = axes[1];

    // determine what the high and low of the visible axis range is
    double yLow = double.PositiveInfinity;
    double yHigh = double.NegativeInfinity;
    for (int i = 0; i < ohlcs.Length; i++)
    {
        var ohlc = ohlcs[i];
        if (ohlc.time < xLow || ohlc.time > xHigh)
            continue;
        yLow = Math.Min(yLow, ohlc.low);
        yHigh = Math.Max(yHigh, ohlc.high);
    }

    // set the Y axis limits to the high and low of the range
    formsPlot1.plt.Axis(xLow, xHigh, yLow, yHigh);
}
```

I added some finance-related goals to the [ScottPlot roadmap](https://github.com/swharden/ScottPlot/blob/master/dev/roadmap.md). Ultimately the best solution here is to create a user control designed to mimic TradingView or TC2000 or some other finance software commonly known for an excellent user interface (I'm open to suggestions!)

Hope it helps!

**Comment by Minu476** [comment]
great thank you very much! Yes the above code is helpful.
