### ISSUE TITLE
mouse-interactive plots with shared axes

### ISSUE THREAD

**Issue by LogDogg** [swharden/ScottPlot#399]
Would be really nice if there was a way to synchronise the axes of multiple plots. I've tried doing it using the AxesChanged event, but the result doesn't feel responsive and the performance is underwhelming.
I propose implementing the ability to add multiple plots to the control (FormsPlot in WinForms) or making a new control with this functionality. There should also be an option to sync the axes, something like

`formsPlot1.SyncPlotAxes(horizontal: true, vertical: true); `

Then, instead of accessing the plot using `formsPlot1.plt`, it would go something like `formsPlot1.Plots[0]`

**Comment by swharden** [comment]
@LogDogg thanks for the suggestion! I agree that having two controls with shared axis feels clunky if it only updates on MouseUp events or by a timer. 

I'll look into how I can make this better! I think the best starting place is to figure out how to sync axes across two controls, then later I can figure out if/how to update the controls to support multiplots.

My experimental plotting library [QuickPlot](https://github.com/swharden/QuickPlot) supported this type of behavior (a user control that could handle multi-plots and truly shared axes)... but it used a pretty different rendering sequence to do this. I just added a ZIP demo if you want to check it out https://github.com/swharden/QuickPlot#download-demo

**Comment by swharden** [comment]
This is added to the list of upcoming changes (#399) so I'll track it there and close this issue for now.
