### ISSUE TITLE
Resize bug (crashes when user control is created)

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#4]
This works fine in console applications, but not well in forms.
```
plt.settings.SetDataPadding(150, 50, 100, 100);
```

**Comment by alex555176** [comment]
Dear all, 
While I was following the instruction on this step: Drag/Drop the ScottPlotUC (from the toolbox) onto your form. It suddenly appears this dia was saying that Fail to create the component. 

![fail to create the component](https://user-images.githubusercontent.com/10681492/53151193-e19e0500-35f5-11e9-8903-10cda323b9a9.PNG)

My configuration: Visual Studio 2017 with C# Form Application.
I've tried on so many ways to find a solution. 
Do anyone know how to solve this problem.
Thank you so much.

**Comment by swharden** [comment]
Hi @alex555176, I'm sorry to hear you're having trouble. Here is my suggestion!

1) ensure you have the latest version of ScottPlot downloaded

2) Try commenting out these two lines. Does your situation improve?

https://github.com/swharden/ScottPlot/blob/bcedb663acfabd0cbf5f2bfb85536a877faf26ed/src/ScottPlot/ScottPlotUC.cs#L58-L59

**Comment by swharden** [comment]
Also, after making the change, use "build" -> "rebuild solution" to ensure the user control gets updated before you try to drag/drop it again.

**Comment by alex555176** [comment]
Dear Mr. Swharden,
Thank you so much for your advisement.

And it works, but I would like to add one addition revision.
Since we commenced code to resize the component, an setting to fit the size of it might be better.
![image](https://user-images.githubusercontent.com/10681492/53287134-49ea1380-37bb-11e9-8121-65b356d2f8d2.png)

Pretty appreciate for your code and assistant.
Best Regards,

**Comment by swharden** [comment]
I'm glad you found a fix that works well for you! Thanks for reporting this issue!

I made several changes to the way the code handles resize events now. I _think_ it will work on your machine, but since the code crashed on your computer and not mine I don't have a good way to test it. Would you be willing to download the latest ScottPlot and see if it still works for you?
