### ISSUE TITLE
Rendering problem - angled lines appear during mouse interaction

### ISSUE THREAD

**Issue by bukkideme** [swharden/ScottPlot#401]
**Describe the bug**
When the docked ScottPlot.FormsPlot is maximized together with the parent Form's window, strange angled lines appear at top right during middle mouse button pushed down. Same artifact happens when we use the right mouse button for zoom. 

**To Reproduce**
VS Community 2019, Version 16.5.5. 
ScottPlot 4.0.32 (previous version also has the same bug)

Steps to reproduce:

Create a new Winform project.
Drop a ScottPlot.FormsPlot user control into the Form, and set it as "Dock - Fill".
Run the project.
Maximize the Form window.
Start to use the mouse buttons for the different zoom options.
Bug appears visible.

Another info, if you set the grid line width to value 2 or higher (i did it in the Form's constructor), the bug seems to disappear:
formsPlot1.plt.Grid(lineWidth: 2);

**Screenshots**
I set the Grid color to red to make the bug more visible!

![Scottplot_bug1](https://user-images.githubusercontent.com/51174971/82195508-ad98b900-98f8-11ea-9af6-ecbc1628be26.png)

**Comment by citizen3942** [comment]
I have the same issue.
Unfortunately, I have not taken a closer look at the issue myself yet.

**Comment by swharden** [comment]
This is so frustrating! This is an error in `System.Drawing` when rendering perfectly horizontal lines that touch the edge of the bitmap described in #327

This issue may have re-emerged from recent work on the grid system https://github.com/swharden/ScottPlot/commit/a63eba9d67616488baa365d2c12963a5c6a952e0

I'll take a closer look!

**Comment by swharden** [comment]
It's a weird fix, but I can prevent the grid line from drawing the last pixel on the right (only when anti-aliasing is off) and it corrects this problem. This might be better than the current solution which tilts the line up by a fraction of a pixel.

![image](https://user-images.githubusercontent.com/4165489/82234648-ae811900-98ff-11ea-9fd1-a34c17065893.png)

**Comment by swharden** [comment]
This should be fixed in ScottPlot 4.0.33 now on NuGet. I'd appreciate your feedback to confirm it works on your machines!

**Comment by swharden** [comment]
FWIW it's not just `System.Drawing`, this also happens with `System.Drawing.Common` in .NET Core 2.0 🤔 

```cs
var plt = new ScottPlot.Plot(400, 300);
plt.Grid(xSpacing: 2, ySpacing: 2, color: Color.Red);
plt.Axis(-13, 13, -10, 10);
plt.GetSettings(false).misc.antiAliasData = false;
plt.GetSettings(false).misc.correctGridRenderingBug = false;
plt.SaveFig("microsoftPleaseExplain.png");
```

![image](https://user-images.githubusercontent.com/4165489/82251253-db8ef500-991a-11ea-90c4-6951198cc24b.png)

**Comment by swharden** [comment]
### SOLVED: Never create a solid Pen.DashPattern (set Pen.DashStyle to Solid instead)

Assigning a dash pattern (even a solid one) automatically switches a pen's DashPattern from Solid to Custom. Custom dash patterns produce rendering artifacts when anti-aliasing is off. They're also less performant.

I searched the code and removed all instances where the DashPattern was manually set.
https://github.com/swharden/ScottPlot/search?q=dashpattern&unscoped_q=dashpattern

I created a helper function to safely make pens:
https://github.com/swharden/ScottPlot/blob/f9c1c8bedc8c0c6da98084867b949178c3036f38/src/ScottPlot/Drawing/GDI.cs#L63-L97
