### ISSUE TITLE
How To remember plots Positions( pan , zoom , visibility, etc) before clearing needed for update with live data?

### ISSUE THREAD

**Issue by Minu476** [swharden/ScottPlot#405]
I am using plt.clear() and creating my new plt.Plottables.  Since my update is every 1 minute the performance is not a big concern for now, but if I have Zoomed or changed limits , etc after update I will lose them.

**Comment by swharden** [comment]
```cs
double[] originalAxisLimits = plt.Axis();
plt.clear();
/* plot new stuff */
plt.Axis(originalAxisLimits);
```

Something like this should do the trick!

**Comment by swharden** [comment]
You may also find the `Margin()` method useful:

```cs
plt.AxisAuto(horizontalMargin: 0, verticalMargin: 0.5);
```
