### ISSUE TITLE
Open plot in new window don't copy source plot styles.

### ISSUE THREAD

**Issue by StendProg** [swharden/ScottPlot#416]
**Describe the bug**
Open plot in new window using context menu don't copy plot styles.
Maybe this is what you intended.
Copy styles is usefull feature, and reset style on new plot usefull too.
Some configuration param like 'bool copyStyles' would be ideal solution.

**To Reproduce**
Open any demo with custom styles and select `Open in new window` context menu item.

**Screenshots**
![image](https://user-images.githubusercontent.com/53831487/82684704-b7555000-9c5b-11ea-854b-b831360b30d6.png)

**Comment by swharden** [comment]
Thanks for reporting this @StendProg! Interestingly this only affected the WinForms control. It should be fixed now 👍
