### ISSUE TITLE
optional parallel processing for Signal and SignalXY

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#419]
Now that `Settings.GetPixel()` and `Settings.GetLocation()` are thread safe (#245, #72) maybe we can turn on `settings.misc.useParallel` by default.

I created a GUI test app (/dev/Benchmark) which tests performance and assesses stability of the user controls. They seem stable for me, and parallel processing definitely improves performance for large datasets. With 10 million points my FPS doubled (`25.5 FPS` to `57.5 FPS`)

![image](https://user-images.githubusercontent.com/4165489/82717437-13bf6c00-9c6a-11ea-8142-d17678e85400.png)

There's also a pure-bitmap test which doesn't use the user control.

![image](https://user-images.githubusercontent.com/4165489/82717452-2d60b380-9c6a-11ea-88c5-3050af37d6c0.png)

**Comment by swharden** [comment]
@StendProg I enabled parallel processing by default, removed `useParallel` as an option, and even removed the old methods from plottables which don't use parallel processing. 

I think this is ok since the pixel lookup methods are now thread-safe (and your helpful tests confirm this will remain true, #245), but since this was a big change to `Signal` and `SignalConst` I wanted to make sure you were aware of it and find this acceptable.

**Comment by StendProg** [comment]
@swharden 
A bit late sorry,
As i understand main reasone switching to parallel implementation only, is the code duplicates.
I think it's better stay it configurable. Parallel implementation works slower on small data sets, load all processor cores, contains a bunch of potential errors etc..
I will try to remove code duplicates in all parallel/sequental methods, to make it easy to support like in https://github.com/swharden/ScottPlot/pull/454/commits/3d8ae63e39967ed8d26f53049b6a98280ef1fef5 . But in low priority task.

**Comment by swharden** [comment]
Hi @StendProg, thank you for correcting this issue and refactoring the Signal module in #454. I am very happy about your modifications! This is a great example of using LINQ to improve readability and utilize parallel processing.

https://github.com/swharden/ScottPlot/blob/08d42d0447a2cf0097f86c19969f973b0a71fa44/src/ScottPlot/plottables/PlottableSignal.cs#L203-L216

`ScatterXY` (#374) does not use parallel processing, but after 08d42d0447a2cf0097f86c19969f973b0a71fa44 it now accepts `bool useParallel` as a constructor argument. I believe the two slow calls which may benefit from parallel processing are these: 

https://github.com/swharden/ScottPlot/blob/08d42d0447a2cf0097f86c19969f973b0a71fa44/src/ScottPlot/plottables/PlottableSignalXY.cs#L77-L78

Do you think SignalXY could be easily modified to optionally support optimization from parallel processing?

**Comment by StendProg** [comment]
> Do you think SignalXY could be easily modified to optionally support optimization from parallel processing?

It does not seem to be a simple task. There are many places where the code has strong dependencies between iterations. I'll see what i can do.

**Comment by swharden** [comment]
> > Do you think SignalXY could be easily modified to optionally support optimization from parallel processing?
> 
> It does not seem to be a simple task. There are many places where the code has strong dependencies between iterations. I'll see what i can do.

No worries! Having the ability to control whether Signal plots use parallel processing is very useful, and `useParallel` is now an argument for `Plot.PlotScatter()` so this issue is in a good place.

If in the future we decide to add parallel support to SiganlXY we can explore the idea further - thanks for looking into it! 👍
