### ISSUE TITLE
Pie Charts

### ISSUE THREAD

**Issue by Benny121221** [swharden/ScottPlot#421]
**What can we do to make ScottPlot better?**
A new Pie Chart plottable:
![image](https://user-images.githubusercontent.com/8635304/82717768-9e4c9f00-9c5b-11ea-9eac-b7d7549b289f.png)

```cs
var pieChart = plt.PlotPie(proportions, labels);
```

Check the ScottPlot Roadmap to see if your feature is already planned for an upcoming release:
https://github.com/swharden/ScottPlot/blob/master/dev/roadmap.md

**Comment by swharden** [comment]
This would be awesome if you want to give it a stab! 

This might be a little more straightforward than the heatmap (#420)

**Comment by Benny121221** [comment]
#423

**Comment by swharden** [comment]
Pie charts will be in ScottPlot 4.0.35, thanks @Benny121221!
