### ISSUE TITLE
ScottPlot Cookbook doesn't go past 4.0.32

### ISSUE THREAD

**Issue by Benny121221** [swharden/ScottPlot#422]
**Describe the bug**
The latest cookbook version is 4.0.32:

**To Reproduce**
Go to https://swharden.com/scottplot/cookbook.md.html

**Screenshots**
If applicable, add screenshots to help explain your problem
![image](https://user-images.githubusercontent.com/8635304/82717857-2468e580-9c5c-11ea-9e93-40bef2b18784.png)

**Comment by swharden** [comment]
Yeah, this one is intentional. If I make really little tweaks that just affect the user controls or are just performance optimizations I don't regenerate the cookbook. 4.0.32 was the last "big" release.

https://github.com/swharden/ScottPlot/releases
