### ISSUE TITLE
ScatterPlot consecutive xs (if xs is null)

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#427]
I'd like to be able to do this:

```cs
double[] ys = { 1, 4, 9, 16, 25 };
plt.PlotScatter(null, ys);
```

...and `xs` would get generated as a set of consecutive numbers.

The alternative would be an overload which has no `xs` argument.

**Comment by StendProg** [comment]
It's better to use `Signal` or `SignalConst` if `xs` is set of consecutive numbers. And they already have `API` to easy setup that consecutive `xs`.

**Comment by swharden** [comment]
> It's better to use `Signal` or `SignalConst` if `xs` is set of consecutive numbers.

This is a very good point. Making it easy to use PlotScatter for a consecutive list of X values communicates to the use that this is encouraged, when it's almost always a bad idea. This is a good reason _not_ to make this task easy.

Thanks for the suggestion!
