### ISSUE TITLE
Radar Graphs

### ISSUE THREAD

**Issue by Benny121221** [swharden/ScottPlot#428]
**What can we do to make ScottPlot better?**
A new plottable for Radar Graphs (AKA spider/star chart):

A 7-Point Radar Graph:
![image](https://user-images.githubusercontent.com/8635304/82853151-2633e280-9ec2-11ea-8133-d540757640fd.png)

A 4-Point Radar Graph:
![image](https://user-images.githubusercontent.com/8635304/82853198-4a8fbf00-9ec2-11ea-9d77-a1c7c5480d7c.png)

User code being something like this:

```cs
var radar = plt.PlotRadar(double[] values, string[] labels);
```

**Comment by swharden** [comment]
This looks great @Benny121221, thanks!
