### ISSUE TITLE
Cannot show multiplot in a Winform window

### ISSUE THREAD

**Issue by dprevato** [swharden/ScottPlot#429]
I cannot see a way to render a multiplot object in a FormsPlot: all the examples show how to build a very nice multiplot, and how to save it to a bitmap file.
Have I missed something? Is it possible in WPF only? How? 
If it's not possible to have an interactive multiplot in a FormsPlot object now, will this feature be implemented in a future?
Thanks

**Comment by Benny121221** [comment]
@dprevato Multiplots are static images, no pan or zoom. You can use the bitmap in a WinForms (or WPF) app however like this.

```cs
var mp = new MultiPlot(width: width, height: height, rows: 2, cols: 2);
//Add some subplots
.
.
.
var bmp = mp.GetBitmap()
```

You can then use this bitmap in your app. You don't need to save it to a file. Although you could with: 
```cs
mp.SaveFig("filename.png");
```

**Comment by swharden** [comment]
Hey @dprevato, @Benny121221 gave a good summary of the state of multiplot and it looks like they are working on a solution to make the Bitmap solution easier.

> If it's not possible to have an interactive multiplot in a FormsPlot object now, will this feature be implemented in a future?

I think the direction I'm going to try to go is to make it easy to drop multiple `FormsPlot` or `WpfPlot` controls onto a window, and link their axes together #412 #399 

This method is somewhat supported now. Check the "linked axes" demo application

![image](https://user-images.githubusercontent.com/4165489/82962362-00740f80-9f8e-11ea-8655-3363864b1c77.png)

Hope it helps!

**Comment by swharden** [comment]
I'll expand on @Benny121221's example and note that you could just throw a PictureBox on your form, then assign a Bitmap to it. It's not mouse-interactive, but if you really want a multiplot without multiple controls, it's another option.

```cs
var mp = new MultiPlot(width: width, height: height, rows: 2, cols: 2);
//Add some subplots
pictureBox1.Image = mp.GetBitmap();
```

**Comment by swharden** [comment]
@dprevato thanks again for bringing-up this topic! I added "_figure out how to implement better shared axes in user controls #399, #429_" to #412 and will track development there.

**Comment by dprevato** [comment]
Many thanks to you all, for the replays and the infos!

**Comment by Ismaeeleyfa** [comment]
Hello, 
Thank you for this amazing, fast and nice library! 
I have a question regarding linked axis though, in the demo App we can see that it works very well. I'm however unable to find source code for axis linking.  Thanks again!

**Comment by Benny121221** [comment]
@Ismaeeleyfa The linked axis demos are not in the cookbook, as they're in platform-specific demos. You can find those in [AvaloniaDemos](https://github.com/swharden/ScottPlot/tree/master/src/demo/ScottPlot.Demo.Avalonia/AvaloniaDemos), [WpfDemos](https://github.com/swharden/ScottPlot/tree/master/src/demo/ScottPlot.Demo.WPF/WpfDemos), or [WinFormsDemos](https://github.com/swharden/ScottPlot/tree/master/src/demo/ScottPlot.Demo.WinForms/WinFormsDemos)

**Comment by swharden** [comment]
Hi @Ismaeeleyfa, see #670 for a similar question and link to source code there.

**Comment by Ismaeeleyfa** [comment]
Problem solved, thanks a lot for your help and replies!
