### ISSUE TITLE
PlotBitmap

### ISSUE THREAD

**Issue by Benny121221** [swharden/ScottPlot#431]
**What can we do to make ScottPlot better?**
Perhaps a function to allow drawing a bitmap without swapping to a different control. This would be useful in the case of multiplots, as they can only be rendered as a static image: #429 

Does your proposed feature allow users to do new things in source code? If so, show us how you'd like to be able to use the new feature:

```cs
var bmp = multiplot.GetBitmap();
plt.PlotBitmap(bmp)
```

Check the ScottPlot Roadmap to see if your feature is already planned for an upcoming release:
https://github.com/swharden/ScottPlot/blob/master/dev/roadmap.md

**Comment by Benny121221** [comment]
This is simple to implement, I'm just wondering if its outside the scope of ScottPlot. I could see it being inconvenient that most plottables can be added just by installing the nuget package, but multiplots (and perhaps some future plottables) need some trickery.

If this is added, I think `PlottablePie`, `PlottableHeatmap` and `PlottableRadar` would be best changed such that they return a bitmap, as there isn't much use in panning or zooming them.

**Comment by swharden** [comment]
> ```cs
> plt.PlotBitmap(bmp)
> ```

This is interesting in itself. It may be useful somehow, but I can't think of an immediate use case, so I'm agnostic about its implementation.

> ```cs
> var bmp = multiplot.GetBitmap();
> plt.PlotBitmap(bmp)
> ```

I probably wouldn't go this direction though. The user wanting to display a Bitmap can just:

```cs
pictureBox1.Image = multiplot.GetBitmap();
```

**Comment by swharden** [comment]
I definitely like this idea, but considering all the other stuff that's going on (#412 💀) I don't plan to implement this soon. If you give it a go and issue PR I'd be happy to review it and merge it in!
