### ISSUE TITLE
How to fit axes to the data for a scatter plot?

### ISSUE THREAD

**Issue by pbanta** [swharden/ScottPlot#445]
After rendering the plot I can use a right mouse click to open a Settings dialog. In the settings dialog the horizontal and vertical axis sections have a Fit button.

How can I make horizontal and vertical axis size to fit the min/max of the data?

I tried 
    DischargeGraphPlot.plt.AxisAuto(xExpandOnly: true, yExpandOnly: true);

This is how the graph appears:
![image](https://user-images.githubusercontent.com/19985411/83587220-26f8f400-a514-11ea-9ec4-8fec26b93a05.png)

This is what I want:
![image](https://user-images.githubusercontent.com/19985411/83587314-69bacc00-a514-11ea-8306-86c0fa6ba6a1.png)

**Comment by swharden** [comment]
Hey @pbanta, you're pretty close! Just call `AxisAuto()` without arguments.

```cs
DischargeGraphPlot.plt.AxisAuto();
```

Using the "expand only" arguments was preventing the axis limits from _contracting_ to fit your data. Let me know if this does the trick! 👍

**Comment by swharden** [comment]
Also, FWIW, if your data is evenly spaced on the horizontal axis consider using `PlotSignal()` or `PlotSignalConst()` for improved performance.

**Comment by pbanta** [comment]
Yes, that fixed it in addition to calling `AxisAuto()` after `PlotScatter()`.

I will experiment with `PlotSignal()` and `PlotSignalConst()` because the data is evenly spaced.

Thank you very much for the help!
