### ISSUE TITLE
Allowing images as plot/axis labels?

### ISSUE THREAD

**Issue by Benny121221** [swharden/ScottPlot#446]
**What can we do to make ScottPlot better?**
Allowing images as plot titles or axis labels allows a user to do their own formatting should they wish, including TeX.

```cs
plt.YLabelImage("label.png")
```

For example, a user could get a result similar to this:
![image](https://user-images.githubusercontent.com/8635304/83700686-b52cb300-a5c4-11ea-8848-2d3e4d1c3c9b.png)

Pardon my poor handwriting, it's not so great when it isn't converted to mathprint :/ If you couldn't read it, it says I forgot to add a vector hat.

Also, don't bother trying to find out what that graph is supposed to be, it's meaningless.

**Comment by Benny121221** [comment]
I blame my 30 dollar drawing tablet for my poor handwriting.

And that's Canadian dollars, so that's probably 5 dollars in freedom land

**Comment by swharden** [comment]
I'll close this issue while I tackle some of the more pressing topics, but this feature has been added to #412 so it won't be forgotten, and this issue can be re-opened as work toward this resumes 👍
