### ISSUE TITLE
Best approaches to automatically plot IEnumerables (Lists, Queues, etc.)

### ISSUE THREAD

**Issue by bukkideme** [swharden/ScottPlot#447]
I remember some time back, I have found some examples here how to automatically plot my data to a FormsPlot control, but I cannot find these examples anymore in the latest Cookbook, might be I just did not try searching hard enough! :)

So practically I am asking for examples from simple to advanced cases when we want to "auto plot" data from a List, Queue, or other collections. I often collect data from hardware in such "buffer" collection, and it would be great to see approaches how to "bind" such collection to a FormsPlot. So as the collection grows/changes, what are the different ways/tricks to re-plot? Most often the plotting frequency is less than 1 Hz, so in my case speed is not a factor.

Thanks for advises and any links where I can see such examples!

**Comment by swharden** [comment]
Hey @bukkideme, the cookbook demonstrates features that can be implemented in console applications. User-control-specific examples can  be found in the demo program.

Currently the user controls do not bind data objects - they just take in `double[]` and display it whenever `formsPlot1.Render()` is called. That said, you may find these two examples in the demo application useful:

### Live Data

This demo uses a fixed-size array and frequently updates its values and re-plots

![image](https://user-images.githubusercontent.com/4165489/83765805-9f150600-a649-11ea-9848-8046607d9e1a.png)

### Growing Data

This demo shows how to plot growing data

![image](https://user-images.githubusercontent.com/4165489/83765624-6a08b380-a649-11ea-959b-99359f9a3a24.png)

Hope it helps!
