### ISSUE TITLE
growing data demo breaks after several seconds

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#448]
![image](https://user-images.githubusercontent.com/4165489/83765751-915f8080-a649-11ea-8988-395d5756d94f.png)

**Comment by StendProg** [comment]
Hi @swharden 
This error happens when the `Signal` goes to `RenderHighDensity` mode. It haven't any respects to `maxRenderIndex` and render full signal. But limits calculates correct...
Fixed in #454

**Comment by swharden** [comment]
#454 is now merged
