### ISSUE TITLE
TightenLayout() resets custom layout options

### ISSUE THREAD

**Issue by ismdiego** [swharden/ScottPlot#449]
I am using ScottPlot.WinForms 4.0.34, and I have found that if you customize the layout (for instance, changing the xScaleHeight), then when you move or zoom the plot with the mouse, the layout is reset. Other typical use case is when you use long tick labels and a rotation. When the layout is reset you cannot read the full label anymore.

I think I have found the "culprit" in FormsPlot.cs. Both in PbPlot_MouseUp and PbPlot_MouseWheel methods the Render method is called with recalculateLayout: true (hardcoded).

I think that this should be better suited with a configuration setting, like "enableResetLayout" (bool).

Anyway, many thanks for this fantastic library.

**Comment by swharden** [comment]
Thanks for the descriptive suggestion @ismdiego!

Like you suggested, I think the problem boils down to this getting called on MouseUp events:
https://github.com/swharden/ScottPlot/blob/01a2621d5e19b9dfad6f9768199f3dcf07d5509f/src/ScottPlot.WinForms/FormsPlot.cs#L99-L100

A good solution would be to ensure this "tightening" respects user-defined padding.

I'll take a closer look this weekend! Thanks again for the suggestion, and I'm happy to hear you enjoy this library 👍

**Comment by swharden** [comment]
doh! I already implemented this and I forgot. You can do this:

```cs
formsPlot1.plt.Layout(yLabelWidth: 100, xScaleHeight: 50);
formsPlot1.Configure(recalculateLayoutOnMouseUp: false);
```

The whole layout system will get refactored to make this easier in the future, but for now this should do the trick! Good luck! 👍

**Comment by swharden** [comment]
somehow I got confused which version this was in... I just published it on NuGet and that code should work in version 4.0.35 and up
