### ISSUE TITLE
AxesChanged - MatchAxis feature has shots and lags

### ISSUE THREAD

**Issue by robokamran** [swharden/ScottPlot#451]
I synchronize 2 or more FormsPlots using AxesChanged and MatchAxis. When I zoom or pan, there is a noticeable shot/lag in synchronization. It is also detectable in the demos. This has happened since the version 4.0.20 (version 4.0.19 is OK). Consider the following code which synchronizes 4 "FormsPlot"s, in previous versions it was perfect for synchronizing 4 FormsPlots each include a 10000 points Signal. But now it has shot/lag. (currently I have to use V4.0.19)

```cs
private void FormsPlot_AxesChanged(object sender, EventArgs e)
{
    foreach (var plot in PlotList)
    {
        plot.plt.MatchAxis((sender as FormsPlot).plt, vertical: false);
        plot.Render();
    }
}
```

**Comment by StendProg** [comment]
Hi @robokamran,
I fixed lagging in #452 
 if you don't want wait for new release, you can grab changes manualy (its only few lines of code).
If you need additional performance, you can render linked plot in low quality
`Render(true, lowQuality:true, processEvents:true)`

**Comment by swharden** [comment]
Hey @robokamran, thanks for reporting this! @StendProg, thank you for your rapid identification of the issue, and your helpful PR (#452). I'll take a closer look and release an updated NuGet package tonight 👍

**Comment by robokamran** [comment]
I have just noticed a key point and somehow my mistake!
In V4.0.19, the axis change update happened on the "right click up" event after the zoom/pan on the original plot is completed. In newer version the synchronization happens in real-time. I write log programs for hardware interfaces and the former type of functionality was so good and applicational that all our guys (the users) didn't care about the real-time synchronization! Their focus was on the original plot, since we have up to 16 plots at the same time with more than 20K points and we need time synchronization for all of them when we zoom in time. Could this sync type be optional? Because the "not real-time" type is very clear, robust, applicational and render OK.

**Comment by robokamran** [comment]
It seems that it does the trick! :sunglasses:
Thanks a lot @swharden :wink: 🙏🏻
