### ISSUE TITLE
Waterfall Charts

### ISSUE THREAD

**Issue by Benny121221** [swharden/ScottPlot#463]
**What can we do to make ScottPlot better?**
Waterfall charts:
![image](https://user-images.githubusercontent.com/8635304/84610454-e1bfb500-ae77-11ea-8f45-00f8ec36835e.png)

Does your proposed feature allow users to do new things in source code? If so, show us how you'd like to be able to use the new feature:

```cs
var waterfallPlot = plt.PlotWaterfall(double[] xs, double[] ys, double[] yOffsets)
```

I am undecided if it should be done like above, or as an added parameter for `PlotBar`:
```cs
var waterfallPlot = plt.PlotBar(double[] xs, double[] ys, double[] yOffsets)
```

Check the ScottPlot Roadmap to see if your feature is already planned for an upcoming release:
https://github.com/swharden/ScottPlot/blob/master/dev/roadmap.md

**Comment by swharden** [comment]
Looks great, thanks @Benny121221!

![image](https://user-images.githubusercontent.com/4165489/86537227-6754e480-bebb-11ea-9bd9-13cd3d9efc64.png)
