### ISSUE TITLE
Selectively remove (clear) axis lines from a plot

### ISSUE THREAD

**Issue by imka-code** [swharden/ScottPlot#464]
Hi! 
I would like to remove these old lines on the Scatter Plot before next action on the Scatter Plot.  

This is what I have used to draw lines :
fPlot.plt.PlotVLine(x,color: Color.DarkGreen, lineStyle: LineStyle.DashDot);
But I can't find the way to remove the lines.   

**Here's an example of what I'd like to do:**
![image](https://user-images.githubusercontent.com/54004247/84644268-63ffb600-af18-11ea-9c2d-9a816c199e8f.png)

**Comment by swharden** [comment]
Hey @imka-code, what you're looking for is the `Clear()` method. You can pass in an argument to clear just one plot type if you like, something like:

```cs
formsPlot1.plt.Clear(ScottPlot.PlottableVLine);
```

Let me know if this doesn't do the trick! 👍

**Comment by imka-code** [comment]
> Hey @imka-code, what you're looking for is the `Clear()` method. You can pass in an argument to clear just one plot type if you like, something like:
> 
> ```cs
> formsPlot1.plt.Clear(ScottPlot.PlottableVLine);
> ```
> 
> Let me know if this doesn't do the trick! 👍

It doesn't work(  invalid type

**Comment by swharden** [comment]
Hey @imka-code, I took another look and it looks what must be done is:
```cs
plt.Clear(typeof(ScottPlot.PlottableVLine));
```

That said, this is a pretty confusing requirement, so I'll try to add an overload which accepts a `Plottable` to make this task easier to accomplish in the future. Thanks for sharing your question!

**Comment by imka-code** [comment]
> Hey @imka-code, I took another look and it seems what must be done is:
> 
> ```cs
> plt.Clear(typeof(ScottPlot.PlottableVLine));
> ```
> 
> That said, this is confusing for the user to figure out, so I'll make an overload which accepts a `Plottable` or `Plottable[]` to make this task easier in the future. (relates to #275)
> 
> Thanks for sharing your question!

Thanks! It works.
