### ISSUE TITLE
Interactive way of displaying specific points on line plot

### ISSUE THREAD

**Issue by LB767** [swharden/ScottPlot#465]
First of all, thank you for creating this library. It feels great to use while remaining simple and fast which is all one could ask for.

Unless I've missed an easy way of doing this, it would be nice if you could display points by clicking on the plot directly, similarly to how Matlab does it.
[![Image from Gyazo](https://i.gyazo.com/2f87570b374f31428121c900072ae728.gif)](https://gyazo.com/2f87570b374f31428121c900072ae728)

Since there are already a few keyboard shortcuts maybe Shift+Click could allow this?

**Comment by swharden** [comment]
> First of all, thank you for creating this library. It feels great to use while remaining simple and fast which is all one could ask for.

I'm glad you enjoy using ScottPlot! I definitely aimed for simplicity while creating it, so I'm happy to hear you found it simple to use 

> Unless I've missed an easy way of doing this, it would be nice if you could display points by clicking on the plot directly, similarly to how Matlab does it.

Check out the "show value on hover" demo in the demo application. It's _show value on hover_, not _show value on click_, but this might get you pretty close to what you're trying to do.

![image](https://user-images.githubusercontent.com/4165489/84663858-b8d90780-aeeb-11ea-8358-3dd2c81d6afe.png)

> Since there are already a few keyboard shortcuts maybe Shift+Click could allow this?

Using a key-press to enable _show value on hover_ function is an interesting idea. Perhaps the _show value on hover_ demo could be modified to do this, as it only runs the calculations if the `S` key is held. 

Most common keypresses are already in use (https://github.com/swharden/ScottPlot/issues/436#issuecomment-636543971) but perhaps we could enable this functionality through the right-click menu.

Thanks for the suggestion! I added this idea to the list of upcoming topics for me to explore #412. It would be nice if _show value under mouse_ were easier to turn on and off. I'll close this issue for now, but will re-open it when development toward this end resumes.

Let me know if you have any further questions,
Scott
