### ISSUE TITLE
Allow Axis Labels in different radices

### ISSUE THREAD

**Issue by Benny121221** [swharden/ScottPlot#469]
**What can we do to make ScottPlot better?**
In some domains number systems other than decimal are appropriate. For example hexadecimal in Computer Science and Electrical Engineering (and to a lesser extent octal).

You would think this would be provided by the overload which allows the ticks to take format strings, however, the hexadecimal `x` format specifier is only valid for integral types and the ticks are doubles.

I suggest something like this:
```cs
plt.TicksRadixX(int radix = 16, string prefix = "0x");
plt.TicksRadixY(int radix = 16, string prefix = "0x");
```

Another notation for non-decimal radices is to put the base in subscript after the number: ![image](https://render.githubusercontent.com/render/math?math=\mathbf{FFFFFFFF_{16}}&mode=inline)

The prefix notation is going to be easier to implement, even though it doesn't generalize to other radices (except octal with prefix "0" and binary "0b"). In reality bases other than decimal and hex are rare. I'm unsure if the prefix should be on by default or not.

Check the ScottPlot Roadmap to see if your feature is already planned for an upcoming release:
https://github.com/swharden/ScottPlot/blob/master/dev/roadmap.md

**Comment by swharden** [comment]
Thanks @Benny121221! I'll merge #475 in today
