### ISSUE TITLE
Draw Y axis at top of the plot and highlight selected line completely

### ISSUE THREAD

**Issue by metehanpataci** [swharden/ScottPlot#470]
Hello,

 I want to  draw a train graph bu using ScottPlot at WPF. It will look like http://www.opentrack.ch/opentrack/images/otTrainGraph.gif

X axis (time values) should be at top of the plot and Y axis should include station names (string values). I have studied your examples but I couldnt find some features.

Question 1: Can I put X axis labels (ticks) to the top of the plot? I couldnt find 
Question 2: Can I highlight a whole line by clicking on it (may be stroke will increase)?

**Comment by swharden** [comment]
Hi @metehanpataci, 

A train graph like this will be difficult to show in ScottPlot, but it may be possible. Here are some tips/thoughts that may help.

![image](https://user-images.githubusercontent.com/4165489/84909123-4a2eb200-b083-11ea-8b5e-63a889b4242e.png)


### Multiple plots with no padding

I'd probably start by creating 4 plots which touch edge-to-edge, then adjust the vertical padding of each so there is 0 padding for most graphs, and padding only for the top of the top graph and the bottom of the bottom graph. Arguments of the `plt.TightenLayout()` method will help here. 

A limitation here is that the little tick marks in ScottPlot currently display _outside_ the graph area, not inside it like in your picture, so even if you stack 4 plots you'll only see ticks on the outside edges of the outermost plots. This might make this approach unfeasible.

### Plot everything on one graph

An alternative approach could be to create a single scatter plot, plot your data, then add horizontal lines to visually separate the graph into 4, while it's really a single graph. For now the `plt.PlotHLine()` can help draw a flat line at a Y position, but perhaps we could create a new plot type which is designed to mimic a mid-graph axis line with ticks like what is shown in your picture.

Another way to think of this is in terms of a feature request title is, "option to add tick marks to grid lines". This may be the simplest approach to get what you're looking for. You could then simply customize the vertical axis tick labels to say your various STAT titles.

### Can you X axis on top of plot?

Not currently. This is a goal I'm working toward #412 but progress is a bit slow as I have several tasks I'm trying to accomplish before I refactor the axis/layout system.

### Can I highlight a line by clicking on it?

I don't have an example for how to do this, but it seems possible, although it might take a little work. Check out the _show value on hover_ demo application. It's designed to highlight the point in a line closest to the mouse, but I bet it could be modified to indicate which line the mouse is over, and adjust that line's width to reflect this information.

---

Hope it helps! Sorry I don't have a simpler, more streamlined solution. This is an interesting type of graph I have not seen before. Thanks for raising these interesting questions!

**Comment by metehanpataci** [comment]
Hi Scott,

Thank you for reply and kindness. I will try your suggestions but I must find quick solution for train graph drawing.

**Comment by swharden** [comment]
Sounds good! Let me know if you have further questions.

Feel free to e-mail me swharden@gmail.com if you're interested in commissioning rapid development of a custom solution for a commercial application. While the free/open-source ScottPlot library has big to-do list I'm trying to tackle in order (#412), I sometimes spin-off a custom version where I can rapidly implement special functionality for people trying to do something special for their commercial application in a pinch (e.g., a version that specifically supports train plots).
