### ISSUE TITLE
create "plottable under mouse" demo

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#471]
All the demos so far focus on _show value on hover_, but a demo should be created where multiple scatter plots are plotted on top of each other and the mouse can hover and/or click to select a single line by clicking on it. This idea came from a question in #470

On one hand custom mouse-aware plottables could be used here (#414, @Benny121221), but on the other hand it would be nice to have this functionality with common plottables (like scatter and signal).

**Comment by Benny121221** [comment]
It may make sense to move the `GetPointNearest` functions from `IHighlightable` to a new interface and apply that to every applicable plot type (scatter, signal, OHLC, candlestick, etc).

Alternatively, and this was what I originally thought of when doing the `scatterHighlight` stuff, every (applicable) plot could implement IHighlightable. There would he no `PlotSignalHighlight` as the regular `PlotSignal` would support highlighting. Then `PlotScatterHighlight` can be deprecated and made an alias for `PlotScatter`

As for grabbing the closest plot, that becomes very easy when they all overload `GetNearestPoint`

**Comment by swharden** [comment]
Thanks for these suggestions! Since implementation here trails off into refactoring land, I added this to the list of changes in #412 and will close this issue so I can focus on more pressing issues for now
