### ISSUE TITLE
How to check if a chart has been zoomed or panned

### ISSUE THREAD

**Issue by dprevato** [swharden/ScottPlot#472]
I would like to react to a zoom operation: the user draws a chart, let's say a scatter plot with some tens of thousend points, and then he zooms to see more clearly a portion of it. My question is: is there a way to react to the zoom event? I couldn't find an event related to zoom operations.
My workaround is:
- save the initial limits of the axes when the chart is first drawn;
- check with plt.Axis() if the actual limits are different than the inital ones. 
It would be nice if I could attach that check to an event...

**Comment by swharden** [comment]
Hey @dprevato, it sounds like you found a pretty good workaround! The windows forms user control has an `AxesChanged` event you can create a handler for which might be more consistent with what you were initially looking for. The downside there is that I think it's fired _as_ the axes are being changed (click-dragged), not just when they're released (dropped)... but perhaps for that you could create a handler for the `MouseUp` event if that's the event you wish to target.

Long-term I'm trying to make ScottPlot stateless, so storing previous axis states isn't really consistent with the future design goals, and saving and comparing current axis limits with previous ones on the user side (like you're doing) is probably the best long-term solution for this.

Hope it helps!
Scott

**Comment by dprevato** [comment]
It sure does... I've been studying Scottplot for some time now, and I like it more and more. I will certainly make more questions in the near future :)
