### ISSUE TITLE
minRenderIndex for PlottableSignal (and it's derivatives)

### ISSUE THREAD

**Issue by Benny121221** [swharden/ScottPlot#474]
**What can we do to make ScottPlot better?**
`PlottableSignal` has an argument for the maxRenderIndex, to avoid rendering indices above it. A minRenderIndex parameter would allow the same thing, but for indices below it.

Does your proposed feature allow users to do new things in source code? If so, show us how you'd like to be able to use the new feature:

```cs
var sigplot = plt.PlotSignal(ys, minRenderIndex : 100, maxRenderIndex : 500);
```

This came up in this app: https://github.com/Benny121221/AssettoCorsaTelemetryApp. I was interested in plotting the last laps throttle trace in a lighter colour than the current lap.

Check the ScottPlot Roadmap to see if your feature is already planned for an upcoming release:
https://github.com/swharden/ScottPlot/blob/master/dev/roadmap.md

**Comment by swharden** [comment]
I like the idea - done! Thanks @Benny121221
