### ISSUE TITLE
Multiple Y axes on a single graph 

### ISSUE THREAD

**Issue by imka-code** [swharden/ScottPlot#478]
Hi! Again) 
I would like to show multiple Y axes on a single graph. My data has different y scales. I want to show them on a one graph. 
Is there any way I can do this? Without dividing on few plots.

**Comment by swharden** [comment]
Hey @imka-code, this is something that is asked sometimes (#180, #213) but is not currently possible. I'm currently working on refactoring the axis/tick system to make this possible in an upcoming version though (#412)

An _extreme_ option which I have done before is to make two plots with different axes, then add their `Bitmap` images together to produce a merged image. Depending on how you do it it may or may not be mouse interactive.
