### ISSUE TITLE
Clear() plots and Reset() plots

### ISSUE THREAD

**Issue by Resonanz** [swharden/ScottPlot#479]
**What can we do to make ScottPlot better?**
At the mo, there is a Clear() method that removes data shown on plots. This however does not clear the axes and title.

How about...

```
plt.Reset();     // Reset the plot, including data, axes, title, etc.
```

**Comment by cstyx** [comment]
Hi there!

another neat featur would be a  methode to allow the removal of a single/multiple selected plottables
when plotting live data

`public void ClearSelected(Collection<Plottable> plottables)`

and

`public void ClearSingle(Plottable plottable)`

**Comment by swharden** [comment]
Regarding `plt.Reset()`, I agree with @Resonanz this would be useful. It's actually mentioned as #407 and is now being tracked on #412, but I'll probably work through a large style-related refactor process before I add that feature.

Regarding the `ClearSingle(Plottable plottable)`, I like the direction @cstyx's suggestion is going!

However, `Clear` currently has this method signature:
https://github.com/swharden/ScottPlot/blob/2c3dcc98d886b9ee1d6a8f9e4be65551f7296ee4/src/ScottPlot/Plot.cs#L300-L309

I think what I'll do is create a new method `Remove(Plottable plottableToRemote)` to make it easy to specifically remove a single plottable from the list.

**Comment by swharden** [comment]
Done! This test shows how to use it. This new feature will be in ScottPlot 4.0.38, thanks @cstyx and @Resonanz!
https://github.com/swharden/ScottPlot/blob/d7f76e81b19ff316f247e8f163fb5d8b4eb604e2/tests/Plot/Clear.cs#L131-L144

**Comment by anose001** [comment]
I really like the ` Remove() ` a plottable method. It makes sense to call this when a plot consists of multiple plottables which are changing. Especially when one wants to change only one element on the plot. Exactly what I was looking for, although somewhat hidden in this discussion forum. I was not able to find it in the cookbook. Maybe this could be added in the Cookbook>Quickstart> after "Manually Add a Plottable" section or something like this?
