### ISSUE TITLE
Crash when zoom out

### ISSUE THREAD

**Issue by HowardWhile** [swharden/ScottPlot#480]
**Describe the bug**
When I use plot types population and zoom out to very small.
The program will crash.

**To Reproduce**
Can be reproduced in this way.
![3](https://user-images.githubusercontent.com/18715360/86227433-9586ab80-bbbf-11ea-950f-799d765e7870.gif)

**Screenshots**
I think because the input length of the line drawing function is incorrect.
![image](https://user-images.githubusercontent.com/18715360/86227931-51e07180-bbc0-11ea-86d3-ad86a0ac1f80.png)

Can add a protection like this! Or maybe there are other better method?
![image](https://user-images.githubusercontent.com/18715360/86228325-cf0be680-bbc0-11ea-9957-a5ea4829298d.png)

**Comment by swharden** [comment]
Thank you for reporting this @HowardWhile! The fix you suggested is perfect, and it will get released into ScottPlot 4.0.38 shortly.
