### ISSUE TITLE
Heatmap areas not equal

### ISSUE THREAD

**Issue by Resonanz** [swharden/ScottPlot#482]
**Describe the bug**
Referring to [https://swharden.com/scottplot/cookbooks/4.0.36/#experimental-heatmap-heatmap-quickstart](https://swharden.com/scottplot/cookbooks/4.0.36/#experimental-heatmap-heatmap-quickstart) we can see that there are 6 values added to the heatmap, however dimensionally some are 1x1 units, some 2x1 or 1x2 units, and the remainder 2x2 units. 

On the plus side, this heatmap plot is perfect for what I am needing to do, which is to provide a "heat" for each of 96 wells in a well plate.

**Comment by swharden** [comment]
@Benny121221 what do you think about this one? Want to add it to the list at #457? If not let me know and I'll see what I can do 😎

**Comment by Benny121221** [comment]
I had a look but and I assume something is being rounded unintentionally but I can't for the life of me seem to find where. I think I'll add it to the list, maybe future me will be smarter and figure it out.

**Comment by swharden** [comment]
> I had a look but and I assume something is being rounded unintentionally but I can't for the life of me seem to find where. I think I'll add it to the list, maybe future me will be smarter and figure it out.

Okay cool. @Resonanz thanks for reporting this! I'll close this issue and we can track progress on #457
