### ISSUE TITLE
Changing the color of the value's above the bars

### ISSUE THREAD

**Issue by WillemWever** [swharden/ScottPlot#483]
I would like to change the color of the text from the values above the bars, which appears after enabling showValues on the bars, like described in the following chapter: https://swharden.com/scottplot/cookbooks/4.0.36/#plottypes-bar-show-values-above-bars

This is what I have tried:
- Reviewed the ScottPlot Cookbook.
- Reviewed the ScottPlot Demo.
- Tried to find the option under the metadata from Plot.

**Comment by swharden** [comment]
Hey @WillemWever, thanks for asking this question!

I took a look and found that black color is hard-coded here (and valueTextBrush is not a public property).

https://github.com/swharden/ScottPlot/blob/0684ae790b740e5ca85cbcca6206ec313e075bf5/src/ScottPlot/plottables/PlottableBar.cs#L89

I'll modify this file to make it easier to customize, then add a cookbook example showing how to do this. It might take a day or two, but it'll make it into the next NuGet release 👍

**Comment by swharden** [comment]
There's now a simple way to customize the color:
```cs
plt.PlotBar(xs, ys, showValues: true, valueColor: Color.Magenta);
```

![image](https://user-images.githubusercontent.com/4165489/86662617-e0873100-bfba-11ea-85b1-1ea9a66ac9bf.png)

To further customize the font or font size, the bar plot returned now has public properties to allow this:
```cs
var barPlot = plt.PlotBar(xs, ys, showValues: true);
barPlot.valueTextFont = new Font("Arial", 12);
```

This will be in ScottPlot 4.0.38

**Comment by WillemWever** [comment]
Hi Swharden,

It's working really well. Thank you for being able to help so quickly. Awesome!

Best Regards,

Willem
