### ISSUE TITLE
improve pie chart alignment

### ISSUE THREAD

**Issue by WillemWever** [swharden/ScottPlot#484]
I would like allign the piechart to the left of the PNG instead of the centre.

This is what I have tried:

Reviewed the ScottPlot Cookbook.
Reviewed the ScottPlot Demo.
Reviewed the Upcoming Changes.
Tried to find the option under the metadata from Plot.

In the preview file you can see what is going wrong if it's centered:
![preview](https://user-images.githubusercontent.com/14298928/86766168-6f8f5a00-c04a-11ea-80a9-d8afd754ec9e.png)

There is a lot of empty space on the left side.

**Comment by swharden** [comment]
Hey @WillemWever, thank you for this suggestion! At first it wasn't obvious why this is useful, because if you just make a square ScottPlot it will be perfectly aligned. Indeed, I would imagine most circle charts should be displayed in square windows. However, when considering legend placement is offset to the right, it makes sense that a rectangular window is desired. In this situation, a left-aligned pie chart makes sense. I'll look into this and add this feature in an upcoming release!

**Comment by Benny121221** [comment]
@WillemWever For the timebeing you can use this:

```cs
plt.PlotPie(values);
plt.Axis(-0.33, 1, -1, 1);
```

These numbers work for a 600x400 plotting window (or anything with a 3:2 aspect ratio). You will likely need to tweak them for different window sizes.

**Comment by WillemWever** [comment]
Thanks Benny and Swharden,

I'll look forward to the upcoming release. For now, Benny's interim solution is working well:

![foutmeldingenPerApplicatie](https://user-images.githubusercontent.com/14298928/87008706-7215bf00-c1c4-11ea-91cb-00d22153d967.png)

I used `plt.Axis(-0.5, 1, -1.1, 1.1);` for a 750 x 450 plotting window.

Nice work!

**Comment by swharden** [comment]
... it also seems that pie charts get messed up when plots are very narrow.

@Benny121221 don't dive into the code to fix these issues - I can get to it today. Thanks for you useful response earlier!

![image](https://user-images.githubusercontent.com/4165489/87234969-86b0ad80-c3a4-11ea-846c-50ea35c97ddc.png)

**Comment by swharden** [comment]
I actually coded this in... but then realized left-aligned pie charts don't even make sense 😆 The more I mess with rendering, the more I realize `AxisAuto()` just wants to center everything 🙈 

I think @Benny121221's suggestion of adjusting the Axis to move the pie chart around is probably actually the best solution here...

![image](https://user-images.githubusercontent.com/4165489/87235178-54547f80-c3a7-11ea-9eff-6b7b29247432.png)
