### ISSUE TITLE
Obey LineStyle in legend

### ISSUE THREAD

**Issue by Benny121221** [swharden/ScottPlot#488]
**What can we do to make ScottPlot better?**
Currently the legend always displays with the solid line style, even if the plottable uses a different one (e.g. dashed).

Does your proposed feature allow users to do new things in source code? If so, show us how you'd like to be able to use the new feature:

No, it just changes existing behaviour

Check the ScottPlot Roadmap to see if your feature is already planned for an upcoming release:
https://github.com/swharden/ScottPlot/blob/master/dev/roadmap.md

**Comment by swharden** [comment]
I like this idea! I think it even came up before but I'm not sure why we didn't do it then 🤔 

Previous discussion may have been about respecting lineWidth in the legend. There is now an argument for `fixedLineWidth` which I guess solved that issue, so the solution to this issue would involve making a new argument like `respectLineStyle`or something...

**Comment by Benny121221** [comment]
My apologies, it appears that the legend _does_ obey the linestyle for most plottables. The exception is the signal plottables, which is where I noticed it.

**Comment by swharden** [comment]
Clarifying the issue, signal plot line style is not reflected in the legend 

```cs
var plt = new ScottPlot.Plot(600, 400);
plt.PlotSignal(DataGen.Sin(10), label: "sin", color: Color.Red, lineStyle: LineStyle.Dash, lineWidth: 1);
plt.PlotSignal(DataGen.Cos(10), label: "cos", color: Color.Blue, lineStyle: LineStyle.Dot, lineWidth: 3, markerSize: 10);
plt.Legend();
```

![image](https://user-images.githubusercontent.com/4165489/89719636-5276df80-d998-11ea-92f0-c6b6448cd801.png)

**Comment by swharden** [comment]
Fixed! Will be in next release. Thanks for noting this @Benny121221 

![image](https://user-images.githubusercontent.com/4165489/89719732-6e2eb580-d999-11ea-8591-aadc1486f49f.png)

**Comment by Benny121221** [comment]
I couldn't replicate this issue

![image](https://user-images.githubusercontent.com/8635304/89719751-e6d94600-d988-11ea-99df-72b08d7a2c6c.png)

**Comment by Benny121221** [comment]
ecc1ad4 well it looks like #489 is no longer relevant, I'll close it
