### ISSUE TITLE
WpfPlot mouse wheel zoom with custom DPI

### ISSUE THREAD

**Issue by nashilnik** [swharden/ScottPlot#490]
**Describe the bug**
If the screen scaling is set to a custom value (anything but 100%) the zoom point is wrong when you zoom with mouse wheel.

**To Reproduce**
1. Set screen scaling to 125%
2. Launch any plot in the demo
3. Zoom to a point using mouse wheel
4. Verify that the zoom point is wrong

**Screenshots**
![wJbP2BIPlh](https://user-images.githubusercontent.com/17297106/87657826-056e6780-c764-11ea-8d96-7e93f6251d4b.gif)

**Fix**
To fix it you need to change https://github.com/swharden/ScottPlot/blob/404105e5d7ae8399b2e40e9bd64b246d3b3b80dd/src/ScottPlot.WPF/WpfPlot.xaml.cs#L448
From
`var mousePixel = GetPixelPosition(e);`
to
`var mousePixel = e.GetPosition(this);`

**Comment by nashilnik** [comment]
The same happens with "draw rectangle to zoom".
![D3cWVrya3E](https://user-images.githubusercontent.com/17297106/87659194-e07af400-c765-11ea-9c02-bf36aeae011b.gif)

I suppose, the fix is the same, you need to add 
`mouseLocation = e.GetPosition(this);`
before this line https://github.com/swharden/ScottPlot/blob/404105e5d7ae8399b2e40e9bd64b246d3b3b80dd/src/ScottPlot.WPF/WpfPlot.xaml.cs#L382

**Comment by swharden** [comment]
Fixed it! Thanks @nashilnik, and sorry for the delay here. The zoom-to-cursor was an easy fix but the rectangular zoom issue took a little more head scratching. Anyway, all is well now and I'll push a new package to NuGet later tonight. Thanks again!

Scott
