### ISSUE TITLE
layout not rendered properly

### ISSUE THREAD

**Issue by cchiu827** [swharden/ScottPlot#491]
Hi Scott,
Thanks for the awesome library.
I am trying to create more space for x-axis scale label using the layout(xScaleHeight:100) property when turn the x scale label to 90 degree. The chart shows up with no layout padding when first running it but when clicking the refresh button to render it again, the layout padding is correct. I use WPF for the testing.
**To Reproduce**
I called the button click event when starting up but the chart didn't render properly. When the button was clicked, the chart rendered properly with the space for x scale.

```cs
//xaml.cs part
public MainWindow()
        {
            InitializeComponent();
            Button_Click(null, null);
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            double[] dataX = new double[] { 1, 2, 3, 4, 5 };
            double[] dataY = new double[] { 1, 4, 9, 16, 25 };

            sPlot.plt.PlotScatter(dataX, dataY, label: "series 1");
            sPlot.plt.AxisAuto();

            sPlot.plt.XTicks(new double[] { 1, 2, 3, 4, 5 }, new string[] { "Label 123456789", "Label 2", "Label 3", "Label 4", "Label 5" });

            // titles
            sPlot.plt.Title("Plot Title");
            sPlot.plt.XLabel("Horizontal Axis");
            sPlot.plt.YLabel("Vertical Axis");

            sPlot.plt.Ticks(xTickRotation: 90);
            sPlot.plt.Layout(yLabelWidth: 20, titleHeight: 50, xLabelHeight: 100, y2LabelWidth: 20, xScaleHeight: 100);
            sPlot.Configure(recalculateLayoutOnMouseUp: false);

            sPlot.Render();           
        }
```
```cs
// xaml
 <Grid>
        <Grid.RowDefinitions>
            <RowDefinition/>
            <RowDefinition Height="auto"/>
        </Grid.RowDefinitions>

        <WpfPlot Name="sPlot" Grid.Row="0" BorderBrush="Red" BorderThickness="1"/>
        <Button Content="Refresh" Grid.Row="1" Click="Button_Click"/>        
    </Grid>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/30455670/87728481-03ae9f00-c778-11ea-8a7d-d81258691407.png)
![image](https://user-images.githubusercontent.com/30455670/87728573-3193e380-c778-11ea-99e7-d2795bc714bd.png)

**Comment by swharden** [comment]
Hey @cchiu827 thanks for opening this issue! Sorry it too so long for me to get back to you.

The problem is that the layout cannot be properly calculated before the control is displayed because it doesn't know how big its final size will be. So, don't do this:

```cs
public MainWindow()
{
    InitializeComponent();
    Button_Click(null, null);
}
```

Instead, just this inside your `<Window>`:

```xaml
<Window ... Loaded="Button_Click">
```

This will cause the layout method to be called after the window is fully loaded, fixing your issue! 👍

**Comment by cchiu827** [comment]
Hi Scott,

Thanks for the reply. It works after moving to loaded event.

Awesome. Many thanks.
Chao-An

Scott W Harden <notifications@github.com> 於 2020年8月9日 週日 下午1:14寫道：
