### ISSUE TITLE
Heatmap temperature bar not displaying correctly

### ISSUE THREAD

**Issue by Resonanz** [swharden/ScottPlot#492]
**Describe the bug**
Heatmap temperature bar is displayed under the plot area. 

I have an application that has multiple tabs, thus the TabItem. The temperature bar is mostly hidden -- you can see the top of it poking above the black border line in the image below. I have messed around with the grid Width but the bar remains hidden as shown.

UPDATE: If I add `wpfHeatMapPlot.Render();` as shown below, then is displays correctly. The call to Render however is not mentioned in the Cookbook for the heatmaps, perhaps because all heatmaps were being piped to a PDF file rather than to the screen window.

```            <TabItem Name="HeatMap" Header="Heat map">
                <WrapPanel>
                    <Grid Width="800" Height="700" Margin="10,10,10,10" Background="WhiteSmoke">
                        <WpfPlot Name="wpfHeatMapPlot" />
                    </Grid>
                    <Grid x:Name="bt_Plot" Width="300" Height="80" >
                        <Button x:Name="bt_plotme" Content="Plot Heat Map" Click="Button_PlotHeat"/>
                    </Grid>
                </WrapPanel>
```

```
        public void PlottyInitializeHeatMap()
        {
            var plt = new ScottPlot.Plot(600, 400);
        }
```

```
        public void PlottyHeatMap(HeatMapDataStor dataStor)
        {
            wpfHeatMapPlot.plt.Title("Viscosity heat map", fontSize: 20);
            wpfHeatMapPlot.plt.XLabel("Well plate columns 1-12", fontSize: 16, bold: true);
            wpfHeatMapPlot.plt.YLabel("Well plate rows A-H", fontSize: 16, bold: true);
            wpfHeatMapPlot.plt.PlotHeatmap(dataStor.Intensities);
            >>> UPDATE wpfHeatMapPlot.Render();
        }
```

**Screenshots**
![image](https://user-images.githubusercontent.com/6218191/87887918-52f91600-ca7d-11ea-9889-239da0190101.png)

**Comment by swharden** [comment]
thanks for reporting this @Resonanz! I added it to the list at the top of #457 and, it's closed right now because it's not actively being worked on, but if/when work resumes on this front this issue will be addressed then
