### ISSUE TITLE
minRenderIndex, maxRenderIndex doesn't seem to work with PlotSignalXY

### ISSUE THREAD

**Issue by envine** [swharden/ScottPlot#493]
I am trying to limit the data points shown in the plot.  

As I see in the demo, I confirmed that minRenderIndex, maxRenderIndex works well with PlotSignal.
```csharp
double[] data = DataGen.RandomWalk(rand, 100_000);
formsPlot1.plt.PlotSignal(data, minRenderIndex: 4000, maxRenderIndex: 5000);
```
However, when I try to do the same things with PlotSignalXY, it doesn't seem to work.
All 100_000 points of data are shown in the plot.
```csharp
double[] x = DataGen.Consecutive(100_000);
double[] data = DataGen.RandomWalk(rand, 100_000);
formsPlot1.plt.PlotSignalXY(x, data, minRenderIndex: 4000, maxRenderIndex: 5000);
```
Is there a way to limit the range of data points with the array index supplied to PlotSignalXY?

**Comment by swharden** [comment]
Hey @envine, thanks for reporting this!

I'll ask over on #374 if this was intended to be supported or not. I'll either add support for it, or remove the arguments and decide not to support it (depending on what they say over there)

**Comment by StendProg** [comment]
HI there,
It seems it is not difficult to fix, I'll see what i can do.

**Comment by swharden** [comment]
Hi @StendProg, thank you so much for looking into this! I took a quick look at your PR #495 and it's looking great. 

I'm pretty busy over the next few days with work, but I plan to return to ScottPlot later this week or weekend to incorporate this change and address some of the other issues, then release a new version on NuGet.

Thanks too for your input on #494! I'd like to engage in that conversation when I have a little more time to study the topic better.

Best,
Scott

**Comment by swharden** [comment]
Thank you so much @StendProg for this excellent improvement to SignalXY! I can tell the rework in #500 was extensive and very thoughtfully implemented. I will merge it in now, and release this on NuGet later today. Thanks @envine for raising this issue!

```cs
Random rand = new Random(0);
double[] xs = ScottPlot.DataGen.Consecutive(100_000);
double[] ys = ScottPlot.DataGen.RandomWalk(rand, 100_000);
var plt = new ScottPlot.Plot(500, 350);
plt.PlotSignalXY(xs, ys, minRenderIndex: 4000, maxRenderIndex: 5000);
```

limits ignored (original behavior) | limits respected (new behavior)
---|---
![image](https://user-images.githubusercontent.com/4165489/89741252-b6afa700-da5d-11ea-8740-436380cc690a.png)|![image](https://user-images.githubusercontent.com/4165489/89741224-8e27ad00-da5d-11ea-8e7d-7896a11f1cc3.png)
