### ISSUE TITLE
Is there a function to get an X value, given a Y value?

### ISSUE THREAD

**Issue by antithing** [swharden/ScottPlot#497]
Hi, and thank you very much for making this code available.

I have a line that is plotted using X and Y values, like this:

![image](https://user-images.githubusercontent.com/11506730/89186538-d7768900-d593-11ea-9acf-0562e773054f.png)

Is there a function existing that will give me the X value from a new given Y value?

For example, in the image above, given the Y value 150, can i calculate the X value 27.5 using code?

Thank you.

**Comment by StendProg** [comment]
Hi @antithing,
You can find nearest point to given `Y` value. For that you need plot `PlottableScatterHighlight` and then call it's member `GetPointNearestY(double y)`. 
If you want interpolate between existing points, there is no solution for that in `ScottPlot` (library have spline interpolation, but i think it's too complex for your task ). For linear interpolation you can do something like that:
```c#
            double yValue = 150;
            double[] xArray = { 1, 2, 3, 4, 5, 6, 7 };
            double[] yArray = { 0, 1, 2, 100, 200, 200, 0 };
            var xyPairs = xArray.Zip(yArray, (x, y) => (x, y));
            var pointsPairs = xyPairs.Zip(xyPairs.Skip(1), (f, s) => (f, s));
            var xValues = pointsPairs.Where(pair => (pair.f.y <= yValue && pair.s.y >= yValue) 
                                                    || (pair.f.y >= yValue && pair.s.y <= yValue))
                                     .Select(pair => 
                                                    {
                                                        if ((pair.s.y - pair.f.y) == 0)
                                                            return pair.f.x;
                                                        return (yValue - pair.f.y) / (pair.s.y - pair.f.y) * (pair.s.x - pair.f.x) + pair.f.x;
                                                    });
            Assert.AreEqual(4.5, xValues.First());
            Assert.AreEqual(6.25, xValues.Skip(1).First()); 
```

**Comment by antithing** [comment]
Thank you! much appreciated.
