### ISSUE TITLE
What is the correct way to update vLines with live data?

### ISSUE THREAD

**Issue by antithing** [swharden/ScottPlot#498]
I am trying to use a vline to show the current data position on a line graph plot.

Following the mouse tracker example, I have:

```
  ScottPlot.PlottableVLine vLine;

        public FormZoomPlot()
        {
                       // plot the data array only once
            signalPlot = ZoomPlot.plt.PlotSignalXY(dataX, dataY);
           vLine = ZoomPlot.plt.PlotVLine(0, color: System.Drawing.Color.Red, lineStyle: ScottPlot.LineStyle.Dash);


        }

```
Then, on a callback, I have:
```

 public void ProcessingEventHandler(object sender, ProcessingEventArgsFrames args)
        {            
                vLine.position = val;

        //   ZoomPlot.plt.PlotVLine(x: val, color: System.Drawing.Color.Red, lineStyle: ScottPlot.LineStyle.Dash);
            ZoomPlot.Dispatcher.BeginInvoke((Action)(() => { ZoomPlot.Render(skipIfCurrentlyRendering: true); }));
            
        }
```

updating the line position as above does not show the line on the Plot.
Using this line instead:

`          ZoomPlot.plt.PlotVLine(x: val, color: System.Drawing.Color.Red, lineStyle: ScottPlot.LineStyle.Dash);
`

Does plot the line, but obviously adds a new line every time the function is called.

What is the correct way to do this?

Thanks!

**Comment by StendProg** [comment]
Hi @antithing 
That's correct way to update `position` and call `Render()`. Mouse tracker demo work correct.
Maybe you `val` goes outside of axis limits and visible area? Try to add `recalculateLayout` flag to your `Render` call:
`Render(skipIfCurrentlyRendering: true, recalculateLayout: true)`

**Comment by antithing** [comment]
Hi, thanks for getting back to me!
The val variable is correct, as it works when I use:

`ZoomPlot.plt.PlotVLine(x: val, color: System.Drawing.Color.Red, lineStyle: ScottPlot.LineStyle.Dash`);

To draw the line. (it draws the line every callback however, instead of replacing a single line) 
Its weird. Is there anything else I might be doing wrong?

The mouse tracker demo works great, so I must be missing something!

**Comment by StendProg** [comment]
Sorry have no idea. `PlottableVLine.Render()` code very simple and should work.
Can you share a bit more code to reproduce this bug?

**Comment by antithing** [comment]
Ah, found it! Unsurprisingly, it was my error. I was calling ` ZoomPlot.plt.Clear();`, so I needed to run:

`vLine = ZoomPlot.plt.PlotVLine(0, color: System.Drawing.Color.Red, lineStyle: ScottPlot.LineStyle.Dash);`

again.

Thank you for your time, and for this awesome lib.
