### ISSUE TITLE
Option for controls to always render with anti-aliasing off

### ISSUE THREAD

**Issue by RachamimYaakobov** [swharden/ScottPlot#499]
**Describe the bug**
In [UserControl_MouseUp](https://github.com/swharden/ScottPlot/blob/404105e5d7ae8399b2e40e9bd64b246d3b3b80dd/src/ScottPlot.WPF/WpfPlot.xaml.cs#L436) and in [UserControl_MouseWheel](https://github.com/swharden/ScottPlot/blob/404105e5d7ae8399b2e40e9bd64b246d3b3b80dd/src/ScottPlot.WPF/WpfPlot.xaml.cs#L458) whenever `Render` with lowQuality == `false`, and nowhere set it to `true`

And the same problem exists in Winforms.

**To Reproduce**
Should provide an option to configure in `WpfPlot.Configure`

**Comment by swharden** [comment]
Hey @RachamimYaakobov, thanks for raising this issue! I want to make sure I understand your suggestion. 

Currently you can tell the user control not to use anti-aliasing while dragging so performance can be increased. This is the default behavior.

```cs
wpfPlot1.Configure(lowQualityWhileDragging = true);
```

However, when the user does a mouse up, the plot is drawn in high quality. It sounds like you'd like to be able to override this behavior, and always render in low quality. Is this a good description of your suggestion? 

Would adding an argument like this be a solution?
```cs
wpfPlot1.Configure(lowQualityAlways = true);
```

Also, a solution which may work now is something like this:
```cs
wpfPlot1.plt.AntiAlias(figure: false, data: false, legend: false);
```
More information: https://swharden.com/scottplot/cookbooks/4.0.38/#customize-figure-anti-aliasing

Looking forward to hearing your thoughts!
Scott

**Comment by swharden** [comment]
Just made the change and will upload a new version to NuGet shortly, then this configuration will work:

```cs
formsPlot1.Configure(lowQualityAlways = true);
```

```cs
wpfPlot1.Configure(lowQualityAlways = true);
```

Thanks for opening this issue @RachamimYaakobov!
