### ISSUE TITLE
Audio Monitor FFT Exception

### ISSUE THREAD

**Issue by Tiuipuv** [swharden/ScottPlot#5]
When swapping from Stereo Mix to microphone, it throws the following exception:
![c sharp exception](https://user-images.githubusercontent.com/23466445/53059791-c4dec180-347d-11e9-9385-c1c11bf5bbf4.png)

**Comment by swharden** [comment]
Thanks for bringing my attention to this! I'll fix it tonight, most likely using the sound card selection form from a project I made more recently: https://github.com/swharden/SoundCardECG

**Comment by swharden** [comment]
It's possible that connecting to a weird sound card could crash the application. Now sound cards don't automatically start "listening" until you manually select a card and hit the start button. 

**Want do see if that works better for you new? New compiled demos are in:**
https://github.com/swharden/ScottPlot/tree/master/demos/AudioMonitor/compiled/
