### ISSUE TITLE
4.0.39 published to different WPF package

### ISSUE THREAD

**Issue by Benny121221** [swharden/ScottPlot#502]
**Describe the bug**
`ScottPlot.WPF` received no update to 4.0.39:

![image](https://user-images.githubusercontent.com/8635304/89743561-81a55380-da61-11ea-8bb3-ff081e768569.png)

However, there's a new package, `ScottPlot.WPF.NUGET`:

![image](https://user-images.githubusercontent.com/8635304/89743567-9255c980-da61-11ea-90b4-74a0fe337ff3.png)

Is this intentional? Ought I to shift my projects to the new package? Or is this just a mistake?

**To Reproduce**
Go to nuget.org

**Screenshots**
If applicable, add screenshots to help explain your problem

**Comment by swharden** [comment]
Microsoft takes ~20 minutes to update their webpage after a new package is accepted

It's there now https://www.nuget.org/packages/ScottPlot/

Similarly, their download stats take 1-2 days to update! I know this because I poll it every hour 😈  https://swhardendev.z13.web.core.windows.net/

**Comment by swharden** [comment]
oh dang, you're right! dang, somehow it's name changed 😝 

![image](https://user-images.githubusercontent.com/4165489/89743657-31cf8800-da73-11ea-9637-f796e9940c4d.png)

**Comment by swharden** [comment]
I added `AssemblyName` to its csproj file. I guess absent this element it uses the filename as the assembly name and that becomes the package name 🤔 

https://github.com/swharden/ScottPlot/blob/bdbab67052452d9f4b1dd161ba0e9ee4e96f7380/src/ScottPlot.WPF/ScottPlot.WPF.NUGET.csproj#L6

I think it's resolved now and will take a few minutes to update on the website... Thanks for reporting it!
