### ISSUE TITLE
Performance issue with large amount of data points

### ISSUE THREAD

**Issue by FadyDev** [swharden/ScottPlot#508]
Hello, 

I face an issue when it comes to plot a timeseries that has a large amount of data points (over 100000 data points).
The UI is blocked for about 30-40 seconds, user cannot interact with it and with the whole App till Scottplot finishes the plotting.
Is there any acceleration mechanisms that could be used to prevent the WinForm window from being frozen till after plotting?

Thanks in advance for your help.

Br,
Fady

**Comment by swharden** [comment]
Hi @FadyDev,

If you are plotting a large number of points, ensure you are using one of the Signal plot types. Signal, SignalXY, or SignalConst all have their strengths. These plot types are optimized for speed and allow real-time interaction with tens of millions of data points. Their usage is demonstrated in the ScottPlot cookbook, for example https://swharden.com/scottplot/cookbooks/4.0.38/#plottypes-signal-5m-points-signal

If this doesn't solve your problem let me know and we can re-open this issue!
