### ISSUE TITLE
custom marker shapes

### ISSUE THREAD

**Issue by bukkideme** [swharden/ScottPlot#52]
Recently plt.PlotScatter() only gives option to change size and color of the markers. What about giving extra options, like filled and none filled markers with different shapes? Using different markers and not only colors greatly increases the readability of scientific charts/graphs.
I used a lot [GLE](http://glx.sourceforge.net/index.html) in the past, which is a scripting language for vector graphic plots. Maybe it can give you some good inspiration during further dev of ScottPlot? I link here the optional marker types in this environment: [http://glx.sourceforge.net/examples/other/wallx.html](http://glx.sourceforge.net/examples/other/wallx.html)

Off topic in this very feature request, but since I mentioned GLE, I would like to ask your opinion about a possible interfacing (any kind or level) between ScottPlot and GLE? Just to explain what I think of, see my very primitive past attempt to do something similar using LabVIEW: [https://forums.ni.com/t5/Community-Documents/Interface-to-Graphics-Layout-Engine-GLE-to-create-publication/ta-p/3592762?profile.language=en](https://forums.ni.com/t5/Community-Documents/Interface-to-Graphics-Layout-Engine-GLE-to-create-publication/ta-p/3592762?profile.language=en)

**Comment by swharden** [comment]
I really like this idea! The matplotlib library is a good example of the type of markers we could support: https://matplotlib.org/3.1.1/api/markers_api.html

I’ll get this started in the next day or two by creating a class for handling markers (I’ll just add filledCircle and filledSquare but make it easy to add new ones) and I’ll add a markerStyle argument to PlotPoint() and PlotScatter(). 

Once implemented we should probably draw these unique markers in the legend too.

**Comment by bukkideme** [comment]
Thanks! And it is good you did not forget that the Legend should show the corresponding markers too.

**Comment by swharden** [comment]
I created a markerShape argument: 

https://github.com/swharden/ScottPlot/blob/585d4c2adb009b6fe4acb9ada7679a88d73ae890/demos/ScottPlotCookbook/Recipes.cs#L137-L140

![01f_Custom_Marker_Shapes](https://user-images.githubusercontent.com/4165489/61911330-31fef300-af05-11e9-915a-812745050cde.png)

Marker shape definitions and drawing code are confined to ([Markers.cs](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/Markers.cs)). This means new marker shapes can be added by editing this one file. 

I modified the legend demo to also have a drop-down menu for markers. As new shapes are added to ([Markers.cs](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/Markers.cs)) the legend demo program will display them automatically.

I got it started with 4 shapes, but if someone is inspired to add more the [matplotlib shapes](https://matplotlib.org/3.1.1/api/markers_api.html) are a good reference. We don't have to add all of those (some are pretty funky), but having a dozen easy-to-draw shapes would be great.

@Padanian do you want to add a few shapes and also update the legend to draw markers? (#39, #45)

![image](https://user-images.githubusercontent.com/4165489/61910556-0975f980-af03-11e9-9c2c-54a2b97d72b8.png)

**Comment by Padanian** [comment]
Of course.

**Comment by Padanian** [comment]
![immagine](https://user-images.githubusercontent.com/7769348/61942124-147b6900-af99-11e9-8cb7-311f2ff955ff.png)

Hope you like it

**Comment by swharden** [comment]
Thanks @Padanian this looks awesome!

The markers aren't matching up with the right labels which was easy to overlook when we practiced with random data... I'll see if I can fix that real quick

![image](https://user-images.githubusercontent.com/4165489/61994647-39c8af80-b04b-11e9-8852-95f1bc1004b7.png)

**Comment by swharden** [comment]
Got it! 77036a16bf7f02c913e34ab4ca3a8176be768ac9

**Comment by swharden** [comment]
All marker shapes are now displayed in the cookbook. It's a nice use of the legend.
https://github.com/swharden/ScottPlot/tree/master/cookbook#all-marker-shapes

![image](https://user-images.githubusercontent.com/4165489/62824987-8c898780-bb72-11e9-8ae4-0fe2cfd7124d.png)
