### ISSUE TITLE
Colored background of plot area for WPF plots

### ISSUE THREAD

**Issue by Scrat9876** [swharden/ScottPlot#520]
**I would like to:**
Color plot background of a WPF plot.

**This is what I have tried:**
Issuing a wpfPlot1.plt.Colorset(Colorset.OneHalfDark); has no effect.  I have also tried to change the internal ScottPlot rendering just to see something other than white. No joy:)

What am I missing?

Thanks,
Mark

**Comment by swharden** [comment]
Hi @Scrat9876, check out the arguments available with `wpfPlot1.plt.Style()`.

You can pass in individual colors:
https://swharden.com/scottplot/cookbooks/4.0.38/#customize-figure-background-colors

or pass in a Style which contains a collection of pre-selected colors which match:https://swharden.com/scottplot/cookbooks/4.0.38/#customize-plotstyles-plot-style-seaborn

I see where you got confused by `Plot.Colorset()` method. A color set is like a color palette... but I recognize this name makes it seem like this is how you "set the color". I'll consider improving this name in ScottPlot 4.1!

Let me know if this does the trick

**Comment by stefan7189** [comment]
> wpfPlot1.plt.Style(figBg: Color.LightBlue);
> wpfPlot1.plt.Style(dataBg: Color.LightYellow);
> ```
> 
> https://swharden.com/scottplot/cookbooks/4.0.38/#customize-figure-background-colors
> 

I have just tried that and it won't work. 

`            double[] dataX = new double[] { 1, 2, 3, 4, 5 };
            double[] dataY = new double[] { 1, 4, 9, 16, 25 };
            WpfPlot1.Plot.AddScatter(dataX, dataY);

            WpfPlot1.plt.Style(figBg: Color.FromRgb(222,27,27));
            WpfPlot1.plt.Style(dataBg: Color.FromRgb(27, 222, 157));
            `WpfPlot1.Refresh();``

This is my code and error says: "The best overload for 'Style' does not  a parameter named dataBg"...

**Comment by swharden** [comment]
Hi @stefan7189, 

It looks like that code/documentation is for an old version of ScottPlot. 

This code example can help you achieve your desired effect:

```cs
WpfPlot1.plt.Style(figureBackground: Color.FromRgb(222,27,27));
WpfPlot1.plt.Style(dataBackground: Color.FromRgb(27, 222, 157));
```

**Comment by swharden** [comment]
@stefan7189 also note that there are collections of predefined styles you may find useful:
https://scottplot.net/cookbook/4.1/category/style/
