### ISSUE TITLE
How to print a ScottPlot

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#524]
How do you print a plot? How do you print a bitmap with C#? Document this somewhere.

**Comment by swharden** [comment]
This isn't fancy, but it works

![image](https://user-images.githubusercontent.com/4165489/91903211-df981600-ec70-11ea-998e-cad9ba150179.png)

```cs
using System;
using System.Drawing.Printing;
using System.Windows.Forms;

namespace ScottPlotPrint
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
            formsPlot1.plt.PlotSignal(ScottPlot.DataGen.Sin(51));
            formsPlot1.Render();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            using (var pd = new PrintDocument())
            {
                pd.PrintPage += new PrintPageEventHandler(pd_PrintPage);
                pd.Print();
            }
        }

        private void pd_PrintPage(object sender, PrintPageEventArgs e)
        {
            formsPlot1.plt.Resize(e.MarginBounds.Width, e.MarginBounds.Height);
            e.Graphics.DrawImage(formsPlot1.plt.GetBitmap(), e.MarginBounds.Left, e.MarginBounds.Top);
        }
    }
}
```

**Comment by swharden** [comment]
The code above fires-up your printer immediately without a dialog.\
This code shows a print preview dialog and also launches a printer configuration dialog.\
In practice this is probably best handled by two separate buttons.

PrintPreviewDialog | PrintDialog 
---|---
![image](https://user-images.githubusercontent.com/4165489/91904370-d0b26300-ec72-11ea-8848-136d0e51f40b.png) | ![image](https://user-images.githubusercontent.com/4165489/91904390-d9a33480-ec72-11ea-9bc2-583120ed9cb2.png)



```cs
using System;
using System.Drawing.Printing;
using System.Windows.Forms;

namespace ScottPlotPrint
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
            formsPlot1.plt.PlotSignal(ScottPlot.DataGen.Sin(51));
            formsPlot1.Render();
        }

        private void PrintPage(object sender, PrintPageEventArgs e)
        {
            formsPlot1.plt.Resize(e.MarginBounds.Width, e.MarginBounds.Height);
            e.Graphics.DrawImage(formsPlot1.plt.GetBitmap(), e.MarginBounds.Left, e.MarginBounds.Top);
        }

        private void Print_Click(object sender, EventArgs e)
        {
            PrintDocument pd = new PrintDocument();
            pd.PrintPage += new PrintPageEventHandler(PrintPage);

            new PrintPreviewDialog { Document = pd }.ShowDialog();

            if (new PrintDialog { Document = pd }.ShowDialog() == DialogResult.OK)
                pd.Print();
        }
    }
}
```

**Comment by swharden** [comment]
This code shows improved styling and has separate Print and Print Preview buttons

![image](https://user-images.githubusercontent.com/4165489/91905109-03109000-ec74-11ea-9945-31422e51d5c4.png)

```cs
using System;
using System.Drawing;
using System.Drawing.Printing;
using System.Windows.Forms;

namespace ScottPlotPrint
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
            formsPlot1.plt.PlotSignal(ScottPlot.DataGen.Sin(51));
            formsPlot1.Render();
        }

        private void PrintPage(object sender, PrintPageEventArgs e)
        {
            formsPlot1.plt.Resize(e.MarginBounds.Width, (int)(e.MarginBounds.Width * .5));
            formsPlot1.plt.Style(figBg: Color.White);
            e.Graphics.DrawImage(formsPlot1.plt.GetBitmap(), e.MarginBounds.Left, e.MarginBounds.Top);
        }

        private void Print_Click(object sender, EventArgs e)
        {
            var pd = new PrintDocument();
            pd.PrintPage += new PrintPageEventHandler(PrintPage);
            if (new PrintDialog { Document = pd }.ShowDialog() == DialogResult.OK)
                pd.Print();
        }

        private void PrintPreview_Click(object sender, EventArgs e)
        {
            var pd = new PrintDocument();
            pd.PrintPage += new PrintPageEventHandler(PrintPage);
            new PrintPreviewDialog { Document = pd }.ShowDialog();
        }
    }
}
```

**Comment by Benny121221** [comment]
This might make sense in the right-click context menu? Copy to clipboard is in there so it seems like a good idea.

**Comment by swharden** [comment]
@Benny121221 you're right, a "print" and "print preview" option would fit nicely in that list!

I'm pretty busy with #521 these days so I'll close this issue for now (since the answer was found and documented here) but I added your idea to the list on #412 so I can swing back around to it when things stabalize again.

Thanks for the suggestion!

**Comment by AteCoder** [comment]
[rawdatatremor.pdf](https://github.com/swharden/ScottPlot/files/5192037/rawdatatremor.pdf)
finally i got a chance to check rendering the image onto the print document.  As far as I can tell, the image (see attached file) is rendered in screen resolution.

**Comment by swharden** [comment]
> As far as I can tell, the image (see attached file) is rendered in screen resolution

Hi @AteCoder, 

Regarding this portion of the code above:

```cs
private void PrintPage(object sender, PrintPageEventArgs e)
{
	formsPlot1.plt.Resize(e.MarginBounds.Width, (int)(e.MarginBounds.Width * .5));
	formsPlot1.plt.Style(figBg: Color.White);
	e.Graphics.DrawImage(formsPlot1.plt.GetBitmap(), e.MarginBounds.Left, e.MarginBounds.Top);
}
```

Note that `formsPlot1.plt.Resize()` takes two integers, `width` and `height`. The size of the image you print is defined by these two numbers. In this code example those numbers are scaled to the size of the sheet of paper (with paper margins accounted for), but you can set the image to other sizes by changing these numbers.

**Comment by AteCoder** [comment]
Right. I printed four plots each onto a 'recrtangle' defined in the page and scaled to that rectangle.

Notice that the images on the printer have shadows seemingly reflecting the working of the image refered filling in for the different DPI.  Also note the differences between the image printer from the plot to the one printed from the screen shot.

Perhaps this is an issue of image resolution. I am out of my elements on this.

That said, my previous printing code drew and wrote into the graphic context, which rendered the image at the printer DPI yielding super fine results. But I that seems to entail a departure from the current design, right?

At the same time, it would seem entirely reasonable to assume that rendering a image onto the printer graphics should be as good as to the screen. Perhaps there are some hidden gems we r yet to discover.

How is version 5 comming along?
________________________________

**Comment by swharden** [comment]
Ah, I see the problem now. When plotting several plots, the legends of the upper ones seem to be cut-off.

![image](https://user-images.githubusercontent.com/4165489/93022007-5fe54200-f5b4-11ea-96f8-a524ebb6516e.png)

Since the lower-right legend is not cut-off, I'm inclined to believe this problem relates to how you calculate the location and dimensions of the rectangles you wish to place on the page. We can eliminate a lot of complexity in this troubleshooting phase by removing ScottPlot from the loop entirely: What does the page look like when you just draw 4 rectangles? If there's a size/location problem on your end, that would probably reveal itself as rectangles that overlap or run off the page.

Work toward ScottPlot 5 is... a lot of work 😩 https://github.com/swharden/ScottPlot/pulls I decided not to have a hard transition between 4 and 5, and instead will develop both in parallel (giving me more flexibility to develop 5 slowly). There are lots of complexities and edge cases to consider!

**Comment by AteCoder** [comment]
On the cut off, seeing that the bottom plot is not cut off, I assume that each plot hides the bottom of the plot above it. I will add a gap between the rectangles to validate this conjecture.

I find myself doing hard breaks too. As great as I think my code was, I find time illuminating my limitations.

I am now walking through moving my code to C#; the joy of learning new tricks.

Let me know how I can be of help on rev. 5.

________________________________

**Comment by swharden** [comment]
I look forward to hearing what you find!

I find a lot of utility in working heavily on code for a few days, then working on something else for a bit, and coming back to the original project with fresh eyes. If I find it's confusing to read the code or use the new features I implemented, it's a good indication that improvements are needed. It's a humbling, yet rewarding process!

Regarding version 5, it's all preliminary, but you're welcome to run it and see what you think. It's being developed in a separate branch of this repository at the moment: https://github.com/swharden/ScottPlot/pull/521 

The biggest change is that ScottPlot5 does not use System.Drawing. It can use it, but doesn't require it. There is a SkiaSharp control which uses OpenGL for hardware-accelerated rendering of plots now, which really takes performance to another level

**Comment by AteCoder** [comment]
Interesting. So different graphics card would entail different performance, ha? I have Radon RX5700 on my new system.

Also, I assume SkiaSharp must have a way to handle printer context. Which gots me thinking. What do u do these days for rendering an image for publication? It must have higher resolution than screen graphics, right?  The reason. I am grappling with this is because I dread sharing subpart images with my PhD adviser who draws beautiful graphics using VB4!

Do you think the current rev. 5 will allow me to create the plots I shared with you?

Did you notice the acceleration chart? I thought that one was pretty cool using a moving Savitzky–Golay filter with decimation because the motion was oversampled.

________________________________
