### ISSUE TITLE
Automatic render after a plottable is added?

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#525]
### Problem

After plotting in user controls you have to call Render() to force a redraw.\
This is not intuitive to new users and is easy to forget.

```cs
double[] dataX = new double[] {1, 2, 3, 4, 5};
double[] dataY = new double[] {1, 4, 9, 16, 25};
formsPlot1.plt.PlotScatter(dataX, dataY);
formsPlot1.Render(); // <-- you must do this
```

### Solution?

Add a delegate to the Plot module:
```cs
public delegate void PlottablesUpdated();
public PlottablesUpdated PlottablesUpdatedHandler;
```

Invoke the delegate whenever the list of plottables is modified:
```cs
PlottablesUpdatedHandler?.Invoke();
```

User control constructors would wire it together like this:
```cs
plt.PlottablesUpdatedHandler = () => Render();
```

### Thoughts
* There may be a slight performance hit since adding 5 scatter plots will cause 5 renders
* Automatic rendering can be disabled with `formsPlot1.plt.PlottablesUpdatedHandler = null`

**Comment by StendProg** [comment]
Hi Scott,

`ObservableCollection` raise events on any collection change. You just need to subscribe to this event with `Render()`.
Not sure about dependencies, it came with `WPF`, but I think what is included in `.Net Standart`.

The problem of multiple `Render` calls can be solved by starting `Render` with a timer, say after 100ms. If new event come before this time, you just restart timer. In typical use, when plots are added one by one, Render will be called once 100ms after adding the last  one. There will be certain problems with calling the interface update from another thread...

**Comment by swharden** [comment]
@StendProg the timer approach is an excellent idea. It will also solve the problem where a render occurs too soon, before a plottable is done being customized by modifying its properties:

```cs
double[] xs = Generate.Consecutive(51);
double[] ys1 = Generate.Sin(51);
double[] ys2 = Generate.Cos(51);

var sp1 = interactivePlot1.Plot.PlotScatter(xs, ys1);
sp1.Color = Colors.Blue;
```

You are correct that with a timer there may be implications where different threads may ask for a render simultaneously. I will keep this in mind if/when I experiment implementing this!

**Comment by swharden** [comment]
A timer in the controls definitely works, and ideally can check the number of plottables every 50ms and automatically re-render if it observes the number has changed.

However, some users may get confused why changes to plottable _styles_ (e.g., color) later don't update the screen.

Calling `Render()` manually seems desirable. It forces the user to be aware of this method, and lets them call it at a time they think is best. This was a good discussion, but I don't think I'll implement this feature.
