### ISSUE TITLE
GetLegend() fails when called before rendering

### ISSUE THREAD

**Issue by el-aasi** [swharden/ScottPlot#527]
**I would like to:**
I am trying to get the legend and save it as an image so that I can place it outside the graph area to not obstruct the graph itself.

**This is what I have tried:**
I have tried using the ` plt.GetLegendBitmap(); ` method and I am not sure if this is a bug or I am just a tool and I am not using it properly, but the image that I am getting from the method is a 1x1 bitmap, which when saved is unusable. I have tried saving it in a different format (btm, png, jpeg) but nothing seems to make the difference. I was thinking that it was because I did not have the `plt.Legend()` method, so I included it first with location set to none, and with location set to upperLeft still no luck.
 
![image](https://user-images.githubusercontent.com/27493937/92207114-fca73180-ee88-11ea-8a4d-b48e295f0261.png)

This is what I get. 

If I am a tool let me know how can I use it properly. Thanks and have a great day. 

Just saw the #388 issue, will try the options provided there too see if I can fix my issue.

**Comment by el-aasi** [comment]
OK, so after digging a while, the workaround (or maybe this is how it was intended to be used) to get a proper legend (not 1x1) one needs to get the legend after `plt.SaveFig()` is called so that the image would be rendered....donno if still relevant cause from what I've seen the are quite a few changes coming anyway, but in case someone gets stuck, that's what worked for me

**Comment by swharden** [comment]
Hi @el-aasi, thanks for raising this issue! I'm glad you found a fix for it by calling `plt.SaveFig()`. You could also do this by calling `plt.GetBitmap()`, discard the object it returns, and you wouldn't have to save a file.

However, I'd consider this a bug! I can fix it by making `plt.GetLegendBitmap()` smart enough to automatically perform a render if a render has not happened yet so it always returns a bitmap 👍

**Comment by swharden** [comment]
This has been fixed and will be in the next release (4.0.40), thanks again @el-aasi!
