### ISSUE TITLE
Update Samples in an existing signal plot to acheive windowing functionality

### ISSUE THREAD

**Issue by gkankanh** [swharden/ScottPlot#530]
First of all thanks for fantastic work!Awesome!. I am dealing with a relatively large data set of samples and I need to analyze them in a windowed function. Is there a way to do this? Using the same plot with updated samples worked but I have the previous window samples as well.
Another aspect I am wondering about is the ability to select a small portion of the displayed graph/plot and mark/annotate the corresponding samples somehow. Is this possible? It will be useful to detect anomalies in the signal visually and identify the sample subset.

**Comment by StendProg** [comment]
Hi @gkankanh,
>I am dealing with a relatively large data set of samples and I need to analyze them in a windowed function. Is there a way to do this? Using the same plot with updated samples worked but I have the previous window samples as well.

You can pass large array to `Plottable` and setup displayed range with `MinRenderIndex` `MaxRenderIndex`.
To change window you just need to change this indexes and call `Render()` it works fast.

>  Another aspect I am wondering about is the ability to select a small portion of the displayed graph/plot and mark/annotate the corresponding samples somehow. Is this possible? It will be useful to detect anomalies in the signal visually and identify the sample subset..

There is no ready to use solution, but you can try mark range with  `PlottableHSpan` over your data and manualy set annotation with `PlottableText`.

**Comment by swharden** [comment]
> First of all thanks for fantastic work! Awesome!

Hi @gkankanh, I am happy to hear you are enjoying ScottPlot! @StendProg's answers are excellent. I'll add a few comments, and also ask for clarification about what you are trying to display.

> I am dealing with a relatively large data set of samples and I need to analyze them in a windowed function. Is there a way to do this? Using the same plot with updated samples worked but I have the previous window samples as well.

The ScottPlot demo application https://swharden.com/scottplot/demo has some examples about how to display "plots with updated samples". Source code for the demo is in `/src/ScottPlot.Demo.WPF` and  `/src/ScottPlot.Demo.WinForms`.

I'm not sure exactly what you mean when you refer to windowing. If your question is about how to set the axis limits, you can call `formsPlot1.plt.Axis(-10, 10, -1, 1)` to set the axis limits (the "window" of the view area).

If the windowing you refer to describes modifying values of a fixed-size array (e.g., filling the array with source data then multiplying each point by a window function), it probably doesn't relate to ScottPlot. Once you load an array into a plot with something like `PlotScatter()` or `PlotSignal()`, the latest values in that array will be displayed every time the plot renders. This way you can do any math you want on the values in that array, and the latest values will always be plotted.

![live](https://user-images.githubusercontent.com/4165489/92328344-31a0b900-f02e-11ea-9ab1-b67c644f4ffa.gif)

> Another aspect I am wondering about is the ability to select a small portion of the displayed graph/plot and mark/annotate the corresponding samples somehow. Is this possible? It will be useful to detect anomalies in the signal visually and identify the sample subset.

Yes, @StendProg gave a good answer about signal plots: you can set min and max index and only the values between those indexes will be plotted:
https://swharden.com/scottplot/cookbooks/4.0.38/#plottypes-signal-plot-a-range-of-points

A simpler option that works for all plot types is to adjust the axes to only display the region of data you are interested in:
`formsPlot1.plt.Axis(-10, 10, -1, 1)` 

Regarding placing arrows and text on the plot, that is possible too. These plot types take X/Y coordinates, so you can place them where you want relative to data:
https://swharden.com/scottplot/cookbooks/4.0.38/#plottypes-arrow-plot-arrows
https://swharden.com/scottplot/cookbooks/4.0.38/#plottypes-text-text-quickstart

There is an "annotation" object, but that places text on the figure (not using X/Y coordinates):
https://swharden.com/scottplot/cookbooks/4.0.38/#plottypes-annotation-annotation-quickstart

@gkankanh let me know if this answers your questions! I'll close this issue for now, but feel free to open it again if I misunderstood your goals. Good luck! -Scott

**Comment by gkankanh** [comment]
Perfect. Thanks.
