### ISSUE TITLE
[New plot] Stacked filled line plots

### ISSUE THREAD

**Issue by AlexFsmn** [swharden/ScottPlot#531]
First, thanks for creating a great plotting library!

**Idea:**
Would be great if stacked filled line plots were available in this project.
Something similar to the left image here:
![Stacked chart](https://raw.githubusercontent.com/alandefreitas/matplotplusplus/master/documentation/examples/line_plot/area/area_1.svg)

Bonus is if you have the option to always make the charts use 100% space, meaning the empty space on top of this image should be filled.

How hard would this be to create? Let me know if I can help.

**Comment by swharden** [comment]
This is a good question! The Polygon plottable can be used for this. It's not super intuitive (perhaps a function could help streamline this), but this is the gist:

```cs
var plt = new ScottPlot.Plot(600, 400);

double[] xs = { 1, 2, 3, 4 };
double[] ys1 = { 1, 3, 1, 2 };
double[] ys2 = { 3, 7, 3, 1 };
double[] ys3 = { 5, 2, 5, 6 };

double[] filledXs = xs.Take(1).Concat(xs).Concat(new double[] { xs.Last() }).ToArray();
double[] filledYs1 = new List<double>() { 0 }.Concat(ys1).Concat(new double[] { 0 }).ToArray();
double[] filledYs2 = new List<double>() { 0 }.Concat(ys2).Concat(new double[] { 0 }).ToArray();
double[] filledYs3 = new List<double>() { 0 }.Concat(ys3).Concat(new double[] { 0 }).ToArray();

plt.PlotPolygon(filledXs, filledYs3, lineWidth: 2, lineColor: Color.Black, fillAlpha: .7);
plt.PlotPolygon(filledXs, filledYs2, lineWidth: 2, lineColor: Color.Black, fillAlpha: .7);
plt.PlotPolygon(filledXs, filledYs1, lineWidth: 2, lineColor: Color.Black, fillAlpha: .7);

plt.AxisAuto(0, 0);
plt.Title("Filled Line Plots");
```
![image](https://user-images.githubusercontent.com/4165489/92336221-5d429400-f06c-11ea-99c2-b40895eb0368.png)

```cs
var plt = new ScottPlot.Plot(600, 400);

double[] xs = { 1, 2, 3, 4 };
double[] ys1 = { 1, 3, 1, 2 };
double[] ys2 = { 3, 7, 3, 1 };
double[] ys3 = { 5, 2, 5, 6 };

// manually stack plots
ys2 = Enumerable.Range(0, ys2.Length).Select(x => ys2[x] + ys1[x]).ToArray();
ys3 = Enumerable.Range(0, ys2.Length).Select(x => ys3[x] + ys2[x]).ToArray();

// create polygons for each data point
double[] filledXs = xs.Take(1).Concat(xs).Concat(new double[] { xs.Last() }).ToArray();
double[] filledYs1 = new List<double>() { 0 }.Concat(ys1).Concat(new double[] { 0 }).ToArray();
double[] filledYs2 = new List<double>() { 0 }.Concat(ys2).Concat(new double[] { 0 }).ToArray();
double[] filledYs3 = new List<double>() { 0 }.Concat(ys3).Concat(new double[] { 0 }).ToArray();

plt.PlotPolygon(filledXs, filledYs3, lineWidth: 2, lineColor: Color.Black);
plt.PlotPolygon(filledXs, filledYs2, lineWidth: 2, lineColor: Color.Black);
plt.PlotPolygon(filledXs, filledYs1, lineWidth: 2, lineColor: Color.Black);

plt.AxisAuto(0, 0);
plt.Title("Stacked Filled Line Plots");
```
![image](https://user-images.githubusercontent.com/4165489/92336242-806d4380-f06c-11ea-8f1f-51712190f5c1.png)

Since it's already possible a code modification is probably not needed, but I hope this new cookbook example will make it easier to find out how to do this in the future!

**Comment by swharden** [comment]
... that said, we could add a `PlotFilledLine()` and `PlotStackedLine()` method to the `Plot` module which just does this under the hood. This is similar to how `PlotFillAboveBelow()` works.

https://github.com/swharden/ScottPlot/blob/6dcf72a4245b36a2e42500e6b8778603817284e3/src/ScottPlot/Plot.cs#L491-L538

The function signature would get a bit confusing though. It would have to accept a 1D array of Xs and a 2D array of Ys, and it's not super obvious what type is best there (`double[][]` or `double[,]` or `List<double[]>`). 

Anyway, my lean is that for now it's probably unnecessary complexity, and I'm a little worried about collecting cruft in the plot module 🙃

Perhaps the fancy linq above could be put in the `Tools` module, ~~something like~~ lol a tool already exists!

```cs
double[] xs = { 1, 2, 3, 4 };
double[] ys1 = { 1, 3, 1, 2 };

double[] filledXs= Tools.Pad(xs, cloneEdges: true);
double[] filledYs1= Tools.Pad(ys, padWithLeft: 0, padWithRight: 0);
```
