### ISSUE TITLE
Render many plots problem

### ISSUE THREAD

**Issue by nurozcan** [swharden/ScottPlot#538]
Hello, I am working on rendering live data plots. I have 20 lines to draw and they have about 10 million points. When I try to render changes on graph, it uses 50% of cpu and it causes freeze. I tried plotscatter for drawing lines then changed to plotsignal but there are so many points and it didn't help. Is there any solution about problem? Have you ever faced that?

Thank you
Nur

**Comment by StendProg** [comment]
Hi @nurozcan,

You absolutely shouldn't use `Scatter` when talking about millions of points.
Can you clarify, You have 10 million points in total, or 10 million on each line?
If the latter, then you are trying to solve a rather resource-intensive task. However, after modification `QuickStart->Signal 5 million points demo` to 20 lines each 10 million points I got about 3 FPS. Is this acceptable to you?
There is `PlottableSignalConst` which is even more optimized in terms of speed and allows you to display your task at great Render speed, about 70 FPS in my test.
A significant disadvantage of this `SignalConst` is that it is not meant to update data. In fact, it has API methods for updating data, but they are quite resource intensive compared to the very fast data update for `Signal`. How critical is the data update rate in your task?

**Comment by nurozcan** [comment]
Hi. 

10 million is total. Datas should be updated each 200 ms. 
I can try PlottableSignalConst.

Thank u

**Comment by nurozcan** [comment]
I want to update 10 million points in 1 second, but i guess signalconst is not useful for it. Do you have any other suggestion?

**Comment by StendProg** [comment]
20 `PlottableSignals` 500_000 points in each, and 10 million in total, rendered at acceptable 30 fps for me.
It seems that the problem is not so much in the rendering as in how you update the data.
If you can provide more information about your task, I could suggest something in addition.

The only thing I can assume is that the rendering speed depends on the type of lines. Signals similar in shape to white noise are rendered many times slower. To check this assumption, try to render 20 of your signals, but let's say 1000 points in each, will the speed greatly increase, or will it remain about the same?

**Comment by swharden** [comment]
Hi @nurozcan, 

Check out the ScottPlot demo application. https://swharden.com/scottplot/demo There you can open the cookbook (interactively) and see what 5 million data points looks like on your computer. On my computer I find an extremely high frame rate (7 ms render time, 140 Hz update rate). You can double-click on the plot to display the frame rate for yourself.

Check the code for these examples to ensure you're plotting your data using similar methods. If you find performance to be significantly slower than you expect, double-check to make sure you're displaying data using the same methods these demos do.

![image](https://user-images.githubusercontent.com/4165489/93028175-114d9d00-f5e0-11ea-8050-c2bc10a901ea.png)

I hope this helps you reach a solution! If you still have questions or find that your plotting is still slow, feel free to re-open this issue.

--Scott
