### ISSUE TITLE
Constant Changes chart

### ISSUE THREAD

**Issue by jytcfhgqmucrfmgqks** [swharden/ScottPlot#541]
Hey, I looked over the demo. I haven't found an example of how to do something like this. To add points. And the graph moved over time.

https://lvcharts.net/App/examples/v1/wf/Constant%20Changes

![constant](https://user-images.githubusercontent.com/71137347/92933883-1e835400-f447-11ea-901a-577184f2b3a0.gif)

Or something like the network bandwidth monitor here

https://youtu.be/3leNNGmAYD4

**Comment by swharden** [comment]
Hi @jytcfhgqmucrfmgqks, I can create a code sample to do this. How many data points are you seeking to display? Are they evenly spaced? This answer will help determine if you should use a scatter plot or signal plot.

You may find the demo application helpful. It has multiple examples of how to plot live, incoming data. https://swharden.com/scottplot/demo

Source code for these demos is in this repository too. Notably the demo for "live data" uses scatter plot (which is good for 100s of data points), while the "growing data" demo uses signal plot (good for millions of points).

The short answer is that if you plot an array, you can change the data underlying the array _on your end_ any time, then trigger a render whenever you want (using a timer or something). Something like

```cs
double[] yourData = { /* */ };
formsPlot1.plt.plotSignal(yourData);

// modify your data however you want (including shifting points to the left and adding new points to the right)
yourData[0] = /* */;

// update the plot whenever you want (e.g., from a timer)
formsPlot1.Render();
```

**Comment by swharden** [comment]
Hi @jytcfhgqmucrfmgqks I just updated the strip chart demo (#540) to demonstrate how to do something like this. It's not published as a binary yet, but if you download this repository and compile it you'll be able to try it out. I hope this helps! 

![ecg2](https://user-images.githubusercontent.com/4165489/93027564-bb76f600-f5db-11ea-9afb-67399158daef.gif)
https://github.com/swharden/ScottPlot/blob/096062f5dfde8fd5f1e2eb2e15e0e7ce9b17a54b/src/ScottPlot.Demo.WinForms/WinFormsDemos/LiveDataUpdate.cs#L14-L91
