### ISSUE TITLE
Getting the value(object/index/properties) of the PlotVLine I just dragged?

### ISSUE THREAD

**Issue by vrdriver** [swharden/ScottPlot#542]
How do I get the value(object/index/properties) of the PlotVLine I just dragged, or am presently dragging in either realtime for MouseDown, or on MouseUp?

It would be nice to know what it's exact location for the xAxis (yet again). I can loop through all of the PlotLines and get the values, but knowing that actual line and addressing it directly would be better.

I have added the following to my code, to know when the mouse is up on the control, but, it doesn't give me much at all.

```
  public Form1()
  {
        InitializeComponent();

        this.formsPlot1.MouseUp += new System.Windows.Forms.MouseEventHandler(this.formsPlot1_MouseUp);
}
```
and
```
private void formsPlot1_MouseUp(object sender, MouseEventArgs e)
{
      Console.WriteLine("MouseUp");
      Console.WriteLine(sender.ToString());
      Console.WriteLine(e.ToString());

     // This would be ideal, though it will fail at this present time.
      var X = sender.PlotVLine.X;

    // ... update values based on X etc 
}

```

This next bit, I realise this may be the wrong, or not the original intended way of doing this, but I couldn't find any other way... it seems to work for individual elements for a short search, but not at all good for real-time. Basically, it you need to find the index of a known 'label'.

```
formsPlot1.plt.PlotVLine(label: "green", lineWidth: 3, x: position, draggable: true, dragLimitLower: 0, dragLimitUpper: 100000);                            
String plotname = "";

int plottablescount = formsPlot1.plt.GetSettings(false).plottables.Count; 
for (int i = 0; i < plottablescount; i++)
{
                                
Console.WriteLine(formsPlot1.plt.GetSettings(false).plottables[i].ToString());      //  PlottableVLine (green) at X=516587
Console.WriteLine(formsPlot1.plt.GetSettings(false).plottables[i].GetLegendItems());//  ScottPlot.Config.LegendItem[]
Console.WriteLine(formsPlot1.plt.GetSettings(false).plottables[i].GetLimits());     //  x1=516587.000, x2=516587.000, y1=NaN, y2=NaN
Console.WriteLine(formsPlot1.plt.GetSettings(false).plottables[i].GetType());       //  ScottPlot.PlottableVLine
Console.WriteLine(formsPlot1.plt.GetSettings(false).plottables[i].GetHashCode());   //  2383799
var stringlabel = formsPlot1.plt.GetSettings(false).plottables[i].ToString();       //  PlottableVLine (green) at X=516587
                                
Console.WriteLine(Regex.Match(stringlabel, @"\(([^)]*)\)").Groups[1].Value); // This will extract the name of the moveable plotline

plotname = Regex.Match(stringlabel, @"\(([^)]*)\)").Groups[1].Value;

if (plotname == "green")
{
    // do stuff as the 'green' label was found
}

}
```

Thanks again.

**Comment by StendProg** [comment]
Hi @vrdriver,

Just save your `PlottableVLine` on `Forms` level:
```c#
public Form1
{
PlottableVLine vLine;

public someButtonClick(...)
{
 ...
  vline = formsPlot1.plt.PlotVLine(label: "green", lineWidth: 3, x: position, draggable: true, dragLimitLower: 0, dragLimitUpper: 
  100000);
...
}
}
```
And use it whenever and wherever you need it.

ScottPlot.WinForms control have `MouseDragPlottable` event, you can subscribe to it and check value of your stored vLine.
```c#
formsPlot.MouseDragPlottable += (s, e) => SomeCaption.Text = vLine.X.ToString();
```

You don't need iterate over plottables. `GetSettings()` for debug and experiments porpouse only. If you have a problem that can only be solved using `GetSettings`, this is a reason to expand the existing API.

**Comment by vrdriver** [comment]
If this is not possible in the current version then, not to worry, as I may be able to use a different system altogether. I was just wondering if it was possible. After writing this question, I noticed that it's probably marked for version 5.

**Comment by vrdriver** [comment]
Thanks @StendProg. I'll take a look at this.

**Comment by vrdriver** [comment]
@StendProg . Thanks for helping with guiding me the right direction. It has helped **a lot.**

As I have multiple vplots, I've redirected the entire event, which keeps that real-time thing happening and I'm then able to get all of them separately and detect changes. 

```
PlottableVLine vLine_cue;
PlottableVLine vLine_overlap;
PlottableVLine vLine_intro;
// .. etc

public Form1()
{
    InitializeComponent();
    this.formsPlot1.MouseDragPlottable += (s, e) => { formsPlot1_MouseDragPlottable(s, e); };
} 

private void formsPlot1_MouseDragPlottable(object s, EventArgs e)
{ 
    // This is for detecting the plot lines that have been changed in ScottPlot
 

    // check if each link has changed
    if (plot_Meta_Cue_sample != vLine_cue.position)
    { 
        textBox_vLine_cue.Text = vLine_cue.position.ToString(); // with added formating later
        plot_Meta_Cue_sample = vLine_cue.position;
        button_Save.BackColor = Color.LightPink;
    }
 
    // repeat the above statement for the rest of them... 
    if (plot_Meta_Overlap_sample != vLine_cue.position)
    { 
        textBox_vLine_overlap.Text = vLine_overlap.position.ToString(); // with added formating later
        plot_Meta_Overlap_sample = vLine_overlap.position;
        button_Save.BackColor = Color.LightPink;
    }
 
    // etc
 
}



private void Form1_Load(object sender, EventArgs e)
{ 

    double position = 100;

    vLine_cue = formsPlot1.plt.PlotVLine(label: "vLine_cue", lineWidth: 3, x: position, draggable: true, dragLimitLower: 0, dragLimitUpper:   100000);
    vLine_overlap = formsPlot1.plt.PlotVLine(label: "vLine_overlap", lineWidth: 3, x: position+10, draggable: true, dragLimitLower: 0, dragLimitUpper: 100000);
    vLine_intro = formsPlot1.plt.PlotVLine(label: "vLine_intro", lineWidth: 3, x: position+20, draggable: true, dragLimitLower: 0, dragLimitUpper: 100000);
}

```
 
I've included this code for others to discover if required.

**Comment by vrdriver** [comment]
Before I close this question, I have just one more.
For context, I'm needing to move the playhead of an audio track when the song is playing. 
I use `vlinePlayhead.position = song.samplesposition;` to reposition the vlineplayhead. 
Now the problem I have is that it appears to refresh the entire plot.
I didn't see it in any examples, but is there a way to only refresh that vlineplayhead, and leave the rest of the plot untouched?
I can use plt.render to do the entire thing,  or I can do
```
plt.remove(vlineplayhead);
Vlineplayhead.position = song.samplesposition;
plt.add(vlineplayhead);
```

But this seems a little cumbersome and still ends up with the same result.

**Comment by StendProg** [comment]
This is the base concept of `ScottPlot`. Full plot rerender from scratch on each render call without any caching. There is nothing to do with that. This concept work fine, because ScottPlot have fast render time in most cases.

For signal with 40 million samples i want to point you to `PlottableSignalConst`. It super fast for any size.
There are few negative sides of `PlottableSignalConst` compare to `PlottableSignal`:
1. You can't update its data after ploting (`Const`). In fact, it have `Api` for updates, but it works very slow compare to `PlottableSignal` updates.
2. First render take significant additional time for data preprocessing.
3. It allocate  2-4 times more memory then source array. (You should switch to `x64` for 50-100 million points plot).

If the proposed does not suit you, then you can manual draw the line yourself on top of ScottPlotControl. Of course this is a bad solution, but I cannot suggest anything else.

**Comment by vrdriver** [comment]
Thanks, that's what I suspected. As I'm able to get the range of the plot of the in and out points (can't remember the exact variable names) I can do some maths and plot an image of 3 pixels over the graph as the playhead then. Not a difficult task to do.
I'll have a test of the PlottableSignalConst and see what the results are. 
Thanks again. Really appreciate all the help, and I look forward to seeing the new time only axis for the plots. 😊

**Comment by swharden** [comment]
Hey @vrdriver, sorry it took so long for me to get to this but I'm really happy that @StendProg was able to provide an excellent and thorough answer.

To summarize the conclusion about how to continuously read the position of dragged axis lines, the best way is to save the object `PlotVLine()` returns and access its `position` property whenever you want to know where the line is. Whether reading this property is triggered by a timer or some type of mouse move event is up to you.

Regarding the rendering system, ScottPlot uses System.Drawing to draw a plot as a Bitmap. User controls are just thin wrappers that watch the mouse and request next Bitmap whenever something changes. The appearance of animation comes from ScottPlot being pretty fast at drawing this way, but all interactivity is achieved by creating new Bitmaps. On one hand this makes it really easy to use and it's supported on many systems, but on the other hand adding advanced interactivity requires writing your own control.

I second @StendProg's recommendation to use PlotSignalCost() for plotting things like audio data. It is so fast, even with millions of samples, that refreshing the whole screen takes very little time.

I think this answers all the questions raised in this thread so I'll close this issue, but feel free to open it again if more questions pop up! --Scott
