### ISSUE TITLE
Potential bug in TightenLayout method

### ISSUE THREAD

**Issue by vrdriver** [swharden/ScottPlot#544]
Hi Scott,

Sorry to be flooding your project with questions. 
I may have discovered a layout bug, which after searching may even be a duplicate of this bug? #449 
Has this been resolved, or is it something new?
                    
This is what I'm currently calling:
                    
```
formsPlot1.Configure(lockVerticalAxis: true);                
formsPlot1.plt.PlotSignalConst(dataX1, color: Color.SkyBlue); // Makes it draw
formsPlot1.plt.PlotSignalConst(dataX2, color: Color.LightBlue); // Makes it draw
formsPlot1.plt.Style(ScottPlot.Style.Gray1);
formsPlot1.plt.Ticks(rulerModeX: true, displayTicksY: false);
formsPlot1.plt.AxisAuto(0);
formsPlot1.plt.Ticks(rulerModeX: true, displayTicksY: false);
formsPlot1.plt.Frame(left: false, right: false, top: false);
formsPlot1.plt.TightenLayout(padding: 0, render: true); 
formsPlot1.Configure(recalculateLayoutOnMouseUp: false);
formsPlot1.plt.AxisBounds(0, samples, -1, 1);
```

This first graph is how the plots looks at first (which is great).
Correct:
![Screen Shot 2020-09-15 at 22 22 59](https://user-images.githubusercontent.com/5615487/93209918-207c4880-f7a2-11ea-8c56-eaaa480c2ce0.png)

But, when I click on the plot, it adds the borders all back.

Not Correct, after clicking on the plot.
![Screen Shot 2020-09-15 at 22 23 05](https://user-images.githubusercontent.com/5615487/93209956-2d993780-f7a2-11ea-831f-533e90ee216b.png)

This bug is also present in the current 4.0.38 ScottPlot Demos (WPF) -> Customize -> Axis -> Ruler Mod (X only).

**Comment by vrdriver** [comment]
Wait. Hold the fort! I have found a solution!

```
 public Form1()
{
        InitializeComponent();

      // Add this to prevent potential bug https://github.com/swharden/ScottPlot/issues/449
       this.formsPlot1.MouseUp += new System.Windows.Forms.MouseEventHandler(this.formsPlot1_MouseUp);
}

          
public void formsPlot1_MouseUp(object sender, MouseEventArgs e)
{
      // Add this to prevent potential bug https://github.com/swharden/ScottPlot/issues/449
      formsPlot1.plt.TightenLayout(padding: 0, render: true);
      formsPlot1.Configure(recalculateLayoutOnMouseUp: false);
      Console.WriteLine("MouseUp");
      // End fix
}
```

I'll close the comment now.

**Comment by swharden** [comment]
It looks like you found a solution! The key line is 

```cs
formsPlot1.Configure(recalculateLayoutOnMouseUp: false);
```

Although I plan to make options like this easier to discover in the future #547...

> Sorry to be flooding your project with questions.

No worries! Feedback about how to improve ScottPlot for use cases I hadn't considered are helpful at this stage. If I get overwhelmed I'll let you know, but I'm good for now 👍

**Comment by vrdriver** [comment]
Yes, that is the key line, and I also had to add it to these as well. Basically anywhere the mouse interacts with the plot.


```
        private void formsPlot1_MouseDownOnPlottable(object s, EventArgs e)
        {
            formsPlot1.plt.TightenLayout(padding: 0, render: false);
            formsPlot1.Configure(recalculateLayoutOnMouseUp: false);

        }

        private void formsPlot1_MouseDown(object s, EventArgs e)
        {
            formsPlot1.plt.TightenLayout(padding: 0, render: false);
            formsPlot1.Configure(recalculateLayoutOnMouseUp: false);

        }
```
