### ISSUE TITLE
Tick labels improperly display extremely large values

### ISSUE THREAD

**Issue by StendProg** [swharden/ScottPlot#549]
**Describe the bug**
At extrime zoom out Axis ticks behaving strange.
Negative ticks values looks fine, but positive try to show every digit in huge numbers.

**To Reproduce**
Extreeme zoom out with mouse wheel.

**Screenshots**
![image](https://user-images.githubusercontent.com/53831487/93358891-b1a6fa00-f84a-11ea-979a-be4386108b8f.png)

**Comment by StendProg** [comment]
It looks like 
https://github.com/swharden/ScottPlot/blob/2972c4b5120d4e73ab85fbd1c800baa435d99446/src/ScottPlot/Config/TickCollection.cs#L221
should be
```c#
bool isLargeNumber = (Math.Abs(value) > 1000);
```
but then the negative labels will become huge too.

Maybe this line contain wrong logic too:
https://github.com/swharden/ScottPlot/blob/2972c4b5120d4e73ab85fbd1c800baa435d99446/src/ScottPlot/Config/TickCollection.cs#L226

**Comment by swharden** [comment]
I think the `Abs()` change fixed this bug. Thanks for finding the problem!

![image](https://user-images.githubusercontent.com/4165489/93718744-0cdb3400-fb4c-11ea-8867-30dc618fd726.png)
