### ISSUE TITLE
WpfPlot ignores layout padding if defined during window initialization

### ISSUE THREAD

**Issue by mdinescu** [swharden/ScottPlot#551]
**Describe the bug**
Rendering a WPF plot includes an unnecessary and undesirable margin that cannot be removed (or at least I couldn't find a way to remove it).   

**To Reproduce**
To reproduce the problem, create a WPF project and add a window with a single WpfPlot element like this:
```
<Window>
    <Grid>
         <Grid.ColumnDefinitions>
            <ColumnDefinition Width="*"/>
        </Grid.ColumnDefinitions>
         <WpfPlot x:Name="testWpfPlot" Padding="0"/>
    </Grid>
</Window>
```

Then, configure the plot to render some signal or any plottable and then remove the ticks and attempt to change layout to remove any additional padding or extra space around the figure. 

```cs
testWpfPlot.plt.Clear(scatterPlots: true);
testWpfPlot.plt.PlotBar(xs: new double[100], ys: new double[100],    // can generate some random data and plot 
            barWidth: 2, 
            xOffset: -0.5, 
            fillColor: System.Drawing.Color.SlateGray,
            outlineWidth: 0,
            label: "test");
testWpfPlot.plt.Grid(xSpacing: 2);
testWpfPlot.plt.Style(ScottPlot.Style.Gray2);
testWpfPlot.plt.AxisAuto();
testWpfPlot.plt.Ticks(displayTickLabelsX: false, displayTickLabelsY: false, displayTicksX: false, displayTicksY: false);
testWpfPlot.plt.TightenLayout(padding: 0);
testWpfPlot.plt.Frame(false);
```

The expectation is that the plot would render using the full available space without leaving any additional space 

**Screenshots**
<img width="789" alt="Screen Shot 2020-09-16 at 3 56 05 PM" src="https://user-images.githubusercontent.com/3202132/93400808-8960d080-f835-11ea-8e77-5c662517dce4.png">

**Comment by swharden** [comment]
Hey @mdinescu, without getting too deep into this yet, what is the padding you are struggling to eliminate? A, B, or both?

![image](https://user-images.githubusercontent.com/4165489/93402044-adcaa600-f851-11ea-97a8-9e4c4f1f1b7b.png)

### Tight Axes

"A" relates to axis limits, and you may be able to fix it with something like this. 

```cs
plt.AxisAuto(0, 0);
```
or
```cs
plt.AxisAuto(0);
plt.Axis(y1: 0);
```
and for middle-click mouse:
```cs
wpfPlot1.Configure(middleClickMarginX: 0, middleClickMarginY: 0);
```

### Figure Padding

Regarding "B", perhaps try something like
```cs
wpfPlot1.Configure(recalculateLayoutOnMouseUp: false);
```

I hope this helps! I can take a deeper look at this one soon...

**Comment by mdinescu** [comment]
The padding I'm trying to remove is B.

I've just tested the `wpfPlot1.Configure(recalculateLayoutOnMouseUp: false);` suggestion and that didn't have any effect on the plot rendering.

**Comment by mdinescu** [comment]
For what it's worth, I've investigated this a bit and the padding seems to be embedded into the bitmap image that is being rendered, meaning it's not added in the WPF layer but in the rendering of the plot.

**Comment by swharden** [comment]
Ah, good catch! I replicated this bug in the "no padding" demo

![image](https://user-images.githubusercontent.com/4165489/93403948-e91ba380-f856-11ea-99e9-d82af917aa30.png)

on mouse-up it looks like this

![image](https://user-images.githubusercontent.com/4165489/93403956-f0db4800-f856-11ea-954e-7b5cf8125618.png)

**Comment by swharden** [comment]
@mdinescu sorry for how long it took me to get to this one. I figured it out though!

Solution: interact with the plot ***after the window has loaded***

```xml
<Window x:Class="WpfPlotSandbox.MainWindow"
        ...
        Loaded="Window_Loaded">
```

```cs
public MainWindow()
{
    InitializeComponent();
}

private void Window_Loaded(object sender, RoutedEventArgs e)
{
    wpfPlot1.plt.PlotSignal(DataGen.Sin(51));
    wpfPlot1.plt.PlotSignal(DataGen.Cos(51));

    wpfPlot1.plt.Ticks(false, false);
    wpfPlot1.plt.Frame(false);
    wpfPlot1.plt.TightenLayout(padding: 0);
    wpfPlot1.Configure(recalculateLayoutOnMouseUp: false);
    wpfPlot1.plt.Style(ScottPlot.Style.Gray2);

    wpfPlot1.Render();
}
```

If you defined a layout in the window initializer, the window was probably resized after you defined that layout, and the resize event caused the layout to be recalculated and overwritten. I'll think about what I can do to make this solution more obvious in the future, but in the mean time this should do the trick 👍 

Let me know if you hit any other snags!
Scott

**Comment by mdinescu** [comment]
Interesting. Thank you for looking into this.

It turn out that the `TightenLayout(padding: 0)` is the key.  In my case, I had the code to setup the chart in the Loaded event but I also had some code to clear the plot and regenerate it on a timer and it looks like you have to call `TightenLayout(padding: 0)` every time.

It's a bit counterintuitive that the layout settings are not persistent.

On the timer, I had something like this:

```
wpfPlot1.plt.Clear(p => p is PlottableBar);
wpfPlot1.plt.PlotBar(xs: xs, ys: ys, 
                    barWidth: 0.8, 
                    outlineWidth: 0);
wpfPlot.plt.AxisAuto(0,0);
wpfPlot.Render(true);
```

It looks like in order to preserve the "no padding" setting I needed to call `TightenLayout(padding: 0)` before the Render call each time.

**Comment by swharden** [comment]
> It's a bit counterintuitive that the layout settings are not persistent.

Every time new plottables are added the plot resets the layout to make all the axis labels, tick labels, etc. fit properly with the new dimensions. Calling `TightenLayout()` or `Layout()` replaces this automatic layout with one you define.

I agree this isn't intuitive, and I'll continue to think of ways to make this easier to use in the future! Thanks for the tip, and I'm glad we got this one figured out! 👍

**Comment by mdinescu** [comment]
Thanks a lot.  Perhaps for now it'll be enough to add this info to the cookbook as a note, or even as a separate example. This is applicable to any plot, with or without axis labels, ticks etc, where you just want the layout to not have any additional padding.

**Comment by swharden** [comment]
> add this info to the cookbook

This is a good idea! I'll add a note about this in the [no padding cookbook example](https://swharden.com/scottplot/cookbooks/4.0.40/#customize-figure-no-padding)

https://github.com/swharden/ScottPlot/blob/faee0e63a26b56939d8b69d3cbb179e2c052faf9/src/ScottPlot.Demo/Customize/Figure.cs#L72-L95

**Comment by sopgenorth** [comment]
It looks like this was removed from the latest ScottPlot Cookbook, and "TightenLayout()" is no longer an available method.

Is there a newer recommended way of achieving this same tight layout?

**Comment by swharden** [comment]
@sopgenorth you may also find use in your plot's `Frameless()` method

https://scottplot.net/cookbook/4.1/category/axis-and-ticks/#frameless-plots
