### ISSUE TITLE
Format Ticks with Custom Culture

### ISSUE THREAD

**Issue by cosmicDustOfLightLength** [swharden/ScottPlot#554]
**Describe the bug**
Set your own date format. I don't know why the HH:mm:ss time is additionally displayed?

```cs
wpfPlot1.plt.Clear();
dataYdownload.Add(mbpsDownload);
dataYupload.Add(mbpsUpload);

dataXTime.Add(DateTime.Now.ToOADate());

wpfPlot1.plt.XLabel("Time");
wpfPlot1.plt.YLabel("Mb/s");
wpfPlot1.plt.Title("demo");

wpfPlot1.plt.PlotScatter(dataXTime.ToArray(), dataYdownload.ToArray(), label: "Download: ");
wpfPlot1.plt.PlotScatter(dataXTime.ToArray(), dataYupload.ToArray(), label: "Upload: ");
wpfPlot1.plt.Legend();

wpfPlot1.plt.Ticks(dateTimeX: true);
wpfPlot1.plt.SetCulture(shortDatePattern: "a) HH:mm:ss");

wpfPlot1.Render();
```

**Screenshots**
If applicable, add screenshots to help explain your problem
![sc problem](https://user-images.githubusercontent.com/71566296/93686728-81fd2980-fab8-11ea-9681-2b3bf60d2376.png)

**Comment by StendProg** [comment]
Hi @cosmicDustOfLightLengt,
Can you provide information on which version of `ScottPlot` you got this bug.
Literally today, the DateTime Ticks subsystem was updated, and I would like to understand if the bug is related to this.

**Comment by cosmicDustOfLightLength** [comment]
Thanks this solves the problem!

**Comment by swharden** [comment]
Actually, thanks to the feature that got added a few minutes ago #537 this got much simpler! I added an example to the cookbook to make it easy to find. Thanks for the tip @cosmicDustOfLightLength!

```cs
plt.Ticks(dateTimeX: true, dateTimeFormatStringX: "HH:mm:ss");
```

It's not on NuGet yet but it should be in an hour or two 👍 
Scott
