### ISSUE TITLE
Live Updating X and Y Axis

### ISSUE THREAD

**Issue by icelord2** [swharden/ScottPlot#558]
**I would like to:**
I am trying to use your demo LiveDataFixed but instead of the X axis going from 0 to 500 i would like it to move with the data. https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot.Demo.WPF/WpfDemos/LiveDataFixed.xaml.cs
All the Examples start at 0 and didnt see anything with live updating with X moving on either a Data count or Timestamp

**This is what I have tried:**
I tried changing from 
```cs
wpfPlot1.plt.PlotSignal(liveData);
```
to
```cs
wpfPlot1.plt.PlotScatter(liveDataX, liveDataY);
```
and liveDataX just has a incrementing number to match the Y data being inserted but the graph doesnt seem to update on render

**Here's an example of what I'd like to do:**
This is a example of what i am trying to achieve.
![CE095C33-036A-4D8B-B4E2-0A1116BE4490](https://user-images.githubusercontent.com/5852995/93794717-74ee5080-fc06-11ea-90f0-ecbc4f7741cd.GIF)

**Comment by swharden** [comment]
Hi @icelord2, 

I can take a closer look at this later today, but you may be able to accomplish this using the Signal plot by adjusting the xOffset as you add new data.

```cs
sig = wpfPlot1.plt.PlotSignal(liveData);

/* update your data /*

// update the offset to indicate where (X) your data starts
sig.xOffset = 1234;

// move the axis limits to keep up with the moving data
wpfPlot1.plt.Axis(x1: 1234, x2: 1234-500);

// force a redraw
wpfPlot1.Render();
```

Does this help you accomplish the effect you're trying to achieve?

**Comment by icelord2** [comment]
@swharden Thank you that worked.

![E2D235E4-61F8-48EC-B30A-6D44F2EDC622](https://user-images.githubusercontent.com/5852995/93796426-d6afba00-fc08-11ea-88a4-0cedd8e590f5.GIF)

**Comment by swharden** [comment]
Awesome, glad you got it figured out!

**Comment by Matze1703** [comment]
Hey!

I have a problem. In my case I read one value from a serial connection every second and want these values to be shown on a diagram. I want to implement that the user can enter a specific number of points which are then shown on the plot and every second a new value is received, the plot moves one unit to the left and displays the new point on the graph. 

I used: 

`var sig = formsPlot1.Plot.PlotSignal(valueBar);` in my Form class and after that I start a thread to read out my serial connection. 

Each time I receive something from the serial connection I write the new value on my `valuebar` array and to limit the axis I use:
`formsPlot1.Plot.SetAxisLimitsX(runCount - (displayPoints - 1), runCount);`
_displayPoints --> is the amount of points to be shown 
runCount --> is raised by one every time I receive a value from my serial connection_

After that I render the plot with `formsPlot1.Plot.Render();` , but the plot doesnt update. When I click in my FormsPlot the X Axis and the graph update as it should. (each mousclick updates the plot)

Am I doing something wrong here or are there any other commands to update the plot?
I would be very thankful for any helpful answer!
Thanks,
Matthias

**Comment by icelord2** [comment]
@Matze1703 Here is a snippet of how I am using it which is similar to what you are trying to do. Though I am using WPF and have databound properties to my Graph component so not sure the differences between Forms and WPF.

PlotPoints is a integer that allows the user to pick how many points to plot.
Data is where I store all the data coming in from the connection.
I have a Timer that calls UpdateData every x milliseconds which the user can also change how fast it updates. 

Hope this code might help you

```
private void UpdateData()
{
    // Clear and re-plot points
    scottPlot.plt.Clear();

    if (Data == null)
    {
        // No Data so render Default
        scottPlot.plt.AxisAutoY();
        scottPlot.plt.Axis(0, PlotPoints);
        scottPlot.Render(true);
        return;
    }

    ObservableCollection<IData> data = Data as ObservableCollection<IData> ?? new ObservableCollection<IData>();

    int dataCount = data.Count;
    if (dataCount == 0)
    {
        // No Data so render Default
        scottPlot.plt.AxisAutoY();
        scottPlot.plt.Axis(0, PlotPoints);
        scottPlot.Render(true);
        return;
    }
    int x1 = dataCount < PlotPoints ? 0 : dataCount - PlotPoints;
    int x2 = dataCount < PlotPoints ? PlotPoints : dataCount - 1;

    _line1Data = data.Select(d => (double)d.datavalue).ToArray();
    scottPlot.plt.PlotSignal(_line1Data, color: _color1, label: "Label");

    // Update Axis Labels
    scottPlot.plt.Axis(x1, x2);
    scottPlot.plt.AxisAutoY();

    // Redraw Graph
    scottPlot.Render(true);
}
```
