### ISSUE TITLE
Failed to create component 'FormsPlot' .NET Core 3.1 WinForms

### ISSUE THREAD

**Issue by wiwalsh** [swharden/ScottPlot#562]
**Describe the bug**
When dragging and dropping a new FormsPlot onto a new blank form in a new c# Core 3.1 Winforms project.  
Receive the following error: "Failed to create component 'FormsPlot'. ..."  Image of error window attached.

**To Reproduce**
Add ScottPlot and ScottPlot.WinForms from Nuget package manager
open Form1.cs [Design]
Drag and drop FormsPlot (ScottPlot) onto Form1

Visual Studio 16.6.2
WinForms project .NET Core 3.1
ScottPlot 4.0.40

**Screenshots**
<img width="599" alt="2020-09-24_16-11-47" src="https://user-images.githubusercontent.com/24740264/94205951-8ee79780-fe81-11ea-9eb7-41bcc8b52d3d.png">
<img width="312" alt="2020-09-24_16-11-52" src="https://user-images.githubusercontent.com/24740264/94205952-8f802e00-fe81-11ea-9120-2a5417272d4b.png">
<img width="200" alt="2020-09-24_16-12-11" src="https://user-images.githubusercontent.com/24740264/94205953-8f802e00-fe81-11ea-89eb-0247092f1892.png">

Tested this on .NET Framework and it works as intended.

**Comment by swharden** [comment]
Weird, this works for me and it doesn't seem like we're doing anything different.

I'm using Visual Studio Community 2019 16.7.3. What version are you using?

![image](https://user-images.githubusercontent.com/4165489/94208690-6d45da80-fe98-11ea-8bdf-f645a5782e87.png)

**Comment by wiwalsh** [comment]
VS 16.6.2   I'll try upgrading and see what happens.

**Comment by wiwalsh** [comment]
Scott, 16.7.4 does work.  16.6.2 does not.  No idea why.
