### ISSUE TITLE
DateTime axis has too few ticks in large plots

### ISSUE THREAD

**Issue by waynetheron** [swharden/ScottPlot#564]
I have about 15k points and using toOdate with a range from the year 2000 to 2020. When plotting I only see 3 major year markers and lose all the granular markers. If i disable this it shows all the ODate labels. How can i show more date labels?

![test](https://user-images.githubusercontent.com/12031860/94248136-f2230980-ff15-11ea-9529-22884d3fd3e6.png)

**Comment by StendProg** [comment]
Hi @waynetheron,
Can you provide code example to reproduce picture above? Interested in the type of `Plottable` used and the arguments passed. Then maybe I can suggest something.

**Comment by waynetheron** [comment]
actually, I ended up just writing a separate WinForms app and with the control, I can work around it as the scaling of dates does work so you ignore - thanks

**Comment by swharden** [comment]
This is a problem, and I recreated it. Interestingly it only seems to apply to this scale, whereas other DateTime tick densities produce the expected number of ticks.

```cs
Random rand = new Random(0);
double[] data = DataGen.RandomWalk(rand, 100_000);
DateTime firstDay = new DateTime(2020, 1, 1);

var plt = new ScottPlot.Plot(4000, 400);
plt.PlotSignal(data, sampleRate: 60 * 24, xOffset: firstDay.ToOADate());
plt.Ticks(dateTimeX: true);
```

![image](https://user-images.githubusercontent.com/4165489/94282437-d459a280-ff1d-11ea-9080-ec0360dfe3a2.png)

**Comment by StendProg** [comment]
This is applicable to any type of `DateTimeUnits` and is observed when switching from one type to another. For example, in this case, day ticks are replaced by monthly ticks when the entire time interval is more than 2 months, which corresponds to 3 Month
 tick on whole interval.
Probably this behavior comes with #539, but I think it was before.
Solution of this problem may be more smart `DateTimeUnit` select in `DateTimeUnitFactory` additionaly based on `maxTickCount` param.

**Comment by swharden** [comment]
Thanks @StendProg for fixing this as part of #561! This looks much better now
![image](https://user-images.githubusercontent.com/4165489/94347076-51a91400-ffff-11ea-96b7-6b97e814b571.png)

**Comment by waynetheron** [comment]
thanks for sorting this. Actually the winform interactive version more helpful for my situation but will see if the original code will do also. 

⁣Get TypeApp for Android ​
