### ISSUE TITLE
Setting custom subplot size

### ISSUE THREAD

**Issue by ozgur640** [swharden/ScottPlot#569]
If I am not wrong in multiplot.cs, size of each subplots is found simply dividing in to the subplot number in the rows and columns respectively.
Is it possible to add a feature to set the subplot size? For example, multiplot of size 800x600 includes two subplots of size:
subplots[0] is 600x400 pixels
subplots[1] is 200x400 pixels  

Thanks.

**Comment by swharden** [comment]
Hi @ozgur640, 

You are correct, the [multiplot module](https://github.com/swharden/ScottPlot/blob/15b8b0e822e7ab6bb593789e0cff3a928538ac5a/src/ScottPlot/MultiPlot.cs#L1-L97) divides width and height by the number of columns and rows and currently every sub-plot is the same size.

To create a Bitmap which includes multiple plots of different sizes with existing library you could do something like:

```cs
var plt1 = new ScottPlot.Plot(500, 200); // smaller plot
var plt2 = new ScottPlot.Plot(500, 400); // bigger plot

bmp = new Bitmap(500, 600);
gfx = Graphics.FromImage(bmp);
gfx.DrawImage(plt1.GetBitmap(), new Point(0, 0));
gfx.DrawImage(plt2.GetBitmap(), new Point(0, 200));
bmp.Save("demo.bmp");
```

Adding this behavior to the multiplot module may be possible with an overload constructor that takes arrays of widths and heights for each subplot, or perhaps relative ratios. I'll leave this issue open while I investigate this!

Hope it helps
Scott

**Comment by ozgur640** [comment]
Thanks for the support, 
Best regards,
Özgür

**Comment by swharden** [comment]
Hi @ozgur640, after thinking about this some more I decided to support this eventually (I added it to the list on #412) but it's low priority right now since this can be achieved with the code above so I'll close this issue and possibly open it again when I start working on this feature in the future. Thank you for your question!
