### ISSUE TITLE
SignalXY plot with non connecting gaps

### ISSUE THREAD

**Issue by Bajkman** [swharden/ScottPlot#570]
Hi Scott,

first great library! I am looking to switch to it from livecharts, but I have one thing that don't know how to handle. Gaps in my data (date, double) are connected on plot. Is there a way to not have gaps connected? Maybe inputting (date, NaN)?

Best regards,
Greg

**Comment by swharden** [comment]
Hi @Bajkman, I'm happy to hear you enjoy ScottPlot!

ScottPlot strictly does not support arrays containing `double.NaN` (or `double.PositiveInfinity`, or `double.NegativeInfinity`). There is an open PR (#553) which seeks to make this more obvious by throwing exceptions if it is attempted. To show two disconnected lines with the present library you must create two separate scatter plots.

However, your question is a very common one. I find that many people intentionally put `double.NaN` in their data and expect scatter plots to display a gap in the line. This makes me wonder if adding `double.NaN` support to scatter plots is a better route than throwing exceptions if it is attempted. The downside to this is that performance of scatter plots will be reduced, but scatter plots are already not particularly performant so it may not be a huge loss. I'll continue to explore this topic and track progress in this issue.

**Comment by StendProg** [comment]
Hi there, 
@Bajkman I think you shoud use separate `Plottable` for each bunch of data, they are created for this. Just make them all same color. I think `ScottPlot` can easily handle even hundreds of individual `Plotables`. The only problem might be with the incorrect legend.

**Comment by Bajkman** [comment]
Hi,
@swharden Thanks for the quick answer, the scatter plot in our case is not very fast (1 day of 1-sec data) and the signalplot draws that in a matter of second, while scatterplot took quite a while. 
@StendProg I will try with the bunch of separate plottables. Thank for the idea.

Best regards,
Grega

**Comment by Bajkman** [comment]
Hi,
@StendProg your idea is working 👍 I have a plot with gaps.
@swharden Is there a way to show a legend of only certain plots? currently legend isn't showing, which I guess the reason is I have to many plots (14+)?
There is also an issue with grid label, after moving graph, the graph redraws but also the dateTimeX labels are drawn over the labelX.
I recorded it. [https://streamable.com/xkuqfx]

Best regards,
Greg

**Comment by StendProg** [comment]
Hi @Bajkman,
> I have a plot with gaps. Almost 600K+ points and everything happens in less than a second

I'm glad to hear, to be honest, there were small doubts that it won't work


>  Is there a way to show a legend of only certain plots? currently legend isn't showing, which I guess the reason is I have to many plots (14+)? Also can the legend position be set?
There is also an issue with grid label, after moving graph, the graph redraws but also the dateTimeX labels are drawn over the labelX.
I recorded it. [https://streamable.com/xkuqfx]

If you have the time, could you please put these questions into separate `Issues`, that would make it easier for @swharden

**Comment by swharden** [comment]
Thanks @StendProg for answering @Bajkman's question regarding disconnected plots (and the solution being to create multiple plots).

> Is there a way to show a legend of only certain plots?

Hi @Bajkman, 

When creating plots notice the `label` argument. If that argument is set, that item will appear in the legend. If it is not set (or set to `null`) it will not appear in the legend.

This example is similar to your question, and if one of the label arguments were omitted that line would not appear in the legend
https://swharden.com/scottplot/cookbooks/4.0.40/#plottypes-signal-styled-signal-plot

Hope this helps!
Scott
