### ISSUE TITLE
Avalonia Quickstart and Demo

### ISSUE THREAD

**Issue by Benny121221** [swharden/ScottPlot#574]
**What can we do to make ScottPlot better?**
Avalonia has a quickstart demo in /ScottPlot/src/ScottPlot.Demo.Avalonia/, however on your website https://swharden.com/scottplot/quickstart it isn't included. Only CLI, WPF, and WinForms are there. It would also make sense to modify the kink in readme: https://github.com/swharden/ScottPlot/blob/600d3d9d0486a9fea34d241b04f629a98bfc78da/README.md#quickstart

The [ScottPlot Roadmap](https://github.com/swharden/ScottPlot/blob/master/dev/roadmap.md) may provide additional context regarding current goals and future directions.

**Comment by swharden** [comment]
Hi @Benny121221, I committed the website pages (they're markdown) to this repo. 

https://github.com/swharden/ScottPlot/blob/master/dev/website/quickstart.md

If you add an Avalonia Quickstart you think is best and create a PR, I can merge it in and update the website. What do you think?

**Comment by swharden** [comment]
... or if it's easier, if you write some markdown in this issue thread I can copy/paste it into the website. Whichever is most convenient for you! I can help make the screenshot too. It's mostly the simplest way to set up the Avalonia environment I'd really like your input on.

**Comment by StendProg** [comment]
Hi there,
@Benny121221 what do you think about adding `Cookbook` demo in `ScottPlot.Demo.Avalonia`? In my opinion, this is not such a difficult task, since it will rely on `ScottPlot.Demo`. This will make `Avalonia` `Control` noticeably more attractive.

**Comment by Benny121221** [comment]
@StendProg yeah I was actually avoiding doing that...

I have the cookbook working on my fork: https://github.com/Benny121221/ScottPlot/tree/avalonia-cookbook, but I haven't done any of the demos. But that's the easier (and less important) part. All the buttons in the app are dead except the "Open Website" and the "Launch Cookbook" buttons.

There are a few issues with the cookbook as well around resizing, changing demos doesn't prompt the plot to resize until the window is resized. I don't know if this is because of the Avalonia user control or the cookbook. I wrote both of them so I guess either way it's my fault 🙁

**Comment by StendProg** [comment]
> There are a few issues with the cookbook as well around resizing, changing demos doesn't prompt the plot to resize until the window is resized.

https://github.com/Benny121221/ScottPlot/pull/4 fix that.

Of the noted shortcomings, the mouse cursor does not change in `Draggable` demos. Most likely it is the `Avalonia.Control` that does not implement this functionality.

**Comment by Benny121221** [comment]
> Of the noted shortcomings, the mouse cursor does not change in Draggable demos.

AFAIK Avalonia does not yet support changing the cursors over an element, although it's entirely possible that I just haven't found how yet.

**Comment by swharden** [comment]
The new Avalonia demo was merged in #576, thanks again @Benny121221!
