### ISSUE TITLE
Road to ScottPlot 4.1

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#578]
### Update on November 17, 2020

**⚠️ I am reducing effort on issues and PRs while I work on this daily.**

* See [changelog.md](https://github.com/swharden/ScottPlot/blob/master/dev/changelog.md) for a summary of major changes.
* See [roadmap.md](https://github.com/swharden/ScottPlot/blob/master/dev/roadmap.md) for a big-picture discussion of plans and goals
* I merged #605 which accomplishes most of the goals described on this page
* The master branch is now ScottPlot `4.1-beta`. Old source code has its own [4.0-stable](https://github.com/swharden/ScottPlot/tree/4.0-stable) branch.

### Plottables to Refactor
- [x] Candlestick / OHLC - [PlottableOHLC.cs](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/plottables/PlottableOHLC.cs)
- [x] Annotation - [PlottableText.cs](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/plottables/PlottableText.cs)
- [x] Bar - [PlottableBar.cs](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/plottables/PlottableBar.cs)
- [x] ErrorBar - [PlottableErrorBars.cs](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/plottables/PlottableErrorBars.cs)
- [x] Function - [PlottableFunction.cs](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/plottables/PlottableFunction.cs)
- [x] HLine - [PlottableAxisLine.cs](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/plottables/PlottableAxisLine.cs)
- [x] HSpan - [PlottableAxisSpan.cs](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/plottables/PlottableAxisSpan.cs)
- [x] VLine - [PlottableAxisLine.cs](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/plottables/PlottableAxisLine.cs)
- [x] VSpan - [PlottableAxisSpan.cs](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/plottables/PlottableAxisSpan.cs)
- [x] Heatmap - [PlottableHeatmap.cs](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/plottables/PlottableHeatmap.cs)
- [x] Image - [PlottableImage.cs](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/plottables/PlottableImage.cs)
- [x] Pie - [PlottablePie](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/plottables/PlottablePie.cs)
- [x] Polygon - [PlottablePolygon.cs](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/plottables/PlottablePolygon.cs)
- [x] Polygons - [PlottablePolygons.cs](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/plottables/PlottablePolygons.cs)
- [x] Populations - [PlottablePopulations.cs](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/plottables/PlottablePopulations.cs)
- [x] Radar - [PlottableRadar.cs](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/plottables/PlottableRadar.cs)
- [x] ScaleBar - [PlottableScaleBar.cs](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/plottables/PlottableScaleBar.cs)
- [x] Scatter / ScatterHighlight - [PlottableScatter.cs](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/plottables/PlottableScatter.cs) [PlottableScatterHighlight.cs](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/plottables/PlottableScatterHighlight.cs)
- [x] Signal / SignalConst / SignalXY (#585)
- [x] Text - [PlottableText.cs](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/plottables/PlottableText.cs)
- [x] VectorField - [PlottableVectorField.cs](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/plottables/PlottableVectorField.cs)

### Renderables to Refactor
- [x] Axis labels
- [x] Axis tick marks
- [x] Axis tick labels
- [x] Grid lines
- [x] Figure and Data background
- [x] Error message
- [x] Benchmark message

### Refactor / Large Features
- [x] Delete the `Plottable` class and replace it with `IPlottable`
- [x] Change plottable namespaces (`PlottableScatter` becomes `Plottable.Scatter`)
- [x] support multiple X and Y axes ✨

### Remaining Tasks
- [x] Make GetAxisLimits() return AxisLimits object
- [x] Create a control to test a timer-based render method
- [x] Create new plottables specifically for growing data (mark public data fields readonly and provide setters to replace data arrays)
- [x] Improve data validation for plottables (create separate pre-render and deep validation methods in an interface)

### Extra release of 4.0
- [x] Add `RenderLock()` and `RenderUnlock()` fields to help with multi-threaded plot manipulation
- [x] Add NuGet message noting transition to 4.1 and to check preleases
- [x] Review all the items on #412 since many have now been completed or made obsolete

**Comment by StendProg** [comment]
Hi @swharden,
I can take `Signals` after you pave the way on some other Plottables.

The big difficulty in configuring via properties is that you cannot guarantee the valid state when setting related properties. For example, if the user wants to change the size of the `xs` and `ys` arrays. He will first change one array, transfer the Plottable to an invalid state, and it is impossible to control in any way what he then changes and `ys` before calling Render.

This problem can be solved by introducing an additional API for related properties, which allows them to be set only together, and the prohibition to change properties individually. For example SetNewData(newXs, newYs). But this will of course clutter up a lot and complicate everything for the user.

On the other hand, we can implement some sort of `promise` subsystem. When changing the` xs` property, the promise to resolve the discrepancy flag is set. If the correct `ys` array is then given then the promise flag is cleared. If at the time of rendering there are unresolved promises, then inform the user about an invalid state in some way (throw or skip render or ...).

Well, option 3 is the most preferable at the moment, not to consider this problem at this stage.

**Comment by swharden** [comment]
> guarantee the valid state

I am considering making plottables inherit `IPlottable` and implement `void IsValidData(bool deep = false)`...

- This would force people who make plottables to consider how to best validate them. Work you did in #553 can make this easier using decorators and reflection.

- Shallow (non-deep) validation would just check to ensure arrays are not null and have equal lengths. Shallow validation will be run before every render since it is so fast.

- Deep validation would do things like check every value of a double is finite and/or ascending. Deep validations would only be requested manually or if diagnostic mode is enabled.

- Perhaps another property could control the behavior that happens when validation fails. It would be excellent if the user can control if a failed validation throws an exception, prints to the Debug log, or maybe displays a failure message on the graph itself. It seems like a descriptive failure message would be useful, maybe involving `string DataValidationStatus` property or something... I'm still thinking about this one!

**Comment by swharden** [comment]
I implemented most of what was discussed above in the `PlottableText` object. @StendProg if you take a look I'm interested to learn what you think!

I'm most unsure about how to proceed with validation. I know a lot of work was recently done in this area (#553), but if validation occurs _inside_ plottables and custom, string-based, plot-type-specific error messages are involved, it may be a good idea to avoid the complexity associated with decorators and reflection and implement validation inside a simple method defined by the interface. I'm still thinking about this one...

I'm trying to strangle the `Plottable` class (an abstract class with all abstract methods) and move its functionality toward `IPlottable`. Once all plottables implement `IPlottable` I plan to delete the `Plottable` class and move all its methods into the new interface. This last step is a breaking change, so I'll save that for 4.0 -> 4.1.

## Notable New Code

**`IPlottable` has a new Render method** which passes a simple object into the render method (instead of the whole settings module).

https://github.com/swharden/ScottPlot/blob/43264d4ab25a312702b8287ac51b0e15360261ab/src/ScottPlot/plottables/IPlottable.cs#L12-L18

https://github.com/swharden/ScottPlot/blob/43264d4ab25a312702b8287ac51b0e15360261ab/src/ScottPlot/Renderer.cs#L27

https://github.com/swharden/ScottPlot/blob/43264d4ab25a312702b8287ac51b0e15360261ab/src/ScottPlot/Renderer.cs#L36-L45

**Validation methods inside plottables are easy to read and have error messages:**
https://github.com/swharden/ScottPlot/blob/43264d4ab25a312702b8287ac51b0e15360261ab/src/ScottPlot/plottables/PlottableText.cs#L55-L75

**I simplified the constructor.** I think my plan is to only accept arrays as constructor arguments, but all value types will be public properties.
https://github.com/swharden/ScottPlot/blob/43264d4ab25a312702b8287ac51b0e15360261ab/src/ScottPlot/Plot/Plot.PlotText.cs#L30-L46

**Comment by StendProg** [comment]
Hi @swharden ,
I checked PlottableText, and realized that we have a misunderstanding.
I mean by `properties`, directly C # `properties`, i.e. a couple of `get/set` methods flavored with syntactic sugar. You are apparently the properties of the `Plotable` themselves, and you express them as public `fields` in c # terms.
All my thoughts were based on my delusion, and I saw everything differently. You can validate the data directly in the setter, and forget that your object may be in an invalid state, setters will not allow this to be. For this they are created. 
The only problem with this approach is the impossibility of joint validation of separate properties. I described this earlier.

With your current approach, that has a right to exist. Since you do not have any control over the values of the fields, the user can change them at any time, as much as he wants, to any value he wants. You are forced to validate all of these fields before each render, even if none of them actually changed.

Actually, to solve this problem with performance, setters were invented, in fact, they solve much more problems, but I will only say that in this particular case, using an approach with validation is quite acceptable. Using setters will greatly increase  code, albeit in a simpler form. 
In the end, it's up to you, I just stated what I think.

**Comment by StendProg** [comment]
This is an example of how I see it.
https://github.com/StendProg/ScottPlot/blob/PlottableTextProperties/src/ScottPlot/plottables/PlottableText.cs

I don't think it is appropriate to check for NAN and `Infinity` every time in setters, this is the task of the diagnostic mode, or the manual call of `IsValidData()`. I left them in the setters just for an example, `PlottableText` require only one check `FontSize > 0`. In other plotables, more checks will be required.

**Comment by swharden** [comment]
Hi @StendProg, thank you for your feedback!

> realized that we have a misunderstanding

I now see the misunderstanding! Indeed, I frequently used the word `property` when I should have said `field`.

> Since you do not have any control over the values of the fields, the user can change them at any time, as much as he wants, to any value he wants. You are forced to validate all of these fields before each render, even if none of them actually changed.

You raised some excellent points! Here are my thoughts about what you said:

1) **Plottables may temporarily have a bad state, as long as good state is achieved before rendering.** An example is replacing `xs` and `ys` of a scatter plot where the new arrays have different lengths than the originals. You must update one before the other, so briefly one array will be a different length than the other. You correctly pointed out this is why it is not possible to perform all validation logic inside properties.

2) **State validation must be performed before each render.** This is why I think it is useful to have shallow and deep validation methods. Shallow validation (checking arrays are not null and are the same length) is so fast that this is not a performance problem. Deep validation is slow, so this should be run manually (not before every render).

There is one more option... We could add a `bool needsValidation` field and any time a setter is called it could be set to `true` so that validation would occur on the next render. I don't prefer this because it adds "noise" in the code and probably not any meaningful performance improvement. 

> Actually, to solve this problem with performance, setters were invented, in fact, they solve much more problems, but I will only say that in this particular case, using an approach with validation is quite acceptable.

I agree! Putting validation logic in property setters can achieve a lot (e.g., [your code example](https://github.com/StendProg/ScottPlot/blame/PlottableTextProperties/src/ScottPlot/plottables/PlottableText.cs)). However, for this case there are complex validation tasks which require comparing properties to each other, and there are complex differences in shallow vs. deep validation, so I think a validation method (with a `deep` argument) makes sense for this application. One small advantage of [my code example](https://github.com/swharden/ScottPlot/blob/43264d4ab25a312702b8287ac51b0e15360261ab/src/ScottPlot/plottables/PlottableText.cs#L55-L75) is that the `ValidationErrorMessage` string will contain multiple validation error messages if multiple errors exist.

I also noticed how you made all public properties capitol in https://github.com/StendProg/ScottPlot/commit/50ddd79fa3b6c91cbbc51a1e8828b60c0d2aa113. I like this, and it is consistent with the [C# Capitalization Rules for Identifiers](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions). I will make this change for all public fields and properties in ScottPlot 4.1

**Comment by swharden** [comment]
Hi @StendProg, I made some large changes which I isolated in #605 (and transitioned version 4.0 -> 4.1). I don't have to merge this, but so far I think it looks good and I am very interested in your thoughts! Many files changed so I summarized the major changes here:

## `Plottable` has been replaced by `IPlottable`
https://github.com/swharden/ScottPlot/blob/5e7750d8911de43a070694c904c1ff321532b2e7/src/ScottPlot/plottables/IPlottable.cs#L11-L19

## Validation inside plottables
I really liked your diagnostic mode data validation ideas! They are now now incorporated in every plottable. I created a static class to hold methods to make it easy for plottables to validate themselves. If a plottable's `ErrorMessage` method returns a string, it's considered an error. Some plottables have very unique validation rules (e.g., polygons must have at least 3 points).

https://github.com/swharden/ScottPlot/blob/5e7750d8911de43a070694c904c1ff321532b2e7/src/ScottPlot/plottables/PlottablePolygon.cs#L65-L88

Fast validation (like ensuring xs and ys have the same legnth) happen on every render without impairing performance. Deep validation can be turned on and off.

I didn't remove property validation code in the signal plottable yet... but I suspect it can be replaced by simple public fields again.

## Diagnostic mode
`Plot.DiagnosticMode` has been replaced by `Plot.Validate()` with arguments customizing shallow/deep validation and also defining what to do if validation fails (do nothing, show error on the plot, or throw exception)

https://github.com/swharden/ScottPlot/blob/5f6f302794af396ad0c6d202a7a0108c4020c5fb/src/ScottPlot/Plot/Plot.Settings.cs#L18-L24

![image](https://user-images.githubusercontent.com/4165489/96946926-ada47280-14af-11eb-90a1-ae18287e901b.png)

**Comment by StendProg** [comment]
Hi @swharden, looks great, especially customizable error output.

I left a review, but there is nothing significant. (There are a lot of changes, and I could not go through everything very carefully)

**Comment by swharden** [comment]
> Hi @swharden, looks great, especially customizable error output.
> 
> I left a review, but there is nothing significant. (There are a lot of changes, and I could not go through everything very carefully)

This is great to hear! Thanks for your input (and your recent comments in #605). I am reassured that I am on a good path and will continue working in this direction 👍

**Comment by swharden** [comment]
I've been working on the validation system again and I'm close to a solution that feels good. Scatter plots, for example:

* data arrays `xs` and `ys` are exposed so users can change values inside the array easily (this is encouraged), but they are now `private set` so they cannot be replaced by assignment. Users have to call a `ReplaceX()`, `ReplaceY()`, or `ReplaceXY()` to replace these arrays with new ones.
  * Length and null checking are performed upon replacement (so if it fails, it fails fast)
  * I know this could be done in a property, but frequently replacing data arrays in existing plottables is usually not recommended and not something I want to encourage. I hope putting this operation behind a function will make users slow to use it.
  * I will create a ScatterList plot type. I have found that a common task is to add X/Y points over time, and a list is a good way to do this (much better than making new arrays and replacing `xs` and `ys` every time a new point is added!)

* Plottables have a `ValidateData(bool deep)` method.
  * Shallow validation happens before every render to make sure things are not null and have the proper lengths
  * Deep validation can happen upon request
  * When validation fails it always throws an `InvalidOperationException` (no catching or returning strings, no displaying errors on the plot image). I think failing hard and failing fast is a good idea. NaNs in data or mismatched X and Y lengths are big problems, so I think a big error is warranted.

* I thought of some ways to do `NaN` checks without requiring deep validation:
  * `Scatter.GetAxisLimits()` uses uses `Math.Min()` and `Math.Max()` to find data limits, and those methods return `NaN` if one of the inputs is `NaN`. If `NaN` or `Infinity` is present anywhere in the original data, it will be in the final limits, an exception is thrown.
  * `AxisAuto()` calls every plottable's `GetAxisLimits()`, and this happens automatically before the first render in 99% of cases, so I think this will let almost everybody know there is a problem very fast without having to enable "diagnostic mode" manually. 
  * Signal plots are a little different. Their min/max search strategies only return `NaN` if every value is `NaN`. I check for this at the end of `GetAxisLimits()` now, and throw if min or max `NaN`. This only happens if every value in the data is `NaN`, but it's no extra cost and seems worth doing.
  * I added a `NaN` check to Signal plots that occurs on the _pixels_ right before rendering lines. I'll probably do this to scatter plots too. There are not many pixels, so this check is fast. It might not catch a single `NaN` in a big data array, but if a whole pixel column is `NaN` it will throw.

**Comment by swharden** [comment]
There is now a working multi-axis demo in the cookbook 🎉 

```cs
// generate sample data to plot
Random rand = new Random(0);
int pointCount = 100;
double[] xs = DataGen.Consecutive(pointCount);
double[] rainfall = DataGen.RandomWalk(rand, pointCount, 1, 10); // small values
double[] organisms = DataGen.RandomWalk(rand, pointCount, 1000, 20000); // large values

// create a plot and customize the primary X axis
var plt = new ScottPlot.Plot(600, 400);
plt.XAxis.Configure(label: "Days After Volcano Eruption");

// add a scatter plot and customize the primary Y axis
var scatter1 = plt.PlotScatter(xs, rainfall);
plt.YAxis.Configure(label: "Daily Rainfall (cm)", color: scatter1.color);

// add another scatter plot but give it a custom vertical axis index
var scatter2 = plt.PlotScatter(xs, organisms);
scatter2.VerticalAxisIndex = 3;

// add a new vertical axis using same axis index as the second scatter plot
var secondLeftAxis = plt.AddAxis(Renderable.Edge.Left, axisIndex: 3);
secondLeftAxis.Configure(label: "Number of Organisms", color: scatter2.color);
```

![multi-y2](https://user-images.githubusercontent.com/4165489/100549937-4fa04300-3244-11eb-848d-c90c76e23065.gif)

I want to continue to improve the API by simplifying it. I am not satisfied with how messy the argument list is for `Axis.Configure()`. 

* `Axis.Configure()` for options like visibility, layout, label, and color
* `Axis.ConfigureTicks()` for DateTime display, tick density, manual spacing, manual tick labels, multiplier notation, etc.
* `Axis.ConfigureGrid()` for all those grid line options.

Either way, this is a good start!

**Comment by swharden** [comment]
I'll spend some more time today working on the release notes, documentation, and cookbook, but this is on NuGet now 😎
