### ISSUE TITLE
add data export option to right-click menu

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#58]
This feature would be useful for data-logging programs that display new data as it's measured.

This idea was initially raised by @bukkideme in #49 

CSV output makes a lot of sense. It's easy to parse, and easy to load right into programs like Excel.

It gets a little complicated because a single plot may have several plottables, and they can have different X positions. Instead of XYYYY, the output probably needs to be XYXYXYXY.

**Comment by swharden** [comment]
Actually, maybe a pop-up menu to "select which plottable to export" would be nice, as it would let the user only output a single signal. That way output is always XY.

I think the place to start here would be to add an abstract `GetCSV()` method to the `Plottable` object.
https://github.com/swharden/ScottPlot/blob/fe3717fa13b03dd6eb685553af2380746f45e324/src/ScottPlot/plottables/Plottable.cs#L10-L19

**Comment by Padanian** [comment]
Feel free to let me know if I can be of any help at any point.

**Comment by Padanian** [comment]
May I suggest to avoid SaveCSV for every plottable, and just create a JSON or XML with all plottables. It would be much easier to serialize from a Plottable tree class to JSON or XML.

**Comment by swharden** [comment]
This turned out to be pretty easy! I implemented SaveCSV (4a04ffc6f447df522e5247716ea441da66244bd4) and added demos to the cookbook: https://github.com/swharden/ScottPlot/tree/master/cookbook#save-scatter-data

I'll figure out the best way to add it to the right-click menu, because it will probably require creation of a pop-up dialog (to select which of multiple plots to save). I'll keep it simple but leave room to add other data format exports later.

**Comment by swharden** [comment]
I added a "Save Data" button to the right-click menu. It only saves the first object plotted, and the menu item only lights up when the first object is savable as CSV (e.g., you can't save an axis line).

It's a pretty light implementation, but we can add complexity if the need arises. ***The next step would be for a whole new dialog to pop up listing all the plottable objects, allowing the user select which plot to export, and allowing the user to select which format (XML, JSON, CSV), and things like precision and tab vs. comma separation.*** This seems like a pretty heavy addition, and if someone wants to work on that they can, but I'm happy to leave this where it is for now until we are ready to invite the additional complexity.

![image](https://user-images.githubusercontent.com/4165489/62166545-0ad26800-b2ef-11e9-8344-4daf6be17988.png)
