### ISSUE TITLE
Horizontal label draw

### ISSUE THREAD

**Issue by Bajkman** [swharden/ScottPlot#580]
Hi,

Is it possible to have labels drawn horizontally, so that they don't overdraw the plot?

Best regards,
Greg
![Capture1](https://user-images.githubusercontent.com/72062127/95045558-91988700-06e2-11eb-80d2-d0bb86d6f42a.PNG)

**Comment by swharden** [comment]
Hi @Bajkman, currently this is not possible. You can call `plt.GetLegendBitmap()` to get the legend as a `Bitmap` which you can apply to a picturebox elsewhere on your Form. This is the best way to ensure your legend does not interfere with your data.

Supporting horizontal legend items (or even column configuration) is a good idea, and I've added it to the list of features I'd like to eventually support in #412. Thank you for the suggestion!

Scott
