### ISSUE TITLE
More flexible tick spacing

### ISSUE THREAD

**Issue by Benny121221** [swharden/ScottPlot#581]
**What can we do to make ScottPlot better?**
Currently automatic tick spacing is based on "nice numbers". These numbers are defined as a literal here: https://github.com/swharden/ScottPlot/blob/f9b4b2ad5520610c1d8bce4bba8e33bf3e318876/src/ScottPlot/Config/TickCollection.cs#L203

These give nice numbers in decimal, but not any other base. When I worked on #475 I neglected to work on this and then I forgot about it for several months :/ This is theoretically a very easy change, perhaps add another parameter for radix? Then nice numbers in hex could be `[2, 2, 2, 2]`, giving nice numbers of `[16, 8, 4, 2, 1]`. And mentions to `Log10` would be replaced with a call to the log function with the appropriate base.

Admittedly this is a pretty niche feature and while a function to create "nice" numbers for any radix is possible I'm unsure that it would really be used. As it is the only commonly used radices are decimal, hex, and binary. You can't really create a nice looking number in binary anyways so there's probably not much downside to just hardcoding in nice numbers for hex like was done for decimal. Might get nicer results that way too if it's hand done for each radix. If there's a compelling case that other radices might be used then I may change my mind. Keep in mind that [radices above 16 are not currently supported](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/Tools.cs#L420L424).

**Comment by Benny121221** [comment]
I implemented this on my branch https://github.com/Benny121221/ScottPlot/tree/nice-hexnumbers, however, I added some new tests and they didn't pass. I'll try and fix that or rewrite the offending code.

**Comment by swharden** [comment]
Hey @Benny121221, this is an interesting idea! I agree that on one hand this is a pretty obscure use case, but on the other hand it seems that supporting it looks to be pretty simple.

As you refine this you could add another optional argument at the end of the `Plot.Ticks()` list

https://github.com/swharden/ScottPlot/blob/f9b4b2ad5520610c1d8bce4bba8e33bf3e318876/src/ScottPlot/Plot/Plot.Ticks.cs#L40-L42

to store a feature toggle in the end of the ticks config module

**Comment by swharden** [comment]
Oops, I hit enter with the comment button selected and I guess I hit send too early. I pretty much captured all the technical details with the message above, but I wanted to follow-up with a "thanks for your effort on this one"! 

I'm pretty deep working on #578 for at least the next few days (it's taking a lot longer than I expected) so no rush finishing this one, but I'm excited to see how it ends up!

**Comment by Benny121221** [comment]
> As you refine this you could add another optional argument at the end of the Plot.Ticks() list ... to store a feature toggle in the end of the ticks config module

To toggle which feature? The radix and prefixes are already there:
https://github.com/swharden/ScottPlot/blob/f9b4b2ad5520610c1d8bce4bba8e33bf3e318876/src/ScottPlot/Plot/Plot.Ticks.cs#L36-L39

Perhaps the use of both `base` and `radix` here isn't a great plan, but currently base is the only word used for user-facing code. So at least the user isn't confused.

**Comment by swharden** [comment]
> currently base is the only word used for user-facing code

I agree with your assessment - we can leave the method the way it is and use the word "base" in user-facing arguments and documentation. Thanks again for this @Benny121221!
