### ISSUE TITLE
bar plot value labels are wrong when yOffset is used

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#584]
Thank you Terbaco for mentioning this over email.

This bug should be fixed, but also it would be nice if users could provide an array of manual plot value labels. Perhaps if this array is null the values will be used, but if it is not the labels will be used.

![image](https://user-images.githubusercontent.com/4165489/95345371-a6af1a80-0888-11eb-9198-1b87dac40ca5.png)

**Comment by Benny121221** [comment]
Interesting, this one isn't "wrong" so much as it's the wrong choice for the default. For example, this could be a worthwhile addition (excuse the poor photoshop, even by my standards):

![image](https://user-images.githubusercontent.com/8635304/96385266-055d7980-1150-11eb-972b-9ec48e0551ba.png)

I could see this being useful for waterfall plots especially, which were added in June #476, however, the default certainly should be to show the value, not the growth/loss.

**Comment by swharden** [comment]
Probably the best long-term solution would be to let the user define what the labels by passing in a `string[]`... I'll add it to #412 

For now I changed the default behavior based on the _principle of least astonishment_ which I think is good enough to mark this issue resolved 😎
