### ISSUE TITLE
Plottable H and V Span draglimits while drag fixed size

### ISSUE THREAD

**Issue by citizen3942** [swharden/ScottPlot#586]
When a plottable **H-** or **VSpan** is set up and it is configured to be a **DragFixedSize** span, and **dragLimitLower** and/or **dragLimitUpper** are set, the span can exit those limits while dragging. 
Currently, if I drag on the 2nd edge the 1st edge can get lower than the **dragLimitLower** value and the same opposite with the 1st edge dragging.
I believe this is not the kind of reaction one would expect.

I believe this part:
https://github.com/swharden/ScottPlot/blob/0fb684146dceb2c4963c9b2289ba9e8494d160df/src/ScottPlot/plottables/PlottableHSpan.cs#L95-L120

should check for boolean:
https://github.com/swharden/ScottPlot/blob/0fb684146dceb2c4963c9b2289ba9e8494d160df/src/ScottPlot/plottables/PlottableHSpan.cs#L71

And adapt to **dragLimitLower** and **dragLimitUpper** values.

**Comment by citizen3942** [comment]
Even if I disable dragFixedSize it still is fixed size span? Why is that? Technically it should not....

**Comment by StendProg** [comment]
Hi @citizen3942,
#589 fix this issue.

**Comment by citizen3942** [comment]
> Hi @citizen3942,
> #589 fix this issue.

Yes indeed commits 6f0091db8ccf4633a5ed1d9a403df05c9a2280e7 and 2860ea53c2d75b5927ff2bd3a1762c25e459f148 worked perfectly.
I see that there is some refactoring for PlottableAxisSpans.
Merging with refactored function, I get:
```csharp
public void DragTo(double coordinateX, double coordinateY, bool isShiftDown = false, bool isAltDown = false, bool isCtrlDown = false)
        {
            if (!DragEnabled)
                return;

            double sizeBeforeDrag = position2 - position1;

            if (DragFixedSize || isShiftDown)
            {
                double AbsSize = Math.Abs(sizeBeforeDrag);
                bool DragMaxEdge = (position2 >= position1 && edgeUnderMouse == Edge.Edge2)
                                || (position1 >= position2 && edgeUnderMouse == Edge.Edge1);
                if (DragMaxEdge)
                {
                    if (coordinateX < dragLimitX1 + AbsSize) coordinateX = dragLimitX1 + AbsSize;
                    if (coordinateX > dragLimitX2) coordinateX = dragLimitX2;
                    if (coordinateY < dragLimitY1 + AbsSize) coordinateY = dragLimitY1 + AbsSize;
                    if (coordinateY > dragLimitY2) coordinateY = dragLimitY2;
                }
                else
                {
                    if (coordinateX < dragLimitX1) coordinateX = dragLimitX1;
                    if (coordinateX > dragLimitX2 - AbsSize) coordinateX = dragLimitX2 - AbsSize;
                    if (coordinateY < dragLimitY1) coordinateY = dragLimitY1;
                    if (coordinateY > dragLimitY2 - AbsSize) coordinateY = dragLimitY2 - AbsSize;
                }
            }
            else
            {
                if (coordinateX < dragLimitX1) coordinateX = dragLimitX1;
                if (coordinateX > dragLimitX2) coordinateX = dragLimitX2;
                if (coordinateY < dragLimitY1) coordinateY = dragLimitY1;
                if (coordinateY > dragLimitY2) coordinateY = dragLimitY2;
            }

            if (edgeUnderMouse == Edge.Edge1)
            {
                position1 = IsHorizontal ? coordinateX : coordinateY;
                if (DragFixedSize || isShiftDown)
                    position2 = position1 + sizeBeforeDrag;
            }
            else if (edgeUnderMouse == Edge.Edge2)
            {
                position2 = IsHorizontal ? coordinateX : coordinateY;
                if (DragFixedSize || isShiftDown)
                    position1 = position2 - sizeBeforeDrag;
            }
            else
            {
                Debug.WriteLine("DragTo() called but no side selected. Call IsUnderMouse() to select a side.");
            }

        }
```
Perhaps it can be beautified even further.

**Comment by StendProg** [comment]
Hi @citizen3942, thanks for notification.
Changes are too extensive (deleting files that contained all modifications). I think it's easier to make a new PR with the changes you suggested than trying to rebase the existing one.
I have already forgotten the details, so it’s more correct for you to do a PR since you figured it out again. If you have any difficulties, I am always ready to help.

**Comment by swharden** [comment]
Hey @citizen3942, sorry it took me so long to get to this. I've been devoting all my attention to #578 but it has taken longer than expected. 

@StendProg did a good job of fixing this, but then that refactor caused a merge conflict. Sorry for the inconvenience! I'll fix this directly in the master branch today.

**Comment by swharden** [comment]
I think this has been fixed now - thanks for mentioning it @citizen3942!
