### ISSUE TITLE
Draggable DragEnter and DragExit Event 

### ISSUE THREAD

**Issue by charlescao460** [swharden/ScottPlot#592]
Hi,

First of all, thank you for this wonderful library!!

I am now working on a program which will play video, and in the meantime, show corresponding time-series data. 

And, I'd like to use `PlottableHSpan` as a slider to control the video playing, therefore user can use to navigate on displayed data. (See picture attached at the end) 

Unfortunately, I didn't find such drag events in the API. I'm using WPF, so I implemented it by myself in the way below, which is basically filtering `MouseButtonUp` event by myself. 
```C#
WpfPlot Plot = new WpfPlot();
Plot.MouseLeftButtonUp += OnXSpanMouseUp;
```
```C#
        private Point GetPixelPosition(MouseButtonEventArgs e)
        {
            float dpiScale = Plot.plt.GetSettings(false).gfxFigure.DpiX / 96;
            Point pos = e.GetPosition(this);
            pos.X *= dpiScale;
            pos.Y *= dpiScale;
            return pos;
        }
```
```C#
     private void OnXSpanMouseUp(object sender, MouseButtonEventArgs e)
     {
         var mousePixel = GetPixelPosition(e);
         var draggable = Plot.plt.GetDraggableUnderMouse(mousePixel.X, mousePixel.Y);
         if (draggable == null)
         {
             return;
         }
         OnXSpanDragged(); // Actual handler to control video
     }
```

It works fine, but I am wondering if it is possible to add **DragEnter** and **DragExit** event into the API? 

I know how to implement it in WPF, and I can create a PR for it. But I don't know how to implement for other framework. 

It would be great if someone can help. 

![image](https://user-images.githubusercontent.com/33741854/95623437-3dbfd200-0a43-11eb-8000-f5eac1c4ffc5.png)

**Comment by StendProg** [comment]
Hi @charlescao460,
`WinForms control`(`FormsPlot`) already contain `MouseDragPlottable`, `MouseDragged` and `MouseDropPlottable` events. But `WPF control`  does not have this implementation.
>  know how to implement it in WPF, and I can create a PR for it

You are welcome, any helps matter.
The only thing I want to note is that it is important that different controls have a similar API, so try to repeat the events already available in `WinForms`.

**Comment by charlescao460** [comment]
Hi @StendProg 

Thank you for your information!

I checked `OnMouseDragPlottable`, `OnMouseDownOnPlottable`, and `OnMouseDropPlottable` in [FormsPlot.cs](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot.WinForms/FormsPlot.cs), and I don't think they fit my circumstance -- those events are being called when `plottableBeingDragged` is not null, and the event argument is empty. I didn't find a way that API user could know which plottable is being dragged. 

Probably we need a new EventArgs type containing the plottable being dragged and pass it to handler ? (Then where should I add it? I don't think there is any custom EventArgs in this repo, can I add it in the core? )
Or probably we can make `plottableBeingDragged` public (not ideal)?
Or we can make the event sender to be the plottable rather than the Plot, but this does not look good to me either.

**Comment by charlescao460** [comment]
Never mind, I opened a PR here: #593 
I added EventArgs.

**Comment by StendProg** [comment]
The question of how best to do it has already been raised. For me, the ideal would be an event at the level of `PlottableSpan` that occurs during drag and contains a `new position` #238.
But for certain reasons it was postponed, maybe someday we will return to it.

**Comment by charlescao460** [comment]
#593 was merged, close issue.
