### ISSUE TITLE
Second X-Axis

### ISSUE THREAD

**Issue by GekoCH** [swharden/ScottPlot#594]
Hy

Is it possible to draw a second X axis with different span etc?

Andy

**Comment by StendProg** [comment]
Hi @GekoCH,
> Is it possible to draw a second X axis with different span etc?

Unfortunately, there is no support for additional axes at the moment.
There are big plans for the implementation of many axes, but so far without any specific deadlines.
Here is a similar issue in which you can read the case in more detail if interested. #162.

**Comment by swharden** [comment]
Hi @GekoCH,

This is now possible with ScottPlot 4.1 (which just got merged into the master branch) but this new version is still "pre-release" as I continue to make it better and the user controls are not yet as performant as they could be. 

Feel free to experiment with the new multi-axis functionality in the master branch, and once this becomes stable I'll add examples to the cookbook and publish a NuGet release.

https://github.com/swharden/ScottPlot/blob/71c3876dcef9e6e00225603ec9574e76ec32335c/tests/AxisRenderTests/MultiAxis.cs#L10-L44

![image](https://user-images.githubusercontent.com/4165489/99158951-332dd380-26a6-11eb-84a6-b3eafdc5b487.png)

I'm actively working on this and I hope to be finished soon, so I'll close this issue with the expectation that this will be fully supported and documented shortly...
