### ISSUE TITLE
Tick and Grid spacing should be independent

### ISSUE THREAD

**Issue by bukkideme** [swharden/ScottPlot#597]
Hello!
My goal is to manually set a more dense grid line spacing, but keep tick labels automatic, otherwise they will overlap.

The problem is that, there is no xSpacing/ySpacing settable parameters for Ticks.
If I do the following:
`formsPlot1.plt.Axis(-100, 100, -100, 100);`
`formsPlot1.plt.Grid(xSpacing: 1, ySpacing: 1);`

The result is ugly, the tick labels overlap. 

This could be fixed if we had:
` formsPlot1.plt.Ticks(xSpacing: 10, ySpacing: 10);`

Or could be even better, if we want to keep the things fine after zooming in (setting tick labels dynamically not to overlap):
` formsPlot1.plt.Ticks(autoSpacing: true);`

Is the above goal possible with the recent code, or is it possible to get such feature?

Thanks very much! :)

**Comment by swharden** [comment]
Hi @bukkideme, I don't think this is possible with current code, but there may be an option to add something similar easily. 

Currently there are major ticks (with labels) and minor ticks (smaller marks without labels). Major ticks have grid lines, and minor ticks don't. What if I added an option to draw minor tick grid lines too? Perhaps they could even have a customizable (probably lighter) color. I did something similar to this with the experimental ScottPlot 5 grid system:

![](https://user-images.githubusercontent.com/4165489/91741604-f52f1200-eb82-11ea-9361-17641d9f2b96.gif)

Would adding an option to show grid lines for minor ticks solve this issue?

**Comment by bukkideme** [comment]
Hi @swharden !

Yes, such feature would be great if you can add. And the customizable color/line thickness for (minor tick) gridlines would make the graph look very pro! :)
Thanks!

**Comment by swharden** [comment]
Following up on this, ScottPlot 4.1 is now merged, and axes support separate major and minor grid line customizations.

```cs
var yTicks = plt.GetSettings(false).YAxis.Ticks;
yTicks.MajorGridEnable = true;
yTicks.MajorGridColor = Color.Black;
yTicks.MajorGridStyle = ScottPlot.LineStyle.Dash;
yTicks.MinorGridEnable = true;
yTicks.MinorGridColor = Color.Blue;
yTicks.MinorGridStyle = ScottPlot.LineStyle.Dot;
```

![image](https://user-images.githubusercontent.com/4165489/99572143-38d73200-29a2-11eb-8021-8a7c3ca8a248.png)

I'm still working to improve performance of user controls (a main reason it's still beta / pre-release) and this code may change a bit between now and the first release, but the core functionality is now supported so I'll close this issue and hope to have a refined release ready before too long!
