### ISSUE TITLE
Dynamically add and erase PlotPoint-s - best approach

### ISSUE THREAD

**Issue by bukkideme** [swharden/ScottPlot#598]
Hello!

I wonder how I could do the following best.

I would like to plot N points in a WinForm formsPlot, and keep these N points in a FIFO Queue. The newest should be filled circle, the older 9 points empty ones.
So for example, if N=10, then delete the oldest point at every iteration, and plot the new point.

I tried the following:

`Queue<PlottableScatter> MyPoints;`
`int MovAverN = 10;`

Then calling this method in a loop, feeding in new X-Y values:

```
private void PlotValues(double xVal, double yVal)
        {
            PlottableScatter point = formsPlot1.plt.PlotPoint(xVal, yVal, markerSize: 30, markerShape: ScottPlot.MarkerShape.filledCircle, lineStyle: ScottPlot.LineStyle.Solid, color: Color.Red);

            if (MyPoints.Count >= MovAverN) { formsPlot1.plt.Clear(MyPoints.Dequeue()); }
            MyPoints.Enqueue(point);            

            for (int i=1; i < MyPoints.Count; i++)
            {                
                MyPoints.ElementAt(i).markerShape = MarkerShape.openCircle;                
            }         

            formsPlot1.plt.Axis(-100, 100, -100, 100);
            formsPlot1.Render();
        }
```
As a workaround, of course I could just keep the XY values in the Queue, and redraw/Render everything after a plt.Clear() in each iterations, but I wonder how I could only remove the oldest, and keep the others in a more efficient way.
With this actual approach, I guess the problem is that, the  `formsPlot1.plt.Clear(MyPoints.Dequeue());` method clears all these points, since this method works on the type and not the actual object?

Thanks for any suggestions!
Regards!

**Comment by swharden** [comment]
Hey @bukkideme, 

I haven't studied this problem in detail, but at first glance would replacing the xs and ys arrays solve your problem?

```cs
PlottableScatter scatter;

void Init() {
    scatter = formsPlot1.plt.PlotPoint(originalXs, originalYs);
}

void GotNewData() {
    // manage your queue how you like
    double[] newXs = { /* values to display */ };
    double[] newYs = { /* values to display */ };

    // update the Xs and Ys for the scatterplot
    scatter.xs = newXs ;
    scatter.ys = newYs ;

    // optionally adjust the axis limits too?
    formsPlot1.Render();
}
```

**Comment by StendProg** [comment]
Hi @bukkideme,
> I guess the problem is that, the formsPlot1.plt.Clear(MyPoints.Dequeue()); method clears all these points, since this method works on the type and not the actual object?

You can delete object by passing predicate:
```c#
formsPlot1.plt.Clear(p => p == MyPoints.Dequeue())
```

It doesn't matter for the 10-point example, but if you think about performance you don't need to clear the Plottable at all.
You can manually arrange a FIFO buffer on an array of `Plottables`. And having an index, just update the data and marker values at the correct index. The seeding problem can be solved by turning off visibility.

**Comment by bukkideme** [comment]
Thanks very much for the useful tips! :)
