### ISSUE TITLE
refactor IDraggable

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#602]
* `DragTo()` shouldn't pass keyboard state. That logic should be handled in the user controls.
* `SetLimits()` arguments shouldn't be nullable. ~~Negative and positive infinity can be used when limits are disabled.~~ This should be 4 properties instead of a single setter method, with better names like `XMin`, `XMax`, `YMin`, and `YMax`

https://github.com/swharden/ScottPlot/blob/4a33070788865192592abe7b9136fff70e74af8e/src/ScottPlot/plottables/IDraggable.cs#L7-L14

**Comment by StendProg** [comment]
Hi @swharden,
Once you've decided to do this, it might be worth bringing up an old question #238.
This issue was recently discussed #592.

Adding events directly in the draggable will greatly simplify binding positions to interface (IMHO).

**Comment by swharden** [comment]
Hi @StendProg, this is an excellent idea (and it was a good idea when you first suggested it in #238!)

I gave axis spans and axis lines a `EventHandler Dragged` field, allowing code like this:

```cs
var xs = new double[] { 1, 2, 3, 4, 5 };
var ys = new double[] { 1, 4, 9, 16, 25 };
formsPlot1.plt.AddScatter(xs, ys);

var vline = formsPlot1.plt.AddVerticalLine(3.5);
vline.DragEnabled = true;
vline.Dragged += new EventHandler(OnDragLine);

var vspan = formsPlot1.plt.AddVerticalSpan(10, 20);
vspan.DragEnabled = true;
vspan.Dragged += new EventHandler(OnDragSpan);
```

```cs
private void OnDragLine(object sender, EventArgs e)
{
    var line = sender as ScottPlot.Plottable.VLine;
    Text = $"Line X={line.X}";
}
```

```cs
private void OnDragSpan(object sender, EventArgs e)
{
    var span = sender as ScottPlot.Plottable.VSpan;
    Text = $"Span Y={span.Y1} Y2={span.Y2}";
}
```

User controls will still benefit from improved use of events. I will keep this in mind as I begin to refactor the controls...
