### ISSUE TITLE
Enabling and disabling zoom in Winforms

### ISSUE THREAD

**Issue by dprevato** [swharden/ScottPlot#604]
Hi,
I have a question about zooming: I can zoom a chart using mouse wheel, or I can drag with the mouse, while pressing the central button OR pressing SHIFT + left button.
My issue is: may I disable zooming with the mouse wheel, but keeping enabled the zooming by dragging? 
I found in FormPlot.Configure the properties **enableZooming** and **enableScrollWheelZoom** and thought that setting the latter to false would make the trick; but, alas, it disable also the dragging.
Is there a way to solve my problem? I would be happy also having some advice to solve it by myself without make a mess (maybe placing then a PR... :) )

**Comment by swharden** [comment]
Hi @dprevato, it sounds like you wish to disable the mouse scrollwheel function while preserving all click-and-drag functions.

I just tested this, and if you run this configuration (without any other configuration) I think it gives you the effect you're looking for.
```cs
formsPlot1.Configure(enableScrollWheelZoom: false);
```

Let me know if I misunderstood your issue, or if this does the trick! 👍

**Comment by dprevato** [comment]
Hi @swharden , I tried but I found that tha line does not disable zooming with the scrollwheel, but also disable it by dragging; with that disabled, no zoom at all :)

**Comment by dprevato** [comment]
Issue closed, I will open another one more specific

**Comment by dprevato** [comment]
It does, it's just what I needed :)
Thank you


*Daniele PREVATO*
Rivarolo Canavese - TO


Il giorno gio 22 ott 2020 alle ore 16:15 Scott W Harden <
***@***.***> ha scritto:
