### ISSUE TITLE
Alpha property for PlotText() method

### ISSUE THREAD

**Issue by bukkideme** [swharden/ScottPlot#610]
Hi!

Would it be possible to use alpha property not only for annotations, but for the PlotText methodes?
Thanks very much!
regards,

**Comment by swharden** [comment]
Hi @bukkideme, the `Color.FromArgb()` method can help you create transparent colors for use pretty much anywhere in ScottPlot. For example,

```cs
var plt = new ScottPlot.Plot(400, 300);
plt.PlotText("Hello", 4, 2, 
    fontSize: 100, 
    color: Color.FromArgb(50, Color.Red), 
    alignment: ScottPlot.TextAlignment.middleCenter, 
    bold: true);
plt.SaveFig("test.png");
```

![image](https://user-images.githubusercontent.com/4165489/97878552-c6e9c200-1cec-11eb-8baa-de937e511f6f.png)

Let me know if that doesn't do the trick!

**Comment by bukkideme** [comment]
Hello! Yes, it worked, thanks for the info!
