### ISSUE TITLE
WpfPlot double click null reference exception

### ISSUE THREAD

**Issue by cchiu827** [swharden/ScottPlot#611]
Hi Scott,

Thanks for the great tool. It has been working very nicely in my application.
I found a strange error that when double clicking the plot it said 'Object reference not set to an instance of an object' even though I have turned off the splot.Configure(enableDoubleClickBenchmark: false). The output screenshot is attached. 
Please help.

Thanks,
Chao-An
![Screenshot 2020-11-02 155202](https://user-images.githubusercontent.com/30455670/97928044-6e81e700-1d23-11eb-88fa-a0125f7822bf.png)

**Comment by swharden** [comment]
Hi @cchiu827, thanks for reporting this! Unfortunately I am unable to replicate your error...

I tried installing ScottPlot 4.0.42 from NuGet into a WinForms application and ran the following code and don't get the error:

```cs
formsPlot1.plt.PlotSignal(ScottPlot.DataGen.Sin(51));
formsPlot1.Configure(enableDoubleClickBenchmark: false);
formsPlot1.Render();
```

I tried this with WPF too, but still no error:

```cs
wpfPlot1.plt.PlotSignal(ScottPlot.DataGen.Sin(51));
wpfPlot1.Configure(enableDoubleClickBenchmark: false);
wpfPlot1.Render();
```

Can you provide more information about your code, or more debug information? It may also be helpful to try my simple examples and confirm that works on your end as well.

**Comment by StendProg** [comment]
Hi there,
Since this error is difficult to reproduce, @cchiu827 could you please indicate on which object you received the NullReference?

In the benchmark code, only this line looks suspicious, since the set of fonts may differ on different configurations.
https://github.com/swharden/ScottPlot/blob/4bf514cfe65e19d644db25f961a81f30e44caa2d/src/ScottPlot/Renderable/Benchmark.cs#L19

**Comment by cchiu827** [comment]
Hello, sorry for the late response. I am not able to make an example project to duplicate the issue. I currently set the IsEnabled to false and that solve my issue temporarily. I will keep testing it and might circle back if I need to set the IsEnabled to true and the double click event is still an issue.

Thank you,
Chao-An
