### ISSUE TITLE
How to print a ScottPlot in WPF

### ISSUE THREAD

**Issue by Prybe** [swharden/ScottPlot#613]
Hi,

I would like to know how you would implement a printing functionality for WPF.
Let´s say you want to print the graph with data and axis with the standard windows printing dialog.
Is this possible?

regards
Martin

**Comment by swharden** [comment]
Hi @Prybe,

You can get the current plot as a bitmap with `wpfPlot1.plt.GetBitmap()`, then your question becomes _"How can I print a Bitmap with WPF?"_ which should become easier to answer. One caveat is that the object returned is a `System.Drawing.Bitmap` (a cross-platform object) and not a `System.Windows.Media.Imaging.BitmapImage` (a windows-only object that WPF typically works with).

This topic was recently discussed for WinForms in #524 and you can find some working code examples there. Perhaps you can use the same windows print dialog that sample code used?

![image](https://user-images.githubusercontent.com/4165489/98695189-5b34d400-2340-11eb-840b-ef78d471f49e.png)

I hope #524 is enough to help answer your question! If you get it working and could share a code snippet to help future people with the same question, that would be fantastic.

I'm looking forward to hearing what you find! Thanks for the question --Scott

**Comment by Prybe** [comment]
very fast answer answer 👍 
thx a lot

**Comment by swharden** [comment]
Glad it helped! If you create useful code, I encourage you to copy/paste what you found here so other people who search for the same thing can find it too. 

Let me know if any more questions pop up along the way!
Scott
