### ISSUE TITLE
Annotations should be placed above chart

### ISSUE THREAD

**Issue by jsr1611** [swharden/ScottPlot#614]
**Issue:**

My annotations are placed behind the chart.
![image](https://user-images.githubusercontent.com/38090036/98651153-390d7700-237d-11eb-9dd8-8eba734cc874.png)

**Idea:**

I found this line insde going through the **PlotAnnotation class**:
`public PlottableAnnotation(double xPixel, double yPixel, string label, double fontSize, string fontName, Color fontColor, bool fill, Color fillColor, double lineWidth, Color lineColor, bool shadow);
`
How about if we add here `bool BringToFront: true` argument?

How can I make it work? Or is there any other way to bring my annotations to front that ScottPlot provides?

**Comment by swharden** [comment]
Hi @jsr1611,

Plottable objects (like scatter plots and annotations) render in the order they were created. To show annotations on top of the data, use `PlotScatter()` first, then use `PlotAnnotation()`. I suspect this will fix your problem!

Let me know if this doesn't do the trick 👍

**Comment by jsr1611** [comment]
Dear Scott, 
thank you for your prompt feedback.
Actually, I have been running my code placing the PlotAnnotation() after the PlotSignal(). I tried it the other way as well. But there is no effect.
Can you comment on the idea I proposed above ?

**Comment by swharden** [comment]
Hi @jsr1611,

I took a closer look and confirmed the code is working as expected.

```cs
public Form1()
{
    InitializeComponent();
    formsPlot1.plt.PlotSignal(ScottPlot.DataGen.Sin(51));
    formsPlot1.plt.PlotSignal(ScottPlot.DataGen.Cos(51));
    formsPlot1.plt.PlotAnnotation("TEST", fontSize: 48);
    formsPlot1.Render();
}
```
![image](https://user-images.githubusercontent.com/4165489/98832940-728cc380-240b-11eb-87d5-43d73196541e.png)

I suspect the confusion is over the fact the annotation background is semitransparent, so you can see the plot beneath it. You can change the transparency as desired by setting the `fillAlpha` argument:

```cspublic Form1()
{
    InitializeComponent();
    formsPlot1.plt.PlotSignal(ScottPlot.DataGen.Sin(51));
    formsPlot1.plt.PlotSignal(ScottPlot.DataGen.Cos(51));
    formsPlot1.plt.PlotAnnotation("TEST", fontSize: 48, fillAlpha: 1); // <-- alpha 1 means opaque
    formsPlot1.Render();
}
```

![image](https://user-images.githubusercontent.com/4165489/98833053-92bc8280-240b-11eb-865b-5e4a5314bef2.png)

Let me know if this solves your issue! 👍

**Comment by jsr1611** [comment]
Dear Scott,
Thank you very much for your feedback.
I checked it, but I still have some issues. Please check for my attachments.
I am running live data visualization, and have multiple lines drawn one after another in the loop, and that’s why I am using List<PlottableAnnotation> pltAnnot to make it visible to Timer function.
So, seems like I am doing something not correct.
Some charts (lines) are behind the annotations, and some are not.
And if try to check the contents of PlottableAnnotation in the debugger, I don’t get all those arguments that PlotAnnotation has(esp. fillAlpha).

Attachment 1. How can I check the status of the properties of my plottableAnnotation(s)?

[cid:image002.png@01D6B8D4.0B60D040]

Attachment 2. This is the result after changing the fillAlpha to 1.
[cid:image005.png@01D6B8D4.0B60D040]


Looking forward to your feedback!

Best regards,

Jimmy,

Windows 10용 메일<https://go.microsoft.com/fwlink/?LinkId=550986>에서 보냄

보낸 사람: Scott W Harden<mailto:notifications@github.com>
보낸 날짜: Thursday, November 12, 2020 12:50 AM
받는 사람: swharden/ScottPlot<mailto:ScottPlot@noreply.github.com>
참조: Jimmy<mailto:jsr1611@outlook.com>; Mention<mailto:mention@noreply.github.com>
제목: Re: [swharden/ScottPlot] Annotations should be placed above chart (#614)


Hi @jsr1611<https://github.com/jsr1611>,

I took a closer look and confirmed the code is working as expected.

public Form1()



{



    InitializeComponent();



    formsPlot1.plt.PlotSignal(ScottPlot.DataGen.Sin(51));



    formsPlot1.plt.PlotSignal(ScottPlot.DataGen.Cos(51));



    formsPlot1.plt.PlotAnnotation("TEST", fontSize: 48);



    formsPlot1.Render();



}

[image]<https://user-images.githubusercontent.com/4165489/98832940-728cc380-240b-11eb-87d5-43d73196541e.png>

I suspect the confusion is over the fact the annotation background is semitransparent, so you can see the plot beneath it. You can change the transparency as desired by setting the fillAlpha argument:

{



    InitializeComponent();



    formsPlot1.plt.PlotSignal(ScottPlot.DataGen.Sin(51));



    formsPlot1.plt.PlotSignal(ScottPlot.DataGen.Cos(51));



    formsPlot1.plt.PlotAnnotation("TEST", fontSize: 48, fillAlpha: 1); // <-- alpha 1 means opaque



    formsPlot1.Render();



}



[image]<https://user-images.githubusercontent.com/4165489/98833053-92bc8280-240b-11eb-865b-5e4a5314bef2.png>

Let me know if this solves your issue! 👍

**Comment by swharden** [comment]
Hi @jsr1611,

Your email attachments do not come through, however I recommend using the website to posts comments, images, and attachments. The link is https://github.com/swharden/ScottPlot/issues/614

If you look at the `Plot.PlotAnnotation()` method it will probably be helpful to understand how it works.

https://github.com/swharden/ScottPlot/blob/4bf514cfe65e19d644db25f961a81f30e44caa2d/src/ScottPlot/Plot/Plot.PlotText.cs#L52-L94

After plotting an annotation you can change its styling later. Something like

```cs
myAnnotation = plt.PlotAnnotation("original text");
myAnnotation.label = "new text";
```

I hope this helps get you in the right direction! Let me know if you have further questions 👍

**Comment by jsr1611** [comment]
Dear Scottm

THank you very much for being prompt and kind!
I think I resolved it. 
I was using the same loop to create plots and put annotations on it.
And now I am using different loops for them, and it seems it is working well!

![image](https://user-images.githubusercontent.com/38090036/98881523-8f89cb00-24cd-11eb-8d25-f4d1ca19d300.png)

THank you once again!

**Comment by swharden** [comment]
That's great news @jsr1611! I'm happy to hear you got this one figured out. 

Your application looks excellent. I can't read Korean, but I am very interested to learn what your application does 🙃

**Comment by jsr1611** [comment]
I am  not Korean, but I work for a Korean company, so I have to make it in Korean. 😊)

In short, it is a visualization app for sensor (temp, humidity, and particle(dust of 0.3 um and 0.5um size) data for monitoring some manufacturing ‘clean rooms’.

Originally I am from Uzbekistan, Central Asia .One secret I can tell you about our country is that the “algorithm” term originated from the name of a famous scientist named Al-Khwarizmi (also Al-Xorazmiy) who was born in the current Khorezm Province of Uzbekistan. This is where I was born too  😊. But, that’s not boasting that I am “expert” or “all Uzbeks are experts in programming and are born naturally like this”,  that’s just fact, that term is related to Uzbekistan in some way. 😊 And, I am also striving to be good at programming ))).

I really appreciate what you do, and hopefully, someday soon I will also be able to contribute to your good work.
May God bless you!

Best regards,

Jimmy
Windows 10용 메일<https://go.microsoft.com/fwlink/?LinkId=550986>에서 보냄

보낸 사람: Scott W Harden<mailto:notifications@github.com>
보낸 날짜: Thursday, November 12, 2020 10:12 AM
받는 사람: swharden/ScottPlot<mailto:ScottPlot@noreply.github.com>
참조: Jimmy<mailto:jsr1611@outlook.com>; Mention<mailto:mention@noreply.github.com>
제목: Re: [swharden/ScottPlot] Annotations should be placed above chart (#614)


That's great news @jsr1611<https://github.com/jsr1611>! I'm happy to hear you got this one figured out.

Your application looks excellent. I can't read Korean, but I am very interested to learn what your application does 🙃

**Comment by swharden** [comment]
> In short, it is a visualization app for sensor (temp, humidity, and particle(dust of 0.3 um and 0.5um size) data (here I have 3 different sensors generating 4 types of data each) for monitoring some manufacturing ‘clean rooms’.

Very cool, thanks for sharing! I'm always interested to learn what interesting things people use ScottPlot for.

> “algorithm” term originated from the name of a famous scientist named Al-Khwarizmi

This is a fascinating story, thanks for sharing! https://en.wikipedia.org/wiki/Muhammad_ibn_Musa_al-Khwarizmi
