### ISSUE TITLE
Improve WPF Live Data demo

### ISSUE THREAD

**Issue by MichelDequick** [swharden/ScottPlot#616]
This is the ScottPlot.Demo.WPF live demo
![gif](https://user-images.githubusercontent.com/19166246/98849572-b6a3b680-2453-11eb-8cd9-ce8160adb7bb.gif)
As you can see, the plot only updates when interacting with the window.

Is there a solution on my end or should I switch to WinForm for this kind of functionality?

ScottPlot.WPF 4.0.42
Microsoft Visual Studio Enterprise 2019
Version 16.7.5

**Comment by swharden** [comment]
Hey @MichelDequick thanks for posting this!

I'm on mobile and will take a closer look later today, but to force an update after data is modified you can call `wpfPlot1.Render()`. 

My guess is that the WPF demo isn't doing this important step when data updates. Resizing and interacting causes renders to be called for automatically, which is what probably leads to the behavior you observe.

Let me know if this helps!

**Comment by MichelDequick** [comment]
Thanks for the fast response! 
I tryed your suggestion and calling:
```cs
wpfPlot1.Render()
```
in
```cs
UpdateData()
```
Throws
```
System.InvalidOperationException: 'The calling thread cannot access this object because a different thread owns it.'
```

**Comment by swharden** [comment]
Hey @MichelDequick, so to hear this one is causing you so much trouble. 

I'm about to merge a huge PR https://github.com/swharden/ScottPlot/pull/605 and roll a new major version in a few days, so my lean is to fix this problem after the merge and provide better documentation at that time. This may be similar to #609, and ultimately a problem where data triggers a render while a layout or mouse event has already started a render...

As far as an immediate fix, I suspect putting the render call inside a try/catch block will get you past the few instances where new data triggers an update at the same time a layout change or mouse interaction is causing an update. Let me know if this solves your issue, but either way I'll leave this issue open until I get time to come up with a better long-term solution.

Thanks again for your input!

**Comment by MichelDequick** [comment]
After letting this issue behind for a bit I retried solving it without succes.
Reading up online suggested to pass the calls trough to the application invoker. Even thought this does not throw an error like previous methods, the plot still doesn't render. When forcing a render by dragging the window I notice that there is data lacking. This suggest that the UpdateData method is not called as frequently as it should, shifting the blame to the DispatchTimers.

Interested to hear your thoughts and insights

**Comment by MichelDequick** [comment]
I have found a temporary temporary solution by using `System.Timers.Timer` instead of `DispatcherTimer`
and making this timer call `Application.Current.Dispatcher.Invoke(new Action(() => { wpfPlot1.Render(); }));`

**Comment by swharden** [comment]
> I have found a temporary solution by using `System.Timers.Timer` instead of `DispatcherTimer`
and making this timer call `Application.Current.Dispatcher.Invoke(new Action(() => { wpfPlot1.Render(); }));`

Hey @MichelDequick,

I'm working to refactor the user controls to make this easier in the future, and I also plan to document this topic as part of the new FAQ #572 so I'll close this issue, but I really appreciate you for following-up to share your solution!

Scott
