### ISSUE TITLE
How can I NOT draw lines between time gaps in PlotSignalXY

### ISSUE THREAD

**Issue by Wyrus** [swharden/ScottPlot#618]
(Or maybe a different plot type would make more sense - suggestions?)

I am pulling data from a table to be plotted. Each record has a timestamp and associated values. I am able to successful pull this into a PlotSignalXY and have been having all sorts of fun with all the various ScottPlot options - well done!

However, in some cases, I'll have a jump in record times. The plot does draw everything correctly, and the time axis is behaving correctly. However, is there some way to NOT connect data points that are more than X seconds apart?
For instance, if there's a gap of 1 hour in the data, can that appear as a gap in the plotted line?

If not, do you have any guidance as to where to start my search if I wanted to attempt a solution?

Thanks!

**Comment by swharden** [comment]
Hey @Wyrus, 

This is a somewhat common question, so I'll add it to the FAQ (#572) so it's a little easier to figure out.

The short answer is that right now scatter plots and signal plots can only plot a single connected line. Values like `double.PositiveInfinity` and `doube.NaN` are not supported. There is active work (#578) which seeks to detect these invalid values and throw exceptions or write error messages to make this more obvious.

If you have a "disconnected" dataset, the best option is to determine individual lines on your end, then place multiple scatter plots as necessary. If you are in a graphical environment where the data changes a lot, every time there is a new set of data you can call `plt.Clear()` and plot everything again. It's not the most satisfying answer, but it's the best solution given the current state of the project!

Let me know if you have other questions or hit any snags along the way 👍 
Scott

**Comment by johnfoll** [comment]
> 

I figured out already that I could do this. However, doing this causes duplicates to show up in the Legend. Every time the same Label is plotted it adds another instance of the Label to the Legend.

**Comment by swharden** [comment]
Following-up, anyone interested in making scatter plots with gaps can now do so:

* https://scottplot.net/faq/data-gaps/
* https://scottplot.net/cookbook/4.1/category/plottable-scatter-plot/#nan-values-break-the-line

![image](https://user-images.githubusercontent.com/4165489/187461598-e54172c5-0980-4856-a973-aada3fe0b07c.png)

**Comment by johnfoll** [comment]
Thanks! I will try to use double.NaN
