### ISSUE TITLE
How can I ignore "null" values when drawing a PlotSignalXY or PlotSignal

### ISSUE THREAD

**Issue by Wyrus** [swharden/ScottPlot#619]
(Or maybe a different plot type would make more sense - suggestions?)

I am pulling data from a table to be plotted. Each record has a timestamp and multiple associated values. I am able to successfully pull this into a PlotSignalXY and have been having all sorts of fun with all the various ScottPlot options - well done!

However, in some cases, I'll have some null values for various reasons. Is there some way to not include this data value in the plot?

I suppose I could build the xs and ys and strip out the null values. However, I'm driving multiple plots from a single data source (and using a shared xs array). I'd rather be able to set the specific y value to something like double.NaN to just skip the y. (This aligns with my earlier question about time gaps) Any thoughts?

If not, do you have any guidance as to where to start my search if I wanted to attempt a solution? (It would make sense to apply this analysis before the time-gap logic)

Thanks!

**Comment by swharden** [comment]
Hey @Wyrus, 

I'm happy to hear you are enjoying ScottPlot! Similar to #618, line plots do not currently support disconnected data. Multiple lines means creating multiple line plots. This shouldn't be too hard to do on your end though. You can call `PlotScatter()` or `PlotScatter()` multiple times, and `Clear()` if you want to start over. I recognize this feels inefficient (requiring copying the data before plotting it), but part of what makes ScottPlot so fast is that it draws scatter plots and signal plots as a single, unbroken line.

I'm working on alternative solutions (e.g., scatter plots that display `double.NaN` as gaps in data), but for now displaying gaps in data is not currently supported.

I hope this helps! Let me know if more questions pop up along the way
Scott

**Comment by Wyrus** [comment]
For anyone worried about actual performance with this approach, I just finished some testing...

INCLUDING the time to analyze the source data, break it into contiguous chunks, allocate data arrays for each chunk, clear the existing plot, add a new PlotSignalXY for each of 10 chunks, and render...
It took roughly double the time as a single PlotSignalXY with all the points that re-used the data buffers.
What that suggests to me is that performance of ScottPlot is heavily weighted toward point count, and not near as much on the number of plots.
I'll say it again... Duly impressed!

Oh by the way, building contiguous chunks myself gives me full control of the gap fill behavior as well. :)

**Comment by swharden** [comment]
It's often surprising to learn where the bottlenecks are! Most of the optimizations are for continuous data with fixed inter-point spacing, and the farther you go from that model the more it takes testing to figure out the best solution...

Thanks for following-up with your findings @Wyrus, and I'm happy you found a solution that works for you!
