### ISSUE TITLE
Lines get plotted outside the view when plotting multiple lines in multiple formPlots

### ISSUE THREAD

**Issue by jsr1611** [swharden/ScottPlot#620]
**Background**
I have multiple lines (and annotations, too) plotted in multiple formPlots.
And some lines are plotted correctly inside the formPlot, but some lines in other formPlots are plotted incorrectly, i.e. get outside the view. Please check the attached screenshot.
Screenshot: 
![image](https://user-images.githubusercontent.com/38090036/99739497-40b4e480-2b10-11eb-8966-d2e6b98284cd.png)

**In this screenshot, you can see almost all formPlots have some issues.**

**Question:** **What might be the problem here?** 
I am placing these formPlots inside TableLayoutPanel control to make the screen resizable with the mouse.
Here the part I am plotting the lines and annotations:

I have 4 formPlots (index_DataType), 3 arrays of data (index_ID) for each of them:
```
for (int index_DataType = 0; index_DataType < MyDataTypes.Count; index_DataType++)
                {
                    var plt = formsPlots[index_DataType];
                    for (int index_ID = 0; index_ID < MyIDs.Count; index_ID++)
                    {
                        double[] ys = dataArr2[index_ID].Select(x => double.Parse(x)).ToArray();
                        double[] xs = timeData.Select(x => x.ToOADate()).ToArray();
                        formsPlots[index_DataType].plt.PlotSignalXYConst(xs, ys, lineStyle: LineStyle.Dot, color: colorset[index_ID]);    
                        
                        formsPlots[index_DataType].plt.Ticks(dateTimeX: true); //formsPlot1.
                        formsPlots[index_DataType].plt.Title(titleName, fontSize: 24); // formsPlot1.
                        formsPlots[index_DataType].plt.YLabel(titleName, fontSize: 20); // formsPlot1.
                        formsPlots[index_DataType].plt.XLabel("시간", fontSize: 20);
                      }
                    
                } 
```
I have same number of annotations equal to the number of lines I plot:

```
for (int index_DataType = 0; index_DataType < MyDataTypes.Count; index_DataType++)
                {
                    int annotY = 10;
                    int annotY2 = -10;
                    for (int index_ID = 0; index_ID < MyIDs.Count; index_ID++)
                    {
                        double[] ys = dataArr2[index_ID].Select(x => double.Parse(x)).ToArray();
                        Tuple<double, int> tupleMax = FindMax(ys); // returns max and time data as a tuple 
                        double max = tupleMax.Item1;
                        int indexOfMax = tupleMax.Item2;

                        formsPlots[index_DataType].plt.PlotAnnotation(Btn3_SensorLocation[MyIDs[index_ID] - 1].Text, 10, annotY, fontSize: 20, fontColor: colorset[index_ID], fillAlpha: 1);
                        formsPlots[index_DataType].plt.PlotAnnotation(max.ToString() + " "+ char.ConvertFromUtf32(0x2191), -10, annotY2, fontSize: 12, fontColor: colorset[index_ID], fillAlpha: 1);
                        annotY += 35;
                        annotY2 -= 25;
                        formsPlots[index_DataType].Render();
                    } 
                }
```
I am rendering the formPlots one by one here at the end.

For information: I am plotting 4 kinds of different data, each having different scale and so being plotted inside a different formPlot, and I have three different peaces of data for each kind, so in total I plot 3 lines in one formPlot, and I have 4 formPlots to render at the end.

**Comment by swharden** [comment]
Hi @jsr1611, I think I understand your questions but let me know if I got them wrong! I think this will help...

### Ticks Running Off the Figure

The ticks running off the figure can probably be fixed by adding some padding

![image](https://user-images.githubusercontent.com/4165489/99748040-bc2f7b00-2aa9-11eb-9e1d-98fda93168ef.png)

```cs
plt.Layout(y2LabelWidth: 50);
```

https://swharden.com/scottplot/cookbooks/4.0.40/#customize-figure-figure-padding

### Adjust Axis Limits to Fit the Data

After plotting data (or modifying that data) you can call `AxisAuto()` to adjust the axis limits to fit the data

```cs
formsPlots[index_DataType].plt.AxisAuto()
```

**Comment by jsr1611** [comment]
Dear @swharden,
Thank you very much for prompt feedback! 
It worked!

**Comment by swharden** [comment]
> It worked!

That's great news! Let me now if any more questions pop up along the way 👍

**Comment by jsr1611** [comment]
> > It worked!
> 
> That's great news! Let me now if any more questions pop up along the way 👍

Sure!
