### ISSUE TITLE
How to disable mouse interaction in user controls

### ISSUE THREAD

**Issue by martin-brajer** [swharden/ScottPlot#627]
I would like to interact with the plotted data by clicking the plot (which works fine). But while e.g. zooming, my interaction is also triggered. In older version I used ctrl+mouseclick, but now it is occupied too. I would welcome the possibility to temporarily disable/enable build-in interactive-controls.

Ussage example: analyze spectral peak around clicked wavelenght.

**Comment by swharden** [comment]
Hey @martin-brajer,

Plots displayed in user controls are Bitmap images, so they're not particularly interactive (other than zoom/pan). Check out the "highlight point nearest mouse" demo in the demo application for an example of how to make a scatter plot slightly more mouse-interactive: https://swharden.com/scottplot/demo

Regarding how to disable zooming and panning, you may find this helpful

```cs
formsPlot1.Configure(enableZooming: false, enablePanning: false);
```

PS: If you download source code from the current master branch you'll see a "FormsPlotExperimental" control which is a barebones user control that isn't all that complex. Users who desire to add advanced interactive customizations might do well to implement their own control, similar to this one, then they have full control over mouse options https://github.com/swharden/ScottPlot/blob/master/src/controls/ScottPlot.WinForms/FormsPlotExperimental.cs

Hope this helps!
Scott

**Comment by swharden** [comment]
... following-up, I see you're working on https://github.com/martin-brajer/spectrometric-thermometer

I didn't download it and try to run it, but if you show a screenshot of what you've got so far I might be able to offer a more application-specific suggestion!

I closed this issue for now, but feel free to open it up if you have further questions or still aren't able to achieve the functionality you're looking for 👍

**Comment by martin-brajer** [comment]
Thx, `formsPlot1.Configure(enablePanning: value)` combined with some switch should do the trick.
Ad PS: I've already been digging through the code, so thx for directions.

The app tries to find a position of a feature in the data (semiconductor absorption edge if you are interested). See upper image - pls ignore actual numbers, they are pretty random there. Since the data are usually more noisy, the algorithm sometimes finds wrong feature - see the bottom image. So the idea is that the user clicks the correct feature right in the plot and the app recalculates the position. This works just fine, but the process is also triggered when panning.
![GUI](https://user-images.githubusercontent.com/44474116/100258994-fab0b400-2f47-11eb-89c9-966db85905a1.png)
![Fail](https://user-images.githubusercontent.com/44474116/100252521-41021500-2f40-11eb-811c-9731230ab171.png)

**Comment by swharden** [comment]
Thanks for following-up @martin-brajer! Very cool use of this library - it's fascinating to see what people use it for. I'm glad to see you found a solution that works for your application.

Scott
