### ISSUE TITLE
PlotBar() - negative Y values colored black

### ISSUE THREAD

**Issue by bukkideme** [swharden/ScottPlot#630]
Hello!

Why I get different color for the negative values?
I simply use the following method:

plot.plt.PlotBar(sampleData.Select(item => item.NominalCap).ToArray(), sampleData.Select(item => item.CapDiff).ToArray(),
                errorY: sampleData.Select(item => item.CapStDev).ToArray());

![image](https://user-images.githubusercontent.com/51174971/100372588-c3a2d700-3009-11eb-87dc-e6040145c82d.png)

**Comment by swharden** [comment]
Does setting the negative color manually produce the expected output?

```cs
double[] xs = sampleData.Select(item => item.NominalCap).ToArray();
double[] ys = sampleData.Select(item => item.CapDiff).ToArray();
double[] yErr = sampleData.Select(item => item.CapStDev).ToArray();

var scatter = plot.plt.PlotBar(xs, ys, errorY: yErr);
scatter.negativeColor = Color.Magenta; // <-- set the negative color manually
```

**Comment by bukkideme** [comment]
Hi @swharden ,

Thanks!
The scatter.negativeColor = scatter.fillColor; line did the trick! :)
Regards,

**Comment by swharden** [comment]
This line is the problem
https://github.com/swharden/ScottPlot/blob/2f4306280a643ba3944149466df0ab5eec65ace2/src/ScottPlot/Plot/Plot.PlotBar.cs#L57

I'll fix it this weekend 👍
