### ISSUE TITLE
add alignment to PlotText()

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#64]
At its core, PlotText() accepts a location and a string:

```cs
PlotText("test", x, y);
```

There should be a way to set how that text is positioned relative to that point. I added the arguments for this but currently they're not used.

```cs
PlotText("test", x, y, alignment: TextAlginment.upperLeft);
```

Modify this code block so the string is appropriately placed relative to the x and y points.
https://github.com/swharden/ScottPlot/blob/3539a0b286addfa983670c07c0d1e7fe9cd3b4a2/src/ScottPlot/plottables/PlottableText.cs#L46-L49

@Padanian do you want to take this one?

**Comment by Padanian** [comment]
Taking it.

**Comment by Padanian** [comment]
Pull request pending.

**Comment by swharden** [comment]
https://github.com/swharden/ScottPlot/pull/67

Thanks @Padanian! I'll review this shortly

**Comment by swharden** [comment]
Just merged - https://github.com/swharden/ScottPlot/commit/ce45838eee2f43ca72e38d7de44f8aee8c9f815b

I added an example to the cookbook too:
https://github.com/swharden/ScottPlot/tree/master/cookbook#plotting-text

thanks @Padanian!

PS: It's odd your commits are not showing up on https://github.com/swharden/ScottPlot/graphs/contributors ... I can't figure out why, because your name shows up committing to the master branch (https://github.com/swharden/ScottPlot/commits/master). 

StackOverflow suggests ensuring GitHub's record of your email addresses is accurate, then your previous commits might start showing up: https://github.com/settings/emails

**Comment by Padanian** [comment]
My email address is ok. Don’t know if it’s related, but I’m working on a fork, not on the upstream master, and every time you pull, I fast forward my fork.
Git is somewhat obscure to me.

**Comment by swharden** [comment]
I used another GitHub account to create a branch, make a change to a file, and issue a pull request. I merged the pull request (same way I do yours) and that account shows up as a contributor.

I think the issue is on your end and relates to how you commit to branches.

A clue to the problem is that the commit list shows your name but not your GitHub icon or username:
https://github.com/swharden/ScottPlot/commits/master

This is also true at the top of commits themselves. It's like you commit anonymously:
https://github.com/swharden/ScottPlot/commit/432bece2fc94103d2de50ec5cad947aa162424fc

This is also true of your own repos:
https://github.com/Padanian/MultiGauge/commits/master

Whatever the issue is, as soon as your GitHub username/icon starts showing up I think it'll be fixed (and you'll get "credit" for your contributions!)

**Comment by swharden** [comment]
FYI, the email address you commit as is listed at the top of the raw patch: https://github.com/swharden/ScottPlot/commit/432bece2fc94103d2de50ec5cad947aa162424fc.patch

I still suspect that email address is not listed in your settings here:
https://github.com/settings/emails

**Comment by Padanian** [comment]
Good catch. That's the account I use for Visual Studio, and it
doesn't match with my Github account that is registered under another
email address.

**Comment by Padanian** [comment]
Fixed now, but it's definitely a bug in Visual Studio. Git global settings and github account are all set to my home email address, while Visual Studio license is registered with business email address. For some reason, Visual Studio does not honour the repository and/or global git settings, but commits with its own associated email address instead.
Adding my business email address to the list of registered email addresses in Github fixes the issue. Thanks for bringing this up. It went unnoticed from my side.
