### ISSUE TITLE
Create a bar plot without defining X positions

### ISSUE THREAD

**Issue by bukkideme** [swharden/ScottPlot#640]
Hi!

It is a common case when we need to visualize XY data pairs on a Bar graph. However, often we need to show the Y-values/bars side-by-side of each others, therefore we need to code extra lines not to directly use the raw X-values for the PlotBar() methode.

Example what I need to do now for this:

```
double[] xs = { 0, 5, 10, 20, 40, 80 };
double[] ys = { 0.02, 0.01, 0.01, 0.02, 0.04, 0.03 };
int barCount = xs.Length; 
//artificial X values to make Bars side by side without data gaps in X-axis:
double[] x_consecutive = DataGen.Consecutive(barCount);
                        
// make the bar plot
formsPlot1.plt.PlotBar(x_consecutive, ys);
                        
// apply custom axis tick labels
formsPlot1.plt.XTicks(x_consecutive, xs.Select(item => item.ToString()).ToArray());
formsPlot1.Render();
```

It would be great to have an extra parameter for the PlotBar() method, like "consecutive_X_vals". If this set to True, the plot would take the string representations of the X-values, and plot the Y-values side by side, with labels from the X-values.
In this way we avoid the extra required coding.
Thanks! :)

![image](https://user-images.githubusercontent.com/51174971/100723981-aaf83f80-33c2-11eb-9e2a-cb60a05c65e3.png)

**Comment by swharden** [comment]
Hi @bukkideme, 

Summarizing your request, you'd like an easy way to display a series of `Ys` in a bar plot without having to go through the trouble of creating `Xs`. This seems like a common task, and that it should be easier to figure out than it currently is!

I think if you pass in `null` for `xs` it will produce the behavior you're looking for, but I recognize this is poorly documented...
https://github.com/swharden/ScottPlot/blob/8119f0f7795d38f1d659a9f09b8384537a87f14c/src/ScottPlot/Plottable/BarPlot.cs#L47

There's a chance I'll be refining the plottable-creating methods (toward simpler ones with more expressive names, #638) so maybe there's a way we can make this more intuitive somehow. Perhaps reversing the arguments and giving them more expressive names?

```cs
/// <summary>
/// Add a bar plot from a series of values
/// </summary>
Plottable.BarPlot AddBar(
    double[] values, 
    double[] positions = null, 
    Color? color = null, 
    string label = null, 
    bool autoAxis = true)

**Comment by swharden** [comment]
Hi @Benny121221, 

I made this a little easier since the issue was first raised 👍 

```cs
double[] values = ScottPlot.DataGen.Random(rand, count);
plt.AddBar(values);
```

```cs
string[] labels = Enumerable.Range(1, count).Select(x => $"bar number {x}").ToArray();
plt.XTicks(labels);
plt.XAxis.TickLabelStyle(rotation: 45);
```

![image](https://user-images.githubusercontent.com/4165489/102699817-f493b780-4215-11eb-8499-52650eb830b0.png)
