### ISSUE TITLE
Measure Distance between two points

### ISSUE THREAD

**Issue by Pol1000** [swharden/ScottPlot#641]
Hi, 
i've to measure the distance between two points on the chart, the user with the mouse and i drag a line and have to give the distance, in the current scale.

if the user zoom in or out the distance have to consider the new scale.

i've try with plt.CoordinateFromPixel() but the coordinates that i've appears not correct.

Thanks.

**Comment by kutukvpavel** [comment]
Distance between what kind of points do you need to measure? I assume the distance between data points on the plot. Now, given that the dataset of the plot doesn't actually change when zooming, the distance between two selected (!) data points doesn't change upon zooming too.

So the algorithm is as follows:

1. You process some kind of UI event (mousedown etc) that fires when the mouse is on top of the desired starting point. Then you can call `(double mouseX, double mouseY) = pltYourPlot.GetMouseCoordinates();` (I've used this method on version 4.0.42 and it returns accurate values), then save the first point into some kind of global variable.

2. You wait for some other UI event that fires when the mouse is on top of the destination point (mouseup etc). Then you again call GetMouseCoordinates() and compute the distance using two sets of coordinates you now have, based on the coordinate system you work in.

3. Provide some UI mechanics to reset the calculated distance and go to p.1.

I don't see ant problems so far. Correct me, if I'm wrong.

Which leads me to thinking that you want the distance between two selected points (pixels) in the client rectangle of the plot control, and not between two selected point of the dataset. Well, then the task is a bit harder, you'll have to store client rectangle coordinates and recalculate the distance on each pltYourPlot.AxisChanged event. And indeed you'll have to use CoordinateFromPixel(). I'll look into CoordinateFromPixel(), in the mean time, could you please elaborate on "appears incorrect"? What exactly does the method return, and why do you think the values are incorrect?

**Comment by Pol1000** [comment]
Hi 
thanks for the reply, i've to measure the distance between to points on the chart area, maybe there aren't plot draw at the moment or in any case it's possible the points of the click isn't on the plot.
When the user do the first click i want draw a dot in the point, after the second click i draw a 2 points plot with a label.
I take the mouse pos from the event and pass to coordinateFromPixel, but the result is far away from the expetation.
For example i click in the point (0;0) on the chartArea, based on the x-y axis, but the result of the function give me coordinates -50,4232; 30,433.

I continues try today.

**Comment by StendProg** [comment]
Hi there,

> I take the mouse pos from the event and pass to coordinateFromPixel, but the result is far away from the expetation.
For example i click in the point (0;0) on the chartArea, based on the x-y axis, but the result of the function give me coordinates -50,4232; 30,433.

It can't be. No example would work if there was an error in the basic coordinate conversion function.
Most likely there is an error (misunderstanding) somewhere in your handler. If you have the opportunity to provide more source code, then we can try to find it together.

**Comment by Pol1000** [comment]
Hi,
i've tried some methods for get the coordinates of the click, but no one give me the right coordinates (based on the chart X and Y  scaled)
```python
Point pointChart = Mouse.GetPosition(mychart);
Point pointistanza = Mouse.GetPosition(istanzaPrincipal);
Point pointToScreenChart = PointToScreen(pointChart);
Point pointToScreenIstanza = PointToScreen(pointistanza);
Point pointChartEvent = e.GetPosition(mychart);
Point pointistanzaEvent = e.GetPosition(istanzaPrincipal);
var p = System.Windows.Forms.Cursor.Position;
var p2 = System.Windows.Forms.Control.MousePosition;


var graphCoordSystem = mychart.plt.CoordinateFromPixel(p.X, p.Y);
var graphCoordSystem2 = mychart.plt.CoordinateFromPixel(p2.X, p2.Y);
var graphCoordChart = mychart.plt.CoordinateFromPixel(pointChart.X, pointChart.Y);
var graphCoordistanza = mychart.plt.CoordinateFromPixel(pointistanza.X, pointistanza.Y);
var graphCoordChartEvent = mychart.plt.CoordinateFromPixel(pointChartEvent.X, pointChartEvent.Y);
var graphCoordistanzaEvent = mychart.plt.CoordinateFromPixel(pointistanzaEvent.X, pointistanzaEvent.Y);
var graphCoordscreenChart = mychart.plt.CoordinateFromPixel(pointToScreenChart.X, pointToScreenChart.Y);
var graphCoordscreenIstanza = mychart.plt.CoordinateFromPixel(pointToScreenIstanza.X, pointToScreenIstanza.Y);
```

**Comment by StendProg** [comment]
> i've tried some methods for get the coordinates of the click, but no one give me the right coordinates (based on the chart X and Y scaled)

Most likely the problem is that you are using DPI Scaling on OS level. WinForms has well-known problems with this (not only library, but winforms at all). If I guess right and the use of DPI scaling is fundamental for you, I can advise you to try the WPF control.

Check `Demo->MouseTracker` (not cookbook demo). It works perfect for me, but I am never used DPI scaling.

This demo just grab mouse coord from `mouse event -> event arg` and pass it to `plt..GetCoordinateX()/plt.GetCoordinateY()`.
Try something like this:
```c#
private void formsPlot1_MouseMoved_1(object sender, MouseEventArgs e)
{
           
            int pixelX = e.X;
            int pixelY = e.Y;
            
            double coordX = formsPlot1.plt.GetCoordinateX(pixelX);
            double coordX = formsPlot1.plt.GetCoordinateX(pixelY);
}
```
if it still works wrong double check DPI scaling setting on your system.

**Comment by Pol1000** [comment]
> > i've tried some methods for get the coordinates of the click, but no one give me the right coordinates (based on the chart X and Y scaled)
> 
> Most likely the problem is that you are using DPI Scaling on OS level. WinForms has well-known problems with this (not only library, but winforms at all). If I guess right and the use of DPI scaling is fundamental for you, I can advise you to try the WPF control.
> 
> Check `Demo->MouseTracker` (not cookbook demo). It works perfect for me, but I am never used DPI scaling.
> 
> This demo just grab mouse coord from `mouse event -> event arg` and pass it to `plt.GetCoordinateX()/plt.GetCoordinateY()`.
> Try something like this:
> 
> ```cs
> private void formsPlot1_MouseMoved_1(object sender, MouseEventArgs e)
> {
>            
>             int pixelX = e.X;
>             int pixelY = e.Y;
>             
>             double coordX = formsPlot1.plt.GetCoordinateX(pixelX);
>             double coordY = formsPlot1.plt.GetCoordinateY(pixelY);
> }
> ```
> 
> if it still works wrong double check DPI scaling setting on your system.

THANKS!!

it work, i don't think about the dpi scaling... i've two monitors, one 4k with a 200% zoom and one HD with no zoom.

No matter the screen i move the app, ever gave me wrong coordinates until i set both on no zoom.

After that it start work correctly.

The demo indicates not work with the DPI scaling, i try... only without scaling.


now i can have the correct coordinates i can move on ..

Again thanks.
