### ISSUE TITLE
Auto scaling axes are misguided by mouse tracker (crosshair)

### ISSUE THREAD

**Issue by artemiusgreat** [swharden/ScottPlot#643]
Thank you for sharing this library. Meanwhile, there seems to be some issue with the mouse tracker, because it affects auto scaling axes, because horizontal and vertical lines are mixed with actual time series in the plottable collection. Explanation below. 

Trying to create OHLC chart with candles, one moving average line and a mouse tracker (crosshair) in a WPF app with .NET Core 5.0. Then, I'd like to add ability to pan chart along the `X` axis and zoom on `X` and `Y`.

```
var plt = Chart.plt;

// crosshair
_lineX = Chart.plt.PlotVLine(0, color: Color.Red, lineStyle: LineStyle.Dash);
_lineY = Chart.plt.PlotHLine(0, color: Color.Red, lineStyle: LineStyle.Dash);

// candles and sma
var rand = new Random(0);
var ohlcs = DataGen.RandomStockPrices(rand, 50, sequential: true);
var xs = DataGen.Consecutive(ohlcs.Length);
var ys = ohlcs.Select(o => o.close).ToArray();

plt.PlotCandlestick(ohlcs);
plt.PlotScatter(xs, ys, color: Color.Blue, markerSize: 0, lineStyle: LineStyle.Dash);
plt.Ticks(dateTimeX: true);
plt.AxisAuto();

Chart.Render();
```

Then, to see the problem, create a `MouseMove` event to update mouse tracker position. 

```
private void OnMouseMove(object sender, MouseEventArgs e)
{
  var plt = Chart.plt;

  (double coordinateX, double coordinateY) = Chart.GetMouseCoordinates();

  _lineX.position = coordinateX;
  _lineY.position = coordinateY;
  
  plt.AxisAuto(); // This call placed here only to demonstrate the issue

  Chart.Render();
}
```

**Concern #1**

Now, every time when I move the mouse to the edge of the plot it expands the chart area to show more of a crosshair and less of actual time series (candles and sma). **Actual time series are getting squeezed because `AxisAuto` resizes plot based on crosshair, not based on actual time series.** Of course, I don't have to auto scale axes on every mouse move, but I added call of `AxisAuto` here to demonstrate that mixing simple `H` and `V` lines with actual time series makes it confusing to identify actual limits of the data on the chart. 

**Concern #2**

I understand that `AxisAuto` is a generic solution and may not work in all cases, so I'd like to create my own function to set plot limits. I looked at similar issues [here](https://github.com/swharden/ScottPlot/issues/398) and [here](https://github.com/swharden/ScottPlot/issues/225). Then, I debugged what I have in the list of time series. 

```
var series = plt.GetPlottables(); // contains a collection of 4 series [0: lineX, 1: lineY, 2: candles, 3: sma]
```

All of these series have property `visible` set to `true`. **The question, if I want to write the code that automatically finds limits in the arbitrary collection of time series, how this code could separate lines from actual time series (candles and sma)?**

**These 2 questions above can be merged into one.** 

What's the purpose of mixing simple lines with time series arrays? It is possible to keep these types in different variables? For example.

```
var series = plt.GetPlottables(); // contains a collection of 2 series [0: candles, 1: sma]
var shapePrimitives = plt.GetShapes(); // contains a collection of 2 objects [0: lineX, 1: lineY]
```

**Comment by artemiusgreat** [comment]
Alternatively, would be nice to inherit specific, if not all, entities from an extensible object that has CLR properties but can be extended with custom fields, like Expando. 

https://weblog.west-wind.com/posts/2012/feb/08/creating-a-dynamic-extensible-c-expando-object

```
/// <summary>
/// Expando class that allows to extend other models in runtime
/// </summary>
public class ExpandoModel : DynamicObject, IDynamicMetaObjectProvider, ICloneable
{
  /// <summary>
  /// Internal dictionary to keep dynamic properties
  /// </summary>
  private ConcurrentDictionary<string, dynamic> _items = new ConcurrentDictionary<string, dynamic>();

  /// <summary>
  /// Redirect setter for dynamic properties to internal dictionary
  /// </summary>
  /// <param name="binder"></param>
  /// <param name="value"></param>
  /// <returns></returns>
  public override bool TrySetMember(SetMemberBinder binder, object value)
  {
    _items[binder.Name] = value;
    return true;
  }

  /// <summary>
  /// Redirect getter for dynamic properties to internal dictionary
  /// </summary>
  /// <param name="binder"></param>
  /// <param name="result"></param>
  /// <returns></returns>
  public override bool TryGetMember(GetMemberBinder binder, out object result) => _items.TryGetValue(binder.Name, out result);

  /// <summary>
  /// Get all properties for serialization
  /// </summary>
  /// <returns></returns>
  public override IEnumerable<string> GetDynamicMemberNames() => GetType()
    .GetProperties()
    .Select(o => o.Name)
    .Concat(_items.Keys);

  /// <summary>
  /// Implement indexer for internal dictionary
  /// </summary>
  /// <param name="index"></param>
  /// <returns></returns>
  public virtual object this[object index]
  {
    get => _items.TryGetValue(Convert.ToString(index), out object result) ? result : null;
    set => _items[Convert.ToString(index)] = value;
  }

  /// <summary>
  /// Clone
  /// </summary>
  /// <returns></returns>
  public virtual object Clone() => MemberwiseClone();
}
```

**Comment by StendProg** [comment]
Hi @artemiusgreat,

1. Instead of implementing you own plot limits function, you can implement a custom Plottable VLine/HLine that does not affect the calculation of limits.
Just inherit from original PlottableVLine and overload GetLimits method
```c#
public class PlottableVLineNoLimits : PlottableVLine
{
  public override AxisLimits GetLimits() => new AxisLimits(double.NaN, double.NaN, double.NaN, double.NaN);
}
```
If you pass all `double.NaN` this plottable not affect the calculation of limits at all.

Then just create and add your custom Plottable:
```c#
_lineX = new PlottableVLineNoLimits()
{
   x = 0,
  color = Color.Red,
  lineStyle = LineStyle.Dash,
}
Chart.plt.Add(_lineX);
```

I did not test it (browser programming), but think you can easy fix possible mistakes.

2. The main reason for introducing `dynamic` is to simplify interaction with libraries written in other `dynamic` languages (APIs).
I would not advise you to use `dynamic` constructs in a strongly typed language (c#). In addition to syntactic convenience, they have a lot of disadvantages.

> dynamic candles = plt.PlotCandlestick();
dynamic sma = plt.PlotScatter();
candles.Important = true;  //  or candles["Important"] = true if var is used instead of dynamic
var importantSeries = plt.GetPlottables().Select(o => o["Important"]);

Can be easily changed to:
```c#
var candles = plt.PlotCandlestic();

var importantSeries = plt.GetPlottables().Where( o => o == candles);
```

**Comment by artemiusgreat** [comment]
Custom lines look like a good idea. Thanks. 

Still would like to add a couple of words regarding `dynamic`. 
The class and article that I mentioned in the previous comment are not exactly dynamic. 
It is an extension to normal CLR properties. 
Meaning, it doesn't require to specify `dynamic` anywhere, all types and interfaces are strict, VS intellisense shows all CLR properties. When used with `var` or exact class type, it will act exactly the same.
