### ISSUE TITLE
No grid and labels after panning or zooming of the chart without gaps 

### ISSUE THREAD

**Issue by artemiusgreat** [swharden/ScottPlot#644]
Looking at this example. 
https://swharden.com/scottplot/cookbooks/4.0.44/#plottypes-finance-ohlc-without-gaps 

If I define custom tick labels and positions and try to pan or zoom the chart, there are no grid lines and no labels on X axis. 
Is there a way to define custom axis / scale or make new values appear on X axis like it's done by default?

**Comment by StendProg** [comment]
Hi @artemiusgreat,

I have zero experience with financial data. What has been done in your example is just a trick, and if you look closely, you will understand that 5 points are evenly distributed over 7 days of the week, i.e. none is true and is offset by more than 1 day. The fifth point falls at days the market is closed. If you start zooming in and the marks would appear as you want, then this substitution will become more visible. Are you sure this is what you want?

**Comment by artemiusgreat** [comment]
Yes, I understand how those 5 ticks were generated. The question is a bit different and it's not necessary about financial data. It's more about efficient rendering of the data showing only one chunk of it for the selected date range. 

**Expectation**

I have two arrays with data 

* one keeps the whole history of data points, e.g. millions of points of minute data for the last 5 years, let's call it `history`
* one will be actually rendered, e.g. floating window that shows only 50 points, e.g. from 10:00 am to 10:50 am, let's call it `viewport` 

Now, user uses pan control to move chart to the right. 
This way user goes in the past and we need to show 50 previous points from 09:10 am to 10:00 am. 
Every time user shifts chart to the right or left, we identify selected date range, copy 50 points from `history` to `viewport` for this date range, and render it. 

**The question is, how do I know the the selected date or range selected on X scale, so I could render points for these dates?**

**Comment by artemiusgreat** [comment]
Here is an example of what I've been using recently. 
https://codepen.io/artemiusgreat/pen/GRjoEEd

You can try moving chart to the left or right. 
For users, it looks like there are 500 points and he just look back and forth. 
In reality, there is an array of all 500 points in memory, and every time user scroll the chart, we select only 50 points and show render only them. 

Sorry for the bunch of unrelated code in that example, but the main idea is in the `Scale` method. 

```
this.DataBounds = this.DataPoints.slice(minX, maxX);  // copy only 50 points from 0 to 49 from history array to viewport array
this.ScaleX.domain(minX, maxX); // define what indexes will be visible on X scale
this.ScaleY.domain(minY, maxY); // define what indexes will be visible on Y scale
this.Render(); 
```

This is D3FC and it allows to select range that will be rendered and then provide an array with data. 
Indexes of an array will be matched with indexes between `minX` and `maxX` on scale `X`. 
So, after every scroll I know indexes on X scale and create relevant array of data to render for these time stamps. 

I'm not sure how ScottPlot creates mapping between X coordinates and values on X scale and whether it's possible to render only small piece of data when indexes are shifted.

**Comment by artemiusgreat** [comment]
My explanation may sound awkward, so I'm just trying different terms. 
Another way to rephrase my question is, how to implement render [rolling window](https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.researchgate.net%2Fprofile%2FQing_Zhan4%2Fpublication%2F333566343%2Ffigure%2Ffig2%2FAS%3A765641963339776%401559554677817%2FRolling-window-method-for-outlier-detection-supported-by-MathWorks-which-can-also-be.ppm&imgrefurl=https%3A%2F%2Fwww.researchgate.net%2Ffigure%2FRolling-window-method-for-outlier-detection-supported-by-MathWorks-which-can-also-be_fig2_333566343&tbnid=_d5kQzOwNwWcKM&vet=10CAMQxiAoAGoXChMIkOTU4YGz7QIVAAAAAB0AAAAAEAw..i&docid=IfEg6P7gneBjGM&w=850&h=717&itg=1&q=rolling%20window%20of%20data%20visualization&ved=0CAMQxiAoAGoXChMIkOTU4YGz7QIVAAAAAB0AAAAAEAw) of data.

**Comment by StendProg** [comment]
As I understand you want apply some type caching for OHLC plottable. You can override existing Render method and apply filtering to points loop based on minX, maxX ( they passed to Render method).

**Comment by swharden** [comment]
Hi @artemiusgreat, these questions touch on a few different topics here so I'll try to address them best I can.

> Is there a way to define custom axis / scale or make new values appear on X axis like it's done by default?

Currently this is not possible. You can let ScottPlot determine the best ticks positions ***or*** you can define your own tick positions/labels, but currently you cannot define some positions/labels while having ScottPlot generate more.

Manually defined tick labels are good for static images, but interactive plots have the problem you identified: If you manually place grid lines and tick labels, they will overlap and look weird as you zoom out.

> e.g. millions of points of minute data for the last 5 years

I'll point out that real-time interactive display of _millions_ of data points is the primary functionality of ScottPlot! You can plot that data using the Signal, SignalConst, or SignalXY plot types (see the cookbook for examples) and you will be able to interactively navigate that at very high refresh rates. Data won't be appear as candles, but I'd argue 5 million candles will just look like a line anyway. I know this probably isn't your design goal, but I thought I'd mention it.

> I'm not sure how ScottPlot creates mapping between X coordinates and values on X scale and whether it's possible to render only small piece of data when indexes are shifted.

After thinking about it for a while, I think you probably are unlikely to achieve this type of display with the standard user control. Accomplishing this goal seems very possible, but the custom functionality (swapping data values to only render values in the data range on the screen) is probably best achieved with a custom user control. It doesn't have to be very long or complex, but it would give you full control over mouse interaction and the data scaling/windowing you pointed-out above.

I just answered another finance plot related question and thought I'd point you there (#642) in case you wanted a few more finance examples. Notice how it's real data and the dates look good without requiring custom labels

![image](https://user-images.githubusercontent.com/4165489/102702564-36caf200-4232-11eb-8e3f-c6bb5edd39e0.png)

I hope this helps!
Scott
