### ISSUE TITLE
Financial examples for SMA and Bollinger don't work

### ISSUE THREAD

**Issue by Saklut** [swharden/ScottPlot#647]
The Cookbook examples **PlotTypes: Finance - Simple Moving Average (SMA)** and **PlotTypes: Finance - Bollinger Bands** on the 4.0.44 version don't plot the lines for the indicators.

Runnnig it from Visual studio shows en exception on the output window:
```
Excepción producida: 'System.OverflowException' en System.Drawing.dll
OverflowException plotting: PlottableScatter (8 day SMA) with 75 points
```
The exception comes from this line on `PlottableScatter.cs`:
`gfx.DrawLines(penLine, points);`

The `points `array have values like this: `{X = 25.7 Y = NaN}` May this be the problem?

It works ok on version 4.0.40

-------
By the way, this is a great project, congratulations and thank you very much for your work

**Comment by swharden** [comment]
Hey @Saklut, thanks for reporting this!

I just noticed that a lot of the latest ScottPlot 4.0 cookbook recipes have issues, usually relating to validation and/or handling of `NaN`. SMA functions return an array with `NaN`, causing this problem. I'll leave this issue open reminding me to pull these features out of 4.0 (since they're more fully implemented in 4.1, #639 and #578) and to improve the cookbook.

For a quick fix, I think can you trim-off the values containing NaN like this and it should work 🤞 

```cs
var plt = new ScottPlot.Plot(600, 400);

// generate sample stock prices
OHLC[] ohlcs = DataGen.RandomStockPrices(null, 75);
double[] xs = DataGen.Consecutive(ohlcs.Length);

// calculate SMAs of different durations using helper methods
double[] sma8xs = xs.Skip(8).ToArray();
double[] sma8ys = Statistics.Finance.SMA(ohlcs, 8);
double[] sma20xs = xs.Skip(20).ToArray();
double[] sma20ys = Statistics.Finance.SMA(ohlcs, 20);

// plot technical indicators as scatter plots above the financial chart
plt.AddCandlesticks(ohlcs);
plt.PlotScatter(sma8xs, sma8ys, markerSize: 0, color: Color.Blue, lineWidth: 2, label: "SMA 8");
plt.PlotScatter(sma20xs, sma20ys, markerSize: 0, color: Color.Navy, lineWidth: 2, label: "SMA 20");

plt.Legend();
```

![image](https://user-images.githubusercontent.com/4165489/101556183-4754b000-3988-11eb-8e21-be22f020b7e6.png)

**Comment by Saklut** [comment]
Hello,

It works now (first time I use `Skip()`), I just made a couple of changes to your code above:

```C#
// generate sample stock prices
ScottPlot.OHLC[] ohlcs = DataGen.RandomStockPrices(null, 75, sequential: true);    //----
double[] xs = DataGen.Consecutive(ohlcs.Length);

// calculate SMAs of different durations using helper methods
double[] sma8xs = xs.Skip(8).ToArray();
double[] sma8ys = Statistics.Finance.SMA(ohlcs, 8).Skip(8).ToArray();    //----
double[] sma20xs = xs.Skip(20).ToArray();
double[] sma20ys = Statistics.Finance.SMA(ohlcs, 20).Skip(20).ToArray();     //----

// plot technical indicators as scatter plots above the financial chart
plt.PlotCandlestick(ohlcs);
plt.PlotScatter(sma8xs, sma8ys, markerSize: 0, color: Color.Blue, lineWidth: 2, label: "SMA 8");
plt.PlotScatter(sma20xs, sma20ys, markerSize: 0, color: Color.Navy, lineWidth: 2, label: "SMA 20");

plt.Legend();

```

Thank you very much!

**Comment by swharden** [comment]
Thanks for following-up @Saklut! I used your code to help improve the Bollinger recipes in the ScottPlot cookbooks:

* ScottPlot 4.0 https://swharden.com/scottplot/cookbooks/4.0.47/#plottypes-finance-bollinger-bands

* ScottPlot 4.1 https://swharden.com/scottplot/cookbooks/4.1.2-beta/plottable_finance.html#finance_bollinger
