### ISSUE TITLE
ScottPlotWPF not yet on NuGet

### ISSUE THREAD

**Issue by joeltroughton** [swharden/ScottPlot#65]
I'm new to WPF and C#, so I might be wrong! 

It seems ScottPlotWPF has an issue where it either isn't recognised in the namespace or isn't present. The quickstart-wpf demo gives me: `The name "ScottPlotWPF" does not exist in the namespace "clr-namespace:ScottPlot;assembly=ScottPlot"`, and I get the same error in a fresh project with ScottPlot grabbed from NuGet. Sorry if I'm overlooking something!

**Comment by swharden** [comment]
Hi @joeltroughton,

This is because I just added the WPF user control to this development repo but I haven't pushed it to NuGet yet. I plan to do that today or tomorrow, and I'll update this ticket when I do so you can check it out!

**Comment by joeltroughton** [comment]
Nice - Looking forward to checking it out! Keep up the great work

**Comment by swharden** [comment]
I just published 3.0.8 on NuGet. 

WPF Application Quickstart:
https://github.com/swharden/ScottPlot/tree/master/demos#wpf-application

I'd love feedback to hear if you find the WPF user control easy to use.
