### ISSUE TITLE
Initial values of the axes

### ISSUE THREAD

**Issue by DimitryThemes** [swharden/ScottPlot#658]
Hello! How can I make the initial filling of the axes in the plot. For example, the x-axis is the minutes from 00:01 to 23:59. The Y-axis is the price values. I want to fill the chart in real time so it should be empty at first. X and Y axes only.

**Comment by StendProg** [comment]
Hi @DimitryThemes,
Of course, you can manual set the axis limits.
```c#
plt.SetAxisLimits(-20, 80, -2, 2);
```
Check https://swharden.com/scottplot/cookbooks/4.1.2-beta/quickstart.html#quickstart_axis `Axis Labels and Limits` Demo.

Small complications with the `DateTime` axis are also easy to solve. You just need to translate the `DateTime` that way:
```c#
DateTime startTime = new DateTime(2020, 12, 14, 0, 1, 0);
DateTime endTime = new DateTime(2020, 12, 14, 23, 59, 0);
double startTimeOA = startTime.ToOADate();
double endTimeOA = startTime.ToOADate();

plt.SetAxisLimits(startTimeOA, endTimeOA, 0, 100);
```

I didn't test it, sorry for possible mistakes.

**Comment by DimitryThemes** [comment]
Thank you! It works. There is one more question. I am displaying data from Excel using PlotPoint. Each point is one trade at a certain time at a certain price. There are approximately 10,000 points in total. The function blocks the interface until the end of its work. And I want to display data in real time. What can be changed so that the function does not block the interface. Here is my code:
```cs var ex = new Microsoft.Office.Interop.Excel.Application();
            Microsoft.Office.Interop.Excel.Workbook workbook = ex.Workbooks.Open(@"D:\trades1.xls");
            Microsoft.Office.Interop.Excel.Worksheet worksheet = workbook.Sheets[1];
            Microsoft.Office.Interop.Excel.Range range = worksheet.UsedRange;
            for (int i = 2; i <= 10000; i++)
            {
                var Date = range.Cells[i, 4].Value2.ToString();
                if (Date == "#")
                {
                    return;
                }
                var Time = range.Cells[i, 5].Value2.ToString();
                var Price = range.Cells[i, 13].Value2.ToString();
                double priceD = Convert.ToDouble(Price);
                try
                {
                    DateTime dt = DateTime.ParseExact(Date + " " + Time, "dd.MM.yyyy HH:mm:ss", CultureInfo.InvariantCulture);
                    wpfPlot1.plt.PlotPoint(dt.ToOADate(), priceD, color: System.Drawing.Color.Green, markerSize: 10);
                    wpfPlot1.Render(skipIfCurrentlyRendering: true);
                }
                catch (Exception)
                {

                    
                }
}

**Comment by StendProg** [comment]
@DimitryThemes First of all, I strongly advise you to familiarize yourself with the `Cookbook` (https://swharden.com/scottplot/cookbooks/4.1.2-beta/). `ScottPlot` contains many of Plottable types which may be more suitable for your task than plotting by points. There is `OHLC` for financial data. For such a large number of points as in your example, I think only `PlottableSignal` is suitable if you want to interact.

In your example, it is more about some kind of animation than about real time. You already have all the data.
One way or another, so as not to block `UI Thread`, you need to output the data in a separate thread. It is only necessary to take into account that updating the interface (WpfPlot) is possible only in `UI Thread`.
```c#
Task.Run( () => 
{
            Microsoft.Office.Interop.Excel.Workbook workbook = ex.Workbooks.Open(@"D:\trades1.xls");
            Microsoft.Office.Interop.Excel.Worksheet worksheet = workbook.Sheets[1];
            Microsoft.Office.Interop.Excel.Range range = worksheet.UsedRange;
            for (int i = 2; i <= 10000; i++)
            {
                var Date = range.Cells[i, 4].Value2.ToString();
                if (Date == "#")
                {
                    return;
                }
                var Time = range.Cells[i, 5].Value2.ToString();
                var Price = range.Cells[i, 13].Value2.ToString();
                double priceD = Convert.ToDouble(Price);
                try
                {
                    DateTime dt = DateTime.ParseExact(Date + " " + Time, "dd.MM.yyyy HH:mm:ss", CultureInfo.InvariantCulture);
                    wpfPlot1.plt.PlotPoint(dt.ToOADate(), priceD, color: System.Drawing.Color.Green, markerSize: 10);

      // THIS LINE IS DIFFERENT!
                    wpfPlot1.Dispatcher.Invoke(new Action(() => { wpfPlot.Render(skipIfCurrentlyRendering:true) }))
      //
                catch (Exception)
                {

                    
                }
});
```
I didn't test it, sorry for possible mistakes again.

**Comment by swharden** [comment]
Hi @DimitryThemes, 

I agree with @StendProg that you will get a lot of benefit from looking over the cookbook (especially the financial plot examples): https://swharden.com/scottplot/cookbook

@DimitryThemes note that I just posted some cryptocurrency price graphing code examples in #642 you may be interested in
