### ISSUE TITLE
mantissa too large in scientific notation mode

### ISSUE THREAD

**Issue by bukkideme** [swharden/ScottPlot#66]
I just installed the latest version. I realized that in some cases, the mantissa is larger than 10. This looks a bit strange. What do you think, should this be corrected, so the mantissa is always between 0 and 10? For example, in the plot below, the lowest/top values should be 4.3 and 5.5, and the multiplier 1E15.

![mantissa1](https://user-images.githubusercontent.com/51174971/62446407-ecdb8c00-b762-11e9-9af3-73177d0303d6.png)

**Comment by Padanian** [comment]
I submitted to Scott a possible fix for this. Needs to be looked into before, though.

**Comment by bukkideme** [comment]
Another related thing which should be fixed. In the recent ScottPlot version, 10E14 means 10^14.
As much as I know, in every programming language and elsewhere, the conventional format is "1E14". So for example, the Plot should show a multiplier as "1E10", or "10^10".

**Comment by Padanian** [comment]
We've already discussed this here: https://github.com/swharden/ScottPlot/issues/57 and Scott wanted to more forward to other parts of the code.

**Comment by swharden** [comment]
Hey @bukkideme thanks for your suggestions! I added them to the running to-do list in #68 

@Padanian thanks for your pull request! I'll review it shortly. It looks like https://github.com/swharden/ScottPlot/pull/67/commits/77cda053f3297932015f4feb372427820fc84d9c is the part that improves the mantissa issue.

> We've already discussed this here: #57 and Scott wanted to more forward to other parts of the code.

I mostly wanted to focus on refactoring the user control, creating a WPF user control, and releasing on NuGet. Now that those tasks are done, I'm freed to focus on the tick module again.

The current tick generator isn't terrible, and small code fixes can improve it (e.g., this issue). However, considering tick-related issues keep popping up, I think a re-write from scratch (knowing what we know now) would benefit this project. I'll take a couple days to study this problem and track progress on #68

**Comment by swharden** [comment]
@Padanian fixed the mantissa issue (https://github.com/swharden/ScottPlot/commit/77cda053f3297932015f4feb372427820fc84d9c) thanks for bringing it up @bukkideme!
