### ISSUE TITLE
Place Y axis on Right

### ISSUE THREAD

**Issue by Linchy** [swharden/ScottPlot#660]
Hi when viewing financial charts, it can be useful to show the Y axis on the right, closest to the latest data point. It looks like currently this isn't possible, from this code:
```
        public static void FigureTicks(Settings settings)
        {
            if (settings.dataSize.Width >= 1 && settings.dataSize.Height >= 1)
            {
                settings.ticks.x.Recalculate(settings);
                settings.ticks.y.Recalculate(settings);
                RenderTicksOnLeft(settings);
                RenderTicksOnBottom(settings);
                RenderTickMultipliers(settings);
            }
        }
``` 
Would be great to have! Library is very nice nontheless.

**Comment by swharden** [comment]
Hi @Linchy, 

Multiple axes is a is a new feature in ScottPlot 4.1. To make this easier to discover I added a new example to the cookbook:

```cs
OHLC[] prices = DataGen.RandomStockPrices(null, 30, TimeSpan.FromMinutes(5));
plt.AddCandlesticks(prices);
plt.XAxis.DateTimeFormat(true);

plt.YAxis.Ticks(false);
plt.YAxis2.Ticks(true);
plt.YAxis2.Label("Price (USD)");
```

![image](https://user-images.githubusercontent.com/4165489/102703729-a5af4780-4240-11eb-9515-e010875397d3.png)

You can see additional multi-axis examples in the cookbook: https://swharden.com/scottplot/cookbooks/4.1.2-beta/#multi-axis

Hope it helps!
Scott
