### ISSUE TITLE
Wpf Graph is always set to pan or zoom

### ISSUE THREAD

**Issue by Rowwbit** [swharden/ScottPlot#663]
I tested out one of the cookbook examples and converted it to work with WPF. I have a WpfPlot in the MainWindow thats inside a TabItem. It seems if you left click to pan it acts as if the key is stuck and you cant release it. Basically setting the Graph to constantly pan while the mouse is moved. I tested to see if it only occurs if you drag offscreen but it still does it either way.

```
public static WpfPlot Test1()
        {
            WpfPlot wpfPlot = new WpfPlot();

            // generate random data to plot
            System.Random rand = new System.Random(0);
            int pointCount = 10;
            double[] xs = DataGen.Consecutive(pointCount);
            double[] ys = DataGen.RandomNormal(rand, pointCount, 20, 5);
            double[] yError = DataGen.RandomNormal(rand, pointCount, 5, 2);

            // make the bar plot
            wpfPlot.plt.PlotBar(xs, ys, yError);

            // customize the plot to make it look nicer
            wpfPlot.plt.Axis(y1: 0);
            wpfPlot.plt.Grid(enableVertical: false, lineStyle: LineStyle.Solid);

            // apply custom axis tick labels
            string[] labels = { "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten" };
            wpfPlot.plt.XTicks(xs, labels);

            // Restrict moving graph
            wpfPlot.Configure(enablePanning: true, recalculateLayoutOnMouseUp: false, enableRightClickZoom: false, lockVerticalAxis: true);

            return wpfPlot;
        }

// IN MAIN
 public MainWindow()
{ 
     GraphView_Plot.Content = GraphViewGenerator.Test1();
     GraphView_Plot.Render();
}
```

**Comment by swharden** [comment]
Hi @Rowwbit, I put two plots in different tabs and it seems to work on my end, even when I drag/drop off the screen. Could the problem be your XAML or WPF layout? Here's what works for me:

![wpftab](https://user-images.githubusercontent.com/4165489/102703984-199f1f00-4244-11eb-9aff-53f8c70aad55.gif)

```xaml
<DockPanel>
    <TabControl>
        <TabItem Header="ScottPlot 1">
            <DockPanel>
                <ScottPlot:WpfPlot Name="WpfPlot1"/>
            </DockPanel>
        </TabItem>
        <TabItem Header="ScottPlot 2">
            <DockPanel>
                <ScottPlot:WpfPlot Name="WpfPlot2"/>
            </DockPanel>
        </TabItem>
    </TabControl>
</DockPanel>
```

```cs
public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();

        WpfPlot1.plt.Title("Plot 1");
        WpfPlot1.plt.PlotSignal(ScottPlot.DataGen.Sin(51));

        WpfPlot2.plt.Title("Plot 2");
        WpfPlot2.plt.PlotSignal(ScottPlot.DataGen.Cos(51));
    }
}
```

**Comment by Rowwbit** [comment]
Thanks for the reply. I did some more testing with this issue and it seems that its an issue with this bit of code. Assigning the plt.content to a method that returns a WpfPlot causes it. 
``` GraphView_Plot.Content = GraphViewGenerator.Test1(); ```

The code below works perfectly fine as you show with the same plot.
``` GraphView_Plot.plt.PlotSignal(ScottPlot.DataGen.Sin(51)); ```

**Comment by swharden** [comment]
> Assigning the plt.content to a method that returns a WpfPlot causes it

Interesting! I figured it was something to do with that code because it seemed to work okay when explicity defined in the XAML. I'm glad you got this one figured out, and thanks for the follow-up!
