### ISSUE TITLE
How do I use Linked Axes ?

### ISSUE THREAD

**Issue by MosheBarkan** [swharden/ScottPlot#670]
Im sorry I'm asking such a basic question but I couldn't find any examples of how to use it.
In ScottPlot Demo WinForms (4.0.44) there is an example of "Linked Axes",
I couldn't find code example of it in ScottPlot Cookbook...
Im really interested in this feature.

Thanks from advance !

https://user-images.githubusercontent.com/17156929/102805116-6cebab80-43c3-11eb-86fd-e49f67e8359d.mp4

**Comment by swharden** [comment]
Hi @MosheBarkan! Code for that example is here 

https://github.com/swharden/ScottPlot/blob/343f74864cebb3cde3cef579bab7f8fc48bded5f/src/ScottPlot.Demo.WinForms/WinFormsDemos/LinkedPlots.cs#L13-L46

I'm working on a FAQ page (#572, #651) which will make this easier to discover in the future.

Hope it helps!
Scott
