### ISSUE TITLE
Tick label color

### ISSUE THREAD

**Issue by hjlee1978** [swharden/ScottPlot#672]
tested version: 4.0.47 ~ 4.1.2-beta

Can't change the tick label color.
'ScottPlot.Renderable.Axis.TickLabelStyle()' does not change the font color.

![ScottPlot_Style_Blue3](https://user-images.githubusercontent.com/69839560/102836656-4702ed00-443d-11eb-894d-a0c5dd759bd7.png)

![ScottPlot_Plottable_Text](https://user-images.githubusercontent.com/69839560/102836659-48ccb080-443d-11eb-8e98-619de337cd11.png)

**Comment by swharden** [comment]
Thanks @hjlee1978, good catch! Fixed this with dc80d97

This looked bad:
https://swharden.com/scottplot/cookbooks/4.1.2-beta/style.html#style_blue3

But now it's better 👍 
![image](https://user-images.githubusercontent.com/4165489/102843465-40da2580-43d7-11eb-8398-216b5c88e586.png)
