### ISSUE TITLE
Incorrect Fill Rendering for Scatter and Signal plots

### ISSUE THREAD

**Issue by MithrilMan** [swharden/ScottPlot#676]
Hello and thanks for this OS library
I'm trying to use PlotfillAboveBelow but I get inconsistent result

I'm using dotnetcore 3.1 and I'm rendering in memory and this is the result
![image](https://user-images.githubusercontent.com/5107375/103055776-73348000-459b-11eb-8bb9-c372d1914797.png)

How you can see, points above and below doesn't connect properly
If i print same data using bars, these are this is the output
![image](https://user-images.githubusercontent.com/5107375/103055797-82b3c900-459b-11eb-9321-aaad9e92f294.png)

(the green line is a vertical span set at the same height of the baseline of the 1st chart)
how you can see the 1st chart shouldn't have overlapped areas.

Thanks.

**Comment by MithrilMan** [comment]
It's like if the chart split the series in positive and negative and thus connect just points of the same series, so the fix should be to generate intermediate points in each series where the line cross the baseline.

**Comment by swharden** [comment]
Hi @MithrilMan, thanks for pointing this out!

While looking deeper into it I also found that this type of fill renders incorrectly when zoomed in on signal plots

![image](https://user-images.githubusercontent.com/4165489/103098222-f96eb780-45d7-11eb-91a2-5ae5bf5ebb54.png)

I'll look into this and see if I can fix this behavior in both scatter and signal plots

**Comment by MithrilMan** [comment]
thanks!

**Comment by swharden** [comment]
I fixed PlotFillAboveBelow() and it will be available in the next release. See the changes in 0441167 in case you want to implement this change yourself in your existing code: PlotFillAboveBelow() just calculates corners for two polygons (a red one and a green one) then adds them both to the plot. My fix improved that calculation to respect line intersections. This method could still be optimized, but it's functional in its current state.

The rendering issue in signal plots still merits investigation, but the primary issue underlying this ticket is resolved so I'll close it.

Thanks again for mentioning this @MithrilMan! 👍 

before | after
---|---
![image](https://user-images.githubusercontent.com/4165489/103175659-9f6d2c80-4839-11eb-9307-5b769258c176.png)|![image](https://user-images.githubusercontent.com/4165489/103175682-be6bbe80-4839-11eb-8031-8961b158ec0a.png)

**Comment by MithrilMan** [comment]
cool thanks will give it a try
