### ISSUE TITLE
create an improved (and encapsulated) tick mark generator

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#68]
Tick generation in ScottPlot works but has been sub-ideal for quite some time, as noted by several issues: #66, #57, #54, #47, #28, #17, #3, #2, and #1

Creating tick marks for an axis seems like an easy task at first, but there are several tricky parts that make this difficult to implement cleanly, simply, and correctly. Rather than continuing to pile extra functionality onto the current tick module (hacks on top of hacks), let's get this right and demonstrate it working in an isolated class independent of ScottPlot. Once a new (and good) tick generator is working, I can modify ScottPlot to use it. 

### Programming Problem

A procedural style seems ideal for this task. A good solution will be short, easy to read, and avoid nested loops and if statements as much as possible. This function should probably be developed and tested using a Console Application.

The tick generator should take in:
* the 4 corners of a plot (units): `double x1`, `double x2`, `double y1`, `double y2`
* the width and height of the plot (pixels): `int width`, `int height`
* font and font size (for determining if ticks overlap)
* an optional manually-defined tick spacing

The tick generator should produce:
* an array of tick locations for each axis (a double array of actual units)
* an array of tick labels for each axis (a string array)
* a double for the multiplier of each axis (to display in the corners)
* a double for the offset of each axis (to display in the corners)

### Visual Representation

![image](https://user-images.githubusercontent.com/4165489/62467117-f8c64e80-b760-11e9-8908-caeb62469ab1.png)

### Misc
* when using exponential notation, keep the coefficient less than 10 - @bukkideme commented in (#66)
* when using exponential notation, use "1e123" notation (not 10e123) - @bukkideme commented in (#66)
* @Padanian has been working on this in #69

**Comment by bukkideme** [comment]
@swharden 
Indeed, this part is really not an easy thing! I just started to dig into this topic, trying to find some implemented solution, maybe in github?
Actually there are even scientific publications about the "non-data components of a visualization", not a trivial thing for sure! 
One example paper from this topic:
[http://vis.stanford.edu/files/2010-TickLabels-InfoVis.pdf](http://vis.stanford.edu/files/2010-TickLabels-InfoVis.pdf)

**Comment by Padanian** [comment]
Found this in python. Have a look, and if you think it may be useful, I can convert it into an helper class or .dll

[nice.zip](https://github.com/swharden/ScottPlot/files/3468024/nice.zip)

**Comment by Padanian** [comment]
Submitted conversion of Nice.py from netsa.data.nice — “Nice” Numbers for Chart Bounds.
https://tools.netsa.cert.org/netsa-python/doc/netsa_data_nice.html#netsa.data.nice.nice_ticks_seq
License is GNU.

**Comment by swharden** [comment]
> Submitted pull request of conversion of nice.py from netsa.data.nice — “Nice” Numbers for Chart Bounds.

Referencing: https://github.com/swharden/ScottPlot/pull/67/commits/23c17943b9f1b1d3799fa096466c3f1065eb5bcd

This looks great - I'll check it out in detail this evening!

> License is GNU.

This is the first time we may have a licensing conflict...

It's really important to me that ScottPlot is as permissively licensed as possible. Currently it's MIT licensed, which was the most permissive common license I could find. My understanding is that GNU requires that modifications be made open source, which is more restrictive than I'd like... It would be great if ScottPlot end users can use ScottPlot in commercial applications, legally, modifying it however they see fit, without being forced to release the source code of their commercial product.

I wonder what it would take to make this MIT licensed? If we re-wrote the methods that nice implements, would that be enough? Is my concern in the first place even valid? I'm not very familiar with software licensing...

**Comment by Padanian** [comment]
To be completed honest, converting from python to c# already involves re-writing the methods, at least syntactically.
Also I had to cut away the “generator - iterator” part which is python-only related.
The algorithms are in the public domain, after all, being for the most part Paul Heckbert's algorithms, already available throughout the web in a variety of languages and licenses.
Before going deeply into legal matters, have a look at the underlying operation of the methods.

**Comment by swharden** [comment]
> * converting from python to c# already involves re-writing the methods
> * I had to cut away the python-only code
> * The algorithms are in the public domain

I think that's good enough for me! We can rename the methods (let's not call it "nice") and also rewrite the comments so no one accidentally thinks these functions were copy/pasted from somewhere. This seems sufficient to classify the module as original, and covered by the MIT license that covers the rest of this project.

**Comment by Padanian** [comment]
Deal!
Once you incorporated the class, I will pull it my side and complete it with the ticks calculation for time domains.
Please note this is my last week before a two-week holiday.
 
Cheers.

**Comment by swharden** [comment]
I took the "Nice" code and cleaned it up (removed comments, renamed methods) and placed it all in a `TicksExperimental` class for now. All the methods are private except for `GetTicks()`. That code is now in [TicksExperimental.cs](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/TicksExperimental.cs)

I created a console application for testing:
https://github.com/swharden/ScottPlot/blob/8626810704140ccbfc29422f76929faa03ca3001/demos/dev/tick-tester/Program.cs#L11-L28

### Output

```
5 ticks in [-10 - 10]: -10 -5 0 5 10 
5 ticks in [-50 - 50]: -50 -25 0 25 50 
4 ticks in [-77 - 123]: -50 0 50 100 
5 ticks in [-12345678 - -12345677]: -12345678 -12345677.75 -12345677.5 -12345677.25 -12345677 
5 ticks in [-1.23456781234568E+15 - -1.23456781234568E+15]: -1.23456781234568E+15 -1.23456781234568E+15 -1.23456781234568E+15 -1.23456781234568E+15 -1.23456781234568E+15 
5 ticks in [1E-07 - 1.1E-07]: 1E-07 1.025E-07 1.05E-07 1.075E-07 1.1E-07 
```

**Comment by swharden** [comment]
... and you're right! This does an awesome job! These functions take us 90% of the way to our goal. The last steps are:

* add support for offset and multiplier labels
* add method to ensure ticks don't overlap given a certain number of pixels/font

**Comment by Padanian** [comment]
[-1.23456781234568E+15 - -1.23456781234568E+15] is odd because the two differ for 1, which is smaller than the least significant decimal figure.
Trying to get 10 ticks, ends up in infinite loop for some reason.
Apart from that, I’m happy about the result.
 
I will complete the work with time domains ticks calculation tomorrow.

**Comment by Padanian** [comment]
Commited ticks calculator, now to add support for offset and multiplier labels

**Comment by Padanian** [comment]
Would you consider using Unicode characters for multiplier labels?

![immagine](https://user-images.githubusercontent.com/7769348/62605750-09aac780-b8fb-11e9-940d-3237d9f5efa1.png)

**Comment by Padanian** [comment]
And print offset and multiplier with something like this:

![immagine](https://user-images.githubusercontent.com/7769348/62606575-d406de00-b8fc-11e9-8a38-e37b94b0b766.png)

**Comment by Padanian** [comment]
In case offset requires exponential notation, it's supported too

![immagine](https://user-images.githubusercontent.com/7769348/62610583-3e6f4c80-b904-11e9-9301-11fd7501ca7b.png)

**Comment by Padanian** [comment]
The result

![immagine](https://user-images.githubusercontent.com/7769348/62632213-67a6d180-b932-11e9-87b9-d4f4d2b795e7.png)

**Comment by swharden** [comment]
note that this issue references https://github.com/swharden/ScottPlot/pull/69

**Comment by swharden** [comment]
### Conclusion
I made many large changes to the way ScottPlot handles tick calculations, tick labels, and grid lines. These are the highlights:
* The new [TickCollection class](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/TickCollection.cs) does all the tick calculations. It is aware of the graph settings which allows it to do some fancy things:
  *  It assesses the graph dimensions and tick font to predict the best tick density to produce non-overlapping ticks. 
  * Tick marks look natural as the windows are resized.
  * The entire tick generation class is about 100 lines. 
* The ability to manually define grid spacing is preserved. Any future changes to the tick code have to keep in mind that tick spacing can be user-defined as seen in the [manual grid spacing cookbook example](https://github.com/swharden/ScottPlot/tree/master/cookbook#manual-grid-spacing)
* @Padanian did some impressive work in [TickExperimental.cs](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/TickExperimental.cs) but that code is currently inactive. This code is a useful reference, and once this new tick system is more thoroughly tested we can use that code to help add support for DateTime objects. There is also highly useful code for generating scientific notation strings using Unicode exponent characters.

https://github.com/swharden/ScottPlot/blob/fbb2d5c7d7e104450558aaa22441743cdb9f2bce/src/ScottPlot/TickCollection.cs#L10-L114

### tick tester (console application) output
```
Tick Collection: [-2, -1.5, -1, -0.5, 0, 0.5, 1, 1.5, 2] e12
Tick Collection: [0, 0.5, 1, 1.5, 2] e12 +2.1226e16
Tick Collection: [-0.4, -0.3, -0.2, -0.1, 0, 0.1, 0.2, 0.3, 0.4] e-12
Tick Collection: [0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4] e-12 +4.59515e-09
Tick Collection: [-15, -10, -5, 0, 5, 10, 15] 
Tick Collection: [-25, 0, 25] 
Tick Collection: [-50, 0, 50, 100] 
Tick Collection: [0, 0.25, 0.5]  +-12345677.75
Tick Collection: [0, 0.25, 0.5]  +-1.23456781234568e15
Tick Collection: [10, 10.25, 10.5, 10.75] e-8
Tick Collection: [0, 0.25, 0.5, 0.75] e-13 +1.00000125e-07
Tick Collection: [12.5, 15, 17.5, 20] e7
```

### tick tester (winforms)
![image](https://user-images.githubusercontent.com/4165489/62815682-f14ccf80-bae9-11e9-8fa7-02b1dde81e7b.png)

**Comment by swharden** [comment]
@Padanian's code was moved to [/dev/code/TickExperimental.cs](https://github.com/swharden/ScottPlot/tree/master/dev/code/TickExperimental.cs)

It was moved out of the code source folder to make the .NET Core 3.0 transition easier.

It is being kept because many of these functions can be re-used (especially when time axis labels are supported)

**Comment by swharden** [comment]
Connecting the dots here, a desire to use a formal/published tick generation system has recently re-emerged #394
