### ISSUE TITLE
 zoom in and out  by mousewheel

### ISSUE THREAD

**Issue by axmand** [swharden/ScottPlot#7]
Hi~ This is a great plot library under .net framework.
Is there an operation that optimizes the ability to zoom in or out with event 'mousewheel'?

**Comment by swharden** [comment]
Currently the only way to zoom is right click drag. You could make the mouse wheel also zoom by adding your own event handler to catch scroll wheel events. Every time the scroll wheel is scrolled you can use the `AxesZoom` function to zoom in or out.

https://github.com/swharden/ScottPlot/tree/master/doc#signalzoomedpng

Good luck!

**Comment by swharden** [comment]
This feature was added to ScottPlot v3
