### ISSUE TITLE
plotting arrays with >2GB of data

### ISSUE THREAD

**Issue by StendProg** [swharden/ScottPlot#74]
I found solution to break 2GB array size limit.
This allow to plot really huge signals up to array maximum index limit: int.MaxValue = 2G elements.
May be add this in Cookbook, some people may be interested in that.
[Solution](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/gcallowverylargeobjects-element?view=netframework-4.8) is to add in App.config
```xml
<configuration>  
  <runtime>  
    <gcAllowVeryLargeObjects enabled="true" />  
  </runtime>  
</configuration>
```

**Comment by swharden** [comment]
Thanks for this @StendProg! I'll add this to the cookbook.

To restate the problem, the maximum number of elements in an array is typically UInt32.MaxValue (2,147,483,591).

On 64-bit platforms, setting gcAllowVeryLargeObjects enables use of arrays that are greater than 2 gigabytes (GB) in total size. Official documentation: [gcAllowVeryLargeObjects Element](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/gcallowverylargeobjects-element)

**Comment by StendProg** [comment]
Not correct, maximum number of elements always UInt32.MaxValue (2,147,483,591) With this solution too.
This solution for other problem is 2 gigabyte memory limit for any objects, like array.
For array of double this means 2GB / 8 bytes = 256 millions elements.

**Comment by Padanian** [comment]
In september I will inspect the possibility to replace the GDI Draw primitives with DirectX, to overcome the bottleneck of GDI.
 
Ps I’ve got few pending pull request for TickExperimental, in case you didn’t notice. I’d love to hear your opinion.

**Comment by swharden** [comment]
> Not correct, maximum number of elements always UInt32.MaxValue (2,147,483,591) With this solution too.
> This solution for other problem is 2 gigabyte memory limit for any objects, like array.
> For array of double this means 2GB / 8 bytes = 256 millions elements.

Thanks for correcting me! I understand now. I'll add an example of >2GB data to the cookbook.

**Comment by swharden** [comment]
> In september I will inspect the possibility to replace the GDI Draw primitives with DirectX, to overcome the bottleneck of GDI.

This will be a great contribution!

> Ps I’ve got few pending pull request for TickExperimental, in case you didn’t notice. I’d love to hear your opinion.

I haven't gotten to take a thorough look at it yet, but I'll let you know when I do. It looks promising - thanks!

**Comment by Padanian** [comment]
Thanks, I’ll be back in late August.

**Comment by StendProg** [comment]
In my tests i can draw maximum 500M points on 32 GB machine. More points not tested need lots of RAM

**Comment by StendProg** [comment]
> In september I will inspect the possibility to replace the GDI Draw primitives with DirectX, to overcome the bottleneck of GDI.
Sounds amaizing, very interested in that.

**Comment by swharden** [comment]
My system doesn't have enough ram to let me test beyond the 2GB limit so I probably won't add a working demo to the cookbook.

I did add a note about `gcAllowVeryLargeObjects` to the first cookbook example which demonstrates Signal: https://github.com/swharden/ScottPlot/tree/master/cookbook#signal

@StendProg thanks for sharing this tip!
