### ISSUE TITLE
zooming far out crashes signal plots

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#75]
recreating the bug:

* start the "plot types" demo
* clear
* plot a signal (10M points)
* zoom out _horizontally_ very far

If you zoom out far enough it doesn't crash. If you zoom out smoothly it will. It crashes in the "RenderLowDensity" function, which is probably a clue to the problem - that function should only be used when signals are zoomed very far in. Therefore, this problem will probably be corrected code in this function:

https://github.com/swharden/ScottPlot/blob/ffe802fed54f06904f949ea61b1a9eb2e5740c6a/src/ScottPlot/plottables/PlottableSignal.cs#L132-L148

**Comment by swharden** [comment]
Fixed
https://github.com/swharden/ScottPlot/blob/310a27bc0e337f4d426495ed836becec3ff82c40/src/ScottPlot/plottables/PlottableSignal.cs#L142-L148

But now the graph disappears (rather than crashing) when you zoom far out...

**Comment by StendProg** [comment]
I have same problem then testing 500M poins. Zoomed out not far, 2x-4x. This problem based on int overflow during indexes calculation. Int32.MaxValue not so far from 500 millions :).  Get negative visible points count becouse overflow in addition, goes wrong render type and crashed on trying allocate negative size array.
This problem may be more complex then it looks. Whole library based on int types, so fixing one place may be not enouth.

**Comment by StendProg** [comment]
Posible solutions:
- calculate indexes using long type
- block zoming to that ranges
- stay as is, this happened on rare use cases
- stay as is, but documented this behavour, to let users avoid them

**Comment by swharden** [comment]
Heh, I came up with a different solution still! A custom function to render very zoomed-out data as a single vertical line.

https://github.com/swharden/ScottPlot/blob/500b655f604ff73b0f432bfc97425e350545bf8a/src/ScottPlot/plottables/PlottableSignal.cs#L155-L162

https://github.com/swharden/ScottPlot/blob/500b655f604ff73b0f432bfc97425e350545bf8a/src/ScottPlot/plottables/PlottableSignal.cs#L61-L68

... another speed boost for PlotSignalConst() could be storing the values of min/max so they don't have to get looked-up repeatedly.

**Comment by StendProg** [comment]
On huge signals before crasing it looks not like single vertical line.
Render calls only then signal displaying must be change. This means different intervals in most cases, story previous gives nothing.
I think it have enouth speed at queries.
#73 brings significant reduce trees initial calculation time. About 1 second for 50M signal.

**Comment by swharden** [comment]
Sounds good, thank you!

**Comment by swharden** [comment]
I settled on this solution:
https://github.com/swharden/ScottPlot/blob/bf4d562f78c2168bf27179ce3ffbd9ae5bb21b60/src/ScottPlot/plottables/PlottableSignal.cs#L155-L166
