### ISSUE TITLE
Updating data of SignalConst

### ISSUE THREAD

**Issue by StendProg** [swharden/ScottPlot#78]
I did some work on updating data of SignalConst, not fully finished yet.
And i need some interface disscusion help.
At first SignalConst need new name.
Data updates more slow O(log2(n)), compare to constant O(1) for Signal, but possible and works unexpectedly fast in my tests.
Updating by data ranges goes more faster.
On source data changes need to trigger updating trees methods and told it that elements changed.
Array type hasn't any way to do it automatically. So need some interface functions to do that.
User need to be able to trigger 2 types of methods UpdateElem(index,value) and UpdateRange(from, to, newData).
Or maybe update source data manualy and trigger DataUpdated(index) and RangeUpdated(from, to).
Posible solutions:
- Return by Plot.PlotSignalConst interface that contain that methods
- wrap double[] to another type that can notify on data changes like BindableList<> or our own realization of wrapper. And allow user only plot that type of data like 
PlotSignalConst(BindableList<> data).

I think best solution is to make all this interfaces( and all the others that you will find), and allow user to select.
If you are interested in tests i can make early pull request it already works with simple interface.

**Comment by swharden** [comment]
Hi @StendProg, thank you for your hard work on this project! SignalConst() has been a great improvement, and the name is good for now while we continue to develop/test it.

A primary goal for this project is to keep the code as simple and minimal as possible. Although performance improvements are good, I often struggle between wanting to add improvements and not wanting to add more complexity. The simplest solution is probably the best one.

For now, let's add functions which update data (and the trees) as methods of the PlottableSignalConst class. This will help contain experimental code (and complexity) inside the PlottableSignalConst class while we continue to develop and test it. 

```cs
// this is how to access a plottable object after it's been created
plt.PlotSignalConst(tenMillionPoints);
var sig = plt.GetPlottables()[0];

// data could be updated several different ways
sig.updateData(index, value);
sig.updateData(indexFirst, indexLast, values);
```

What do you think about something like this?

**Comment by StendProg** [comment]
It’s so uncomfortable to find the desired plot in the GetPlottables for me. I thinking about
`
IUpdateData updateData = plt.PlotSignalConst()
updateData.update(index, value);
`
With you solution you need provide updateData implementation for all Plottables, but only SignalConst need it at now.

**Comment by StendProg** [comment]
I have some overloads for updateRange, so if it changed to updateData() does look ok at all?
```c#
sig.updateData(int index, double value); // signle element
sig.updateData(int from, int to, double[] newValues); 
sig.updateData(int from, double[] newValues); //to goes from newValues.Length
sig.updateData(double[] newValues); //update from 0 to newValues
sig.updateData(int from, int to, double[] newValues, int dataFrom) // dataFrom offset in newValues
```
Updates by range match typical use case and more faster.
But most users prefer 
```c#
for (int i; i < n ; i++) 
  updateData(i, newValue)
```
because it simple for them and they don't know that this not optimal.
Thats why i thinking about separating names by updateElem and updateRange()
With documentation of benefits updateRange() it teach user to prefer updateRange.
Naming all by updateData makes user to think that its all the same.

**Comment by swharden** [comment]
Your idea for separate `updateElem()` and `updateRange()` makes sense. Your idea is very good - by separating them it becomes difficult to use them incorrectly.

I agree the current "getPlottables()" method is very bad. I've been meaning to update all plot functions to return the object that was just created (#79) so this method can stop being used (I use it elsewhere). Doing this will make it easier to do things like adjust styling (colors, line widths, etc) and positions (for axis lines) of objects after are created by modifying their properties or calling their methods.

This change would allow you to do this:
```cs
PlottableSignalConst sig = plt.PlotSignalConst(data);
sig.updateElem(index, value);
```

Do you think this would work for you? I can implement this change today.

**Comment by StendProg** [comment]
I implement the same but only for PlotSignalConst.

**Comment by StendProg** [comment]
PR #80 implement updateData interface.

**Comment by swharden** [comment]
I just merged #80 - thanks @StendProg! I'll create a demo now dedicated to demonstrating advanced usage of SignalConst.

**Comment by swharden** [comment]
I removed all the advanced functions from the "plot types" demo (I'm trying to keep that as minimal as possible). 

I created a standalone demo just for testing PlotSignalConst(). It's in the master branch ([/demos/src/plottable-const](https://github.com/swharden/ScottPlot/tree/master/demos/src/plottable-const)). We can make this one as complex as we want!

![image](https://user-images.githubusercontent.com/4165489/62824268-5d224d00-bb69-11e9-8f68-16dbd534c257.png)

**Comment by StendProg** [comment]
Looks good. Plot types project has place only for 1 button. I tried to keep it unchange. May be fill PlottableConst Demo in future works.

**Comment by swharden** [comment]
> Looks good. Plot types project has place only for 1 button. I tried to keep it unchange. May be i will fill PlottableConst Demo in future works.

That's okay! The part I wanted to keep minimal is the _code_ of "plot types" (not just the graphical interface). Every plot type is demonstrated in examples that are about 10 lines or less in size: [/demos/src/plot-types/Form1.cs](https://github.com/swharden/ScottPlot/blob/master/demos/src/plot-types/Form1.cs)

The methods you created to update PlotSignalConst data were pretty complicated (in comparison) so I moved them into [/demos/src/plottable-const/Form1.cs](https://github.com/swharden/ScottPlot/blob/master/demos/src/plottable-const/Form1.cs) and you can continue to develop code in that application to demonstrate as much advanced functionality as you'd like.

Thank you again for your contributions @StendProg!
