### ISSUE TITLE
return a Plottable when it is created

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#79]
When I need to modify the properties or data of a plottable after it's been created, I usually pull it with something like:

```cs
plt.PlotScatter(xs, ys);
var scatterPlot = plt.GetPlottables().Last();
```

Let's make this easier by changing the return types of plot methods from void to Plottable to allow the newly created plottables to be placed in memory when they're created. In cases where the user knows they want to modify a plot's properties or access its methods later they could keep it around with:

```cs
var scatterPlot = plt.PlotScatter(xs, ys);
```

Edit: Another use case is situations like #78 where a Plottable's methods need to be easily accessible.

**Comment by StendProg** [comment]
More better then returning void and brings nothing negative.

**Comment by swharden** [comment]
Done! 96f7a757ac39fb6053e9ca4c1f29b285b800563c

Note that `PlotSignalConst()` returns a `PlottableSignalConst` now (not a `PlottableSignal`)

note to self: create cookbook examples demonstrating several ways this can be used, then close this issue.

**Comment by swharden** [comment]
https://github.com/swharden/ScottPlot/tree/master/cookbook#modify-styles-after-plotting
