### ISSUE TITLE
create a serial port data plotter

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#82]
I'd like to plot CSV-formatted data coming in from the serial port in real time (at a rate of about 100 lines per second). These are already some good programs out there that do this job well so there's no need to create a full-featured application here (anyone actually wanting to plot serial data can use one of the existing applications). However, this task is a good demonstration for how to use ScottPlot in realtime graphing applications.

## My Hardware

![image](https://user-images.githubusercontent.com/4165489/62828514-6ab1f400-bbb6-11e9-827e-5af4903f86e2.png)

I'm developing this program using with a custom board (from a private project) that has essentially the same output as my public [USB counter project](https://github.com/swharden/USB-Counter). This serial device I'm working with continuously outputs values like:

```
19018,29773,32,19374
19080,29768,32,19501
19390,29768,32,19117
19694,29763,32,19248
20247,29758,33,18867
```

## Currently Available Software

Seeing how others accomplish this task may be useful. It's also a glimpse into how others use libraries other than ScottPlot to achieve this goal.

### SerialPlot (hyOzd)

After googling for what apps are out there that may do this, the best free free app I found is [hyOzd's SerialPlot](https://bitbucket.org/hyOzd/serialplot). It's open-source (C++) and uses the Qt library for the display. Specifically it seems to be [QwtPlot](https://www.google.com/search?q=qwtplot&tbm=isch). The app works pretty well, although the graph is a bit jittery and it does not support smooth mouse interaction (you can zoom into a square, but there's no zooming out).

![image](https://user-images.githubusercontent.com/4165489/62828391-37ba3100-bbb3-11e9-8998-100d6fbdcd5e.png)

### Serial Lab (ahmedelsayed-93)

I found https://github.com/ahmedelsayed-93/Serial-Lab more recently. It's written in C#. It looks like they use [System.Windows.Forms.DataVisualization.Charting](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datavisualization.charting?view=netframework-4.8) to create graphs.

![image](https://user-images.githubusercontent.com/4165489/62836112-eb600700-bc2d-11e9-8636-04682205c2f0.png)

doh! It seems super buggy when plotting my data. I think it's not able to parse fast enough and drops values. It also can't resize, its axis tick marks broke somehow, and it's not mouse interactive.

**Comment by swharden** [comment]
This works well enough I'm happy with it for now: [/demos/src/serial-data-plotter](https://github.com/swharden/ScottPlot/tree/master/demos/src/serial-data-plotter)

![image](https://user-images.githubusercontent.com/4165489/62840189-5a585280-bc64-11e9-8edc-cb853ade271c.png)

**Comment by strocchia** [comment]
Hi Scott,

This is great, I really like the simple UI you have created! I'm trying to make my own serial plotter implementation for a singular recording channel (whereas you have 4 ADC measurements). I've been reading a lot of blog & stackoverflow posts saying that using the 'DataReceived' event trigger is bad because it is unreliable and does not make proper use of the underlying Win32 API. Are you aware of this? I'm curious if you have recommendations on reliable data streaming. Thanks!
