### ISSUE TITLE
Migrate to .NET Core 3.0

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#86]
This topic was initially discussed in #85. When the time comes consider asking @petarpetrovt for assistance/review of the migration and implementation. Migration has been practiced (#95) and should be straightforward.

**Wait to migrate until Visual Studio fully supports Windows Forms in .NET Core 3.0:** Many demo applications have advanced features (such mouse-draggable axis lines) which are only supported in Windows Forms. Currently, the Visual Studio deisgner does not support Windows Forms in .NET Core 3.0. ScottPlot will conservatively wait to migrate to .NET Core 3.0 until Visual Studio fully supports it.

- [x] consolidate all demos into a single application
- [ ] migrate ScottPlot project to .NET Core 3.0 (using System.Drawing.Common)
- [ ] ensure [target frameworks](https://docs.microsoft.com/en-us/dotnet/standard/frameworks) include `net45` and `netcoreapp3.0`
- [ ] add tests for .NET Framework and .NET Core (to detect issues like #138)
_currently Azure Pipelines does not support running tests in solution files containing mixed .NET Framework and .NET Core projects._
- [ ] publish ScottPlot as a multi-framework package on NuGet

**Comment by swharden** [comment]
After considering whether or not to break this project up into 3 (a plotting class library, a winforms user control, and a WPF user control) I decided to keep it all one project (#87). Briefly, this makes maintaining it and distributing it easier, and I've found that WinForms and WPF can coexist peacefully.

However, I do want to rename `ScottPlotUC` and `ScottPlotWPF` to `FormsPlot` and `WpfPlot`. I know this will be a breaking change which might be a pain to resolve for existing projects (requiring getting into the Designer.cs to fix). I think this change is logical though, and I think it makes sense to do this earlier than later. The transition from .NET Framework to .NET Core next month may be the best time to do this.

Thinking forward, the UserControls folder may eventually contain GUI elements like windows forms (e.g., custom save data dialogues).

WinForms and WPF controls together | The project can stay clean and organized
---|---
![image](https://user-images.githubusercontent.com/4165489/62906718-dc687a00-bd3d-11e9-999e-64290a25bc6d.png) | ![image](https://user-images.githubusercontent.com/4165489/62906721-e68a7880-bd3d-11e9-8849-a7b59ebbed3a.png)

**Comment by swharden** [comment]
* ScottPlot is now .NET Core 3.0 and builds for .NET Framework 4.5 too
* I converted the plot types demo to .NET Core and it runs fine
* Other demos which use .NET Framework still run fine
* I converted the cookbook to .NET Core and the output is identical
* It's generating NuGet packages that look good too: **[ScottPlot.3.1.0.nupkg.zip](https://github.com/swharden/ScottPlot/files/3495065/ScottPlot.3.1.0.nupkg.zip)**

I guess we can start uploading these packages to NuGet whenever we want...

**Comment by swharden** [comment]
I've been building https://github.com/swharden/Spectrogram as .NET Core 3.0 

When it's officially released, I'll convert this project to .NET Core easily

**Comment by swharden** [comment]
.NET Core 3.0 was officially released, but the Visual Studio designer does not yet fully support it. This makes developing and testing many of the demos difficult. 

For this reason, keep using the .NET Framework for all the demos (until .NET Core 3.0 is fully supported supported in Visual Studio) and migrate ScottPlot to .NET Core 3.0 targeting net45 and netcoreapp3.0.

**Comment by swharden** [comment]
Actually, this may be a good time to consider separating this project into different NuGet packages, each using the framework best suited for the task.

* ScottPlot (.NET Standard 1.3) - plots data and returns or saves an image
* ScottPlot.WinForms (.NET Framework) - interactive user control
* ScottPlot.WPF (.NET Core) - interactive user control
* ScottPlot.UWP (.NET Core) - interactive user control

The primary advantage of this separation is it allows the core function of ScottPlot (creating graphs from data, returning or saving an image) be used in all .NET environments (.NET Framework, .NET Core, Xamarin), on Windows, Linux, iOS, Android, OSX, etc. The secondary advantage is the segregation of interactive (user control) complexity away from the primary plotting library.

**Comment by morningkyle** [comment]
Hi @swharden,

> ScottPlot (.NET Standard 1.3) - plots data and returns or saves an image

Can you perform plotting and image handling with .net standard only?  That seems to be a huge effort. By checking the [.net standard APIs](https://github.com/dotnet/standard/blob/master/docs/versions/netstandard1.5_ref.md), only some core C# features are supported, especially no _System.Drawing_.

> The primary advantage of this separation is it allows the core function of ScottPlot (creating graphs from data, returning or saving an image) be used in all .NET environments

The idea is great!  I guess the dependency needs to be either _.net framework_ or _.net core_.

**Comment by swharden** [comment]
> Can you perform plotting and image handling with .net standard only? Only some core C# features are supported, especially no _System.Drawing_.

Actually, [System.Drawing.Common](https://www.nuget.org/packages/System.Drawing.Common) is a .NET Standard version of System.Drawing available as a NuGet package. The migration would be very easy, requiring virtually no code change.

The only painful part is that the ScottPlot library wouldn't have any user controls. Those would be separate libraries (e.g., ScottPlot.WinForms and ScottPlot.WPF). This would be a little confusing for people already using ScottPlot who upgrade their NuGet package.

**Comment by morningkyle** [comment]
@swharden  Thanks for pointing out  [System.Drawing.Common](https://www.nuget.org/packages/System.Drawing.Common) to me.  Indeed, it is a much lighter dependency then the full .net framework or .net core.

Just a note, the idea of separation in general is good. But there is also sacrifice.  Bound the drawing ability to GDI+(System.Drawing.Common) means we might also block the advantages provided with WPF, which uses hardware acceleration through DirectX.  See reference  ["Difference between GDI and WPF"](https://www.leadtools.com/help/leadtools/v20/dh/to/differences-between-gdi-and-wpf.html).

But I agree that, early performance optimization should have lower priority than a good modular design.

**Comment by swharden** [comment]
I did some benchmark tests last week to further investigate WPF as a potential rendering engine for a plotting library. 

GDI's big bottleneck comes from large images (specifically filling large areas). A large image with a few lines drawn on it renders pretty slowly.

WPF was extremely fast at displaying large images with a few lines. However, as lines were added (up to 1,000) performance dropped down extremely fast. Near the end it was on par with GDI. I think the hardware acceleration is ideal for moving around large, semitransparent, complicated shapes and images... but not really designed for high-speed rendering of thousands of small lines (essentially all of what a plot is).

Finally, many of the benefits of WPF require WPF and display hardware... which isn't going to be running in console applications (which I'd like to continue to support). All things considered, I'm leaning back toward System.Drawing.Common because of how well it works on all .NET platforms, despite its moderate performance issues.  

QuickPlot (https://github.com/swharden/QuickPlot) has been progressing well, and it is written in .NET Standard using System.Drawing.Common. Currently I'm getting 40-50 Hz redraw rates at 1080p.

**Comment by swharden** [comment]
I tried a conversion to .NET Core 3.0 today. ScottPlot converts nicely to .NET Core, but the demos and the tests don't do a good job referencing it. Further, converting them to .NET Core makes the solution complicated because now every test/demo is targeting multiple frameworks. Furthermore, Azure Pipelines still does not support running tests in solution files containing mixed .NET Framework and .NET Core projects. 

@petarpetrovt feel free to have a go at it if you think I'm missing something. I want to keep the demos and tests running .NET Framework 4.5.

QuickPlot (https://github.com/swharden/QuickPlot) is written in .NET Standard so it supports .NET Framework and .NET Core apps. It's not done yet, but it's developing quickly. It will probably be ready before Microsoft (and supporting infrastructure) fully supports .NET Core 3.0

**Comment by swharden** [comment]
Following-up, https://www.nuget.org/packages/ScottPlot.WinForms/ now supports .NET Core 3.0 and .NET Framework 4.6.1
