### ISSUE TITLE
remove ValueTuple dependency

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#88]
I noticed that System.ValueTuple.dll is appearing in the build folder now.

It seems to be listed as a dependency:
https://github.com/swharden/ScottPlot/search?q=ValueTuple&unscoped_q=ValueTuple

but I don't think any code is actually using this...

The new lines came in with this commit: https://github.com/swharden/ScottPlot/commit/23c17943b9f1b1d3799fa096466c3f1065eb5bcd

**Comment by swharden** [comment]
82d1119e23e218aeefb5530bf6a8becfae70965b

**Comment by vrdriver** [comment]
Hi Scott, has this been added back in to 4.0.45?

I had this error before when trying to run my program on Windows 7. 

`An unhandled exception of type 'System.IO.FileLoadException' occurred in ScottPlot.dll Additional information: Could not load file or assembly 'System.ValueTuple, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

I was able to overcome the problem by installing ValueTuple through NuGet, and I also upped the .NET version to 4.7.2.

I may not have needed up up the .NET version, but I did that just in case.

**Comment by swharden** [comment]
Hi @vrdriver, thanks for reporting this!

I created a new .NET Framework 4.6.1 WinForms project and installed ScottPlot 4.0.45 with NuGet and had no problem.

I also created a new .NET Framework 4.6.1 WPF project and installed ScottPlot with no problem.

What steps can reproduce this error in a new project?

**Comment by swharden** [comment]
Following-up here, .NET Framework 4.6.1 requires users to install the `System.ValueTuple` NuGet package. 

Later versions of .NET Framework do not require this package.
