### ISSUE TITLE
more mouse zoom/pan options

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#90]
This is a work in progress, but additional mouse commands could be added:

- [x] middle-click-drag to **zoom into a rectangle**
- [x] SHIFT + left-click-drag to **zoom into a rectangle**
- [x] SHIFT + left-click to **auto-axis**
- [x] CTRL + left-click-drag to **pan horizontally** (vertical axis locked)
- [x] CTRL + right-click-drag to **zoom horizontally** (vertical axis locked)
- [x] make CTRL+scrollwheel  **zoom horizontally** (vertical axis locked)
- [x] ALT + left-click-drag to **pan vertically** (horizontal axis locked)
- [x] ALT + right-click-drag to **zoom vertically** (horizontal axis locked)
- [x] make ALT+scrollwheel zoom on one axis only **zoom vertically** (horizontal axis locked)
- [x] document all these commands through the right-click menu

**Comment by StendProg** [comment]
I like it! But want to draw rectangle with left mouse button, and some hotkey pressed?
Middle mouse button so uncomfortable.

**Comment by swharden** [comment]
> I like it! But want to draw rectangle with left mouse button, and some hotkey pressed?
> Middle mouse button so uncomfortable.

Good point! How about SHIFT + left-click-drag? I also edited the original post to add some new ones.

**Comment by StendProg** [comment]
Looks much better. Alt + left-click-drag looks more interesting, but it hard to say before you try it.

**Comment by swharden** [comment]
got the axis locking done (edc7808c3f1d6e0adba6047c12e9e071f5e86bc0)

rectangle drawing will be a little more complex

**Comment by citizen3942** [comment]
For instance, I'd expect to zoom data with left-click drag from left to right into area of interest, whilst maintaining Y scaling. While the mouse button is pressed and dragged, vertical lines appear for visual feedback.
Before or after zooming, one can adjust the Y scale with a mouse scroll.
The panning could be done with the middle mouse button, as I, in particular, am used to do in CAD software (SolidWorks).
 What do you think?

**Comment by swharden** [comment]
The simplistic mouse controls of ScottPlot (left-click-drag to pan, right-click-drag to zoom) were inspired by Qt's qwtplot and something I'd like to keep. Many plotting graphics libraries don't allow real-time panning and zooming like that because they're not fast enough, and that's a strength of ScottPlot I'd like to continue to highlight.

However, improvements could still be made which allow click-drag to zoom in to a specific range. **Perhaps we could keep the current left-click-dragging behavior for the _data area_, but allow users to zoom into a region of interest by left-click-dragging _on an axis_.** This could be made obvious to the user by changing the cursor to arrows as its is hovered over an axis. This might be even better than the original suggestion of zooming into a rectangle...

One program that does something similar is scientific software called ClampFit. You can't pan or zoom in real time (redraws only occur on MouseUp events), but you can left-click-drag on an axis to zoom. Here's a video I recorded to demonstrate that:

![clampfit-interaction](https://user-images.githubusercontent.com/4165489/63170189-c17c5b00-c006-11e9-91c2-f6d07a63dd5f.gif)

**Comment by swharden** [comment]
I tried adding the "click and drag on an _axis_ to zoom into a region" and it felt really unnatural. Interestingly the thing that felt weird was the cursor that changed as I hovered over the axis. It felt like click-dragging on the axis should stretch it (rather than select a span to zoom into).

In contrast, I added the ***middle-click-drag zoom*** and it feels really good! I think it feels natural because we are already middle-clicking to reset the zoom.

![screenshot8](https://user-images.githubusercontent.com/4165489/63401718-520bc000-c3a6-11e9-9e62-35da368b7230.gif)

**Comment by FadyDev2** [comment]
Hello, 

Its seems that in last Nuget update we lost the CTRL+scrollwheel zoom horizontally (vertical axis locked). I don't know if other functionalities in mouse actions are also affected.

Will you please revise the functionality of locking vertical axis while CTRL is pressed?
would be great too if we have the ability to make it configurable, for example:
formsPlot1.Configure(zoomOnX:true, zoomOnY:false)

Thanks a lot for your quick answers and your help :)
Br, 
Fady

**Comment by swharden** [comment]
You're right @FadyDev2, I forgot to re-implement the keyboard controls when I recreated the user controls from scratch in ScottPlot v4. I'll fix this one shortly. Thanks for mentioning it!

**Comment by swharden** [comment]
This is now fixed in both the WinForms and WPF user controls. I'll issue a new package on NuGet later today. Thanks again for catching this @FadyDev2

**Comment by JagDTalcyon** [comment]
I have a difficulty in using the application in laptop which doesn't have middle click.
So, how can i use the select rectangle zoom option in left button or right button ?

**Comment by swharden** [comment]
> I have a difficulty in using the application in laptop which doesn't have middle click.
> So, how can i use the select rectangle zoom option in left button or right button ?

@JagDTalcyon this is an interesting case I hadn't considered! Shift+Left-click-drag is available, what do you think about that as a way to "zoom into a rectangle" without requiring a middle mouse button?

**Comment by swharden** [comment]
@JagDTalcyon it turns out I was able to do this with a one-line modification for the WinForms and WPF controls.

I also made Shift + Left-click "auto-axis" (like middle-click typically does).

This change will make it into version 4.0.10 which I intend to publish on NuGet some time this weekend. Thanks again for your suggestion!

**Comment by RossAylen** [comment]
I have a form with two identical graphs, copied and pasted then renamed. The code that drives them is also the same. However on one graph left click drags but on the other it draws a rectangle and zooms? Any idea why this is happening?

**Comment by RossAylen** [comment]
I have found that if the left mouse has the "drag to zoom into a rectangle" function, I can press the ALT key, and the function changes to pan.
