### ISSUE TITLE
Legend looks bad while dragging

### ISSUE THREAD

**Issue by bukkideme** [swharden/ScottPlot#92]
Hello,
I just found that when you show Legend, and start to pan with keeping Mouse left button, all curves with their marker types in the Legend changes to "ScottPlot.MarkerShape.filledSquare" type from the previously set types. Stop panning and all markers reverts to original.

Edit: actually it looks like this bug happens only, when we create a curve via PlotScatter() method not explicitly specifying marker type. In this case the default marker type is "filledCircle". During mouse panning these default filledCircle markers turn into filledSquare ones.

**Comment by StendProg** [comment]
It is rendered correct. Small filled circle look like filled square with anti aliasing dissabled. After PR #89 antialiasing off during pan by default. If you want to avoid this effect you can set at startup:

```c#
scottPlotUC1.plt.mouseTracker.lowQualityWhileDragging = false;
```

**Comment by swharden** [comment]
You can also toggle this behavior on and off with the right-click menu (which hopefully will be improving soon, #91)

When `lowQualityWhileDragging` is enabled, perhaps we should render the frame and legend in high quality, and only render the data in low quality? I guess then that causes a problem because circles would render well in the legend put poorly on the graph itself...

**Comment by bukkideme** [comment]
Thanks, clear now!

**Comment by swharden** [comment]
To make this clearer in the future should we display a little message in the corner when a frame is rendered low quality? Maybe something that looks kind of like the benchmark? ... or turn this back off by default?

I like how low quality rendering while dragging makes the user interaction faster, but I'm concerned this behavior might be misinterpreted as a glitch...

**Comment by StendProg** [comment]
@swharden it looks like legend render in low resulution and then upscaled with some default method.
Maybe render legend in high resolution initialy help to resolve this problem.

**Comment by StendProg** [comment]
Posible solutions:
- Make new bitmap layer (like figure, and data)  for legend, with AA always on, and just copy it on end render end.
- render each legend element on separate small bitmap with AA disabled, and copy it on dataBitmap.
- disable lowQualityWhileDragging by default

**Comment by swharden** [comment]
Making a standalone legend bitmap is an interesting idea and one I considered before. This would make it easy to render the legend with independent settings from the rest of the graph, but there may be another advantage:

There may be an advantage to doing this - consider applications which want may desire to display the legend _outside_ the graph as as not to cover-up any of the data. It might be nice if they can do something like `GetLegendBitmap()` to get just the legend as a standalone image. It also wouldn't need to be re-rendered every time the data is rendered. If this is desirable, making the legend its own bitmap could be a new and separate issue.

**Comment by StendProg** [comment]
Legend must be rerender on each Render call, or you should check and call UpdateLegend on each posible point that can change legend, or force user to make it manually.

**Comment by swharden** [comment]
> > It also wouldn't need to be re-rendered every time the data is rendered.
> 
> Legend must be rerender on each Render call, or you should check and call UpdateLegend on each posible point that can change legend, or force user to make it manually.

My thinking is that if users `Legend(false)` so no legend is drawn on the graph, then use `GetLegendBitmap()` to get the legend Bitmap and place it somewhere in their application manually, they can be expected to call `GetLegendBitmap()` again when their application does something that would change how the legend looks.

**Comment by swharden** [comment]
@StendProg has improved this behavior (#93) and I just added quality settings to the menu (pictured). This issue is probably good for now, and we can revisit exporting legend as its own bitmap in the future (there's a lot of other stuff going on currently)

![image](https://user-images.githubusercontent.com/4165489/63132008-aae5ed80-bf8d-11e9-9bba-12ea4bd8ed7a.png)
