### ISSUE TITLE
Axis offset - option to turn off automatic appearance?

### ISSUE THREAD

**Issue by bukkideme** [swharden/ScottPlot#94]
This is not an issue, more like a feature request. To get an exponent for an axis for very large/small numbers is a natural thing, you can see such features in every plotting software/programs etc.

However, for me at least, having an offset value for an axis looks very uncommon and strange. In my opinion, having an automatic offset value appear next to the exponent value makes very difficult to read values from the plot, and might create possible mistakes.
Would it be possible to turn off offset using a Bool input for the plt.Axis() method? So keeping the exponent, but turning off the offset.
Thanks!

https://github.com/swharden/ScottPlot/tree/master/cookbook#axis-exponent-and-offset

**Comment by swharden** [comment]
### Let's add ways to customize how ticks are displayed
Right now `plt.Ticks()` sets some functionality of tick marks. Maybe this is where we can add arguments for more functionality. What about arguments like these?

```cs
plt.Ticks(useUnicodeSuperscript: true); // to display small exponents like @Padanian did
plt.Ticks(useMultiplierNotation: true);
plt.Ticks(useOffsetNotation: true);
plt.Ticks(useExponentialNotation: true);
```

I also think it may be useful to allow users to add their own strings as tick marks. This would be especially useful for bar graphs... but also maybe this is doing too much at once and we can add this later when and if it's actually needed.

```cs
plt.Ticks(customLabels = new string[] {"dogs", "cats", "unicorns"};
```

### Why (and when) to use tick offsets

For readers unfamiliar with this topic, tick offsets are displayed automatically in the corner of the graph when one zooms in on a very small region that is very far from zero. Displaying an offset solves the problem where tick numbers are very large, but differences between one tick and the next are very small. Consider how tick labels should look if the axis is zoomed between 1000000000 and 1000000001...

tick labels without using an offset:
```
1000000000.0, 1000000000.25, 1000000000.5, 1000000000.75, 1000000001.0
```

tick labels using an offset (+1e9):
```
0.0, 0.25, 0.5, 0.75, 1.0
```

**Comment by bukkideme** [comment]
> Why (and when) to use tick offsets...

Yep, I see your point! The thing is that, thinking more about other alternatives, I cannot really find better option :) I guess it is just a matter to get used to...

**Comment by swharden** [comment]
I modified the tick tester so new additional arguments let you customize if multipliers, offsets, and exponential notion are used.

I also modified the tick tester demo app to make it easy to test these different behaviors.

![image](https://user-images.githubusercontent.com/4165489/63133369-ed5df900-bf92-11e9-9db1-cf789983f1d1.png)
