### ISSUE TITLE
new library to create and display spectrograms

### ISSUE THREAD

**Issue by citizen3942** [swharden/ScottPlot#98]
Perhaps a very good feature, that could be useful for many applications - an FFT spectrograph (waterfall).
The idea is to have a regular FFT and spectrograph running live and synchronized to its peaks.
Also, control over pan and zoom over those graphs, whilst maintaining the FFT plot and waterfalls' synchroneity.
The waterfall should have controls of what kind of color scheme it uses: black-white, sunrise sunset, darkjet, hot, etc. A good reference: https://www.qsl.net/dl4yhf/speclab/colorpal.htm
Another feature in the waterfall could be timestamping in seconds or ms (perhaps some kind of control over the scaling here). And also a grid setting option.

An example software: https://www.qsl.net/dl4yhf/speclab/index.htm

I know it must be quite a big development case, but there are numerous applications that can use such plotting feature - vibration, audio, rotational dynamics analysis and etc.
 
@swharden has already made a start with *Csharp-Data-Visualization/projects/18-01-11_microphone_spectrograph/* project which was very useful for my software, that I made.

My graphs look like this (signal, waterfall and FFT): ![fft-waterfall-graph](https://user-images.githubusercontent.com/7060628/63148271-60a25200-c009-11e9-895b-7238dde27d65.png)
 
My waterfall is just a bitmap, that is shifted upwards and updated every iteration.

Just fo a hint - for the waterfall color scheme, I interpolate colors like this:
```csharp
private void InitPlots()
        {
........
            // create a few stop colors:
            List<Color> baseColors = new List<Color>();  // create basecolors

            //colormap "DARKJET"
            //baseColors.Add(Color.Black);
            baseColors.Add(ColorTranslator.FromHtml("#001021"));
            baseColors.Add(Color.LightSkyBlue);
            baseColors.Add(Color.LightGreen);
            baseColors.Add(Color.Yellow);
            baseColors.Add(Color.Orange);
            baseColors.Add(Color.Red);
            
            /*
            //colormap "HOT"
            baseColors.Add(Color.Black);
            baseColors.Add(Color.Red);
            baseColors.Add(Color.Yellow);
            baseColors.Add(Color.White);
            */

            // and the interpolate a larger number of grdient colors:
            colors = InterpolateColors(baseColors, /*InterpolationFactor*/ 256) ;
        }

        List<Color> InterpolateColors(List<Color> stopColors, int count)
        {
            SortedDictionary<float, Color> gradient = new SortedDictionary<float, Color>();
            for (int i = 0; i < stopColors.Count; i++)
                gradient.Add(1f * i / (stopColors.Count - 1), stopColors[i]);
            List<Color> ColorList = new List<Color>();

            using (Bitmap bmp = new Bitmap(count, 1))
            using (Graphics G = Graphics.FromImage(bmp))
            {
                Rectangle bmpCRect = new Rectangle(Point.Empty, bmp.Size);
                LinearGradientBrush br = new LinearGradientBrush
                                        (bmpCRect, Color.Empty, Color.Empty, 0, false);
                ColorBlend cb = new ColorBlend();
                cb.Positions = new float[gradient.Count];
                for (int i = 0; i < gradient.Count; i++)
                    cb.Positions[i] = gradient.ElementAt(i).Key;
                cb.Colors = gradient.Values.ToArray();
                br.InterpolationColors = cb;
                G.FillRectangle(br, bmpCRect);
                for (int i = 0; i < count; i++) ColorList.Add(bmp.GetPixel(i, 0));
                br.Dispose();
            }
            return ColorList;
        }
```
And the waterfall can be drawn like this:
```csharp
void Update_waterfall_with_data(bool BW = true) //default is in black-white mode
        {
            int maxColor = 255; //default for grayscale
            // create a bitmap we will work with
            PixelFormat pixelFormat = PixelFormat.Format8bppIndexed;
            if (!BW) {
                maxColor = colors.Count - 1; 
            }
            Bitmap bitmap = new Bitmap(spec_data[0].Count, spec_data.Count, pixelFormat);

            ColorPalette pal = bitmap.Palette;
            for (int i = 0; i < 256; i++)
                pal.Entries[i] = BW ? Color.FromArgb(255, i, i, i) : Color.FromArgb(colors[i].ToArgb());
            bitmap.Palette = pal;

            // prepare to access data via the bitmapdata object
            BitmapData bitmapData = bitmap.LockBits(new Rectangle(0, 0, bitmap.Width, bitmap.Height),
                                                    ImageLockMode.WriteOnly, bitmap.PixelFormat);

            // create a byte array to reflect each pixel in the image
            int bytesPerPixel = Image.GetPixelFormatSize(bitmapData.PixelFormat) / 8;
            byte[] pixels = new byte[Math.Abs(bitmapData.Stride) * bitmap.Height];

            double scaleFactor = (double)fftYscale.Value/280;

            // fill pixel array with data
            for (int row = 0; row < spec_data.Count; row++)
            {
                for (int col = 0; col < spec_data[row].Count; col++)
                {
                    int bytePosition = row * bitmapData.Stride + col*bytesPerPixel;
                    double pixelVal = spec_data[row][col] * scaleFactor-200;
                    pixelVal = Math.Max(0, pixelVal);
                    pixelVal = Math.Min(maxColor, pixelVal);
                    pixels[bytePosition] = (byte)pixelVal; //grayscale mode
                }
            }

            // turn the byte array back into a bitmap
            Marshal.Copy(pixels, 0, bitmapData.Scan0, pixels.Length);
            bitmap.UnlockBits(bitmapData);

            // apply the bitmap to the picturebox
            fftWaterfall.Image = bitmap;
        }
```
I know some parts of my code could be done better and optimized, but please do not judge :smile:. I do have some scaling and shifting implemented in my waterfall generator for that to look nice.

**Comment by swharden** [comment]
Hi @citizen3942, thanks for the suggestion! Your sample code is useful too. As you mentioned I have some previous work in this area (but my coding quality was poor back then as I was brand new to C#). I'll link those below.

A spectrograph is fundamentally different than a data line plot, so I think spectrographs should be their own thing (not part of ScottPlot). However, maybe this is a good project we could start? It's something I've thought about in the back of my head for the last few months. 

I'd like to make a spectrogram class library (no GUI) to create spectorgrams from audio files and microphone input. This library would have many advanced color options (like you implement). That library could come with a user control to control it and display the spectrum and perform measurements. The core spectrogram class could provide access to signal and FFT samples, and ScottPlot could be used to display those. What do you think? Is this a project you might want to work together on?

PS: my motivation for pursuing this is I want to create an open source C# version of [Argo](https://digilander.libero.it/i2phd/argo/) for ultranarrowband radio frequency experiments. You can see my latest hardware efforts to this end [https://github.com/swharden/QRSS-hardware](https://github.com/swharden/QRSS-hardware) and [#spots](https://github.com/swharden/QRSS-hardware/tree/master/spots)

### Microphone Spectrograph
* [Demonstration on YouTube](https://www.youtube.com/watch?v=MS1Qgo710Vo&feature=youtu.be)
* [source code](https://github.com/swharden/Csharp-Data-Visualization/tree/master/projects/18-01-11_microphone_spectrograph)
![image](https://user-images.githubusercontent.com/4165489/63170923-6ea3a300-c008-11e9-96b8-e7f34af9a62d.png)

### QRSS Spectrograph
* [source code](https://github.com/swharden/Csharp-Data-Visualization/tree/master/projects/18-01-14_qrss)
![image](https://user-images.githubusercontent.com/4165489/63170989-985cca00-c008-11e9-9cfb-9fc5fac62686.png)

**Comment by swharden** [comment]
I started https://github.com/swharden/Spectrogram

We can discuss this topic there if / as this project evolves.

**Comment by swharden** [comment]
@citizen3942 I took a closer look at your interpolated colormap generator - I'd love to include it in the new Spectrograph library! Do you want to add it yourself or do you want me to add it? That issue is: https://github.com/swharden/Spectrogram/issues/1

PS: this video on colormaps is pretty good
https://www.youtube.com/watch?v=xAoljeRJ3lU

**Comment by swharden** [comment]
Following up on this, [Spectrogram](https://github.com/swharden/Spectrogram) is now live on NuGet

**Comment by swharden** [comment]
Following up on this, #420 touches on some of these topics
